Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2018-02, with the labels that each got.

#482 Display date of birth field when required on print pins page
  admin/views/pupil-pin/pin-print.ejs
Labels: Ready for review, Tested

#480 Bug/19216 Fix Travis
  .travis.yml
  docker-compose-test.yml
Labels: DNM - WIP

#478 Get travis working reliably
  .travis.yml
  admin/config.js
  admin/test/features/pupil_not_taking_check.feature
  admin/test/features/step_definitions/generate_pupil_pins_steps.rb
  admin/test/features/step_definitions/groups_steps.rb
  admin/test/features/step_definitions/pupil_not_taking_check.rb
  admin/test/features/step_definitions/pupil_register_steps.rb
  admin/test/features/step_definitions/restarts_steps.rb
  admin/test/features/step_definitions/school_landing_page_steps.rb
  admin/test/features/support/env.rb
  admin/test/features/support/mongo_db_helper.rb
  admin/test/features/support/page_objects/group_filter_section.rb
  admin/whitelist-dev.js
  admin/yarn.lock
  docker-compose-test.yml
Labels: Ready for review, Ready to merge

#484 Missing dot added.
  admin/views/groups/manage-group.ejs
  admin/views/restart/select-restart-list.ejs
  admin/views/school/add-multiple-pupils.ejs
  admin/views/school/add-pupil.ejs
  admin/views/school/edit-pupil.ejs
  admin/views/service-manager/check-windows-form.ejs
Labels: Reviewed & approved, Tested

#470 Feature/19129 school trial data
  admin/data/sql/migrations/062.do.sixty-pupils-per-school.js
  admin/data/sql/not-used-reference/do.school-dfeNumber-non-unique.sql
  admin/data/sql/not-used-reference/undo.school-dfeNumber-non-unique.sql
Labels: DNM - WIP

#486 bug/19059 - Bug fix.
  admin/assets/javascripts/global-scripts.js
Labels: Reviewed & approved, Tested

#485 bug/19116 - Enable NCA tools authentication.
  admin/controllers/authentication.js
  admin/routes/index.js
Labels: DNM - Requires Testing, Reviewed & approved

#468 Allocate forms randomly
  admin/data/sql/migrations/061.do.assign-dev-checkform-to-dev-checkwindow.js
  admin/data/sql/migrations/061.undo.assign-dev-checkform-to-dev-checkwindow.js
  admin/lib/random-generator.js
  admin/package.json
  admin/services/check-form.service.js
  admin/services/check-start.service.js
  admin/services/data-access/check-form.data.service.js
  admin/services/data-access/check.data.service.js
  admin/spec/service/check-form.service.spec.js
  admin/spec/service/check-start.service.spec.js
  admin/tests-integration/check-form.service.spec.js
  admin/yarn.lock
Labels: Ready for review, Tested

#471 18942 Handle PIN collision
  admin/config.js
  admin/services/check-start.service.js
  admin/services/pin-generation.service.js
  admin/spec/service/pin-generation.service.spec.js
Labels: Ready to merge, Reviewed & approved, Tested

#483 Bug/19269 check window query
  .travis.yml
  admin/controllers/service-manager.js
  admin/data/sql/migrations/062.do.sixty-pupils-per-school.js
  admin/services/check-window.service.js
  admin/services/data-access/check-window.data.service.js
  admin/spec/service/check-window.service.spec.js
Labels: Ready for review

#496 Feature/19284 copy changes
  pupil-spa/src/app/instructions/instructions.component.html
  pupil-spa/src/app/login-success/login-success.component.html
Labels: Reviewed & approved, Tested

#495 Feature/18295 ps report data service refactor to sql server
  admin/app.js
  admin/bin/psychometrician-report.js
  admin/bin/psychometricians-report-v2.js
  admin/data/sql/migrations/064.do.create-ps-report-cache-table.sql
  admin/data/sql/migrations/064.undo.create-ps-report-cache-table.sql
  admin/data/sql/migrations/065.do.grant-delete-on-ps-report-cache.js
  admin/data/sql/migrations/065.undo.grant-delete-on-ps-report-cache.js
  admin/data/sql/migrations/066.do.add-unique-index-checkform-name.sql
  admin/data/sql/migrations/066.undo.add-unique-index-checkform-name.sql
  admin/package.json
  admin/services/certificate-store.service.js
  admin/services/completed-check-processing.service.js
  admin/services/data-access/check-form.data.service.js
  admin/services/data-access/check.data.service.js
  admin/services/data-access/completed-check.data.service.js
  admin/services/data-access/psychometrician-report-cache.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/data-access/school.data.service.js
  admin/services/data-access/sql.service.js
  admin/services/date.service.js
  admin/services/psychometrician-report.service.js
  admin/services/psychometrician-util.service.js
  admin/spec/controllers/pupil.spec.js
  admin/spec/mocks/completed-check-with-results.js
  admin/spec/service/date.service.spec.js
  admin/spec/service/psychometrician-report.service.spec.js
  admin/spec/service/psychometrician-util.service.spec.js
  admin/yarn.lock
Labels: Testing

#493 Bug/19282 group filtering for restarts
  admin/package.json
  admin/routes/restart.js
  admin/services/data-access/group.data.service.js
  admin/yarn.lock
Labels: Reviewed & approved, Tested

#497 bug/19116 - Bug fix. Wrong path to NCA url.
  admin/controllers/authentication.js
Labels: Reviewed & approved, Tested

#498 bug/19297 - Bug fix
  admin/assets/javascripts/global-scripts.js
Labels: Ready for review, Tested

#502 Bug/19404-extract-migrations-to-build-task
  admin/config.js
  admin/data/fixtures/dummy-users.json
  admin/data/migrations/config.js
  admin/data/migrations/migrations/20170506123415-add_test_data_for_check_windows.js
  admin/data/migrations/migrations/20170508103017-add_check_forms.js
  admin/data/migrations/migrations/20170523165640-add_test_users.js
  admin/data/migrations/migrations/20170920093800-add-attendance-codes.js
  admin/data/migrations/migrations/20170928072142-create_a_current_check_window.js
  admin/data/migrations/migrations/20170928174344-delete_old_checks.js
  admin/data/migrations/migrations/20170928180429-change_field_name_checks.checkStartDate_to_checks.pupilLoginDate.js
  admin/data/migrations/migrations/20170929075953-remove_fields_from_pupil.js
  admin/data/migrations/migrations/20171012093203-remove-attendance-codes-from-pupils.js
  admin/data/migrations/migrations/20171012121301-add-new-attendance-codes.js
  admin/data/migrations/migrations/20171019113308-edit-check-windows-status.js
  admin/data/migrations/migrations/20171019123302-add-check-windows.js
  admin/data/migrations/migrations/20171103081918-question-set-update-for-user-research.js
  admin/data/migrations/migrations/20171107173300-add-service-manager-user.js
  admin/data/migrations/migrations/20171110030904-toggle-speech-synth-on-for-demo-user.js
  admin/data/migrations/migrations/20171130162600-create-pupil-restart-collection.js
  admin/data/migrations/migrations/20171205162400-add-restart-status-code.js
  admin/data/migrations/migrations/20171214105200-create-group-collection.js
  admin/data/migrations/migrations/20171218101000-add-pupil-status-code.js
  admin/data/migrations/migrations/20171220095000-update-pupil-completed-status.js
  admin/data/migrations/migrations/20180112093030-add-known-test-account.js
  admin/data/migrations/migrations/20180112094020-add-speech-synth-user.js
  admin/data/migrations/migrations/20180112112250-add-pin-expiry-to-known-test-account.js
  admin/data/sql/migrations/008.do.sample-pupils.js
  admin/package.json
  deploy/sql-migrations/migrate-db.sh
Labels: DNM - WIP

#505 bug/19414. add startd script to run migrations then start. remove migrate-mongo
  admin/package.json
  admin/yarn.lock
Labels: Ready for review

#507 more copy changes
  admin/views/school/pupils-not-taking-check.ejs
  admin/views/test-developer/assign-check-forms-to-windows.ejs
Labels: Ready for review, Tested

#513 fix req.user.id for nca tools
  admin/authentication/nca-tools-authentication-strategy.js
Labels: Ready for review

#511 bug/19389 fix bug when not an array
  admin/controllers/check-form.js
Labels: Ready for review

#510 Feature/19173 change link guidance
  admin/assets/PDFs/MTC_CAG_Feb_2018_Trial.pdf
  admin/views/groups/groups.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/generated-pins-list.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/school/pupil-register.ejs
  admin/views/school/pupils-not-taking-check.ejs
  admin/views/school/school-home.ejs
  admin/views/service-manager/check-windows.ejs
  admin/views/service-manager/service-manager-home.ejs
  admin/views/test-developer/assign-check-forms-to-windows.ejs
  admin/views/test-developer/test-developer-home.ejs
  admin/views/test-developer/upload-and-view-forms.ejs
  admin/views/test-developer/view-check-form.ejs
Labels: DNM - Requires Testing, Ready for review

#503 Bugfix: pin generation: make date time dynamic
  admin/services/pin-generation.service.js
Labels: DNM - Requires Testing

#504 Bugfix: pupil login
  admin/data/sql/migrations/068.do.change-pupil-pin-to-string.sql
  admin/data/sql/migrations/068.undo.change-pupil-pin-to-string.sql
  admin/services/data-access/pupil.data.service.js
  admin/services/data-access/sql.service.js
Labels: Ready for review, Tested

#506 Bugfix: QnTimeOutResponse field
  admin/services/psychometrician-util.service.js
  admin/spec/service/psychometrician-util.service.spec.js
Labels: Ready for review, Tested

#490 19083 Google Analytics on Pupil SPA
  pupil-spa/.angular-cli.json
  pupil-spa/Dockerfile
  pupil-spa/gulpfile.js
  pupil-spa/package.json
  pupil-spa/src/app/app.component.spec.ts
  pupil-spa/src/app/app.component.ts
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/check-complete/check-complete.component.spec.ts
  pupil-spa/src/app/check-complete/check-complete.component.ts
  pupil-spa/src/app/check/check.component.spec.ts
  pupil-spa/src/app/check/check.component.ts
  pupil-spa/src/app/error-handler.ts
  pupil-spa/src/app/instructions/instructions.component.spec.ts
  pupil-spa/src/app/instructions/instructions.component.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.spec.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.ts
  pupil-spa/src/app/warmup-intro/warmup-intro.component.spec.ts
  pupil-spa/src/app/warmup-intro/warmup-intro.component.ts
  pupil-spa/src/environments/environment.prod.ts
  pupil-spa/src/environments/environment.ts
  pupil-spa/src/index.html
  pupil-spa/src/public/google-analytics/analytics.js
  pupil-spa/yarn.lock
Labels: Ready for review, Tested

#516 fix tests to point to new guidance doc
  admin/test/features/support/page_objects/group_pupils_page.rb
  admin/test/features/support/page_objects/manage_check_window_page.rb
Labels: Ready for review

#509 bug/19351 - Sorting pupils in pupil register
  admin/controllers/school.js
  admin/routes/school.js
  admin/services/data-access/pupil.data.service.js
  admin/services/pupil.service.js
  admin/utils.js
  admin/views/school/pupil-register.ejs
Labels: Reviewed & approved, Tested

#500 Sticky banner bug fix.
  admin/assets/javascripts/global-scripts.js
  admin/test/features/generate_pupil_pins.feature
  admin/test/features/support/page_objects/assign_form_to_window_page.rb
  admin/views/test-developer/assign-check-forms-to-windows.ejs
Labels: Reviewed & approved, Tested

#515 feature/19470 - send express request log entries to logDNA
  admin/app.js
  admin/config.js
  admin/data/sql/migrate-sql.js
  admin/package.json
  admin/yarn.lock
Labels: DNM - WIP

#517 implement connection timeout in postgrator
  admin/data/sql/migrate-sql.js
  admin/yarn.lock
Labels: Ready for review

#514 Bug/19459 add qtload to psychometric report
  admin/services/data-access/psychometrician-report-cache.data.service.js
  admin/services/data-access/sql.pool.service.js
  admin/services/psychometrician-report.service.js
  admin/services/psychometrician-util.service.js
  admin/spec/service/psychometrician-util.service.spec.js
  pupil-spa/src/app/check/check.component.html
  pupil-spa/src/app/practice-question/practice-question.component.ts
  pupil-spa/src/app/question/question.component.ts
  pupil-spa/src/app/spoken-practice-question/spoken-practice-question.component.ts
  pupil-spa/src/app/spoken-question/spoken-question.component.ts
Labels: Ready for review, Tested

#520 Bug/19473 side menu links
  .travis.yml
  admin/controllers/download-file.js
  admin/package.json
  admin/routes/school.js
  admin/routes/service-manager.js
  admin/routes/test-developer.js
  admin/test/features/add_multiple_pupil_validation_error.feature
  admin/test/features/breadcrumbs.feature
  admin/test/features/step_definitions/generate_pupil_pins_steps.rb
  admin/test/features/support/page_objects/group_pupils_page.rb
  admin/test/features/support/page_objects/manage_check_window_page.rb
  admin/test/features/support/page_objects/pupils_not_taking_check_page.rb
  admin/test/features/support/page_objects/school_landing_page.rb
  admin/test/features/support/sql_db_helper.rb
  admin/views/groups/groups.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/generated-pins-list.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/school/_pupil-form.ejs
  admin/views/school/add-multiple-pupils.ejs
  admin/views/school/pupil-register.ejs
  admin/views/school/pupils-not-taking-check.ejs
  admin/views/school/school-home.ejs
  admin/views/service-manager/check-settings.ejs
  admin/views/service-manager/check-windows.ejs
  admin/views/service-manager/service-manager-home.ejs
  admin/views/test-developer/assign-check-forms-to-windows.ejs
  admin/views/test-developer/test-developer-home.ejs
  admin/views/test-developer/upload-and-view-forms.ejs
  admin/views/test-developer/view-check-form.ejs
  admin/yarn.lock
  pupil-spa/test/Gemfile.lock
  pupil-spa/test/features/support/page_objects/confirmation_page.rb
Labels: DNM - Requires Testing, Reviewed & approved

#525 Feature/18177 feedback link
  admin/views/partials/_content.ejs
Labels: Ready for review

#521 bug/19494 allow nca tools users without school assigned
  admin/authentication/nca-tools-authentication-strategy.js
  admin/services/nca-tools-user.service.js
  admin/spec/service/nca-tools-user.service.spec.js
Labels: Ready for review

#519 toggle verbose express logging
  admin/app.js
  admin/config.js
Labels: Ready for review

#523 Add config to allow the auto-marking to be disabled
  admin/README.md
  admin/app.js
  admin/config.js
  admin/package.json
  admin/services/check-complete.service.js
  admin/yarn.lock
Labels: Ready for review, Tested

#524 fail the build if the migrations have not run
  .travis.yml
  admin/data/sql/createDatabase.js
  admin/data/sql/migrate-sql.js
  admin/test/features/support/env.rb
Labels: Reviewed & approved

#527 Add missing schemas into the psychometrician data service.
  admin/services/data-access/psychometrician-report-cache.data.service.js
Labels: Reviewed & approved

#522 Bug/19351 pupil register sorting 2
  admin/controllers/pupil.js
  admin/controllers/school.js
  admin/services/pupil.service.js
  admin/spec/mocks/pupils-with-group-and-status.js
  admin/spec/service/pupil.service.spec.js
  admin/test/features/support/page_objects/pupil_register_page.rb
  admin/test/features/support/page_objects/school_landing_page.rb
  admin/views/restart/restart-overview.ejs
  admin/views/school/_pupil-form.ejs
  admin/views/school/add-multiple-pupils.ejs
  admin/views/school/pupil-register.ejs
  admin/views/school/school-home.ejs
  admin/views/service-manager/check-settings.ejs
  admin/views/test-developer/upload-and-view-forms.ejs
Labels: Reviewed & approved, Tested

#518 SPA: Capture device properties
  admin/bin/inspect-spa-data.js
  admin/controllers/completed-check.js
  admin/package.json
  admin/routes/index.js
  admin/services/psychometrician-report.service.js
  admin/services/psychometrician-util.service.js
  admin/spec/service/group.service.spec.js
  admin/spec/service/psychometrician-report.service.spec.js
  admin/spec/service/psychometrician-util.service.spec.js
  admin/yarn.lock
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/login-success/login-success.component.spec.ts
  pupil-spa/src/app/login-success/login-success.component.ts
  pupil-spa/src/app/services/device/device.service.spec.ts
  pupil-spa/src/app/services/device/device.service.ts
  pupil-spa/src/app/services/storage/storage.service.mock.ts
  pupil-spa/src/app/services/storage/storage.service.ts
Labels: Reviewed & approved, Tested

#530 Drop back to a hopefully more stable version of MSSQL
  .travis.yml
  admin/config.js
  admin/data/sql/migrate-sql.js
  admin/test.sh
  admin/test2.sh
  admin/test3.sh
  docker-compose.yml
Labels: Reviewed & approved

#531 feature/19532-19456 Copy changes
  admin/test/features/support/page_objects/group_pupils_page.rb
  admin/views/groups/groups.ejs
  admin/views/groups/manage-group.ejs
  admin/views/school/pupil-register.ejs
  admin/views/test-developer/upload-and-view-forms.ejs
Labels: Reviewed & approved, Signed Off, Tested

#532 Fix CSP policy for Safari
  admin/app.js
Labels: Reviewed & approved

#534 Bugfix - add support for 'Del' key for MS
  pupil-spa/src/app/practice-question/practice-question.component.spec.ts
  pupil-spa/src/app/practice-question/practice-question.component.ts
  pupil-spa/src/app/question/question.component.spec.ts
  pupil-spa/src/app/question/question.component.ts
Labels: Reviewed & approved, Tested

#528 bug/18514 - Role landing page fix
  admin/routes/index.js
Labels: Reviewed & approved, Signed Off, Tested

#539 bug/19324 - Side links fix
  admin/controllers/download-file.js
  admin/routes/school.js
  admin/routes/service-manager.js
  admin/routes/test-developer.js
  admin/test/features/support/page_objects/manage_check_window_page.rb
  admin/views/service-manager/check-windows.ejs
  admin/views/service-manager/service-manager-home.ejs
  admin/views/test-developer/assign-check-forms-to-windows.ejs
  admin/views/test-developer/test-developer-home.ejs
  admin/views/test-developer/upload-and-view-forms.ejs
  admin/views/test-developer/view-check-form.ejs
Labels: Reviewed & approved, Signed Off, Tested

#536 Bug/19171 group preselect pupils on top
  admin/services/data-access/group.data.service.js
Labels: Reviewed & approved, Signed Off, Tested
