Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2018-06, with the labels that each got.

#681 [21417] Extend the development phase check window
  admin/data/sql/migrations/091.do.extend-development-check-window.sql
  admin/data/sql/migrations/091.undo.extend-development-check-window.sql
  admin/spec/service/check-form.service.spec.js
  test/admin/features/step_definitions/add_multiple_pupil_steps.rb
Labels: CI Enabled, Reviewed & approved, Tested

#679 21363 - Added handling of finished checks on submission-pending
  pupil-spa/src/app/check-complete/check-complete.component.spec.ts
  pupil-spa/src/app/check-complete/check-complete.component.ts
  pupil-spa/src/app/services/check-status/check-status.service.mock.ts
  pupil-spa/src/app/services/check-status/check-status.service.spec.ts
  pupil-spa/src/app/services/check-status/check-status.service.ts
  pupil-spa/src/app/services/storage/storage.service.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.spec.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#680 21238 Process data and bulk import to pupil table
  admin/assets/stylesheets/elements/_pupil-census.scss
  admin/data/sql/migrations/090.do.add-bulk-permissions-pupil-table.js
  admin/data/sql/migrations/090.undo.add-bulk-permissions-pupil-table.js
  admin/data/sql/migrations/092.do.add-jobid-to-pupil.sql
  admin/data/sql/migrations/092.undo.add-jobid-to-pupil.sql
  admin/services/data-access/job.data.service.js
  admin/services/data-access/pupil-census-import.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/pupil-census-processing.service.js
  admin/services/pupil-census.service.js
  admin/spec/service/pupil-census-processing.service.spec.js
  admin/spec/service/pupil-census.service.spec.js
  admin/views/service-manager/upload-pupil-census.ejs
  test/admin/features/support/page_objects/upload_pupil_census_page.rb
Labels: CI Enabled, Ready for review

#686 Escape hyphen characters correctly for database and schema
  admin/services/data-access/pupil-census-import.data.service.js
Labels: Ready for review

#688 Include missing migration
  admin/data/sql/migrations/093.do.add-bulk-permissions-pupil-table.js
  admin/data/sql/migrations/093.undo.add-bulk-permissions-pupil-table.js
Labels: CI Enabled, Ready for review

#683 21411 - Added UI for download-pupil-check according to prototype
  admin/controllers/check-form.js
  admin/routes/test-developer.js
  admin/views/test-developer/download-pupil-check-data.ejs
  admin/views/test-developer/test-developer-home.ejs
  test/admin/features/download_pupil_check_data.feature
  test/admin/features/step_definitions/download_pupil_check_data_steps.rb
  test/admin/features/step_definitions/service_manager_landing_steps.rb
  test/admin/features/support/page_objects/download_pupil_check_data_page.rb
  test/admin/features/support/page_objects/testdeveloper_landing_page.rb
  test/admin/features/test_developer_landing_page.feature
Labels: CI Enabled, Ready for review, Signed Off, Tested

#689 feature/20766 introduce app insights as winston destination
  admin/app.js
  admin/azure.js
  admin/config.js
  admin/helpers/logger.js
  admin/package.json
  admin/yarn.lock
Labels: CI Enabled, Ready for review

#684 Feature/21433 download pupil check data functionality
  admin/config.js
  admin/controllers/check-form.js
  admin/routes/test-developer.js
  admin/services/date.service.js
  admin/services/psychometrician-report.service.js
  admin/spec/service/date.service.spec.js
  admin/spec/service/psychometrician-report.service.spec.js
  admin/views/test-developer/download-pupil-check-data.ejs
Labels: CI Enabled, Ready for review, Signed Off, Tested

#690 feature/21581 Implement restrictive CORS policy for endpoints only
  admin/app.js
  admin/config.js
  admin/helpers/cors-options.js
  admin/routes/check-started.js
  admin/routes/completed-check.js
  admin/routes/pupil-feedback.js
  admin/routes/questions.js
  test/admin/features/step_definitions/add_multiple_pupil_steps.rb
Labels: CI Enabled, Ready for review

#694 feature/21601 - prevent disk caching
  admin/app.js
  admin/helpers/browserSecurity.js
Labels: CI Enabled, Reviewed & approved

#695 feature/21650 tighten cookie policy
  admin/app.js
Labels: CI Enabled, Reviewed & approved

#693 Change guidance link for June trials
  admin/assets/pdfs/mtc-administration-guidance-2018-03-3.pdf
  admin/helpers/index.js
  test/admin/features/support/page_objects/group_pupils_page.rb
  test/admin/features/support/page_objects/manage_check_window_page.rb
Labels: CI Enabled, Reviewed & approved, Tested

#691 Feature/21556 Remove pupil census
  admin/assets/javascripts/custom-file-upload.js
  admin/assets/stylesheets/elements/_pupil-census.scss
  admin/controllers/service-manager.js
  admin/data/sql/migrations/094.do.add-permission-delete-pupil-table.js
  admin/data/sql/migrations/094.undo.add-permission-delete-pupil-table.js
  admin/data/sql/migrations/095.do.insert-delete-job-status-entry.sql
  admin/data/sql/migrations/095.undo.insert-delete-job-status-entry.sql
  admin/data/sql/migrations/096.do.add-job-id-index-to-pupil.sql
  admin/data/sql/migrations/096.undo.add-job-id-index-to-pupil.sql
  admin/routes/service-manager.js
  admin/services/data-access/job.data.service.js
  admin/services/data-access/pupil-census-import.data.service.js
  admin/services/data-access/pupil-census.data.service.js
  admin/services/pupil-census.service.js
  admin/spec/controllers/service-manager.spec.js
  admin/spec/service/pupil-census.service.spec.js
  admin/views/service-manager/upload-pupil-census.ejs
  test/admin/data/fixtures/pupil-census-data_error.csv
  test/admin/data/fixtures/pupilCensusDataEmptyForname.csv
  test/admin/data/fixtures/pupilCensusDataEmptyGender.csv
  test/admin/data/fixtures/pupilCensusDataEmptyLastname.csv
  test/admin/features/step_definitions/upload_pupil_census_steps.rb
  test/admin/features/support/hooks.rb
  test/admin/features/support/page_objects/upload_pupil_census_page.rb
  test/admin/features/upload_pupil_census.feature
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#696 Feature/21644 submission pending refresh problem
  pupil-spa/src/app/check-complete/check-complete.component.spec.ts
  pupil-spa/src/app/check-complete/check-complete.component.ts
  pupil-spa/src/app/login-success/login-success.component.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.spec.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#692 Feature/21516 add anomaly report to pupil check report
  admin/bin/detect-anomalies.js
  admin/bin/psychometricians-report-v2.js
  admin/controllers/check-form.js
  admin/data/sql/migrations/097.do.create-anomaly-report-cache-table.sql
  admin/data/sql/migrations/097.undo.create-anomaly-report-cache-table.sql
  admin/data/sql/migrations/098.do.grant-delete-on-anomaly-report-cache.js
  admin/data/sql/migrations/098.undo.grant-delete-on-anomaly-report-cache.js
  admin/package.json
  admin/public/images/loading.gif
  admin/routes/test-developer.js
  admin/services/anomaly-report.service.js
  admin/services/check-processing.service.js
  admin/services/data-access/anomaly-report-cache.data.service.js
  admin/services/data-access/azure-file.data.service.js
  admin/services/psychometrician-report.service.js
  admin/spec/mocks/completed-check-with-results.js
  admin/spec/service/anomaly-report.service.spec.js
  admin/spec/service/check-processing.service.spec.js
  admin/spec/service/psychometrician-report.service.spec.js
  admin/views/test-developer/download-pupil-check-data.ejs
  admin/yarn.lock
  test/admin/features/support/page_objects/download_pupil_check_data_page.rb
Labels: CI Enabled, Ready for review, Signed Off, Tested

#698 Feature/21335 ncatools unique and displayname
  admin/authentication/nca-tools-authentication-strategy.js
  admin/data/sql/migrations/099.do.alter-user-identifier.sql
  admin/data/sql/migrations/099.undo.alter-user-identifier.sql
Labels: CI Enabled, Reviewed & approved

#702 Feature/21707 build server doc
  vsoBuildServer.md
Labels: Ready for review

#699 Added the CSURF package and CSRF tokens to all POST forms
  admin/app.js
  admin/package.json
  admin/views/groups/manage-group.ejs
  admin/views/pupil-pin/generate-pins-list.ejs
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/restart/select-restart-list.ejs
  admin/views/school/_pupil-form.ejs
  admin/views/school/add-multiple-pupils.ejs
  admin/views/school/declaration-form.ejs
  admin/views/school/submit-attendance-register.ejs
  admin/views/service-manager/check-settings.ejs
  admin/views/service-manager/check-windows-form.ejs
  admin/views/service-manager/choose-check-window.ejs
  admin/views/service-manager/upload-pupil-census.ejs
  admin/views/sign-in.ejs
  admin/views/test-developer/assign-forms.ejs
  admin/views/test-developer/unassign-check-forms.ejs
  admin/views/test-developer/upload-new-form.ejs
  admin/yarn.lock
  test/admin/features/csrf.feature
  test/admin/features/step_definitions/csrf_steps.rb
  test/admin/features/support/page_objects/add_edit_check_window_page.rb
  test/admin/features/support/page_objects/add_multiple_pupil_page.rb
  test/admin/features/support/page_objects/add_pupil_page.rb
  test/admin/features/support/page_objects/assign_form_to_window_page.rb
  test/admin/features/support/page_objects/check_settings_page.rb
  test/admin/features/support/page_objects/generate_pins_overview_page.rb
  test/admin/features/support/page_objects/generated_pins_page.rb
  test/admin/features/support/page_objects/group_pupils_page.rb
  test/admin/features/support/page_objects/pupil_reason_page.rb
  test/admin/features/support/page_objects/restarts_page.rb
  test/admin/features/support/page_objects/upload_and_view_forms_page.rb
  test/admin/features/support/page_objects/upload_pupil_census_page.rb
Labels: CI Enabled, Requires sign off, Reviewed & approved, Testing

#704 Bug/21673 Provide missing related links
  admin/views/groups/groups.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  test/admin/features/generate_pupil_pins.feature
  test/admin/features/pupil_not_taking_check.feature
  test/admin/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin/features/step_definitions/pupil_not_taking_check.rb
  test/admin/features/support/page_objects/generate_pins_overview_page.rb
  test/admin/features/support/page_objects/group_pupils_page.rb
  test/admin/features/support/page_objects/pupils_not_taking_check_page.rb
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested

#697 Feature/21354 disable form assign after check startdate
  admin/controllers/check-form.js
  admin/services/check-window.service.js
  admin/services/data-access/check-window.data.service.js
  admin/spec/controllers/check-form.spec.js
  test/admin/features/assign_check_to_windows.feature
  test/admin/features/step_definitions/assign_check_window_steps.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#703 Feature/21518 full school dataset migration
  admin/NCATools_EduBase_20180604.txt
  admin/bin/generate-migration-from-schooldata.js
  admin/config.js
  admin/data/sql/migrations/100.do.add-school-dataset.js
  admin/data/sql/migrations/100.undo.add-school-dataset.sql
Labels: Ready for review, Reviewed & approved

#701 feature/21038 Fixed the headers for downloading the error CSV file on pupil
  admin/app.js
  admin/controllers/pupil.js
Labels: CI Enabled, Requires sign off, Reviewed & approved, Signed Off, Tested

#706 Bug/19468 Pressing escape key should hide the modal when it is visible
  admin/assets/javascripts/jquery-modal.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#718 Feature/21602 add csrf admin
  admin/app.js
Labels: CI Enabled, Ready for review

#713 bug/21745 Disabled scroll effects on the pupil pin 'number' input
  pupil-spa/src/app/login/login.component.css
  pupil-spa/src/app/login/login.component.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#717 Prevent double-tap on MS touchscreen devices (IE and Edge) from Zooming in
  pupil-spa/src/assets/shared-styles/styles.scss
Labels: CI Enabled, Ready for review, Signed Off, Tested

#716 Bug/21668 teacher1 can edit teacher2 pupil data
  admin/controllers/pupil-pin.js
  admin/controllers/pupil.js
  admin/controllers/pupils-not-taking-the-check.js
  admin/controllers/questions.js
  admin/controllers/restart.js
  admin/services/attendance.service.js
  admin/services/check-start.service.js
  admin/services/data-access/psychometrician.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/pin-generation.service.js
  admin/services/pin.service.js
  admin/services/psychometrician-report.service.js
  admin/services/pupil.service.js
  admin/services/restart.service.js
  admin/spec/controllers/pupil.spec.js
  admin/spec/service/attendance-service.spec.js
  admin/spec/service/check-start.service.spec.js
  admin/spec/service/data-access/pupil.data.service.spec.js
  admin/spec/service/pin-generation.service.spec.js
  admin/spec/service/pin.service.spec.js
  admin/spec/service/psychometrician-report.service.spec.js
  admin/spec/service/pupil.service.spec.js
  admin/spec/service/restart.service.spec.js
  load-test/bin/generate-pupil-load-test-data.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#712 Feature/21346 Update question and loading time defaults
  admin/config.js
  admin/data/sql/migrations/101.do.update-default-time-settings.sql
  admin/data/sql/migrations/101.undo.update-default-time-settings.sql
  admin/spec/service/config.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#707 feature/12609 Updated cookie banner
  admin/assets/stylesheets/application.scss
  admin/public/govuk_template/javascripts/govuk-template.js
  admin/views/partials/_cookie_message.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#715 Feature/21759 Update feedback link
  admin/views/partials/_content.ejs
  test/admin/features/step_definitions/manage_check_forms_steps.rb
  test/admin/features/step_definitions/phase_banner_steps.rb
  test/admin/features/support/page_objects/phase_banner_section.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#722 21845 - Disabled pupil pin change with arrow keys
  pupil-spa/src/app/login/login.component.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#728 21927 - Add mapping for ncaUserRole `SchoolNomAA` to map to `TEACHER` role
  admin/services/role.service.js
Labels: hot fix

#727 Fix regression that prevent scrolling on tablets using touch input
  pupil-spa/src/assets/shared-styles/styles.scss
Labels: Reviewed & approved, Signed Off, Tested

#731 22015 - Increase timeout for pupil data generation to 5 minutes
  admin/controllers/check-form.js
  admin/views/test-developer/download-pupil-check-data.ejs
Labels: CI Enabled, Ready for review

#726 Bug/18787 No forms uploaded indication
  admin/views/test-developer/upload-and-view-forms.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#729 21941 - Add mapping for ncaUserRole `SchoolNomAA` to map to `TEACHER` role
  admin/services/role.service.js
Labels: CI Enabled, Reviewed & approved

#730 Bug/18783 Display form name
  admin/controllers/check-form.js
  admin/spec/controllers/check-form.spec.js
  admin/views/test-developer/view-check-form.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#734 22019 - Increase timeout for pupil data generation to 5 minutes
  admin/controllers/check-form.js
  admin/views/test-developer/download-pupil-check-data.ejs
Labels: CI Enabled, Ready for review

#736 Enclosed the message in a <p> tag and made it navigable through tab
  pupil-spa/src/app/login-success/login-success.component.html
Labels: Reviewed & approved, Signed Off, Tested

#721 Bug/18778 upload multiple files
  admin/controllers/check-form.js
  admin/spec/controllers/check-form.spec.js
  admin/views/test-developer/upload-and-view-forms.ejs
  admin/views/test-developer/upload-new-form.ejs
  test/admin/features/support/page_objects/upload_and_view_forms_page.rb
Labels: Reviewed & approved, Signed Off, Tested

#740 set flag to treat errors as exceptions
  admin/config.js
  admin/controllers/check-form.js
  admin/helpers/logger.js
  admin/services/check-processing.service.js
Labels: Ready for review
