Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2018-12, with the labels that each got.

#912 Feature/26672 pupil views with font size
  pupil-spa/src/app/aa-settings/aa-settings.component.spec.ts
  pupil-spa/src/app/aa-settings/aa-settings.component.ts
  pupil-spa/src/app/check-complete/check-complete.component.html
  pupil-spa/src/app/check-complete/check-complete.component.ts
  pupil-spa/src/app/instructions/instructions.component.html
  pupil-spa/src/app/instructions/instructions.component.ts
  pupil-spa/src/app/services/speech/speech.service.ts
  pupil-spa/src/app/warmup-complete/warmup-complete.component.html
  pupil-spa/src/app/warmup-complete/warmup-complete.component.ts
  pupil-spa/src/app/warmup-intro/warmup-intro.component.html
  pupil-spa/src/app/warmup-intro/warmup-intro.component.ts
  pupil-spa/src/assets/shared-styles/elements/_aa-variables.scss
  pupil-spa/src/assets/shared-styles/elements/_check.scss
  pupil-spa/src/assets/shared-styles/elements/_colour-contrast.scss
  pupil-spa/src/assets/shared-styles/elements/_font-size-copy.scss
  pupil-spa/src/assets/shared-styles/elements/_virtual-keyboard.scss
  pupil-spa/src/assets/shared-styles/styles.scss
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#911 Feature/26679 Refresh preparedCheck when admin updates access arrangements
  admin/data/sql/migrations/184.do.create-vew-pupils-with-active-pins.sql
  admin/data/sql/migrations/184.undo.create-vew-pupils-with-active-pins.sql
  admin/services/access-arrangements.service.js
  admin/services/data-access/pin-generation.data.service.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/services/prepared-check-sync.service.js
  admin/services/pupil-access-arrangements.service.js
  admin/spec/back-end/service/access-arrangements.service.spec.js
  admin/spec/back-end/service/prepared-check-sync.service.spec.js
  admin/spec/back-end/service/pupil-access-arrangements.service.spec.js
  functions/lib/azure-storage-helper.js
  functions/lib/prepared-check-schema-validator.js
  functions/prepare-check/index.js
  functions/prepare-check/index.spec.js
  functions/prepared-check-sync/access-arrangements-sql-util.js
  functions/prepared-check-sync/function.json
  functions/prepared-check-sync/index.js
  functions/prepared-check-sync/message-validator.js
  functions/prepared-check-sync/v1.js
  functions/prepared-check-sync/v1.spec.js
  functions/pupil-login/v1.spec.js
  test/admin-hpa/features/access_arrangements.feature
  test/admin-hpa/features/generate_pupil_pin_familiarisation.feature
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/pupil_status.feature
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/step_definitions/view_and_custom_print_for_live_check_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/access_arrangements_page.rb
Labels: Reviewed & approved, Signed Off, Tested

#918 feature/26631 Pupil prefs queue submission to prepared-check-sync
  functions/lib/sql-helper.js
  functions/prepared-check-sync/v1.js
  functions/prepared-check-sync/v1.spec.js
  functions/pupil-prefs/index.js
  functions/pupil-prefs/message-validator.js
  functions/pupil-prefs/v1.js
  functions/pupil-prefs/v1.spec.js
  pupil-spa/src/app/services/pupil-prefs/pupil-prefs.service.spec.ts
  pupil-spa/src/app/services/pupil-prefs/pupil-prefs.service.ts
  test/pupil-hpa/features/access_arrangements.feature
  test/pupil-hpa/features/step_definitions/access_arrangement_steps.rb
  test/pupil-hpa/features/support/page_objects/access_arrangements_page.rb
  test/pupil-hpa/features/support/page_objects/access_arrangements_setting_page.rb
  test/pupil-hpa/features/support/page_objects/colour_contrast_page.rb
  test/pupil-hpa/features/support/page_objects/font_size_page.rb
  test/pupil-hpa/features/support/page_objects/select_access_arrangements_page.rb
  test/pupil/features/step_definitions/access_arrangement_steps.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#926 load test prep for usage with flood
  .editorconfig
  deploy/sql-migrations/seed-db.sh
  load-test/.gitignore
  load-test/README.md
  load-test/bin/generate-pupil-api-logins.js
  load-test/bin/generate-pupil-data.js
  load-test/exec.sh
  load-test/notes/pin-gen-page.html
  load-test/notes/tips.txt
  load-test/scenarios/admin-generate-pins.jmx
  load-test/scenarios/data/admin_load_test_data.csv
  load-test/scenarios/data/userLogins.csv
  load-test/scenarios/mtc_pupil_check_perf_test.jmx
  load-test/scenarios/pupil-login-start-complete/pupil-login-start-complete.jmx
  load-test/scenarios/pupil-login-start-complete/pupilLogins.csv
  load-test/scenarios/pupil-login-start-complete/questions.json
  load-test/scenarios/pupil-login-start-complete/tokens.json
  load-test/scenarios/z_archive/admin-generate-pins.jmx
Labels: CI NOT Required, Ready for review

#919 27017 - Updated AppUsageService to load counter from local storage
  pupil-spa/src/app/services/app-usage/app-usage.service.spec.ts
  pupil-spa/src/app/services/app-usage/app-usage.service.ts
  pupil-spa/src/app/services/check-complete/check-complete.service.spec.ts
  pupil-spa/src/app/services/check-complete/check-complete.service.ts
  pupil-spa/src/app/services/submission/submission.service.spec.ts
  pupil-spa/src/app/services/submission/submission.service.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.spec.ts
  test/pupil-hpa/features/device_information.feature
  test/pupil-hpa/features/step_definitions/device_steps.rb
  test/pupil-hpa/features/support/hooks.rb
Labels: Reviewed & approved, Signed Off, Tested

#925 Bug/26814 hpa restart count is also counting the familiarisation check
  admin/bin/init-dev-storage.js
  admin/controllers/restart.js
  admin/data/sql/migrations/20181130165738.do.add-view-for-count-of-checks-taken.sql
  admin/data/sql/migrations/20181130165738.undo.add-view-for-count-of-checks-taken.sql
  admin/data/sql/seed-sql.js
  admin/services/data-access/pupil-restart.data.service.js
  admin/services/data-access/restart-v2.data.service.js
  admin/services/data-access/sql.service.js
  admin/services/restart-v2.service.js
  admin/services/restart.service.js
  admin/spec/back-end/service/restart.service.spec.js
  admin/views/restart/restart-overview.ejs
  deploy/storage/create-items.sh
  deploy/storage/tables-queues.json
  functions/check-expiry/v1.js
  functions/check-started/index.js
  functions/completed-checks/index.js
  functions/lib/sql-helper.js
  functions/prepare-check/index.js
  functions/prepared-check-delete/function.json
  functions/prepared-check-delete/index.js
  functions/prepared-check-delete/message-schema/v1.json
  functions/prepared-check-delete/v1.js
  functions/pupil-login/v1.js
Labels: Reviewed & approved, Signed Off, Tested

#924 Feature/27090 Upload check form UI v2
  admin/app.js
  admin/controllers/check-form-v2.js
  admin/controllers/check-form.js
  admin/lib/azure-upload.js
  admin/routes/check-form.js
  admin/services/certificate-store.service.js
  admin/services/data-access/azure-blob.data.service.js
  admin/spec/back-end/controllers/check-form-v2.spec.js
  admin/spec/back-end/controllers/check-window.spec.js
  admin/spec/back-end/service/certificate-store.service.spec.js
  admin/views/check-form/upload-new-forms.ejs
  admin/views/check-form/view-forms.ejs
  admin/views/test-developer/test-developer-home.ejs
  test/admin-hpa/features/step_definitions/upload_view_forms_v2_steps.rb
  test/admin-hpa/features/support/page_objects/upload_and_view_forms_v2_page.rb
  test/admin-hpa/features/support/page_objects/upload_new_forms_page.rb
  test/admin-hpa/features/upload_view_forms_v2.feature
Labels: CI Enabled, Reviewed & approved, Testing

#927 Feature/26400 school staff views updated pupil register
  admin/controllers/pupil-register.js
  admin/data/sql/create-migration.js
  admin/data/sql/create-seed.js
  admin/data/sql/migrations/20181206134835.do.create-pupil-register-view.sql
  admin/data/sql/migrations/20181206134835.undo.create-pupil-register-view.sql
  admin/services/data-access/pupil-register.data.service.js
  admin/services/pupil-register.service.js
  admin/services/pupil.status.service.js
  admin/spec/back-end/service/pupil-register.service.spec.js
  functions/pupil-status/index.js
Labels: CI Enabled, Reviewed & approved

#917 Feature/23751 pupil api improvements
  .travis.yml
  pupil-api/package.json
  pupil-api/readme.md
  pupil-api/src/App.ts
  pupil-api/src/config.ts
  pupil-api/src/helpers/cors-options.ts
  pupil-api/src/helpers/logger.ts
  pupil-api/src/index.ts
  pupil-api/src/swagger.json
  pupil-api/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off, Testing

#929 Feature/27352 update node modules packages
  admin/README.md
  admin/package.json
  admin/services/pin-generation-v2.service.js
  admin/spec/back-end/controllers/check-started.spec.js
  admin/spec/back-end/controllers/completed-check.spec.js
  admin/spec/back-end/controllers/pupil-feedback.spec.js
  admin/spec/back-end/controllers/pupil.spec.js
  admin/spec/back-end/controllers/pupils-not-taking-the-check.spec.js
  admin/spec/back-end/controllers/school.spec.js
  admin/spec/back-end/lib/validator/file-validator.spec.js
  admin/spec/back-end/lib/validator/pin-validator.spec.js
  admin/spec/back-end/lib/validator/pupil-validator.spec.js
  admin/spec/back-end/service/data-access/check.data.service.spec.js
  admin/spec/back-end/service/data-access/school.data.service.spec.js
  admin/spec/back-end/service/data-access/setting-log.data.service.spec.js
  admin/spec/back-end/service/data-access/setting.data.service.spec.js
  admin/spec/back-end/service/generate-error-csv.service.spec.js
  admin/spec/back-end/service/group.service.spec.js
  admin/spec/back-end/service/pin-generation.service.spec.js
  admin/spec/back-end/service/pin.service.spec.js
  admin/spec/back-end/service/pupil-upload.service.spec.js
  admin/spec/back-end/service/restart.service.spec.js
  admin/spec/back-end/service/setting.service.spec.js
  admin/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off

#934 HOTFIX: rollback to winston v2
  admin/package.json
  admin/yarn.lock
Labels: CI Enabled, Ready for review

#933 Feature/27372 restarts pupils should only ever have one row
  admin/data/sql/migrations/20181210130149.do.alter-pupils-eligible-for-restart-view.sql
  admin/data/sql/migrations/20181210130149.undo.alter-pupils-eligible-for-restart-view.sql
  admin/services/data-access/pupil-restart.data.service.js
  admin/services/data-access/restart-v2.data.service.js
  admin/services/restart.service.js
  admin/spec/back-end/service/restart.service.spec.js
Labels: CI Enabled, Reviewed & approved, Tested

#936 Feature/23642 sorting not working on ie11 and edge 15
  admin/assets/javascripts/table-sorting.js
  admin/views/pupil-register/pupils-list.ejs
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested

#935 remove https patch as now included in azure
  admin/app.js
Labels: CI Enabled, Ready for review

#937 Add optional newrelic monitoring module
  admin/app.js
  admin/azure.js
  admin/config.js
  admin/helpers/app-insights.js
  admin/helpers/index.js
  admin/helpers/logger.js
  admin/newrelic.js
  admin/package.json
  admin/yarn.lock
Labels: CI Enabled, Ready for review

#938 update app insights to 1.0.8
  admin/helpers/app-insights.js
  admin/yarn.lock
Labels: CI Enabled, Ready for review

#940 Fix cron expression that fails on Azure
  functions/check-expiry/function.json
Labels: CI NOT Required

#939 Fixed empty 20181129110139.undo.recreate-view-pupils-eligible-for-fam…
  admin/data/sql/migrations/20181129110139.undo.recreate-view-pupils-eligible-for-familiarisation-pin.sql
Labels: Ready for review

#941 Bug/27484 Migrations exit code
  admin/data/sql/migrate-sql.js
Labels: CI Enabled, Ready for review

#931 Bug/26819 aa numpad removal answer box
  test/pupil-hpa/features/access_arrangements.feature
  test/pupil-hpa/features/check.feature
  test/pupil-hpa/features/step_definitions/access_arrangement_steps.rb
  test/pupil-hpa/features/step_definitions/check_steps.rb
  test/pupil-hpa/features/step_definitions/pin_expiry_steps.rb
  test/pupil-hpa/features/step_definitions/warm_up_steps.rb
  test/pupil-hpa/features/support/page_objects/access_arrangements_setting_page.rb
  test/pupil-hpa/features/support/page_objects/confirmation_page.rb
  test/pupil-hpa/features/support/page_objects/mtc_check_start_page.rb
  test/pupil-hpa/features/support/page_objects/start_page.rb
  test/pupil-hpa/features/support/page_objects/warm_up_complete_page.rb
  test/pupil-hpa/features/support/page_objects/warm_up_page.rb
  test/pupil-hpa/features/warm_up_questions.feature
  test/pupil/features/check.feature
  test/pupil/features/step_definitions/check_steps.rb
  test/pupil/features/support/page_objects/access_arrangements_setting_page.rb
  test/pupil/features/support/page_objects/colour_contrast_page.rb
  test/pupil/features/support/page_objects/confirmation_page.rb
  test/pupil/features/support/page_objects/mtc_check_start_page.rb
  test/pupil/features/support/page_objects/start_page.rb
  test/pupil/features/support/page_objects/warm_up_complete_page.rb
  test/pupil/features/support/page_objects/warm_up_page.rb
  test/pupil/features/warm_up_questions.feature
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested

#930 Added tests for uploading multiple forms
  test/admin-hpa/features/step_definitions/upload_view_forms_steps.rb
  test/admin-hpa/features/upload_view_forms.feature
  test/admin/features/step_definitions/upload_view_forms_steps.rb
  test/admin/features/upload_view_forms.feature
Labels: CI Enabled, Reviewed & approved, Tested

#943 Feature/27189 flood load testing updates
  admin/services/check-start.service.js
  load-test/README.md
  load-test/bin/create-teacher-logins-csv.js
  load-test/bin/undo-generate-pupil-load-test-data.sql
  load-test/scenarios-v4/teacher-generate-pins.jmx
  load-test/scenarios-v5/teacherLogins.csv
  load-test/scenarios-v5/z_archive/admin-generate-pins.jmx
  load-test/scenarios/pupil-take-check/pupil-login-start-complete.jmx
  load-test/scenarios/pupil-take-check/pupilLogins.csv
  load-test/scenarios/pupil-take-check/questions.json
  load-test/scenarios/pupil-take-check/tokens.json
  load-test/scenarios/teacher-generate-pins/0-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/1-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/10-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/11-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/12-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/13-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/14-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/15-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/16-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/17-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/2-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/3-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/4-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/5-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/6-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/7-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/8-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/9-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/all-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/teacher-generate-pins.jmx
Labels: CI Enabled, Ready for review

#942 Add missing space in SPA question
  pupil-spa/src/app/question/question.component.html
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested

#947 Feature/27189 flood settings
  load-test/scenarios/teacher-generate-pins/0-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/1-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/10-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/11-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/12-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/13-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/14-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/15-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/16-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/17-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/2-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/3-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/4-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/5-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/6-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/7-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/8-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/9-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/all-teacherLogins.csv
  load-test/scenarios/teacher-generate-pins/teacher-generate-pins.jmx
Labels: CI NOT Required

#950 Feature/27594 send all pupils as one preparecheck message
  admin/data/sql/migrations/20181219120830.do.alter-pupil-register-view-to-only-use-live-checks.sql
  admin/data/sql/migrations/20181219120830.undo.alter-pupil-register-view-to-only-use-live-checks.sql
  admin/services/azure-queue.service.js
  admin/services/check-start.service.js
  admin/spec/back-end/service/check-start.service.spec.js
  functions/check-started/index.js
  functions/lib/prepared-check-schema-validator.js
  functions/package.json
  functions/prepare-check/index.js
  functions/prepare-check/index.spec.js
  functions/prepare-check/message-schema/message.v1.json
  functions/prepare-check/message-schema/message.v2.json
  functions/prepare-check/prepare-entity.js
  functions/prepare-check/v1.js
  functions/prepare-check/v2.js
  functions/pupil-status/index.js
  functions/pupil-status/message-schema/message.v2.json
  functions/pupil-status/pupil-status-analysis.service.js
  functions/pupil-status/pupil-status-analysis.service.spec.js
  functions/pupil-status/pupil-status-batch.service.js
  functions/pupil-status/pupil-status.service.js
  functions/pupil-status/v1.js
  functions/pupil-status/v2.js
Labels: CI Enabled, Reviewed & approved, Signed Off, expedited

#946 Bug/27392 pupils with reasons for not taking the check excluded from familiarisation check
  admin/data/sql/migrations/20181214125314.do.alter-pupils-eligible-for-familiarisation-pin-gen-view.sql
  admin/data/sql/migrations/20181214125314.undo.alter-pupils-eligible-for-familiarisation-pin-gen-view.sql
  admin/data/sql/migrations/20181214130415.do.fix-vewpupilseligibleforlivepingeneration.sql
  admin/data/sql/migrations/20181214130415.undo.fix-vewpupilseligibleforlivepingeneration.sql
  admin/data/sql/migrations/20181214130817.do.fix-vewpupilseligibleforrestart.sql
  admin/data/sql/migrations/20181214130817.undo.fix-vewpupilseligibleforrestart.sql
Labels: Reviewed & approved, Signed Off, Tested

#954 Bug/27798 disable auditlog trigger on sessions adminlogonevent tables
  admin/data/sql/migrations/20181220193807.do.drop-session-trigger.sql
  admin/data/sql/migrations/20181220193807.undo.drop-session-trigger.sql
  admin/data/sql/migrations/20181220194954.do.drop-logonevent-trigger.sql
  admin/data/sql/migrations/20181220194954.undo.drop-logonevent-trigger.sql
  admin/data/sql/migrations/20181220195613.do.alter-sp-gen-audit-triggers.sql
  admin/data/sql/migrations/20181220195613.undo.alter-sp-gen-audit-triggers.sql
Labels: CI Enabled, Ready for review, bug, expedited

#952 Feature/27091 Checkform v2: forms list & actions
  admin/controllers/check-form-v2.js
  admin/data/sql/migrations/20181211135657.do.add-check-form-urlslug.sql
  admin/data/sql/migrations/20181211135657.undo.add-check-form-urlslug.sql
  admin/helpers/check-form-presenter.js
  admin/lib/errors/check-form.js
  admin/lib/validator/check-form/single-check-form-validator.js
  admin/routes/check-form.js
  admin/services/check-form-v2.service.js
  admin/services/data-access/check-form-v2.data.service.js
  admin/spec/back-end/controllers/check-form-v2.spec.js
  admin/spec/back-end/helpers/check-form-presenter.spec.js
  admin/spec/back-end/service/check-form-v2.service.spec.js
  admin/views/check-form/view-form.ejs
  admin/views/check-form/view-forms.ejs
  test/admin-hpa/features/step_definitions/upload_view_forms_v2_steps.rb
  test/admin-hpa/features/support/page_objects/upload_and_view_forms_v2_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/admin-hpa/features/upload_view_forms_v2.feature
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#956 Replace `viewPupilsEligibleForLivePinGeneration` with more performant…
  admin/data/sql/migrations/20181221053829.do.create-more-performant-vewpupilseligibleforfamiliarisationpingeneration.sql
  admin/data/sql/migrations/20181221053829.undo.create-more-performant-vewpupilseligibleforfamiliarisationpingeneration.sql
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#959 Change default error level to 'error'
  admin/config.js
Labels: CI Enabled, Reviewed & approved

#961 Prevent session calls for static files
  admin/app.js
Labels: CI Enabled, Reviewed & approved
