Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2018-09, with the labels that each got.

#801 Feature/23438 prepare check improvements pt 2
  admin/package.json
  admin/services/anomaly-report.service.js
  admin/services/check-start.service.js
  admin/services/data-access/anomaly-report-cache.data.service.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/spec/back-end/controllers/check-form.spec.js
  admin/spec/back-end/controllers/completed-check.spec.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/spec/back-end/mocks/check-form-allocation.js
  admin/spec/back-end/mocks/check-window-2.js
  admin/spec/back-end/mocks/check-windows.js
  admin/spec/back-end/service/access-arrangements.service.spec.js
  admin/spec/back-end/service/check-start.service.spec.js
  admin/spec/front-end/pupil-access-arrangements-selection.spec.js
  admin/tests-integration/run-jasmine-integration.js
  admin/yarn.lock
  functions/prepare-check/index.js
  test/admin/features/download_pupil_check_data.feature
  test/admin/features/step_definitions/download_pupil_check_data_steps.rb
  test/admin/features/support/page_objects/download_pupil_check_data_page.rb
Labels: CI Enabled, Reviewed & approved, Tested

#803 Feature/23740 Add additional column for deleting action on overview page
  admin/assets/stylesheets/elements/_access-arrangements.scss
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/views/access-arrangements/overview.ejs
  test/admin/features/access_arrangements.feature
  test/admin/features/step_definitions/access_arrangements_steps.rb
  test/admin/features/support/hooks.rb
  test/admin/features/support/page_objects/access_arrangements_page.rb
  test/admin/features/support/page_objects/select_access_arrangements_page.rb
  test/admin/features/support/sql_db_helper.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#804 Feature/22856 pupil logs in via dedicated pupil api
  pupil-spa/gen_config.sh
  pupil-spa/package-lock.json
  pupil-spa/package.json
  pupil-spa/src/app/login-success/login-success.component.spec.ts
  pupil-spa/src/app/login/login.component.ts
  pupil-spa/src/app/practice-question/practice-question.component.spec.ts
  pupil-spa/src/app/services/config/config.service.spec.ts
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/services/storage/storage.service.ts
  pupil-spa/src/app/services/submission/submission.service.spec.ts
  pupil-spa/src/app/services/user/user.service.spec.ts
  pupil-spa/src/app/services/user/user.service.ts
  pupil-spa/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#806 Feature/23786 greenbar dynamic sizing
  admin/assets/stylesheets/elements/_flash-messages.scss
  admin/views/access-arrangements/overview.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#814 Fix `ng build --prod`
  pupil-spa/src/app/practice-question/practice-question.component.ts
Labels: Ready for review

#816 Bug/24146 migration 113 undo contains invalid sql
  admin/data/sql/migrations/076.undo.gen-triggers.sql
  admin/data/sql/migrations/081.undo.alter-pupilAttendance-isDeleted-column.sql
  admin/data/sql/migrations/088.undo.create-job-table.sql
  admin/data/sql/migrations/099.undo.alter-user-identifier.sql
  admin/data/sql/migrations/102.undo.add-check-window-urlslug.sql
  admin/data/sql/migrations/112.undo.create-pupil-access-arrangements.sql
  admin/data/sql/migrations/113.undo.add-access-arrangements-id-field.sql
Labels: CI Enabled, Ready for review

#805 Feature/20482 spa configurable font sizes
  admin/services/config.service.js
  admin/spec/back-end/service/config.service.spec.js
  pupil-spa/src/app/access-arrangements.ts
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/check-complete/check-complete.component.html
  pupil-spa/src/app/check/check.component.html
  pupil-spa/src/app/config.model.ts
  pupil-spa/src/app/familiarisation-area/familiarisation-area.component.html
  pupil-spa/src/app/familiarisation-area/familiarisation-area.component.scss
  pupil-spa/src/app/familiarisation-area/familiarisation-area.component.spec.ts
  pupil-spa/src/app/familiarisation-area/familiarisation-area.component.ts
  pupil-spa/src/app/familiarisation-colour/familiarisation-colour.component.html
  pupil-spa/src/app/familiarisation-colour/familiarisation-colour.component.scss
  pupil-spa/src/app/familiarisation-colour/familiarisation-colour.component.spec.ts
  pupil-spa/src/app/familiarisation-colour/familiarisation-colour.component.ts
  pupil-spa/src/app/familiarisation-settings/familiarisation-settings.component.html
  pupil-spa/src/app/familiarisation-settings/familiarisation-settings.component.scss
  pupil-spa/src/app/familiarisation-settings/familiarisation-settings.component.spec.ts
  pupil-spa/src/app/familiarisation-settings/familiarisation-settings.component.ts
  pupil-spa/src/app/instructions/instructions.component.html
  pupil-spa/src/app/login-success/login-success.component.css
  pupil-spa/src/app/login-success/login-success.component.html
  pupil-spa/src/app/login-success/login-success.component.spec.ts
  pupil-spa/src/app/login-success/login-success.component.ts
  pupil-spa/src/app/login/login.component.spec.ts
  pupil-spa/src/app/login/login.component.ts
  pupil-spa/src/app/page-modifications/page-modifications.component.html
  pupil-spa/src/app/page-modifications/page-modifications.component.scss
  pupil-spa/src/app/page-modifications/page-modifications.component.spec.ts
  pupil-spa/src/app/page-modifications/page-modifications.component.ts
  pupil-spa/src/app/practice-question/practice-question.component.spec.ts
  pupil-spa/src/app/practice-question/practice-question.component.ts
  pupil-spa/src/app/question/question.component.html
  pupil-spa/src/app/question/question.component.spec.ts
  pupil-spa/src/app/question/question.component.ts
  pupil-spa/src/app/services/question/question.service.ts
  pupil-spa/src/app/services/question/warmup-question.service.ts
  pupil-spa/src/app/services/storage/storage.service.ts
  pupil-spa/src/app/spoken-practice-question/spoken-practice-question.component.spec.ts
  pupil-spa/src/app/spoken-practice-question/spoken-practice-question.component.ts
  pupil-spa/src/app/spoken-question/spoken-question.component.spec.ts
  pupil-spa/src/app/spoken-question/spoken-question.component.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.html
  pupil-spa/src/app/submission-pending/submission-pending.component.html
  pupil-spa/src/app/warmup-intro/warmup-intro.component.html
  pupil-spa/src/assets/shared-styles/elements/_font-size-copy.scss
  pupil-spa/src/assets/shared-styles/elements/_virtual-keyboard.scss
  pupil-spa/src/assets/shared-styles/styles.scss
  test/pupil/features/support/page_objects/check_page.rb
  test/pupil/features/support/page_objects/confirmation_page.rb
  test/pupil/features/support/page_objects/warm_up_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#810 Feature/23412 check started function persist to pupilevent table storage
  functions/.gitignore
  functions/check-started/index.js
  functions/check-started/readme.md
  functions/check-started/sample-data.json
  functions/config.js
  functions/host.json
  functions/mock-context.js
  functions/package.json
  functions/prepare-check/index.spec.js
  functions/readme.md
  functions/yarn.lock
Labels: CI Enabled, Reviewed & approved

#808 Feature/23824 ict survey thank you feedback pages
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/connection-test/connection-test.component.html
  pupil-spa/src/app/connection-test/connection-test.component.scss
  pupil-spa/src/app/connection-test/connection-test.component.spec.ts
  pupil-spa/src/app/connection-test/connection-test.component.ts
  pupil-spa/src/app/preview-completed/preview-completed.component.html
  pupil-spa/src/app/preview-completed/preview-completed.component.scss
  pupil-spa/src/app/preview-completed/preview-completed.component.spec.ts
  pupil-spa/src/app/preview-completed/preview-completed.component.ts
  pupil-spa/src/app/survey-feedback-thanks/survey-feedback-thanks.component.html
  pupil-spa/src/app/survey-feedback-thanks/survey-feedback-thanks.component.scss
  pupil-spa/src/app/survey-feedback-thanks/survey-feedback-thanks.component.spec.ts
  pupil-spa/src/app/survey-feedback-thanks/survey-feedback-thanks.component.ts
  pupil-spa/src/app/survey-feedback/survey-feedback.component.html
  pupil-spa/src/app/survey-feedback/survey-feedback.component.scss
  pupil-spa/src/app/survey-feedback/survey-feedback.component.spec.ts
  pupil-spa/src/app/survey-feedback/survey-feedback.component.ts
  pupil-spa/src/app/test-completed/test-completed.component.html
  pupil-spa/src/app/test-completed/test-completed.component.scss
  pupil-spa/src/app/test-completed/test-completed.component.spec.ts
  pupil-spa/src/app/test-completed/test-completed.component.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#817 remove logdna from admin app
  admin/helpers/logger.js
  admin/package.json
  admin/yarn.lock
Labels: CI Enabled, Ready for review

#812 Feature/21360 Check pages content updates
  pupil-spa/src/app/check-complete/check-complete.component.html
  pupil-spa/src/app/submission-failed/submission-failed.component.html
  pupil-spa/src/app/submission-failed/submission-failed.component.scss
  pupil-spa/src/app/submission-pending/submission-pending.component.html
  pupil-spa/src/app/submission-pending/submission-pending.component.scss
  pupil-spa/src/app/submission-pending/submission-pending.component.spec.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.ts
  test/pupil/features/support/page_objects/complete_page.rb
Labels: Reviewed & approved, Signed Off, Tested

#809 Feature/24014 check windows hub page
  admin/app.js
  admin/config/feature-toggles.Azure-UAT.json
  admin/config/feature-toggles.default.json
  admin/controllers/check-window.js
  admin/controllers/service-manager.js
  admin/routes/check-window.js
  admin/spec/back-end/controllers/check-window.spec.js
  admin/views/check-window/manage-check-windows.ejs
  admin/views/service-manager/service-manager-home.ejs
  test/admin/features/manage_check_window.feature
  test/admin/features/step_definitions/manage_check_windows.rb
  test/admin/features/step_definitions/service_manager_landing_steps.rb
  test/admin/features/support/page_objects/admin_page.rb
  test/admin/features/support/page_objects/manage_check_window_page.rb
Labels: Reviewed & approved, Signed Off, Tested

#819 Feature/23411 complete check function persist to pupilevent table storage
  admin/data/sql/migrations/116.do.create-check-result-table.sql
  admin/data/sql/migrations/116.undo.create-check-result-table.sql
  admin/services/check-start.service.js
  admin/services/data-access/check-form-allocation.data.service.js
  admin/spec/back-end/mocks/check-form-allocation.js
  admin/spec/back-end/service/access-arrangements.service.spec.js
  admin/spec/back-end/service/check-start.service.spec.js
  functions/check-started/index.js
  functions/completed-checks/index.js
  functions/lib/azure-storage-helper.js
  functions/prepare-check/index.js
Labels: Reviewed & approved

#821 feature/24184 - skeleton pupil status function
  deploy/storage/create-items.sh
  functions/pupil-status/function.json
  functions/pupil-status/index.js
  functions/pupil-status/readme.md
Labels: Blocked, Ready for review

#811 Feature/23827 preview check
  .travis.yml
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/check/check.component.html
  pupil-spa/src/app/check/check.component.spec.ts
  pupil-spa/src/app/check/check.component.ts
  pupil-spa/src/app/config.model.ts
  pupil-spa/src/app/connection-test/connection-test.component.spec.ts
  pupil-spa/src/app/connection-test/connection-test.component.ts
  pupil-spa/src/app/login/login.component.spec.ts
  pupil-spa/src/app/login/login.component.ts
  pupil-spa/src/app/preview-completed/preview-completed.component.spec.ts
  pupil-spa/src/app/preview-completed/preview-completed.component.ts
  pupil-spa/src/app/questions-intro/questions-intro.component.spec.ts
  pupil-spa/src/app/questions-intro/questions-intro.component.ts
  pupil-spa/src/app/services/question/question.service.spec.ts
  pupil-spa/src/app/services/question/question.service.ts
  pupil-spa/src/app/services/question/warmup-question.service.ts
  pupil-spa/src/app/services/storage/storage.service.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.spec.ts
  pupil-spa/src/app/survey-feedback-thanks/survey-feedback-thanks.component.spec.ts
  pupil-spa/src/app/survey-feedback-thanks/survey-feedback-thanks.component.ts
  pupil-spa/src/app/survey-feedback/survey-feedback.component.spec.ts
  pupil-spa/src/app/survey-feedback/survey-feedback.component.ts
  pupil-spa/src/app/survey-welcome/survey-welcome.component.html
  test/pupil/features/ict_survey.feature
  test/pupil/features/step_definitions/ict_survey_steps.rb
  test/pupil/features/support/page_objects/ict_survey_page.rb
  test/pupil/pupil_spa_tests_1.sh
  test/pupil/pupil_spa_tests_2.sh
Labels: Reviewed & approved, Signed Off, Tested

#824 fix api tests and update readme
  api_tests/README.md
  api_tests/spec/security_spec.rb
Labels: Ready to merge, Reviewed & approved, Tested

#818 Feature/22164 submit message to check-started queue
  deploy/storage/create-items.sh
  pupil-spa/angular.json
  pupil-spa/package.json
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/questions-intro/questions-intro.component.spec.ts
  pupil-spa/src/app/questions-intro/questions-intro.component.ts
  pupil-spa/src/app/services/azure-queue/azure-queue.service.spec.ts
  pupil-spa/src/app/services/azure-queue/azure-queue.service.ts
  pupil-spa/src/app/services/azure-queue/azureStorage.ts
  pupil-spa/src/app/services/azure-queue/textBase64QueueMessageEncoder.ts
  pupil-spa/src/app/services/check-start/check-start.service.spec.ts
  pupil-spa/src/app/services/check-start/check-start.service.ts
  pupil-spa/src/app/services/token/token.service.spec.ts
  pupil-spa/src/app/services/token/token.service.ts
  pupil-spa/src/public/azure-storage/azure-storage.queue.min.js
  pupil-spa/yarn.lock
Labels: CI Enabled, Reviewed & approved

#820 Feature/23826 connection test
  pupil-spa/angular.json
  pupil-spa/gen_config.sh
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/connection-test/connection-test.component.spec.ts
  pupil-spa/src/app/connection-test/connection-test.component.ts
  pupil-spa/src/app/footer/footer.component.ts
  pupil-spa/src/app/practice-question/practice-question.component.ts
  pupil-spa/src/app/preview-completed/preview-completed.component.ts
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/services/connection-test/connection-test.service.spec.ts
  pupil-spa/src/app/services/connection-test/connection-test.service.ts
  pupil-spa/src/app/services/device/device.service.ts
  pupil-spa/src/app/services/storage/storage.service.ts
  pupil-spa/src/app/survey-feedback-thanks/survey-feedback-thanks.component.ts
  pupil-spa/src/app/survey-feedback/survey-feedback.component.ts
  pupil-spa/src/app/survey-welcome/survey-welcome.component.ts
  pupil-spa/src/app/test-completed/test-completed.component.spec.ts
  pupil-spa/src/app/test-completed/test-completed.component.ts
  pupil-spa/src/assets/javascripts/azure-storage.queue.min.js
Labels: Reviewed & approved, Signed Off

#826 Feature/23415 feedback function persist to pupil event table storage
  admin/data/sql/migrations/117.do.pupil-feedback-hpa-refactor-part-1.sql
  admin/data/sql/migrations/117.undo.pupil-feedback-hpa-refactor-part-1.sql
  functions/completed-checks/index.js
  functions/feedback/function.json
  functions/feedback/index.js
  functions/feedback/sample.data.json
  functions/lib/sql-helper.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#825 Bug/24021 Detect key presses only when modal is visible
  admin/assets/javascripts/jquery-modal.js
  admin/views/partials/_modal_box.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#827 Feature/23754 pupil api tests
  test/pupil/Gemfile
  test/pupil/Gemfile.lock
  test/pupil/features/pupil_api.feature
  test/pupil/features/step_definitions/pupil_api.rb
  test/pupil/features/support/env.rb
  test/pupil/features/support/helpers.rb
  test/pupil/features/support/request_helper.rb
  test/pupil/features/support/sql_db_helper.rb
Labels: Reviewed & approved, Signed Off, Tested

#828 Feature/24015 Create check window html scaffolding
  admin/assets/stylesheets/elements/_check-windows.scss
  admin/controllers/check-window.js
  admin/routes/check-window.js
  admin/spec/back-end/controllers/check-window.spec.js
  admin/views/check-window/create-check-window.ejs
  admin/views/check-window/manage-check-windows.ejs
  test/admin/features/create_check_window.feature
  test/admin/features/step_definitions/create_window_steps.rb
  test/admin/features/support/page_objects/add_edit_check_window_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#822 Feature/24120 feedback form validation
  pupil-spa/gen_config.sh
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/feedback/feedback.component.spec.ts
  pupil-spa/src/app/services/azure-queue/azure-queue.service.mock.ts
  pupil-spa/src/app/services/azure-queue/azure-queue.service.spec.ts
  pupil-spa/src/app/services/azure-queue/azure-queue.service.ts
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/services/connection-test/connection-test.service.spec.ts
  pupil-spa/src/app/services/connection-test/connection-test.service.ts
  pupil-spa/src/app/services/feedback/feedback.service.spec.ts
  pupil-spa/src/app/services/feedback/feedback.service.ts
  pupil-spa/src/app/survey-feedback/survey-feedback.component.html
  pupil-spa/src/app/survey-feedback/survey-feedback.component.scss
  pupil-spa/src/app/survey-feedback/survey-feedback.component.spec.ts
  pupil-spa/src/app/survey-feedback/survey-feedback.component.ts
  test/pupil/features/ict_feedback.feature
  test/pupil/features/step_definitions/ict_feedback_steps.rb
  test/pupil/features/support/page_objects/ict_feedback_page.rb
  test/pupil/features/support/page_objects/ict_feedback_thanks_page.rb
Labels: Requires sign off, Reviewed & approved, Testing

#832 Feature/24155 privacy page
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/footer/footer.component.html
  pupil-spa/src/app/footer/footer.component.scss
  pupil-spa/src/app/footer/footer.component.ts
  pupil-spa/src/app/privacy/privacy.component.html
  pupil-spa/src/app/privacy/privacy.component.scss
  pupil-spa/src/app/privacy/privacy.component.spec.ts
  pupil-spa/src/app/privacy/privacy.component.ts
  pupil-spa/src/assets/shared-styles/styles.scss
Labels: Signed Off, Tested

#836 Feature/24398 ict survey improvements
  pupil-spa/angular.json
  pupil-spa/gen_config.sh
  pupil-spa/package.json
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/privacy/privacy.component.html
  pupil-spa/src/app/services/azure-queue/azure-queue.service.mock.ts
  pupil-spa/src/app/services/azure-queue/azure-queue.service.ts
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/services/connection-test/connection-test.service.spec.ts
  pupil-spa/src/app/services/connection-test/connection-test.service.ts
  pupil-spa/src/app/services/feedback/feedback.service.spec.ts
  pupil-spa/src/app/services/feedback/feedback.service.ts
  pupil-spa/src/assets/javascripts/azure-storage.table.min.js
  pupil-spa/yarn.lock
Labels: Ready for review

#837 removing empty related section from privacy pagew
  pupil-spa/src/app/privacy/privacy.component.html
Labels: Ready for review, Signed Off, Tested

#838 Feature/24340 sample queue messages
  admin/tables-queues.json
  functions/check-started/sample.data.json
  functions/completed-checks/sample.data.json
  functions/prepare-check/sample.data.json
  functions/pupil-prefs/sample.data.json
  functions/pupil-status/sample.data.json
  messaging.md
Labels: CI NOT Required

#839 Removed contact link from the footer
  pupil-spa/src/app/footer/footer.component.html
  pupil-spa/src/app/footer/footer.component.ts
Labels: Signed Off, Tested

#833 Feature/22166 Submit feedback to queue
  pupil-spa/gen_config.sh
  pupil-spa/src/app/feedback/feedback.component.spec.ts
  pupil-spa/src/app/services/check-complete/check-complete.service.spec.ts
  pupil-spa/src/app/services/check-complete/check-complete.service.ts
  pupil-spa/src/app/services/check-start/check-start.service.ts
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/services/feedback/feedback.service.spec.ts
  pupil-spa/src/app/services/feedback/feedback.service.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#842 adding azure storage gems and classes
  test/pupil/Gemfile
  test/pupil/Gemfile.lock
  test/pupil/README.md
  test/pupil/features/support/azure_blob_helper.rb
  test/pupil/features/support/azure_queue_helper.rb
  test/pupil/features/support/azure_table_helper.rb
  test/pupil/features/support/env.rb
Labels: Reviewed & approved, Tested

#840 Bug/24469 view details not working in safari
  pupil-spa/src/app/survey-welcome/survey-welcome.component.scss
  pupil-spa/src/assets/javascripts/details.polyfill.js
Labels: Ready for review, Signed Off, Tested

#841 Feature/24471 purge queues tables
  .eslintrc
  admin/bin/init-dev-storage.js
  admin/package.json
  deploy/storage/create-items.sh
  deploy/storage/tables-queues.json
Labels: CI NOT Required, Ready for review

#831 Feature/23070 enable toggle of familiarisation live check
  admin/.gitignore
  admin/bin/generate-dependency-graphs.sh
  admin/controllers/check-started.js
  admin/controllers/pupil-pin.js
  admin/controllers/questions.js
  admin/data/sql/migrations/118.do.move-pupil-pins-to-check.sql
  admin/data/sql/migrations/118.undo.move-pupil-pins-to-check.sql
  admin/package.json
  admin/services/check-complete.service.js
  admin/services/check-start.service.js
  admin/services/check-state.service.js
  admin/services/data-access/check-form-allocation.data.service.js
  admin/services/data-access/check-status.data.service.js
  admin/services/data-access/check.data.service.js
  admin/spec/back-end/controllers/check-started.spec.js
  admin/spec/back-end/controllers/check-window.spec.js
  admin/spec/back-end/service/check-complete.service.spec.js
  admin/spec/back-end/service/check-start.service.spec.js
  admin/yarn.lock
  functions/check-started/index.js
  functions/check-started/sample.data.json
  functions/completed-checks/index.js
  functions/feedback/index.js
  functions/lib/sql-helper.js
  functions/prepare-check/index.js
  functions/pupil-status/index.js
  pupil-spa/src/app/services/check-start/check-start.service.spec.ts
  pupil-spa/src/app/services/check-start/check-start.service.ts
  test/admin/features/support/sql_db_helper.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#845 Feature/24638 pin gen v2 data service
  admin/data/sql/migrations/119.do.completed-check-count.view.sql
  admin/data/sql/migrations/119.undo.completed-check-count.view.sql
  admin/data/sql/migrations/120.do.not-started-check-count.view.sql
  admin/data/sql/migrations/120.undo.not-started-check-count.view.sql
  admin/data/sql/migrations/121.do.incomplete-check-count.view.sql
  admin/data/sql/migrations/121.undo.incomplete-check-count.view.sql
  admin/data/sql/migrations/122.do.pupil-activity.view.sql
  admin/data/sql/migrations/122.undo.pupil-activity.view.sql
  admin/data/sql/migrations/123.do.pupil-eligible-for-pin-gen.view.sql
  admin/data/sql/migrations/123.undo.pupil-eligible-for-pin-gen.view.sql
  admin/services/data-access/pin-generation.data.service.js
Labels: CI Enabled, Ready for review

#843 Updated home page and privacy content
  pupil-spa/src/app/privacy/privacy.component.html
  pupil-spa/src/app/survey-welcome/survey-welcome.component.html
Labels: Ready for review, Signed Off, Tested
