Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2018-08, with the labels that each got.

#771 Task/22965 amended descriptions for the generate pins texts
  admin/views/school/school-home.ejs
  test/admin/features/support/page_objects/school_landing_page.rb
Labels: Reviewed & approved, Signed Off, Tested

#769 Feature/22397 check prep as azure function with table storage
  .circleci/config.yml
  admin/README.md
  admin/config.js
  admin/controllers/pupil-pin.js
  admin/controllers/questions.js
  admin/data/sql/migrations/109.do.alter-pupil-table.sql
  admin/data/sql/migrations/109.undo.alter-pupil-table.sql
  admin/helpers/whitelist-dev.js
  admin/services/azure-queue.service.js
  admin/services/check-start.service.js
  admin/services/data-access/check-form-allocation.data.service.js
  admin/services/data-access/check.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/jwt.service.js
  admin/services/sas-token.service.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/spec/back-end/controllers/questions.spec.js
  admin/spec/back-end/service/azure-queue.service.spec.js
  admin/spec/back-end/service/check-form.service.populateFromFile.spec.js
  admin/spec/back-end/service/check-start.service.spec.js
  admin/spec/back-end/service/jwt.service.spec.js
  admin/spec/back-end/service/sas-token.service.spec.js
  functions/package.json
  functions/prepare-check/function.json
  functions/prepare-check/index.js
  functions/prepare-check/index.spec.js
  functions/prepare-check/readme.md
  functions/prepare-check/sample.dat.json
  functions/readme.md
  functions/yarn.lock
Labels: CI Enabled, Ready for review, Tested

#770 Feature/22409 custom print page
  admin/assets/javascripts/print-popup.js
  admin/assets/javascripts/pupil-filter-group.js
  admin/assets/javascripts/pupil-filter-name.js
  admin/assets/javascripts/util-checkbox.js
  admin/assets/stylesheets/elements/_printing.scss
  admin/controllers/pupil-pin.js
  admin/gulpfile.js
  admin/routes/pupil-pin.js
  admin/services/date.service.js
  admin/services/group.service.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/spec/back-end/service/date.service.spec.js
  admin/spec/back-end/service/group.service.spec.js
  admin/spec/front-end/print-popup.spec.js
  admin/views/partials/_print_pupils.ejs
  admin/views/partials/_sticky_confirmation_banner.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/view-and-custom-print-pins.ejs
  admin/views/pupil-pin/view-and-print-pins.ejs
  test/admin/features/step_definitions/custom_pins_familiarisation_steps.rb
  test/admin/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin/features/support/page_objects/custom_pins_familiarisation_page.rb
  test/admin/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/admin/features/support/page_objects/view_and_print_pins_page.rb
  test/admin/features/view_custom_pins_familiarisation.feature
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#773 Fixed the lint errors on master
  admin/app.js
  admin/controllers/service-manager.js
  admin/services/nca-tools-auth.service.js
Labels: CI Enabled

#780 remove obsolete esb connectivity settings
  .eslintrc
  admin/config.js
Labels: CI Enabled, Reviewed & approved

#779 Feature/22319 track build ids appinsights
  admin/azure.js
  admin/helpers/healthcheck.js
  admin/helpers/index.js
  admin/routes/index.js
  admin/views/partials/_body_start.ejs
  pupil-api/src/App.ts
  pupil-api/src/azure.ts
  pupil-api/src/controllers/ping.controller.ts
  pupil-spa/src/app/app.component.ts
Labels: CI Enabled, Reviewed & approved, Signed Off

#778 Automation/23037 live school staff can view custom print page
  test/admin/features/generate_pupil_pins.feature
  test/admin/features/pupil_status.feature
  test/admin/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin/features/step_definitions/groups_steps.rb
  test/admin/features/step_definitions/view_and_custom_print_for_live_check_steps.rb
  test/admin/features/support/page_objects/view_and_custom_print_live_check_page.rb
  test/admin/features/view_and_custom_print_live_check_pin.feature
Labels: CI Enabled, Signed Off

#783 Feature/23410 pupil api prep and tidy up
  pupil-api/package.json
  pupil-api/sql/migrations/001.do.create-schema.sql
  pupil-api/sql/migrations/001.undo.create-schema.sql
  pupil-api/sql/migrations/002.do.create-preparedCheck-table.sql
  pupil-api/sql/migrations/002.undo.create-preparedCheck-table.sql
  pupil-api/sql/migrations/003.do.create-pupilEventType-table.sql
  pupil-api/sql/migrations/003.undo.create-pupilEventType-table.sql
  pupil-api/sql/migrations/004.do.create-pupilEvent-table.sql
  pupil-api/sql/migrations/004.undo.create-pupilEvent-table.sql
  pupil-api/src/App.ts
  pupil-api/src/config.ts
  pupil-api/src/controllers/check-start.controller.ts
  pupil-api/src/controllers/check-submit.controller.ts
  pupil-api/src/migrator/databaseCreator.ts
  pupil-api/src/migrator/migrate.ts
  pupil-api/src/routes/check-started.ts
  pupil-api/src/routes/check-submit.ts
  pupil-api/src/services/data-access/sql.pool.service.ts
  pupil-api/src/services/data-access/sql.service.ts
  pupil-api/src/services/jwt.service.ts
  pupil-api/src/services/pin.service.ts.txt
  pupil-api/src/spec/mocks/dates-req-mock.ts
  pupil-api/src/spec/mocks/jwtToken.ts
  pupil-api/src/spec/mocks/pupil.ts
  pupil-api/src/spec/mocks/sql-modify-response.ts
  pupil-api/yarn.lock
Labels: CI Enabled, Reviewed & approved

#777 Feature/22545 Access arrangements selection
  admin/assets/javascripts/pupil-access-arrangements-selection.js
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_access-arrangements.scss
  admin/assets/stylesheets/elements/_mtc-checkboxes.scss
  admin/controllers/access-arrangements.js
  admin/data/sql/migrations/110.do.create-question-reader-reasons.sql
  admin/data/sql/migrations/110.undo.create-question-reader-reasons.sql
  admin/data/sql/migrations/111.do.insert-question-reader-reasons.sql
  admin/data/sql/migrations/111.undo.insert-question-reader-reasons.sql
  admin/data/sql/migrations/112.do.create-pupil-access-arrangements.sql
  admin/data/sql/migrations/112.undo.create-pupil-access-arrangements.sql
  admin/gulpfile.js
  admin/routes/access-arrangements.js
  admin/services/data-access/question-reader-reasons.data.service.js
  admin/services/question-reader-reasons.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/service/question-reader-reasons.service.spec.js
  admin/spec/front-end/pupil-access-arrangements-selection.spec.js
  admin/spec/front-end/typeahead.spec.js
  admin/views/access-arrangements/select-access-arrangements.ejs
  test/admin/features/step_definitions/access_arrangements_steps.rb
  test/admin/features/support/page_objects/select_access_arrangements_page.rb
  test/admin/features/support/sql_db_helper.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#785 Feature/23262 group pupils pages to show middlename dob
  admin/services/data-access/group.data.service.js
  admin/services/group.service.js
  admin/spec/back-end/service/group.service.spec.js
  admin/views/groups/manage-group.ejs
  test/admin/features/groups.feature
  test/admin/features/step_definitions/add_pupil_steps.rb
  test/admin/features/step_definitions/groups_steps.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#790 Task/23265 Elongate filter bar pin generate
  admin/assets/stylesheets/elements/_filters.scss
  admin/views/pupil-pin/generate-pins-list.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#789 Bug/23264 Fix filterbar deletion in Edge
  admin/assets/javascripts/pupil-filter-name.js
  admin/views/pupil-pin/generate-pins-list.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#791 Task/22428 Replace N/A with dash pupils not taking check
  admin/services/pupils-not-taking-check.service.js
  admin/spec/back-end/mocks/pupils-with-reason-formatted.js
  admin/spec/back-end/service/pupils-not-taking-check.service.spec.js
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  test/admin/features/step_definitions/pupil_not_taking_check.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#792 Bug/23637 Admin docker build gulp
  admin/Dockerfile
Labels: CI Enabled, Reviewed & approved

#784 Include admin client tests in circle ci
  .circleci/config.yml
Labels: CI Enabled, Reviewed & approved

#788 Add documentation
  docs/developer.md
Labels: Reviewed & approved

#787 Feature/23432 Submission & validation on pupil access arrangements
  admin/assets/javascripts/pupil-access-arrangements-selection.js
  admin/assets/stylesheets/elements/_access-arrangements.scss
  admin/assets/stylesheets/elements/_flash-messages.scss
  admin/controllers/access-arrangements.js
  admin/data/sql/migrations/113.do.add-access-arrangements-id-field.sql
  admin/data/sql/migrations/113.undo.add-access-arrangements-id-field.sql
  admin/data/sql/migrations/114.do.grant-delete-pupil-access-arrangements.table.js
  admin/data/sql/migrations/114.undo.grant-delete-pupil-access-arrangements.table.js
  admin/lib/errors/access-arrangements.js
  admin/lib/validator/access-arrangements-validator.js
  admin/services/access-arrangements.service.js
  admin/services/data-access/access-arrangements.data.service.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/services/data-access/question-reader-reasons.data.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/lib/validator/access-arrangements-validator.spec.js
  admin/spec/back-end/service/access-arrangements.service.spec.js
  admin/spec/front-end/pupil-access-arrangements-selection.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/access-arrangements/select-access-arrangements.ejs
  test/admin/features/access_arrangements.feature
  test/admin/features/step_definitions/access_arrangements_steps.rb
  test/admin/features/support/page_objects/select_access_arrangements_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#798 23266 update description for generate pins
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/yarn.lock
  test/admin/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/admin/features/support/page_objects/generate_pins_overview_page.rb
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested

#793 Feature/22557 access arrangements list overview
  admin/assets/stylesheets/elements/_access-arrangements.scss
  admin/controllers/access-arrangements.js
  admin/routes/access-arrangements.js
  admin/services/access-arrangements.service.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/services/pupil-access-arrangements.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/service/access-arrangements.service.spec.js
  admin/spec/back-end/service/pupil-access-arrangements.service.spec.js
  admin/views/access-arrangements/overview.ejs
  test/admin/features/access_arrangements.feature
  test/admin/features/step_definitions/access_arrangements_steps.rb
  test/admin/features/support/page_objects/access_arrangements_page.rb
Labels: CI Enabled, Ready for review, Tested

#796 Feature/22398 pupil api lookup table storage
  admin/services/check-start.service.js
  functions/prepare-check/function.json
  functions/prepare-check/index.js
  pupil-api/package-lock.json
  pupil-api/package.json
  pupil-api/pupil-api.md
  pupil-api/src/App.ts
  pupil-api/src/config.ts
  pupil-api/src/controllers/auth.controller.ts
  pupil-api/src/services/date.service.ts
  pupil-api/src/services/pupil-authentication.service.ts
  pupil-api/src/spec/controller/auth.controller.spec.ts
  pupil-api/src/spec/services/pupil-authorisation.service.spec.ts
  pupil-api/yarn.lock
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#786 Feature/23141 Familiarisation exclude left-school pupils
  admin/services/attendance.service.js
  admin/services/data-access/pupil-attendance.data.service.js
  admin/services/pin-generation.service.js
  admin/spec/back-end/service/attendance-service.spec.js
  admin/spec/back-end/service/pin-generation.service.spec.js
  admin/views/pupil-pin/generate-pins-list.ejs
  test/admin/features/generate_pupil_pin_familiarisation.feature
  test/admin/features/step_definitions/generate_pupil_pins_steps.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#800 Purge BLOB storage containers periodically
  deploy/jobs/purge-pins.js
  deploy/jobs/purge-storage/purge-storage.sh
Labels: Ready for review

#795 Feature/22546 edit access arrangements
  admin/controllers/access-arrangements.js
  admin/data/sql/migrations/115.do.rename-access-arrangements-foreign-key.sql
  admin/data/sql/migrations/115.undo.rename-access-arrangements-foreign-key.sql
  admin/lib/validator/access-arrangements-validator.js
  admin/routes/access-arrangements.js
  admin/services/access-arrangements.service.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/services/pupil-access-arrangements-edit.service.js
  admin/services/pupil-access-arrangements.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/lib/validator/access-arrangements-validator.spec.js
  admin/spec/back-end/service/pupil-access-arrangements-edit.service.spec.js
  admin/spec/back-end/service/pupil-access-arrangements.service.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/access-arrangements/select-access-arrangements.ejs
  test/admin/features/access_arrangements.feature
  test/admin/features/step_definitions/access_arrangements_steps.rb
  test/admin/features/support/page_objects/access_arrangements_page.rb
  test/admin/features/support/page_objects/select_access_arrangements_page.rb
  test/admin/features/support/sql_db_helper.rb
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested

#799 Feature/21908 spa configurable numpad removal
  admin/services/access-arrangements.service.js
  admin/services/config.service.js
  admin/services/data-access/access-arrangements.data.service.js
  admin/services/data-access/question-reader-reasons.data.service.js
  admin/spec/back-end/service/access-arrangements.service.spec.js
  admin/spec/back-end/service/config.service.spec.js
  pupil-spa/src/app/config.model.ts
  pupil-spa/src/app/practice-question/practice-question.component.ts
  pupil-spa/src/app/question/question.component.html
  pupil-spa/src/app/services/question/question.service.ts
  pupil-spa/src/app/services/question/warmup-question.service.ts
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested

#802 Feature/23741 Access arrangements deletions from edit view
  admin/assets/javascripts/jquery-modal.js
  admin/assets/javascripts/pupil-access-arrangements-selection.js
  admin/assets/stylesheets/elements/_access-arrangements.scss
  admin/assets/stylesheets/elements/_flash-messages.scss
  admin/controllers/access-arrangements.js
  admin/lib/validator/access-arrangements-validator.js
  admin/routes/access-arrangements.js
  admin/services/data-access/access-arrangements.data.service.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/services/pupil-access-arrangements.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/lib/validator/access-arrangements-validator.spec.js
  admin/spec/back-end/service/pupil-access-arrangements.service.spec.js
  admin/spec/front-end/pupil-access-arrangements-selection.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/access-arrangements/select-access-arrangements.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested
