Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2018-11, with the labels that each got.

#881 Feature/25424 ict survey agent
  admin/bin/fetch-ict-data.js
Labels: Reviewed & approved, Signed Off, Tested

#878 Feature/22443 aa question reader
  admin/services/config.service.js
  admin/spec/back-end/service/config.service.spec.js
  pupil-spa/src/app/check-complete/check-complete.component.ts
  pupil-spa/src/app/check/check.component.ts
  pupil-spa/src/app/config.model.ts
  pupil-spa/src/app/familiarisation-settings/familiarisation-settings.component.html
  pupil-spa/src/app/familiarisation-settings/familiarisation-settings.component.scss
  pupil-spa/src/app/familiarisation-settings/familiarisation-settings.component.spec.ts
  pupil-spa/src/app/familiarisation-settings/familiarisation-settings.component.ts
  pupil-spa/src/app/feedback-thanks/feedback-thanks.component.html
  pupil-spa/src/app/feedback-thanks/feedback-thanks.component.spec.ts
  pupil-spa/src/app/feedback-thanks/feedback-thanks.component.ts
  pupil-spa/src/app/feedback/feedback.component.html
  pupil-spa/src/app/feedback/feedback.component.spec.ts
  pupil-spa/src/app/feedback/feedback.component.ts
  pupil-spa/src/app/instructions/instructions.component.ts
  pupil-spa/src/app/loading/loading.component.ts
  pupil-spa/src/app/login-success/login-success.component.spec.ts
  pupil-spa/src/app/login-success/login-success.component.ts
  pupil-spa/src/app/login/login.component.spec.ts
  pupil-spa/src/app/practice-question/practice-question.component.spec.ts
  pupil-spa/src/app/practice-question/practice-question.component.ts
  pupil-spa/src/app/questions-intro/questions-intro.component.ts
  pupil-spa/src/app/services/check-status/local.storage.failed.submission.mock.json
  pupil-spa/src/app/services/question/question.service.mock.ts
  pupil-spa/src/app/services/question/question.service.ts
  pupil-spa/src/app/services/question/warmup-question.service.ts
  pupil-spa/src/app/services/speech/speech.service.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.ts
  pupil-spa/src/app/warmup-complete/warmup-complete.component.ts
  pupil-spa/src/app/warmup-intro/warmup-intro.component.ts
  pupil-spa/src/app/warmup-loading/warmup-loading.component.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#887 Feature/25629 colour contrast settings
  pupil-spa/src/app/access-arrangements.ts
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/familiarisation-colour/familiarisation-colour.component.html
  pupil-spa/src/app/familiarisation-colour/familiarisation-colour.component.scss
  pupil-spa/src/app/familiarisation-colour/familiarisation-colour.component.spec.ts
  pupil-spa/src/app/familiarisation-colour/familiarisation-colour.component.ts
  pupil-spa/src/app/familiarisation-settings/familiarisation-settings.component.html
  pupil-spa/src/app/login-success/login-success.component.ts
  pupil-spa/src/app/login/login.component.spec.ts
  pupil-spa/src/app/login/login.component.ts
  pupil-spa/src/app/page-modifications/page-modifications.component.html
  pupil-spa/src/app/page-modifications/page-modifications.component.ts
  pupil-spa/src/app/services/question/question.service.mock.ts
  pupil-spa/src/app/services/route/route.service.mock.ts
  pupil-spa/src/app/services/route/route.service.spec.ts
  pupil-spa/src/app/services/route/route.service.ts
  pupil-spa/src/assets/shared-styles/styles.scss
  test/pupil/features/access_arrangements.feature
  test/pupil/features/step_definitions/access_arrangement_steps.rb
  test/pupil/features/support/page_objects/access_arrangements_setting_page.rb
  test/pupil/features/support/page_objects/colour_contrast_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#885 Feature/25689 Submit, persist(db) and apply pupil prefs
  admin/data/sql/migrations/154.do.create-pupil-font-sizes-table.sql
  admin/data/sql/migrations/154.undo.create-pupil-font-sizes-table.sql
  admin/data/sql/migrations/155.do.create-pupil-colour-contrasts-table.sql
  admin/data/sql/migrations/155.undo.create-pupil-colour-contrasts-table.sql
  admin/data/sql/migrations/156.do.populate-pupil-font-sizes-table.sql
  admin/data/sql/migrations/156.undo.populate-pupil-font-sizes-table.sql
  admin/data/sql/migrations/157.do.populate-pupil-colour-contrasts-table.sql
  admin/data/sql/migrations/157.undo.populate-pupil-colour-contrasts-table.sql
  admin/data/sql/migrations/158.do.add-pupil-access-arrangements-prefs-fields.sql
  admin/data/sql/migrations/158.undo.add-pupil-access-arrangements-prefs-fields.sql
  admin/services/config.service.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/spec/back-end/service/config.service.spec.js
  functions/pupil-prefs/function.json
  functions/pupil-prefs/index.js
  functions/pupil-prefs/message-schema/message.v1.json
  pupil-spa/src/app/access-arrangements.ts
  pupil-spa/src/app/familiarisation-area/familiarisation-area.component.html
  pupil-spa/src/app/familiarisation-area/familiarisation-area.component.spec.ts
  pupil-spa/src/app/familiarisation-area/familiarisation-area.component.ts
  pupil-spa/src/app/pupil.ts
  pupil-spa/src/app/services/audit/auditEntry.ts
  pupil-spa/src/app/services/azure-queue/queue-names.ts
  pupil-spa/src/app/services/config/config.service.ts
  test/admin/features/add_multiple_pupil_validation_error.feature
Labels: CI Enabled, Reviewed & approved, Signed Off, Testing

#886 Feature/25352 school staff generates pupil familiarisation pins
  admin/controllers/pupil-pin.js
  admin/controllers/pupils-not-taking-the-check.js
  admin/controllers/restart.js
  admin/data/sql/migrations/159.do.create-pupil-status-table.sql
  admin/data/sql/migrations/159.undo.create-pupil-status.sql
  admin/data/sql/migrations/160.do.populate-pupil-status-table.sql
  admin/data/sql/migrations/160.undo.populate-pupil-status-table.sql
  admin/data/sql/migrations/162.do.add-pupil-status-col.sql
  admin/data/sql/migrations/162.undo.add-pupil-status-col.sql
  admin/data/sql/migrations/163.do.backfill-pupil-status.sql
  admin/data/sql/migrations/163.undo.backfill-pupil-status.sql
  admin/data/sql/migrations/164.do.create-pupil-status-view.sql
  admin/data/sql/migrations/164.undo.create-pupil-status-view.sql
  admin/data/sql/migrations/165.do.make-pupil-status-not-null.sql
  admin/data/sql/migrations/165.undo.make-pupil-status-not-null.sql
  admin/data/sql/migrations/166.do.create-view-pupils-eligible-for-familiarisation-pin.sql
  admin/data/sql/migrations/166.undo.create-view-pupils-eligible-for-familiarisation-pin.sql
  admin/data/sql/migrations/167.do.drop-view-pupils-eligible-for-pin-generation.sql
  admin/data/sql/migrations/167.undo.drop-view-pupils-eligible-for-pin-generation.sql
  admin/data/sql/migrations/168.do.recreate-view-pupils-eligible-for-live-pin-generation.sql
  admin/data/sql/migrations/168.undo.recreate-view-pupils-eligible-for-live-pin-generation.sql
  admin/data/sql/migrations/169.do.create-view-pupils-with-active-familiarisation-pins.sql
  admin/data/sql/migrations/169.undo.create-view-pupils-with-active-familiarisation-pins.sql
  admin/data/sql/migrations/170.do.drop-view-pupils-with-active-pins.sql
  admin/data/sql/migrations/170.undo.drop-view-pupils-with-active-pins.sql
  admin/data/sql/migrations/171.do.create-view-pupils-with-active-live-pins.sql
  admin/data/sql/migrations/171.undo.create-view-pupils-with-active-live-pins.sql
  admin/data/sql/migrations/172.do.extend-check-status.sql
  admin/data/sql/migrations/172.undo.extend-check-status.sql
  admin/data/sql/migrations/173.do.alter-pupils-eligible-for-restart-view.sql
  admin/data/sql/migrations/173.undo.alter-pupils-eligible-for-restart-view.sql
  admin/services/check-start.service.js
  admin/services/data-access/pin-generation.data.service.js
  admin/services/pin-generation-v2.service.js
  admin/services/pupil.status.service.js
  admin/services/queue-name-service.js
  admin/spec/back-end/controllers/pupils-not-taking-the-check.spec.js
  admin/spec/back-end/controllers/restart.spec.js
  admin/spec/back-end/service/check-start.service.spec.js
  functions/check-started/index.js
  functions/completed-checks/index.js
  functions/host.json
  functions/lib/azure-storage-helper.js
  functions/package.json
  functions/pupil-status/function.json
  functions/pupil-status/index.js
  functions/pupil-status/message-schema/message.v1.json
  functions/pupil-status/pupil-status-analysis.service.js
  functions/pupil-status/pupil-status-analysis.service.spec.js
  functions/yarn.lock
  restart.sh
  test/admin/admin_tests_2.sh
  test/admin/admin_tests_3.sh
Labels: CI Enabled, Reviewed & approved, Signed Off, Testing

#900 26162 - enable HPA mode in Travis
  .travis.yml
  admin/config/feature-toggles.hpa-travis.json
  test/admin/admin_tests_1.sh
Labels: CI Enabled

#888 Feature/25630 colour contrast applied
  pupil-spa/src/app/check-complete/check-complete.component.html
  pupil-spa/src/app/check/check.component.html
  pupil-spa/src/app/familiarisation-area/familiarisation-area.component.html
  pupil-spa/src/app/familiarisation-colour/familiarisation-colour.component.html
  pupil-spa/src/app/familiarisation-colour/familiarisation-colour.component.scss
  pupil-spa/src/app/familiarisation-settings/familiarisation-settings.component.html
  pupil-spa/src/app/feedback-thanks/feedback-thanks.component.html
  pupil-spa/src/app/feedback/feedback.component.html
  pupil-spa/src/app/instructions/instructions.component.html
  pupil-spa/src/app/login-success/login-success.component.html
  pupil-spa/src/app/login-success/login-success.component.spec.ts
  pupil-spa/src/app/login-success/login-success.component.ts
  pupil-spa/src/app/page-modifications/page-modifications.component.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.html
  pupil-spa/src/app/submission-pending/submission-pending.component.html
  pupil-spa/src/app/submission-pending/submission-pending.component.scss
  pupil-spa/src/app/warmup-intro/warmup-intro.component.html
  pupil-spa/src/assets/shared-styles/elements/_colour-contrast.scss
  pupil-spa/src/assets/shared-styles/elements/_timer.scss
  pupil-spa/src/assets/shared-styles/elements/_warm-up.scss
  pupil-spa/src/assets/shared-styles/styles.scss
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#895 Feature/24366 Inaccessible pin generation links
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_custom_banners.scss
  admin/controllers/access-arrangements.js
  admin/controllers/group.js
  admin/controllers/pupil-pin.js
  admin/controllers/pupils-not-taking-the-check.js
  admin/controllers/restart.js
  admin/controllers/school.js
  admin/helpers/school-home-pin-generation-eligibility-presenter.js
  admin/services/business-availability.service.js
  admin/services/check-window-v2.service.js
  admin/services/data-access/check-window.data.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/controllers/group.spec.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/spec/back-end/controllers/pupils-not-taking-the-check.spec.js
  admin/spec/back-end/controllers/restart.spec.js
  admin/spec/back-end/controllers/school.spec.js
  admin/spec/back-end/helpers/check-window-presenter.spec.js
  admin/spec/back-end/helpers/school-home-pin-generation-eligibility-presenter.spec.js
  admin/spec/back-end/service/business-availability.service.spec.js
  admin/spec/back-end/service/check-window-v2.service.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/groups/groups.ejs
  admin/views/pupil-pin/view-and-print-pins.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/school/school-home.ejs
  test/admin/features/step_definitions/pupil_not_taking_check.rb
  test/admin/features/support/page_objects/group_pupils_page.rb
  test/admin/features/support/page_objects/pupils_not_taking_check_page.rb
Labels: CI Enabled, Reviewed & approved, Testing

#901 Bug/26009 hpa pupil register page is throwing 500
  admin/services/pupil.status.service.js
  functions/completed-checks/index.js
Labels: CI Enabled, Ready for review, Signed Off, Tested

#899 Feature/26135 view all active pins button
  admin/views/pupil-pin/view-and-print-pins.ejs
Labels: Reviewed & approved, Signed Off, Tested

#905 Include 8 AM as accessible hour
  admin/helpers/school-home-pin-generation-eligibility-presenter.js
Labels: CI Enabled

#907 bug/26617 fix parameter prefix for CORS in queue setup script
  deploy/storage/create-items.sh
Labels: CI NOT Required, Ready for review

#904 Feature/26376 hpa pupil login date not being recorded in the check table
  admin/data/sql/migrations/174.do.add-diagnostic-check-view.sql
  admin/data/sql/migrations/174.undo.add-diagnostic-check-view.sql
  admin/data/sql/migrations/175.do.drop-vewPupilsWithActiveLivePins.sql
  admin/data/sql/migrations/175.undo.drop-vewPupilsWithActiveLivePins.sql
  admin/data/sql/migrations/176.do.drop-vewPupilsWithActiveFamiliarisationPins.sql
  admin/data/sql/migrations/176.undo.drop-vewPupilsWithActiveFamiliarisationPins.sql
  admin/data/sql/migrations/177.do.create-vewPupilsWithActiveLivePins.sql
  admin/data/sql/migrations/177.undo.create-vewPupilsWithActiveLivePins.sql
  admin/data/sql/migrations/178.do.create-vewPupilsWithActiveFamiliarisationPin.sql
  admin/data/sql/migrations/178.undo.create-vewPupilsWithActiveFamiliarisationPin.sql
  functions/completed-checks/index.js
  functions/pupil-login/index.js
  functions/pupil-login/message-schema/message.v1.json
  functions/pupil-login/message-validator.js
  functions/pupil-login/message-validator.spec.js
  functions/pupil-login/v1.js
  functions/pupil-login/v1.spec.js
  functions/pupil-status/pupil-status-analysis.service.js
  pupil-api/package.json
  pupil-api/src/services/azure-queue.service.ts
  pupil-api/src/services/pupil-authentication.service.ts
  pupil-api/src/spec/services/pupil-authorisation.service.spec.ts
  pupil-api/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#908 Feature/26630 prepared check sync prerequisites
  admin/data/sql/migrations/183.do.index-pupil-urlslug-check-checkcode.sql
  admin/data/sql/migrations/183.undo.index-pupil-urlslug-check-checkcode.sql
  deploy/storage/create-items.sh
  deploy/storage/tables-queues.json
  functions/prepared-check-sync/function.json
  functions/prepared-check-sync/index.js
  functions/prepared-check-sync/message-schema/message.v1.json
Labels: CI Enabled, Ready for review, Signed Off, Tested

#910 update build server pre-reqs docs
  vsoBuildServer.md
Labels: CI NOT Required, Ready for review

#914 Bug/26288 fix SPA app counter on check submission
  pupil-spa/src/app/services/check-complete/check-complete.service.spec.ts
  pupil-spa/src/app/services/check-complete/check-complete.service.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.spec.ts
Labels: CI Enabled, Ready for review

#913 Feature/26639 fontsize changes
  pupil-spa/src/app/aa-colours/aa-colours.component.html
  pupil-spa/src/app/aa-fonts/aa-fonts.component.html
  pupil-spa/src/app/question/question.component.html
  pupil-spa/src/app/svg/svg.arrow.component.html
  pupil-spa/src/assets/shared-styles/elements/_aa-variables.scss
  pupil-spa/src/assets/shared-styles/elements/_check.scss
  pupil-spa/src/assets/shared-styles/elements/_font-size-copy.scss
  pupil-spa/src/assets/shared-styles/elements/_virtual-keyboard.scss
  pupil-spa/src/assets/shared-styles/styles.scss
Labels: CI Enabled, Ready for review, Signed Off, Tested

#916 Feature/26671 pupil views with question reader
  pupil-spa/src/app/aa-colours/aa-colours.component.html
  pupil-spa/src/app/aa-colours/aa-colours.component.spec.ts
  pupil-spa/src/app/aa-colours/aa-colours.component.ts
  pupil-spa/src/app/aa-fonts/aa-fonts.component.html
  pupil-spa/src/app/aa-fonts/aa-fonts.component.spec.ts
  pupil-spa/src/app/aa-fonts/aa-fonts.component.ts
  pupil-spa/src/app/check-complete/check-complete.component.html
  pupil-spa/src/app/login-success/login-success.component.html
  pupil-spa/src/app/services/speech/speech.service.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.html
  pupil-spa/src/assets/shared-styles/elements/_font-size-copy.scss
  pupil-spa/src/assets/shared-styles/styles.scss
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#923 Feature/pupil api load test
  load-test/bin/fill-prepared-check.js
  load-test/package.json
  load-test/scenarios/data/questions.json
  load-test/scenarios/data/tokens.json
  load-test/yarn.lock
  pupil-api/src/App.ts
Labels: CI NOT Required, Ready for review

#921 Feature/add pupil load test script
  load-test/bin/generate-pupil-data.js
Labels: CI Enabled, Reviewed & approved

#906 Feature/23713 timed function run expiry process
  admin/bin/init-dev-storage.js
  functions/check-expiry/function.json
  functions/check-expiry/index.js
  functions/check-expiry/v1.js
  functions/check-not-received/function.json
  functions/check-not-received/index.js
  functions/check-not-received/v1.js
  functions/config.js
  functions/diag/index.js
  functions/expire-prepared-check/function.json
  functions/expire-prepared-check/index.js
  functions/expire-prepared-check/v1.js
  functions/lib/azure-storage-helper.js
  functions/lib/mock-table-service.js
  functions/prepare-check/function.json
  functions/prepare-check/index.js
  functions/prepare-check/index.spec.js
  functions/pupil-status/pupil-status-analysis.service.js
  functions/pupil-status/pupil-status-analysis.service.spec.js
Labels: Reviewed & approved, Signed Off, Tested

#920 Fixed missing pupil group id
  admin/data/sql/migrations/20181129104632.do.drop-view-pupils-eligible-for-pin-generation.sql
  admin/data/sql/migrations/20181129104632.undo.drop-view-pupils-eligible-for-pin-generation.sql
  admin/data/sql/migrations/20181129104750.do.recreate-view-pupils-eligible-for-live-pin-generation.sql
  admin/data/sql/migrations/20181129104750.undo.recreate-view-pupils-eligible-for-live-pin-generation.sql
  admin/data/sql/migrations/20181129110126.do.drop-view-pupils-eligible-for-familiarisation-pin.sql
  admin/data/sql/migrations/20181129110126.undo.drop-view-pupils-eligible-for-familiarisation-pin.sql
  admin/data/sql/migrations/20181129110139.do.recreate-view-pupils-eligible-for-familiarisation-pin.sql
  admin/data/sql/migrations/20181129110139.undo.recreate-view-pupils-eligible-for-familiarisation-pin.sql
Labels: CI Enabled, Ready for review, Signed Off, Tested

#922 Feature/27087 Check form v2 prerequisites
  admin/config/feature-toggles.Azure-DEV.json
  admin/config/feature-toggles.Azure-PP.json
  admin/config/feature-toggles.default.json
  admin/config/feature-toggles.hpa-dev.json
  admin/config/feature-toggles.hpa-travis.json
  admin/data/sql/migrations/20181129141323.do.add-islivecheckform-to-checkform.sql
  admin/data/sql/migrations/20181129141323.undo.add-islivecheckform-to-checkform.sql
Labels: Reviewed & approved, Signed Off, Tested
