Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2018-03, with the labels that each got.

#540 Feature/19053 add group to print pin card
  admin/assets/stylesheets/elements/_pupils.scss
  admin/controllers/pupil-pin.js
  admin/services/data-access/pupil.data.service.js
  admin/services/data-access/school.data.service.js
  admin/services/pin.service.js
  admin/spec/controllers/pupil-pin.spec.js
  admin/views/pupil-pin/pin-print.ejs
Labels: Reviewed & approved, Signed Off, Tested

#541 bug/19323 - Cancel button fix [master]
  admin/test/features/question_time_limits.feature
  admin/test/features/step_definitions/question_time_limit_steps.rb
  admin/test/features/support/page_objects/check_settings_page.rb
  admin/test/features/time_between_questions.feature
  admin/views/service-manager/check-settings.ejs
Labels: Reviewed & approved, Signed Off, Tested

#542 create docker image from admin public assets
  admin-assets/.gitignore
  admin-assets/Dockerfile
  admin-assets/build.sh
  admin/app.js
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_check-forms.scss
  admin/assets/stylesheets/elements/_modal.scss
  admin/assets/stylesheets/elements/_pupils.scss
  admin/assets/stylesheets/elements/_top_navigation.scss
  admin/config.js
  admin/gulpfile.js
  admin/helpers/index.js
  admin/package.json
  admin/views/partials/_head.ejs
  admin/views/pupil-pin/generated-pins-list.ejs
  admin/views/pupil-pin/pin-print.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/school/pupil-register.ejs
  admin/views/school/pupils-not-taking-check.ejs
  admin/views/test-developer/upload-new-form.ejs
  admin/yarn.lock
Labels: Ready for review

#545 Feature toggle
  admin/app.js
  admin/assets/stylesheets/application.scss
  admin/config/feature-toggles.Azure_UAT.json
  admin/config/feature-toggles.default.json
  admin/package.json
  admin/views/groups/groups.ejs
  admin/views/school/pupil-register.ejs
  admin/yarn.lock
Labels: DNM - Requires Testing, Ready for review

#546 disable insights error handling and logging
  admin/azure.js
Labels: Ready for review

#547 Update copy for the March trials (and March training)
  admin/services/pin-generation.service.js
  pupil-spa/src/app/instructions/instructions.component.html
  pupil-spa/src/app/login-success/login-success.component.html
  pupil-spa/test/Gemfile.lock
  pupil-spa/test/features/instructions_page.feature
  pupil-spa/test/features/support/page_objects/confirmation_page.rb
  pupil-spa/test/features/support/page_objects/start_page.rb
Labels: Reviewed & approved, Signed Off, Tested

#543 bug/19372 - Improvements in sticky banner position
  admin/assets/javascripts/global-scripts.js
Labels: DNM - Requires Testing, Ready for review, Testing

#551 Bug/19723 revert sass root variable change
  admin-assets/copy-assets.sh
  admin-assets/nginx/default.conf
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_check-forms.scss
  admin/assets/stylesheets/elements/_modal.scss
  admin/assets/stylesheets/elements/_pupils.scss
  admin/assets/stylesheets/elements/_top_navigation.scss
  admin/gulpfile.js
Labels: Ready for review

#554 Move feature toggle output to be *after* we configure log drivers
  admin/app.js
Labels: Ready for review

#552 feature/19771 - Show date in printed PIN card
  admin/assets/stylesheets/elements/_pupils.scss
  admin/services/pin.service.js
  admin/views/pupil-pin/pin-print.ejs
Labels: DNM - Requires Testing, Ready for review

#553 19752 Check window end date value correction
  admin/controllers/service-manager.js
Labels: DNM - Requires Testing, Ready for review

#555 Bug/19797 normalise all assets to lowercase
  admin-assets/nginx/default.conf
  admin/.gitignore
  admin/controllers/download-file.js
  admin/controllers/pupil.js
  admin/gulpfile.js
  admin/spec/controllers/pupil.spec.js
  admin/test/features/support/page_objects/group_pupils_page.rb
  admin/views/groups/groups.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/generated-pins-list.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/school/pupil-register.ejs
  admin/views/school/pupils-not-taking-check.ejs
  admin/views/school/school-home.ejs
  admin/views/test-developer/upload-new-form.ejs
Labels: Ready for review

#558 feature/19771 - Date format on PIN print card
  admin/controllers/pupil-pin.js
  admin/spec/controllers/pupil-pin.spec.js
  admin/views/pupil-pin/pin-print.ejs
Labels: Ready for review, Signed Off, Tested

#535 Feature/18197 enhance date service to incorporate millisecond precision
  admin/services/data-access/sql.service.js
  admin/services/date.service.js
  admin/spec/service/date.service.spec.js
  admin/tests-integration/check-form.service.spec.js
  admin/tests-integration/sql.service.spec.js
Labels: Reviewed & approved, Signed Off, Tested

#537 Performance load testing scenarios
  admin/controllers/questions.js
  admin/services/data-access/school.data.service.js
  load-test/README.md
  load-test/bin/extract-pins-to-csv.js
  load-test/bin/generate-pupil-load-test-data.js
  load-test/bin/undo-generate-pupil-load-test-data.sql
  load-test/package.json
  load-test/scenarios/data/admin_load_test_data.csv
  load-test/scenarios/data/userLogins.csv
  load-test/scenarios/mtc_admin_login.jmx
  load-test/scenarios/mtc_pupil_check_perf_test.jmx
  load-test/yarn.lock
Labels: DNM - Requires Testing, Ready for review

#556 Feature/18246 ps report to mark and process again
  admin/bin/psychometricians-report-v2.js
  admin/services/psychometrician-report.service.js
Labels: Ready for review, Tested

#560 Feature/19773 change the guidance document
  admin/app.js
  admin/assets/PDFs/MTC_CAG_Feb_2018_Trial.pdf
  admin/assets/PDFs/MTC_administration_guidance_June-2017-trial.pdf
  admin/assets/pdfs/mtc-administration-guidance-2018-03.pdf
  admin/controllers/download-file.js
  admin/helpers/index.js
  admin/routes/school.js
  admin/routes/service-manager.js
  admin/routes/test-developer.js
  admin/test/features/support/page_objects/group_pupils_page.rb
  admin/test/features/support/page_objects/manage_check_window_page.rb
  admin/views/groups/groups.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/generated-pins-list.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/school/pupil-register.ejs
  admin/views/school/pupils-not-taking-check.ejs
  admin/views/school/school-home.ejs
  admin/views/service-manager/check-windows.ejs
  admin/views/service-manager/service-manager-home.ejs
  admin/views/test-developer/assign-check-forms-to-windows.ejs
  admin/views/test-developer/test-developer-home.ejs
  admin/views/test-developer/upload-and-view-forms.ejs
  admin/views/test-developer/view-check-form.ejs
Labels: Reviewed & approved, Sign off, Tested

#563 bug/19334 - Sorting group by group name
  admin/assets/stylesheets/elements/_filters.scss
  admin/services/data-access/group.data.service.js
Labels: Reviewed & approved, Signed Off, Tested

#559 feature/19713 - submit without pins
  pupil-spa/src/app/login/login.component.html
  pupil-spa/src/app/login/login.component.spec.ts
  pupil-spa/src/app/login/login.component.ts
  pupil-spa/src/app/login/login.model.ts
  pupil-spa/test/features/login_page.feature
  pupil-spa/test/features/step_definitions/login_page_steps.rb
  pupil-spa/test/features/step_definitions/pin_expiry_steps.rb
  pupil-spa/test/features/support/page_objects/sign_in_page.rb
  pupil-spa/test/features/support/sql_db_helper.rb
Labels: Reviewed & approved, Signed Off, Tested

#557 added condition to check for question to load after refresh
  admin/test/config/cucumber.yml
  admin/test/features/support/hooks.rb
  pupil-spa/test/config/cucumber.yml
  pupil-spa/test/features/support/page_objects/check_page.rb
Labels: CI Enabled, Testing

#549 19508 Display pins overview page errors and prevent pins generation
  admin/config.js
  admin/controllers/pupil-pin.js
  admin/lib/errors/service-manager.js
  admin/lib/errors/test-developer.js
  admin/services/check-window-sanity-check.service.js
  admin/spec/controllers/pupil-pin.spec.js
  admin/spec/mocks/check-form.js
  admin/spec/mocks/check-window.js
  admin/spec/service/check-window-sanity-check.service.spec.js
  admin/spec/service/pin.service.spec.js
  admin/test/features/generate_pupil_pins.feature
  admin/test/features/step_definitions/generate_pupil_pins_steps.rb
  admin/test/features/support/hooks.rb
  admin/test/features/support/page_objects/generate_pins_overview_page.rb
  admin/test/features/support/sql_db_helper.rb
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/generated-pins-list.ejs
  pupil-spa/test/features/support/hooks.rb
  pupil-spa/test/features/support/sql_db_helper.rb
Labels: CI Enabled, Ready for review, Tested

#567 Feature/19759 ux and copy changes
  admin/controllers/pupil.js
  admin/controllers/service-manager.js
  admin/services/date.service.js
  admin/services/pupil-add-service.js
  admin/spec/service/date.service.spec.js
  admin/test/features/support/page_objects/pupils_not_taking_check_page.rb
  admin/test/features/support/page_objects/school_landing_page.rb
  admin/test/features/support/page_objects/upload_and_view_forms_page.rb
  admin/views/contact.ejs
  admin/views/partials/_footer_support_links.ejs
  admin/views/school/pupils-not-taking-check.ejs
  admin/views/school/school-home.ejs
Labels: CI Enabled, Ready for review, Requires sign off, Tested

#565 Add a new message if all assigned forms have been assigned to a checkwindow
  admin/views/test-developer/assign-forms.ejs
Labels: CI Enabled, DNM - Requires Testing, Ready for review, Testing

#564 Retry check submission on failed screen
  pupil-spa/src/app/submission-failed/submission-failed.component.html
Labels: CI Enabled, Ready for review, Signed Off, Tested

#568 Put surname first
  admin/views/pupil-pin/pin-print.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#571 Introduce loading time limit and question time limit within groups
  admin/data/sql/migrations/069.do.add-time-limits-to-group.sql
  admin/data/sql/migrations/069.undo.add-time-limits-to-group.sql
  admin/services/config.service.js
  admin/services/data-access/group.data.service.js
  admin/spec/service/config.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#572 feature/19285 - Copy changes
  admin/config/feature-toggles.Azure-Feb-Trial.json
  admin/views/school/pupil-register.ejs
  admin/views/school/school-home.ejs
Labels: DNM - Requires Testing, Reviewed & approved, Testing

#576 add github client and secret to API call to raise rate limits
  deploy/should-it-build.js
Labels: CI Enabled, Ready for review

#577 Feature/19773 copy changes restore
  admin/views/contact.ejs
  admin/views/groups/groups.ejs
  admin/views/partials/_content.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/school/pupil-register.ejs
  admin/views/school/pupils-not-taking-check.ejs
  admin/views/school/school-home.ejs
  admin/views/service-manager/service-manager-home.ejs
Labels: CI Enabled, Reviewed & approved, Tested

#578 Add extra columns in the psychometric report
  admin/services/psychometrician-report.service.js
  admin/services/psychometrician-util.service.js
  admin/spec/service/psychometrician-util.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#579 Update Content Security Policy to allow PDFs to load from the asset path
  admin-assets/nginx/default.conf
  admin/app.js
  admin/assets/pdfs/mtc-administration-guidance-2018-03-1.pdf
  admin/helpers/index.js
  admin/test/features/support/page_objects/group_pupils_page.rb
  admin/test/features/support/page_objects/manage_check_window_page.rb
Labels: CI Enabled, Reviewed & approved, Testing

#573 Extend access token expiration based on check window end date time
  admin/controllers/questions.js
  admin/services/check-window.service.js
  admin/services/jwt.service.js
  admin/spec/controllers/questions.spec.js
  admin/spec/service/check-window.service.spec.js
  admin/spec/service/jwt.service.spec.js
  pupil-spa/test/features/step_definitions/check_steps.rb
  pupil-spa/test/features/step_definitions/complete_page_steps.rb
  pupil-spa/test/features/step_definitions/pin_expiry_steps.rb
  pupil-spa/test/features/step_definitions/state_steps.rb
Labels: CI Enabled, DNM - Requires Testing, Ready for review

#575 Allows a helpdesk user to impersonate a school user
  .gitignore
  admin/authentication/local-strategy.js
  admin/data/sql/migrations/070.do.add-helpdesk-role.sql
  admin/data/sql/migrations/070.undo.add-helpdesk-role.sql
  admin/data/sql/migrations/071.do.add-helpdesk-user.sql
  admin/data/sql/migrations/071.undo.add-helpdesk-user.sql
  admin/services/data-access/role.data.service.js
  admin/services/nca-tools-user.service.js
  admin/services/role.service.js
  admin/spec/service/role.service.spec.js
Labels: CI Enabled, DNM - Requires Testing, Reviewed & approved, Testing

#574 Extend pending submission minimum display view time
  pupil-spa/src/environments/environment.prod.ts
  pupil-spa/src/environments/environment.ts
Labels: CI Enabled, DNM - Requires Testing, Ready for review

#584 Feedback redirect issue
  pupil-spa/src/app/check-complete/check-complete.component.spec.ts
  pupil-spa/src/app/check-complete/check-complete.component.ts
Labels: DNM - Requires Testing, Ready for review

#583 Feature/fix pupil spa test
  pupil-spa/test/features/step_definitions/check_steps.rb
  pupil-spa/test/features/step_definitions/complete_page_steps.rb
  pupil-spa/test/features/step_definitions/event_auditing_steps.rb
  pupil-spa/test/features/step_definitions/pin_expiry_steps.rb
  pupil-spa/test/features/step_definitions/state_steps.rb
  pupil-spa/test/features/support/hooks.rb
  pupil-spa/test/features/support/page_objects/check_page.rb
  pupil-spa/test/features/support/page_objects/complete_page.rb
  pupil-spa/test/features/support/page_objects/warm_up_page.rb
Labels: CI Enabled, Testing

#581 19874 - backfill check.startedAt date if its missing
  admin/services/check-complete.service.js
  admin/spec/mocks/check.js
  admin/spec/service/check-complete.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off

#586 Mods to inspect-spa-data.js script
  admin/bin/inspect-spa-data.js
  admin/package.json
  admin/yarn.lock
Labels: CI Enabled, Ready for review, Reviewed & approved

#585 Class disruption mandatory textarea on restart select screen
  admin/assets/stylesheets/elements/_restarts.scss
  admin/controllers/restart.js
  admin/data/sql/migrations/072.do.add-restart-classroom-disruption-info.sql
  admin/data/sql/migrations/072.undo.add-restart-classroom-disruption-info.sql
  admin/lib/consts/pupil-restart-reasons.js
  admin/lib/errors/restart.js
  admin/lib/validator/restart-validator.js
  admin/services/restart.service.js
  admin/spec/lib/validator/restart-validator.spec.js
  admin/spec/mocks/pupil-restart.js
  admin/spec/mocks/pupil-restarts-isDeleted.js
  admin/test/features/restarts.feature
  admin/test/features/step_definitions/restarts_steps.rb
  admin/test/features/support/page_objects/restarts_page.rb
  admin/views/restart/select-restart-list.ejs
  design/schemas/database/pupilrestarts.json
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#582 Feature/19795 service manager user takes school persona read write access
  admin/authentication/local-strategy.js
  admin/bin/inspect-spa-data.js
  admin/gulpfile.js
  admin/services/data-access/check-form.data.service.js
  admin/services/data-access/check-window.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/pupil.service.js
  admin/services/role.service.js
  admin/spec/service/nca-tools-auth-service.spec.js
  admin/spec/service/nca-tools-user.service.spec.js
  admin/spec/service/pupil-authentication.service.spec.js
  admin/spec/service/role.service.spec.js
  admin/test/features/school_landing.feature
  admin/test/features/step_definitions/school_landing_page_steps.rb
  admin/tests-integration/sql.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#587 19326 Remove link ux changes
  admin/assets/stylesheets/elements/_not-taking-check.scss
  admin/views/restart/restart-overview.ejs
Labels: CI Enabled, Ready for review, Tested

#591 Groups: underline remove link and adjust font size
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_groups.scss
  admin/views/groups/groups.ejs
Labels: CI Enabled, DNM - Requires Testing, Ready for review, Tested

#588 17599 - Pupil name and dob
  admin/assets/stylesheets/elements/_flash-messages.scss
  admin/assets/stylesheets/elements/_restarts.scss
  admin/controllers/restart.js
  admin/controllers/school.js
  admin/services/data-access/group.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/data-access/pupils-not-taking-check.data.service.js
  admin/services/pin-generation.service.js
  admin/services/pin.service.js
  admin/services/pupil-identification-flag.service.js
  admin/services/pupil.service.js
  admin/services/pupils-not-taking-check.service.js
  admin/services/restart.service.js
  admin/spec/controllers/restart.spec.js
  admin/spec/controllers/school.spec.js
  admin/spec/mocks/pupil.js
  admin/spec/service/pin-generation.service.spec.js
  admin/spec/service/pupil-identification-flag.service.spec.js
  admin/views/pupil-pin/generate-pins-list.ejs
  admin/views/pupil-pin/generated-pins-list.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/restart/select-restart-list.ejs
  admin/views/school/pupil-register.ejs
  admin/views/school/pupils-not-taking-check.ejs
  admin/views/school/select-pupils-not-taking-check.ejs
Labels: Reviewed & approved, Signed Off, Tested

#590 Feature/17255 school controller refactoring (part 1)
  admin/app.js
  admin/controllers/pupils-not-taking-the-check.js
  admin/controllers/school.js
  admin/package.json
  admin/routes/pupils-not-taking-the-check.js
  admin/routes/school.js
  admin/services/attendance.service.js
  admin/services/data-access/attendance-code.data.service.js
  admin/services/pupils-not-taking-check.service.js
  admin/spec/controllers/pupils-not-taking-the-check.spec.js
  admin/spec/controllers/school.spec.js
  admin/spec/service/pupils-not-taking-check.service.spec.js
  admin/test/features/support/page_objects/assign_form_to_window_page.rb
  admin/test/features/support/page_objects/pupil_reason_page.rb
  admin/test/features/support/page_objects/pupils_not_taking_check_page.rb
  admin/test/features/support/page_objects/school_landing_page.rb
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  admin/views/school/pupil-register.ejs
  admin/views/school/school-home.ejs
Labels: DNM - Requires Testing, Reviewed & approved

#595 Feature/17255 school controller refactoring part 1
  admin/app.js
  admin/controllers/pupils-not-taking-the-check.js
  admin/controllers/school.js
  admin/package.json
  admin/routes/pupils-not-taking-the-check.js
  admin/routes/school.js
  admin/services/attendance.service.js
  admin/services/data-access/attendance-code.data.service.js
  admin/services/pupil-identification-flag.service.js
  admin/services/pupils-not-taking-check.service.js
  admin/services/school.service.js
  admin/spec/controllers/pupils-not-taking-the-check.spec.js
  admin/spec/controllers/school.spec.js
  admin/spec/service/pupils-not-taking-check.service.spec.js
  admin/test/features/support/page_objects/assign_form_to_window_page.rb
  admin/test/features/support/page_objects/pupil_reason_page.rb
  admin/test/features/support/page_objects/pupils_not_taking_check_page.rb
  admin/test/features/support/page_objects/school_landing_page.rb
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  admin/views/school/pupil-register.ejs
  admin/views/school/school-home.ejs
  admin/yarn.lock
Labels: CI Enabled, DNM - Requires Testing, Ready for review

#580 Update to Angular 5
  pupil-spa/package.json
  pupil-spa/yarn.lock
Labels: CI Enabled, Ready for review, Tested, enhancement

#592 Feature/20091 add anomaly detection script
  admin/bin/detect-anomalies.js
  admin/services/data-access/completed-check.data.service.js
  pupil-spa/src/app/services/device/device.service.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#596 Feature/17255 school controller refactoring part 2
  admin/app.js
  admin/controllers/group.js
  admin/controllers/school.js
  admin/routes/group.js
  admin/routes/school.js
  admin/services/data-access/school.data.service.js
  admin/services/pupil-identification-flag.service.js
  admin/services/pupils-not-taking-check.service.js
  admin/spec/controllers/group.spec.js
  admin/spec/controllers/pupils-not-taking-the-check.spec.js
  admin/spec/controllers/school.spec.js
  admin/test/features/school_landing.feature
  admin/test/features/support/page_objects/add_edit_groups_page.rb
  admin/test/features/support/page_objects/group_pupils_page.rb
  admin/test/features/support/page_objects/school_landing_page.rb
  admin/views/groups/groups.ejs
  admin/views/groups/manage-group.ejs
  admin/views/school/pupil-register.ejs
  admin/views/school/school-home.ejs
Labels: CI Enabled, Reviewed & approved, Tested

#598 updated security test for admin app
  api_tests/spec/security_spec.rb
Labels: CI Enabled, Ready for review
