Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2018-07, with the labels that each got.

#741 22088 - Trial Hotfix- pupil data generation fails with error
  .travis.yml
  admin/app.js
  admin/services/anomaly-report.service.js
  admin/services/psychometrician-util.service.js
  admin/spec/service/psychometrician-report.service.spec.js
  admin/spec/service/psychometrician-util.service.spec.js
  test/admin/features/step_definitions/manage_check_forms_steps.rb
  test/admin/features/support/page_objects/assign_form_to_window_page.rb
Labels: CI Enabled, Ready for review, Tested

#719 20512 - Added device type/model/identifier in the psychometrician report
  admin/package.json
  admin/services/psychometrician-report.service.js
  admin/services/psychometrician-util.service.js
  admin/spec/service/psychometrician-util.service.spec.js
  admin/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#732 Feature/15191 school admin prolong session
  admin/app.js
  admin/assets/stylesheets/application.scss
  admin/config.js
  admin/helpers/index.js
  admin/views/groups/groups.ejs
  admin/views/groups/manage-group.ejs
  admin/views/layout.ejs
  admin/views/partials/_session_expiry.ejs
  admin/views/pupil-pin/generate-pins-list.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/generated-pins-list.ejs
  admin/views/pupil-register/add-pupil.ejs
  admin/views/pupil-register/edit-pupil.ejs
  admin/views/pupil-register/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/restart/select-restart-list.ejs
  admin/views/school/add-multiple-pupils.ejs
  admin/views/school/declaration-form-submitted.ejs
  admin/views/school/declaration-form.ejs
  admin/views/school/no-results.ejs
  admin/views/school/results.ejs
  admin/views/school/school-home.ejs
  admin/views/school/submit-attendance-register.ejs
  admin/views/service-manager/check-settings.ejs
  admin/views/service-manager/check-windows-form.ejs
  admin/views/service-manager/check-windows.ejs
  admin/views/service-manager/choose-check-window.ejs
  admin/views/service-manager/service-manager-home.ejs
  admin/views/service-manager/upload-pupil-census.ejs
  admin/views/test-developer/assign-check-forms-to-windows.ejs
  admin/views/test-developer/assign-forms.ejs
  admin/views/test-developer/download-pupil-check-data.ejs
  admin/views/test-developer/test-developer-home.ejs
  admin/views/test-developer/unassign-check-forms.ejs
  admin/views/test-developer/upload-and-view-forms.ejs
  admin/views/test-developer/upload-new-form.ejs
  admin/views/test-developer/view-check-form.ejs
  test/admin/features/step_definitions/add_multiple_pupil_steps.rb
  test/admin/features/support/page_objects/add_edit_check_window_page.rb
  test/admin/features/support/page_objects/add_edit_groups_page.rb
  test/admin/features/support/page_objects/add_multiple_pupil_page.rb
  test/admin/features/support/page_objects/add_pupil_page.rb
  test/admin/features/support/page_objects/check_settings_page.rb
  test/admin/features/support/page_objects/edit_pupil_page.rb
  test/admin/features/support/page_objects/generate_pins_overview_page.rb
  test/admin/features/support/page_objects/restarts_page.rb
  test/admin/features/support/page_objects/upload_and_view_forms_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#739 Spike/22076 exploratory work on changes to check
  admin/data/sql/new-tables/01. checkFormAllocation.sql
  admin/data/sql/new-tables/02. checkStatus.sql
  admin/data/sql/new-tables/03. checkStatus-data.sql
  pupil-api/sql/migrations/002.do.create-checks-table.sql
  spike-storage-queue/client/.vscode/settings.json
  spike-storage-queue/client/azure-storage.queue.js
  spike-storage-queue/client/index.html
  spike-storage-queue/client/queue-util.js
  spike-storage-queue/client/readme.md
  spike-storage-queue/server-issue-sas/index.js
  spike-storage-queue/server-issue-sas/package.json
  spike-storage-queue/server-issue-sas/readme.md
  spike-storage-queue/server-issue-sas/yarn.lock
Labels: Ready for review

#744 Bug/22098 Update pupil PIN text
  pupil-spa/src/app/login/login.component.html
Labels: CI Enabled, DNM - Requires Testing, Reviewed & approved, Signed Off, Tested

#735 Feature/21905 speech disable reading header
  pupil-spa/src/app/header/header.component.html
  pupil-spa/src/app/services/speech/speech.service.ts
Labels: CI Enabled, Ready for review, Signed Off, Tested

#745 Bug/22092 trial hotfix pupil data generation fails with error merge to master
  admin/app.js
  admin/services/anomaly-report.service.js
  admin/services/psychometrician-util.service.js
  admin/spec/service/psychometrician-report.service.spec.js
  admin/spec/service/psychometrician-util.service.spec.js
  test/admin/features/step_definitions/manage_check_forms_steps.rb
  test/admin/features/support/page_objects/assign_form_to_window_page.rb
Labels: CI Enabled, Reviewed & approved

#743 Bug/22083 Pupil download check IE11
  admin/controllers/check-form.js
  admin/views/test-developer/download-pupil-check-data.ejs
Labels: CI Enabled, DNM - Requires Testing, Reviewed & approved, Signed Off, Tested

#751 Bug/22133 Remove pupil localstorage after login
  pupil-spa/src/app/login-success/login-success.component.spec.ts
  pupil-spa/src/app/login-success/login-success.component.ts
  test/pupil/features/login_page.feature
Labels: Reviewed & approved, Signed Off, Tested

#747 feature/22060 - refactored some of the tests to make them more efficient
  test/admin/features/add_multiple_pupil.feature
  test/admin/features/add_pupil.feature
  test/admin/features/assign_check_to_windows.feature
  test/admin/features/create_check_window.feature
  test/admin/features/download_pupil_check_data.feature
  test/admin/features/edit_check_window.feature
  test/admin/features/edit_pupil.feature
  test/admin/features/step_definitions/add_multiple_pupil_steps.rb
  test/admin/features/step_definitions/add_pupil_steps.rb
  test/admin/features/step_definitions/assign_check_window_steps.rb
  test/admin/features/step_definitions/create_window_steps.rb
  test/admin/features/step_definitions/download_pupil_check_data_steps.rb
  test/admin/features/step_definitions/manage_pupil_steps.rb
  test/admin/features/step_definitions/unauthorized_steps.rb
  test/admin/features/step_definitions/upload_pupil_census_steps.rb
  test/admin/features/step_definitions/upload_view_forms_steps.rb
  test/admin/features/support/page_objects/download_pupil_check_data_page.rb
  test/admin/features/unauthorized_login.feature
  test/admin/features/upload_pupil_census.feature
  test/admin/features/upload_view_forms.feature
  test/admin/features/view_check.feature
  test/pupil/features/check.feature
  test/pupil/features/complete_page.feature
  test/pupil/features/feedback.feature
  test/pupil/features/instructions_page.feature
  test/pupil/features/login_page.feature
  test/pupil/features/pin_expiry.feature
  test/pupil/features/step_definitions/check_steps.rb
  test/pupil/features/step_definitions/complete_page_steps.rb
  test/pupil/features/step_definitions/feedback_steps.rb
  test/pupil/features/step_definitions/instructions_steps.rb
  test/pupil/features/step_definitions/pin_expiry_steps.rb
  test/pupil/features/step_definitions/warm_up_steps.rb
  test/pupil/features/warm_up_questions.feature
Labels: Reviewed & approved, Tested

#750 Bug/22117 Catch CSRF errors
  admin/app.js
  admin/views/sign-in.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#760 Feature/22407 create azure storage tables & queues during deployment
  deploy/cosmos/create-collections.sh
  deploy/storage/create-items.sh
  design/schemas/database/adminlogonevents.json
  design/schemas/database/adminsessions.json
  design/schemas/database/attendancecodes.json
  design/schemas/database/changelog.json
  design/schemas/database/checkforms.json
  design/schemas/database/checks.json
  design/schemas/database/checkwindows.json
  design/schemas/database/completedchecks.json
  design/schemas/database/identitycounters.json
  design/schemas/database/logonevents.json
  design/schemas/database/pupilfeedbacks.json
  design/schemas/database/pupilrestarts.json
  design/schemas/database/pupils.json
  design/schemas/database/pupilstatuscodes.json
  design/schemas/database/readme.md
  design/schemas/database/restartcodes.json
  design/schemas/database/schools.json
  design/schemas/database/sessions.json
  design/schemas/database/settinglogs.json
  design/schemas/database/settings.json
  design/schemas/database/users.json
  design/schemas/storage-queues/check-started.json
  design/schemas/storage-queues/completed-check.json
  functions/check-started/function.json
  functions/completed-checks/function.json
  functions/feedback/function.json
  functions/pupil-prefs/function.json
  functions/readme.md
  vsoBuildServer.md
Labels: Ready for review

#754 Feature/18551 Client side sorting
  admin/assets/javascripts/global-scripts.js
  admin/assets/javascripts/table-sorting.js
  admin/assets/stylesheets/elements/_sorting.scss
  admin/controllers/check-form.js
  admin/controllers/pupil-pin.js
  admin/controllers/pupil-register.js
  admin/controllers/pupil.js
  admin/controllers/pupils-not-taking-the-check.js
  admin/gulpfile.js
  admin/routes/pupil-pin.js
  admin/routes/pupil-register.js
  admin/routes/pupils-not-taking-the-check.js
  admin/routes/test-developer.js
  admin/services/data-access/pupil.data.service.js
  admin/services/pin-generation.service.js
  admin/services/pupils-not-taking-check.service.js
  admin/spec/controllers/check-form.spec.js
  admin/spec/controllers/pupil-pin.spec.js
  admin/spec/controllers/pupils-not-taking-the-check.spec.js
  admin/spec/service/pin-generation.service.spec.js
  admin/views/groups/groups.ejs
  admin/views/pupil-pin/generate-pins-list.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/generated-pins-list.ejs
  admin/views/pupil-register/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/school/_pupil-form.ejs
  admin/views/school/add-multiple-pupils.ejs
  admin/views/school/school-home.ejs
  admin/views/test-developer/upload-and-view-forms.ejs
  test/admin/features/support/page_objects/group_pupils_page.rb
  test/admin/features/support/page_objects/pupil_register_page.rb
  test/admin/features/support/page_objects/school_landing_page.rb
Labels: Reviewed & approved, Signed Off, Tested

#753 Feature/22058 Replaced loops with join when getting checks with forms
  admin/services/anomaly-report.service.js
  admin/services/check-complete.service.js
  admin/services/data-access/completed-check.data.service.js
  admin/services/marking.service.js
  admin/spec/service/anomaly-report.service.spec.js
  admin/spec/service/marking.service.spec.js
Labels: CI Enabled, Reviewed & approved, Tested

#758 Bug/18734 check window error messages
  admin/controllers/service-manager.js
  admin/lib/errors/check-window.js
  admin/lib/validator/check-window/check-window-add-validator.js
  admin/lib/validator/check-window/check-window-admin-start-date-validator.js
  admin/lib/validator/check-window/check-window-check-end-date-validator.js
  admin/lib/validator/check-window/check-window-check-start-date-validator.js
  admin/lib/validator/check-window/check-window-edit-validator.js
  admin/spec/controllers/service-manager.spec.js
  admin/spec/lib/validator/check-window/check-window-add-validator.spec.js
  admin/spec/lib/validator/check-window/check-window-admin-start-date-validator.spec.js
  admin/spec/lib/validator/check-window/check-window-check-end-date-validator.spec.js
  admin/spec/lib/validator/check-window/check-window-check-start-date-validator.spec.js
  admin/spec/lib/validator/check-window/check-window-edit-validator.spec.js
  admin/views/service-manager/check-window-form.ejs
  admin/views/service-manager/check-windows-form.ejs
  test/admin/features/step_definitions/create_window_steps.rb
  test/admin/features/support/page_objects/add_edit_check_window_page.rb
Labels: Reviewed & approved, Signed Off, Tested

#761 Feature/21345 add bacpac importer
  _util/bacpac-importer/Dockerfile
  _util/bacpac-importer/README.md
  _util/bacpac-importer/example-env
  _util/bacpac-importer/import-bacpac.sh
  admin/bin/inspect-spa-data.js
Labels: CI Enabled, Reviewed & approved

#755 optimising admin cucumber test
  test/admin/features/generate_pupil_pins.feature
  test/admin/features/groups.feature
  test/admin/features/manage_check_window.feature
  test/admin/features/pupil_not_taking_check.feature
  test/admin/features/restarts.feature
  test/admin/features/school_landing.feature
  test/admin/features/service_manager_landing.feature
  test/admin/features/sign_in.feature
  test/admin/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin/features/step_definitions/groups_steps.rb
  test/admin/features/step_definitions/manage_check_windows.rb
  test/admin/features/step_definitions/pupil_not_taking_check.rb
  test/admin/features/step_definitions/restarts_steps.rb
  test/admin/features/step_definitions/school_landing_page_steps.rb
  test/admin/features/step_definitions/service_manager_landing_steps.rb
  test/admin/features/step_definitions/sign_in_steps.rb
  test/admin/features/step_definitions/test_developer_homepage_steps.rb
  test/admin/features/test_developer_landing_page.feature
Labels: Reviewed & approved, Signed Off, Tested

#756 Feature/22280 add application insights library
  admin/helpers/browserSecurity.js
  admin/helpers/index.js
  admin/views/partials/_body_start.ejs
  pupil-spa/Dockerfile
  pupil-spa/gulpfile.js
  pupil-spa/package.json
  pupil-spa/src/app/app.component.ts
  pupil-spa/src/app/check-complete/check-complete.component.ts
  pupil-spa/src/app/check/check.component.ts
  pupil-spa/src/app/error-handler.ts
  pupil-spa/src/app/instructions/instructions.component.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.ts
  pupil-spa/src/app/warmup-intro/warmup-intro.component.ts
  pupil-spa/src/environments/environment.prod.ts
  pupil-spa/src/environments/environment.ts
  pupil-spa/yarn.lock
Labels: CI Enabled, Reviewed & approved

#749 Feature/19548 spa inject env vars runtime
  .gitignore
  pupil-spa/Dockerfile
  pupil-spa/docker-start.sh
  pupil-spa/gen_config.sh
  pupil-spa/gulpfile.js
  pupil-spa/package.json
  pupil-spa/src/app/app.component.spec.ts
  pupil-spa/src/app/app.component.ts
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/services/config/config.service.spec.ts
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/services/feedback/feedback.service.spec.ts
  pupil-spa/src/app/services/feedback/feedback.service.ts
  pupil-spa/src/app/services/submission/submission.service.spec.ts
  pupil-spa/src/app/services/submission/submission.service.ts
  pupil-spa/src/app/services/user/user.service.spec.ts
  pupil-spa/src/app/services/user/user.service.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.ts
  pupil-spa/src/environments/environment.prod.ts
  pupil-spa/src/environments/environment.ts
Labels: CI Enabled, Ready for review

#757 Feature/22322 admin familiarisation pins
  admin/assets/images/icon-search.png
  admin/assets/javascripts/global-scripts.js
  admin/assets/javascripts/pupil-filter-group.js
  admin/assets/javascripts/pupil-filter-name.js
  admin/assets/javascripts/util-checkbox.js
  admin/assets/stylesheets/elements/_filters.scss
  admin/controllers/pupil-pin.js
  admin/controllers/questions.js
  admin/gulpfile.js
  admin/routes/pupil-pin.js
  admin/services/check-start.service.js
  admin/services/data-access/check.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/pin-generation.service.js
  admin/services/pin.service.js
  admin/spec/back-end/controllers/check-form.spec.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/spec/back-end/service/check-start.service.spec.js
  admin/spec/back-end/service/pin-generation.service.spec.js
  admin/spec/back-end/service/pin.service.spec.js
  admin/views/pupil-pin/generate-pins-list.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/generated-pins-list.ejs
  admin/views/pupil-pin/pin-print.ejs
  admin/views/school/school-home.ejs
  test/admin/features/breadcrumbs.feature
  test/admin/features/generate_pupil_pin_familiarisation.feature
  test/admin/features/step_definitions/generate_pupil_pin_familiarisation_steps.rb
  test/admin/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin/features/step_definitions/school_landing_page_steps.rb
  test/admin/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/admin/features/support/page_objects/generate_pins_overview_page.rb
  test/admin/features/support/page_objects/generated_pins_page.rb
  test/admin/features/support/page_objects/school_landing_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#763 Feature/22497 Access arrangements home view
  admin/app.js
  admin/controllers/access-arrangements.js
  admin/routes/access-arrangements.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/school/school-home.ejs
  test/admin/features/access_arrangements.feature
  test/admin/features/step_definitions/access_arrangements_steps.rb
  test/admin/features/support/page_objects/access_arrangements_page.rb
  test/admin/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/admin/features/support/page_objects/generate_pins_overview_page.rb
Labels: CI Enabled, Ready for review, Signed Off, Tested

#765 Feature/22405 view and print pins page
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_pupil-pin.scss
  admin/controllers/pupil-pin.js
  admin/routes/pupil-pin.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/views/pupil-pin/view-and-print-pins.ejs
  test/admin/features/generate_pupil_pin_familiarisation.feature
  test/admin/features/generate_pupil_pins.feature
  test/admin/features/pupil_status.feature
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#766 Feature/22406 print preview page
  admin/assets/stylesheets/elements/_printing.scss
  admin/controllers/pupil-pin.js
  admin/services/pupil-identification-flag.service.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/spec/back-end/service/pupil-identification-flag.service.spec.js
  admin/views/pupil-pin/pin-print.ejs
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested

#764 Added header to disable cache for config.json in the nginx config
  pupil-spa/nginx/default.conf
Labels: CI Enabled, Ready for review

#774 remove google drive secure env vars
  .travis.yml
Labels: CI Enabled

#768 Feature/22544 access arrangements list
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_lists.scss
  admin/assets/stylesheets/elements/_restarts.scss
  admin/config/feature-toggles.Azure-UAT.json
  admin/config/feature-toggles.default.json
  admin/controllers/access-arrangements.js
  admin/data/sql/migrations/106.do.create-access-arrangements.sql
  admin/data/sql/migrations/106.undo.create-access-arrangements.sql
  admin/data/sql/migrations/107.do.insert-access-arrangements.sql
  admin/data/sql/migrations/107.undo.insert-access-arrangements.sql
  admin/routes/access-arrangements.js
  admin/services/access-arrangements.service.js
  admin/services/data-access/access-arrangements.data.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/service/access-arrangements.service.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/access-arrangements/select-access-arrangements.ejs
  admin/views/restart/select-restart-list.ejs
  admin/views/school/school-home.ejs
  test/admin/features/access_arrangements.feature
  test/admin/features/step_definitions/access_arrangements_steps.rb
  test/admin/features/support/page_objects/restarts_page.rb
  test/admin/features/support/page_objects/select_access_arrangements_page.rb
  test/admin/features/support/sql_db_helper.rb
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested
