Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2018-04, with the labels that each got.

#589 Service manager manage check windows refactor
  admin/controllers/service-manager.js
  admin/services/check-window.service.js
  admin/services/data-access/check-window.data.service.js
  admin/spec/service/check-window.service.spec.js
  admin/views/service-manager/check-windows.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#597 Bug/20087 fix mouse and touch event parsing
  admin/package.json
  admin/services/psychometrician-util.service.js
  admin/spec/service/psychometrician-util.service.spec.js
  pupil-spa/src/app/check/check.component.ts
  pupil-spa/src/app/question/question.component.ts
  pupil-spa/tsconfig.json
  pupil-spa/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#601 20241 - Fixed the Chrome errors that occur when building the test containers
  test/admin/Dockerfile
  test/pupil/Dockerfile
Labels: Ready for review

#603 bug/20218 Updated input type and pattern for pupilPin input
  admin/spec/service/psychometrician-util.service.spec.js
  pupil-spa/src/app/login/login.component.html
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#593 Feature/20144 Refactor add and edit check window functionality
  admin/controllers/service-manager.js
  admin/routes/service-manager.js
  admin/services/check-window.service.js
  admin/services/data-access/check-window.data.service.js
  admin/spec/mocks/check-window.js
  admin/spec/service/check-window.service.spec.js
  admin/views/service-manager/check-windows-form.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#609 reset feature toggles on UAT
  admin/config/feature-toggles.Azure-UAT.json
Labels: Ready for review

#608 Tech chore: make the anomaly detection script more robust
  admin/bin/detect-anomalies.js
Labels: CI Enabled, Reviewed & approved

#606 Feature/20299 pupil check audible timer
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/check/check.component.html
  pupil-spa/src/app/practice-question/practice-question.component.ts
  pupil-spa/src/app/question/question.component.spec.ts
  pupil-spa/src/app/sound/sound.component.html
  pupil-spa/src/app/sound/sound.component.scss
  pupil-spa/src/app/sound/sound.component.spec.ts
  pupil-spa/src/app/sound/sound.component.ts
  pupil-spa/src/app/spoken-practice-question/spoken-practice-question.component.ts
  pupil-spa/src/app/spoken-question/spoken-question.component.spec.ts
  pupil-spa/src/app/spoken-question/spoken-question.component.ts
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#610 20409 copy, sidebar and disabled link changes
  admin/assets/stylesheets/application.scss
  admin/views/pupil-register/pupils-list.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/school/school-home.ejs
Labels: CI Enabled, Ready for review

#604 Added receivedByServerAt field to application service tier
  admin/data/sql/migrations/073.do.add-receivedbyserverat-to-check.sql
  admin/data/sql/migrations/073.undo.add-receivedbyserverat-to-check.sql
  admin/services/check-complete.service.js
  admin/services/data-access/completed-check.data.service.js
  admin/spec/service/check-complete.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#607 Feature/20322 Service manager refactor
  admin/controllers/service-manager.js
  admin/lib/validator/check-window-validator.js
  admin/lib/validator/settings-validator.js
  admin/routes/service-manager.js
  admin/services/check-window.service.js
  admin/services/data-access/setting.data.service.js
  admin/services/setting.service.js
  admin/spec/controllers/service-manager.js
  admin/spec/lib/validator/check-window-validator.spec.js
  admin/spec/lib/validator/settings-validator.spec.js
  admin/spec/service/check-window.service.spec.js
  admin/spec/service/setting.service.spec.js
  admin/views/service-manager/check-settings.ejs
  admin/views/service-manager/check-windows-form.ejs
Labels: CI Enabled, DNM - Requires Testing, Ready for review, Sign off, Tested

#611 20090 Remove wrong number of inputs detection
  admin/bin/detect-anomalies.js
Labels: CI Enabled, Reviewed & approved

#614 Feature/20523 use shared linux build host instead of dedicated VMs
  admin-assets/copy-assets.sh
  deploy/sql-migrations/migrate-db.sh
Labels: CI Enabled, Ready for review

#616 Feature/20351 anomaly detection update
  admin/bin/detect-anomalies.js
  admin/services/data-access/sql.pool.service.js
Labels: CI Enabled, Reviewed & approved

#612 Feature/20300 pupilspa webspeech api
  pupil-spa/src/app/check-complete/check-complete.component.spec.ts
  pupil-spa/src/app/check-complete/check-complete.component.ts
  pupil-spa/src/app/instructions/instructions.component.ts
  pupil-spa/src/app/loading/loading.component.spec.ts
  pupil-spa/src/app/loading/loading.component.ts
  pupil-spa/src/app/login-success/login-success.component.spec.ts
  pupil-spa/src/app/login-success/login-success.component.ts
  pupil-spa/src/app/practice-question/practice-question.component.spec.ts
  pupil-spa/src/app/practice-question/practice-question.component.ts
  pupil-spa/src/app/question/question.component.spec.ts
  pupil-spa/src/app/question/question.component.ts
  pupil-spa/src/app/services/audit/auditEntry.ts
  pupil-spa/src/app/services/question/question.service.mock.ts
  pupil-spa/src/app/services/speech/speech.service.mock.ts
  pupil-spa/src/app/services/speech/speech.service.spec.ts
  pupil-spa/src/app/services/speech/speech.service.ts
  pupil-spa/src/app/spoken-practice-question/spoken-practice-question.component.spec.ts
  pupil-spa/src/app/spoken-practice-question/spoken-practice-question.component.ts
  pupil-spa/src/app/spoken-question/spoken-question.component.spec.ts
  pupil-spa/src/app/spoken-question/spoken-question.component.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.spec.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.spec.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.ts
  pupil-spa/src/app/warmup-complete/warmup-complete.component.spec.ts
  pupil-spa/src/app/warmup-complete/warmup-complete.component.ts
  pupil-spa/src/app/warmup-intro/warmup-intro.component.spec.ts
  pupil-spa/src/app/warmup-intro/warmup-intro.component.ts
  pupil-spa/src/app/warmup-loading/warmup-loading.component.spec.ts
  pupil-spa/src/app/warmup-loading/warmup-loading.component.ts
Labels: CI Enabled, Reviewed & approved, Testing

#618 Update media-src content security policy for the SPA
  pupil-spa/nginx/default.conf
Labels: CI Enabled, Ready for review

#613 19990 Anomaly script and spa improvements
  admin/bin/detect-anomalies.js
  pupil-spa/src/app/question/question.component.spec.ts
  pupil-spa/src/app/question/question.component.ts
  test/pupil/features/step_definitions/registered_inputs_steps.rb
  test/pupil/features/support/page_objects/check_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#617 SQL Server Auditing - 1st Pass
  admin/data/sql/migrations/074.do.create-auditlog-table.sql
  admin/data/sql/migrations/074.undo.create-auditlog-table.sql
  admin/data/sql/migrations/075.do.create-spGenAuditTriggers.sql
  admin/data/sql/migrations/075.undo.create-spGenAuditTriggers.sql
  admin/data/sql/migrations/076.do.gen-triggers.sql
  admin/data/sql/migrations/076.undo.gen-triggers.sql
  admin/services/data-access/sql.service.js
  design/auditing/spGenTriggers.sql
Labels: CI Enabled, Ready for review

#622 20616 - fix failing security test
  api_tests/spec/security_spec.rb
Labels: CI Enabled, Ready for review, Tested

#619 Feature/20617 pupilspa webspeech api fixes
  pupil-spa/src/app/check-complete/check-complete.component.ts
  pupil-spa/src/app/instructions/instructions.component.ts
  pupil-spa/src/app/loading/loading.component.ts
  pupil-spa/src/app/login-success/login-success.component.ts
  pupil-spa/src/app/practice-question/practice-question.component.ts
  pupil-spa/src/app/services/speech/speech.service.ts
  pupil-spa/src/app/spoken-practice-question/spoken-practice-question.component.ts
  pupil-spa/src/app/spoken-question/spoken-question.component.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.html
  pupil-spa/src/app/submission-pending/submission-pending.component.ts
  pupil-spa/src/app/warmup-complete/warmup-complete.component.ts
  pupil-spa/src/app/warmup-intro/warmup-intro.component.ts
Labels: Ready to merge, Signed Off, Tested

#621 Bug/20320 question response time is recorded for entries without numeric values
  admin/controllers/service-manager.js
  admin/package.json
  admin/services/data-access/sql.pool.service.js
  admin/services/psychometrician-report.service.js
  admin/services/psychometrician-util.service.js
  admin/spec/controllers/service-manager.spec.js
  admin/spec/mocks/keyboard-input-2.js
  admin/spec/mocks/keyboard-input-3.js
  admin/spec/mocks/keyboard-input-4.js
  admin/spec/mocks/keyboard-input-5.js
  admin/spec/mocks/mouse-input.js
  admin/spec/service/psychometrician-util.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#624 feature/20612 SQL Session store for Express
  admin/app.js
  admin/data/sql/migrations/077.do.sql-session-store.sql
  admin/data/sql/migrations/077.undo.sql-session-store.sql
  admin/data/sql/migrations/078.do.grant-session-delete.js
  admin/data/sql/migrations/078.undo.grant-session-delete.js
  admin/package.json
  admin/services/data-access/sql.pool.service.js
  admin/yarn.lock
  docker-compose.admin-test.yml
  docker-compose.pupil-test.yml
  docker-compose.yml
Labels: CI Enabled, Ready for review

#623 Feature/20393 disable pinch and zoom on tablets and trackpads
  pupil-spa/src/index.html
Labels: Reviewed & approved, Tested

#626 sql connection - default to UTC
  admin/app.js
  admin/services/data-access/sql.pool.service.js
Labels: CI Enabled, DNM - WIP

#625 Feature/18249 ncatools identifier
  admin/authentication/local-strategy.js
  admin/data/sql/migrations/079.do.add-displayname-to-user.sql
  admin/data/sql/migrations/079.undo.add-displayname-to-user.sql
  admin/data/sql/migrations/080.do.drop-nca-tools-session.sql
  admin/data/sql/migrations/080.undo.drop-nca-tools-session.sql
  admin/services/data-access/nca-tools-session.data.service.js
  admin/services/nca-tools-user.service.js
  admin/spec/service/nca-tools-user.service.spec.js
  admin/views/partials/_name_and_sign_out.ejs
Labels: CI Enabled, Reviewed & approved

#630 20756 CSV links bug
  admin/.gitignore
  admin/assets/csv/check-form-sample.csv
  admin/assets/csv/mtc-pupil-details-template-sheet-1.csv
  admin/gulpfile.js
  admin/views/school/add-multiple-pupils.ejs
  admin/views/test-developer/upload-new-form.ejs
Labels: Ready to merge, Requires sign off, Reviewed & approved, Tested
