Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2019-02, with the labels that each got.

#996 Feature/23280 staff submit hdf
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_hdf.scss
  admin/controllers/attendance.js
  admin/lib/errors/hdf-confirm.js
  admin/lib/validation-error.js
  admin/lib/validator/hdf-confirm-validator.js
  admin/routes/attendance.js
  admin/services/data-access/pupil.data.service.js
  admin/services/headteacher-declaration.service.js
  admin/spec/back-end/controllers/attendance.spec.js
  admin/spec/back-end/lib/validator/hdf-confirm-validator.spec.js
  admin/spec/back-end/service/headteacher-declaration.service.spec.js
  admin/views/hdf/attendance-edit-reason.ejs
  admin/views/hdf/confirm-and-submit.ejs
  admin/views/hdf/review-pupil-details.ejs
  test/admin-hpa/features/declaration_confirm.feature
  test/admin-hpa/features/declaration_edit_reason.feature
  test/admin-hpa/features/declaration_form.feature
  test/admin-hpa/features/declaration_review_pupils.feature
  test/admin-hpa/features/step_definitions/declaration_confirm_steps.rb
  test/admin-hpa/features/step_definitions/declaration_edit_reason_steps.rb
  test/admin-hpa/features/step_definitions/declaration_form_steps.rb
  test/admin-hpa/features/step_definitions/declaration_review_pupil_steps.rb
  test/admin-hpa/features/support/page_objects/declaration_confirm_page.rb
  test/admin-hpa/features/support/page_objects/declaration_edit_reason_page.rb
  test/admin-hpa/features/support/page_objects/declaration_page.rb
  test/admin-hpa/features/support/page_objects/declaration_review_pupils_page.rb
  test/admin-hpa/features/support/page_objects/edit_reason_for_hdf_pupil_page.rb
  test/admin-hpa/features/support/page_objects/error_summary_section.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1008 Activate new check forms feature in all envs
  admin/config.js
  admin/config/feature-toggles.Azure-Demo.json
  admin/config/feature-toggles.Azure-EE-Prod.json
  admin/config/feature-toggles.Azure-Proto.json
  admin/config/feature-toggles.eazure-demo.json
  admin/config/feature-toggles.eazure-dev.json
  admin/config/feature-toggles.eazure-live.json
  admin/config/feature-toggles.eazure-preprod.json
  admin/config/feature-toggles.eazure-proto.json
  admin/config/feature-toggles.eazure-test.json
  admin/config/feature-toggles.hpa-dev.json
  admin/config/feature-toggles.hpa-travis.json
Labels: Ready for review, Urgent

#1009 Bug/type checking issue on check form lines length comparison
  admin/config.js
  admin/lib/validator/check-form/single-check-form-validator.js
Labels: Ready for review, Urgent

#1006 Add and use new Guidance document for trial.
  admin/assets/pdfs/mtc-administration-guidance-2019-02-01.pdf
  admin/helpers/index.js
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1002 Feature/28374 refactor ps report to support hpa mode for feb trial
  admin/bin/psychometricians-report-v2.js
  admin/services/anomaly-report.service.js
  admin/services/check-processing.service.js
  admin/services/data-access/completed-check.data.service.js
  admin/services/data-access/psychometrician-report-cache.data.service.js
  admin/services/psychometrician-report.service.js
  admin/spec/back-end/service/anomaly-report.service.spec.js
  admin/spec/back-end/service/psychometrician-report.service.spec.js
Labels: CI Enabled, Ready for review, Signed Off, Tested

#1010 Update privacy notice
  admin/views/privacy.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1014 Feature/29216 - updated smart survey link for admin feedback
  admin/views/partials/_content.ejs
  load-test/notes/pin-gen-page.html
  test/admin-hpa/features/support/page_objects/phase_banner_section.rb
Labels: CI Enabled, Requires sign off, Reviewed & approved, Tested

#1004 Feature/29148 Introduced schoolScore and nationalScore tables
  admin/data/sql/migrations/20190131100745.do.create-school-score-national-score.sql
  admin/data/sql/migrations/20190131100745.undo.create-school-score-national-score.sql
Labels: CI Enabled, Reviewed & approved, Tested

#1016 Feature/29279 fix nightly failure
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/phase_banner.feature
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/phase_banner_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
  test/pupil-hpa/features/access_arrangements.feature
  test/pupil-hpa/features/support/hooks.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1017 fix estab codes by extracting from dfeNumber
  admin/data/sql/README.md
  admin/data/sql/seeds/20190207112809.custom.fix-estab-code.sql
  rabbit_enabled_plugins
Labels: CI Enabled, Ready for review, Signed Off, Tested

#1013 Feature/27642 view hdf submission
  admin/assets/stylesheets/elements/_hdf.scss
  admin/controllers/access-arrangements.js
  admin/controllers/attendance.js
  admin/controllers/pupil-pin.js
  admin/controllers/pupil-register.js
  admin/controllers/pupils-not-taking-the-check.js
  admin/controllers/restart.js
  admin/data/sql/migrations/20190121115615.do.alter-hdf-table.sql
  admin/data/sql/migrations/20190121115615.undo.alter-hdf-table.sql
  admin/helpers/hdf-presenter.js
  admin/helpers/school-home-feature-eligibility-presenter.js
  admin/routes/attendance.js
  admin/services/data-access/check-window.data.service.js
  admin/services/data-access/headteacher-declaration.data.service.js
  admin/services/headteacher-declaration.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/controllers/attendance.spec.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/spec/back-end/controllers/pupils-not-taking-the-check.spec.js
  admin/spec/back-end/controllers/restart.spec.js
  admin/spec/back-end/service/data-access/headteacher-declaration.data.service.spec.js
  admin/spec/back-end/service/headteacher-declaration.service.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/hdf/confirm-and-submit.ejs
  admin/views/hdf/submitted-form.ejs
  admin/views/hdf/submitted.ejs
  admin/views/hdf/unavailable.ejs
  admin/views/partials/_readonly.ejs
  admin/views/pupil-register/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  admin/views/school/declaration-form-submitted.ejs
  test/admin-hpa/features/declaration_confirm.feature
  test/admin-hpa/features/declaration_submitted.feature
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/step_definitions/declaration_form_steps.rb
  test/admin-hpa/features/step_definitions/declaration_submitted_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/declaration_complete_page.rb
  test/admin-hpa/features/support/page_objects/declaration_submitted_form_page.rb
  test/admin-hpa/features/support/page_objects/declaration_submitted_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1018 Bug/28079 pupil appears in pin list after restart is removed
  admin/data/sql/migrations/20190207152016.do.update-check-diagnostic-view.sql
  admin/data/sql/migrations/20190207152016.undo.update-check-diagnostic-view.sql
  functions/pupil-status/pupil-status-analysis.service.js
  functions/pupil-status/pupil-status-analysis.service.spec.js
  functions/pupil-status/pupil-status-batch.service.js
  functions/pupil-status/pupil-status.service.js
  test/admin-hpa/features/restarts.feature
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/support/hooks.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1019 Feature/29404 nightly build - pre & post database reset
  deploy/build-defs/full-deploy.yml
  test/admin-hpa/features/support/env.rb
  test/pupil-hpa/features/support/env.rb
Labels: CI NOT Required, Ready for review

#1020 Update vewPupilsEligibleForRestart view
  admin/data/sql/migrations/20190208111343.do.update-view-pupils-eligible-for-restart.sql
  admin/data/sql/migrations/20190208111343.undo.update-view-pupils-eligible-for-restart.sql
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1022 feature/automation-test-refactoring
  test/admin-hpa/features/generate_pupil_pin_familiarisation.feature
  test/admin-hpa/features/pupil_not_taking_check.feature
  test/admin-hpa/features/step_definitions/declaration_form_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/groups_steps.rb
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
  test/admin-hpa/features/support/page_objects/add_edit_groups_page.rb
  test/admin-hpa/features/support/page_objects/pupil_reason_page.rb
Labels: CI Enabled, Ready for review

#1023 Feature/28864 Result view for teacher level
  admin/app.js
  admin/assets/stylesheets/elements/_results.scss
  admin/controllers/results.js
  admin/helpers/result-presenter.js
  admin/routes/results.js
  admin/services/data-access/result.data.service.js
  admin/services/result.service.js
  admin/spec/back-end/controllers/results.spec.js
  admin/spec/back-end/helpers/result-presenter.spec.js
  admin/spec/back-end/service/result.service.spec.js
  admin/views/results/view-results.ejs
  admin/views/results/view-unavailable-results.ejs
  admin/views/school/school-home.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1025 Feature/29465 NBQ reason
  admin/assets/javascripts/pupil-access-arrangements-selection.js
  admin/controllers/access-arrangements.js
  admin/data/sql/migrations/107.do.insert-access-arrangements.sql
  admin/data/sql/migrations/20190213124312.do.aa-next-button-information.sql
  admin/data/sql/migrations/20190213124312.undo.aa-next-button-information.sql
  admin/lib/errors/access-arrangements.js
  admin/lib/validator/access-arrangements-validator.js
  admin/services/access-arrangements.service.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/services/pupil-access-arrangements.service.js
  admin/spec/back-end/lib/validator/access-arrangements-validator.spec.js
  admin/spec/back-end/service/access-arrangements.service.spec.js
  admin/spec/back-end/service/pupil-access-arrangements.service.spec.js
  admin/views/access-arrangements/select-access-arrangements.ejs
  test/admin-hpa/features/access_arrangements.feature
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/support/page_objects/select_access_arrangements_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1021 Spike pin collisions for schools at high volumes
  _spikes-poc/key-vault/README.md
  _spikes-poc/key-vault/index.js
  _spikes-poc/key-vault/key-vault.service.js
  _spikes-poc/key-vault/package.json
  _spikes-poc/key-vault/yarn.lock
  _spikes-poc/school-pin-aux-table/README.md
  _spikes-poc/school-pin-aux-table/ddl.sql
  _spikes-poc/school-pin-aux-table/migration.js
  _spikes-poc/school-pin-aux-table/package.json
  _spikes-poc/school-pin-aux-table/yarn.lock
Labels: Reviewed & approved, Signed Off

#1024 Feature/28534 psychometrician report updates
  admin/services/data-access/completed-check.data.service.js
  admin/services/psychometrician-report.service.js
  admin/services/psychometrician-util.service.js
  admin/spec/back-end/service/psychometrician-report.service.spec.js
  pupil-spa/src/app/practice-question/practice-question.component.ts
  pupil-spa/src/app/services/speech/speech.service.ts
  pupil-spa/src/app/spoken-practice-question/spoken-practice-question.component.ts
  pupil-spa/src/app/spoken-question/spoken-question.component.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1026 Feature/29241 School home HDF availability
  admin/views/school/school-home.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off

#967 Feature/27776 implement mssql lib for tedious
  admin/README.md
  admin/app.js
  admin/config/sql.config.js
  admin/controllers/pupil-pin.js
  admin/data/sql/migrations/20190114114600.do.add-max-nvarchar-to-integration-test.sql
  admin/data/sql/migrations/20190114114600.undo.add-max-nvarchar-to-integration-test.sql
  admin/data/sql/seed-sql.js
  admin/services/data-access/anomaly-report-cache.data.service.js
  admin/services/data-access/answer.data.service.js
  admin/services/data-access/attendance-code.data.service.js
  admin/services/data-access/check-form-allocation.data.service.js
  admin/services/data-access/check-form-v2.data.service.js
  admin/services/data-access/check-form.data.service.js
  admin/services/data-access/check-status.data.service.js
  admin/services/data-access/check-window.data.service.js
  admin/services/data-access/check.data.service.js
  admin/services/data-access/completed-check.data.service.js
  admin/services/data-access/config.data.service.js
  admin/services/data-access/group.data.service.js
  admin/services/data-access/headteacher-declaration.data.service.js
  admin/services/data-access/job-status.data.service.js
  admin/services/data-access/job-type.data.service.js
  admin/services/data-access/job.data.service.js
  admin/services/data-access/pin-generation.data.service.js
  admin/services/data-access/psychometrician-report-cache.data.service.js
  admin/services/data-access/psychometrician.data.service.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/services/data-access/pupil-attendance.data.service.js
  admin/services/data-access/pupil-census-import.data.service.js
  admin/services/data-access/pupil-census.data.service.js
  admin/services/data-access/pupil-register.data.service.js
  admin/services/data-access/pupil-restart.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/data-access/pupils-not-taking-check.data.service.js
  admin/services/data-access/restart-v2.data.service.js
  admin/services/data-access/result.data.service.js
  admin/services/data-access/role.data.service.js
  admin/services/data-access/school.data.service.js
  admin/services/data-access/setting-log.data.service.js
  admin/services/data-access/setting.data.service.js
  admin/services/data-access/sql.service.js
  admin/services/data-access/user.data.service.js
  admin/tests-integration/sql.service.spec.js
  docs/developer.md
  load-test/bin/generate-pupil-data.js
  load-test/bin/generate-teacher-for-each-school.js
  load-test/package-lock.json
Labels: CI Enabled, Reviewed & approved, Tested

#1032 Feature/29691 dynamic waiting
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/Rakefile
  test/admin-hpa/features/access_arrangements.feature
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/step_definitions/sign_in_steps.rb
  test/admin-hpa/features/step_definitions/upload_view_forms_steps.rb
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/generate_pins_overview_page.rb
  test/admin-hpa/features/support/page_objects/upload_new_forms_page.rb
  test/admin-hpa/features/support/site_prism_config.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/pupil-hpa/Rakefile
  test/pupil-hpa/features/support/env.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
Labels: Ready to merge, Reviewed & approved, Tested

#1027 Bug/24935 clicking yes on session expiry window is not extending the session
  admin/assets/javascripts/session-expiry.js
  admin/controllers/pupil.js
  admin/routes/pupil-register.js
  admin/views/check-form/view-assign-forms-to-check-windows.ejs
  admin/views/check-window/create-check-window.ejs
  admin/views/contact.ejs
  admin/views/cookies.ejs
  admin/views/error.ejs
  admin/views/partials/_print_pupils.ejs
  admin/views/privacy.ejs
  admin/views/pupil-register/pupils-print.ejs
  admin/views/results/view-results.ejs
  admin/views/results/view-unavailable-results.ejs
  admin/views/service-manager/check-window-form.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1031 Feature/29466 aa readonly check closed
  admin/controllers/access-arrangements.js
  admin/controllers/pupil-register.js
  admin/services/business-availability.service.js
  admin/services/data-access/headteacher-declaration.data.service.js
  admin/services/date.service.js
  admin/services/headteacher-declaration.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/service/data-access/headteacher-declaration.data.service.spec.js
  admin/spec/back-end/service/headteacher-declaration.service.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/partials/_readonly.ejs
  admin/views/pupil-register/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  admin/views/school/school-home.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1028 Bug/29827 Stringified numeric values sorting
  admin/assets/javascripts/table-sorting.js
  admin/spec/front-end/table-sorting.spec.js
  admin/views/results/view-results.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1030 Feature/29889 - Added NTR checks to psychometrician report
  admin/services/data-access/psychometrician-report-cache.data.service.js
  admin/services/psychometrician-report.service.js
  admin/services/psychometrician-util.service.js
  admin/spec/back-end/service/psychometrician-util.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1015 Feature/29191 Score calculation
  admin/controllers/results.js
  admin/data/sql/migrations/20190210204450.do.grant-delete-school-score.js
  admin/data/sql/migrations/20190210204450.undo.grant-delete-school-score.js
  admin/data/sql/migrations/20190214125344.do.add-date-fields-and-version-school-score.sql
  admin/data/sql/migrations/20190214125344.undo.add-date-fields-and-version-school-score.sql
  admin/data/sql/migrations/20190214132032.do.create-sp-refresh-score-data.sql
  admin/data/sql/migrations/20190214132032.undo.create-sp-refresh-score-data.sql
  admin/helpers/result-presenter.js
  admin/spec/back-end/controllers/results.spec.js
  admin/spec/back-end/helpers/result-presenter.spec.js
  functions/calculate-score/check-window.data.service.js
  functions/calculate-score/function.json
  functions/calculate-score/index.js
  functions/calculate-score/score-calculation.data.service.js
  functions/calculate-score/v1.js
  functions/calculate-score/v1.spec.js
  test/admin-hpa/features/support/azure_table_helper.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  test/pupil-hpa/features/check.feature
  test/pupil-hpa/features/step_definitions/check_steps.rb
  test/pupil-hpa/features/step_definitions/login_page_steps.rb
  test/pupil-hpa/features/support/page_objects/check_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1029 Feature/29910 Unassign familiarisation form and view changes
  admin/controllers/check-form-v2.js
  admin/helpers/check-form-presenter.js
  admin/services/check-form-v2.service.js
  admin/services/data-access/check-form-v2.data.service.js
  admin/spec/back-end/controllers/check-form-v2.spec.js
  admin/spec/back-end/helpers/check-form-presenter.spec.js
  admin/spec/back-end/service/check-form-v2.service.spec.js
  admin/views/check-form/view-select-forms.ejs
  test/admin-hpa/features/assign_to_check_window_v2.feature
  test/admin-hpa/features/step_definitions/assign_to_check_window_v2_steps.rb
  test/admin-hpa/features/support/page_objects/assign_form_to_window_v2_page.rb
  test/admin-hpa/features/support/page_objects/select_check_forms_to_assign_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested
