Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2019-07, with the labels that each got.

#1280 feature/automation-fix-checkwindow-redis-cache
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/features/support/hooks.rb
Labels: CI Enabled, Ready for review

#1273 33942 - fix ps report error
  functions-app/report-psychometrician/service/anomaly-report.service.js
  functions-app/report-psychometrician/service/psychometrician-util.service.js
  functions-app/report-psychometrician/spec/anomaly-report.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested, Urgent

#1281 test changes
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/step_definitions/add_multiple_pupil_steps.rb
  test/admin-hpa/features/step_definitions/add_multiple_pupil_validation_steps.rb
  test/admin-hpa/features/step_definitions/manage_check_windows.rb
  test/admin-hpa/features/support/page_objects/access_arrangements_page.rb
  test/admin-hpa/features/support/page_objects/group_pupils_page.rb
  test/admin-hpa/features/support/page_objects/manage_check_window_page.rb
  test/admin-hpa/features/support/page_objects/mod_schools_page.rb
  test/admin-hpa/features/support/page_objects/upload_and_view_forms_page.rb
  test/admin-hpa/features/support/page_objects/view_form_page.rb
Labels: CI Enabled, Reviewed & approved

#1283 revert gemfile updates
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/features/restarts.feature
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/step_definitions/add_multiple_pupil_steps.rb
  test/admin-hpa/features/step_definitions/add_multiple_pupil_validation_steps.rb
  test/admin-hpa/features/step_definitions/manage_check_windows.rb
  test/admin-hpa/features/support/page_objects/access_arrangements_page.rb
  test/admin-hpa/features/support/page_objects/group_pupils_page.rb
  test/admin-hpa/features/support/page_objects/manage_check_window_page.rb
  test/admin-hpa/features/support/page_objects/mod_schools_page.rb
  test/admin-hpa/features/support/page_objects/upload_and_view_forms_page.rb
  test/admin-hpa/features/support/page_objects/view_form_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1287 Bug/34643 prod error ps report unable to process
  functions-app/report-psychometrician-create-download/service/psychometrician-report.service.js
  functions-app/report-psychometrician/service/psychometrician-report.service.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1276 Bug/34407 Filter for non deleted check windows when fetching active check window
  functions-app/calculate-score-v2/check-window.data.service.js
  functions/calculate-score/check-window.data.service.js
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1278 Bug/33232 update config on current prepared checks
  functions/lib/sql-helper.js
  functions/prepared-check-sync/check.data.service.js
  functions/prepared-check-sync/v1.js
  functions/prepared-check-sync/v1.spec.js
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1288 Feature/automation fix check complete payload
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/support/request_helper.rb
Labels: CI Enabled

#1286 Bug/33928 Provided dedicated styling for numpad preview box
  pupil-spa/src/app/aa-fonts/aa-fonts.component.html
  pupil-spa/src/assets/shared-styles/elements/_aa-variables.scss
  pupil-spa/src/assets/shared-styles/elements/_virtual-keyboard.scss
  test/pupil-hpa/features/support/page_objects/font_size_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1285 Bug/34410 Add requestTimeout and connectionTimeout to admin and functions configs
  admin/config.js
  functions/config.js
Labels: CI Enabled, Reviewed & approved, Signed Off

#1290 Feature/34771 fix ps download file
  functions-app/report-psychometrician-create-download/service/data-access/azure-file.data.service.js
  functions-app/report-psychometrician-create-download/service/psychometrician-report.service.js
  functions-app/report-psychometrician-create-download/v1.js
Labels: CI Enabled, Ready for review, Requires Tech Sign Off, Signed Off

#1279 Feature/34406 Removed redis caching env var
  admin/README.md
  admin/config.js
  admin/services/data-access/group.data.service.js
  admin/services/redis-cache.service.js
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1265 Spike/32415 change dfenumber joins to schoolid
  admin/controllers/access-arrangements.js
  admin/controllers/attendance.js
  admin/controllers/group.js
  admin/controllers/pupil-pin.js
  admin/controllers/pupil-register.js
  admin/controllers/pupil.js
  admin/controllers/pupils-not-taking-the-check.js
  admin/controllers/restart.js
  admin/controllers/results.js
  admin/services/access-arrangements.service.js
  admin/services/attendance.service.js
  admin/services/business-availability.service.js
  admin/services/data-access/headteacher-declaration.data.service.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/data-access/pupils-not-taking-check.data.service.js
  admin/services/headteacher-declaration.service.js
  admin/services/pin-generation.service.js
  admin/services/pin.service.js
  admin/services/pupil-access-arrangements.service.js
  admin/services/pupil-register.service.js
  admin/services/pupil.service.js
  admin/services/pupils-not-taking-check.service.js
  admin/services/restart.service.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/spec/back-end/controllers/pupil.spec.js
  admin/spec/back-end/controllers/pupils-not-taking-the-check.spec.js
  admin/spec/back-end/service/data-access/pupil.data.service.spec.js
  admin/spec/back-end/service/headteacher-declaration.service.spec.js
  admin/spec/back-end/service/pin-generation.service.spec.js
  admin/spec/back-end/service/pupil-access-arrangements.service.spec.js
  admin/spec/back-end/service/pupil.service.spec.js
  admin/spec/back-end/service/pupils-not-taking-check.service.spec.js
  admin/spec/back-end/service/restart.service.spec.js
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1270 feature/34348-informative error message
  admin/README.md
  admin/app.js
  admin/error-types/mtc-error.js
  admin/services/check-window-v2.service.js
  admin/services/nca-tools-user.service.js
  admin/services/role.service.js
  admin/spec/back-end/service/check-window-v2.service.spec.js
  admin/spec/back-end/service/nca-tools-user.service.spec.js
  admin/spec/back-end/service/role.service.spec.js
  admin/views/error.ejs
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Tested

#1295 34971 - Resolve issue with sorting tests
  test/admin-hpa/features/pupil_not_taking_check.feature
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
Labels: CI Enabled, Reviewed & approved, Tested

#1296 feature/automation-update-hdf-test
  test/admin-hpa/features/step_definitions/declaration_review_pupil_steps.rb
  test/admin-hpa/features/support/hooks.rb
Labels: CI Enabled, Reviewed & approved

#1297 remove references to 'HPA' toggle
  .travis.yml
  deploy/arm/template-basics.json
  pupil-spa/README.md
Labels: CI Enabled, Reviewed & approved, Signed Off

#1298 flushing redis before test run
  test/admin-hpa/features/support/env.rb
Labels: CI Enabled, Reviewed & approved, Tested

#1300 updated csp expectation
  api_tests/spec/security_spec.rb
Labels: CI Enabled, Ready for review, Signed Off, Tested

#1304 Feature 35214 - refactored tests so we are not resetting pins
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Tested, ruby

#1305 Feature/automation cleanup sql query
  test/admin-hpa/features/generate_pupil_pin_familiarisation.feature
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/step_definitions/generate_pupil_pin_familiarisation_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/admin-hpa/features/view_and_custom_print_live_check_pin.feature
  test/admin-hpa/features/view_custom_pins_familiarisation.feature
  test/pupil-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled

#1302 Feature/35130 Added frontend toolkit to admin
  admin/.gitignore
  admin/assets/javascripts/gds-cookie-banner.js
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_gds-app-cookie-banner.scss
  admin/controllers/authentication.js
  admin/gulpfile.js
  admin/package.json
  admin/spec/front-end/gds-cookie-banner.spec.js
  admin/views/gds-layout.ejs
  admin/views/partials/_gds_body_footer.ejs
  admin/views/partials/_gds_body_header.ejs
  admin/views/partials/_gds_content.ejs
  admin/views/partials/_gds_cookie_message.ejs
  admin/views/partials/_gds_head.ejs
  admin/yarn.lock
  test/admin-hpa/features/step_definitions/phase_banner_steps.rb
  test/admin-hpa/features/support/page_objects/phase_banner_section.rb
  test/admin-hpa/features/support/page_objects/sign_in_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1303 35176 [functions-app] make tmp directory configurable
  functions-app/config.js
  functions-app/report-psychometrician-create-download/service/psychometrician-report.service.js
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1307 Feature/35260 pupil spa config
  admin/data/sql/migrations/20190724120809.do.remove-speech-synthesis-col.sql
  admin/data/sql/migrations/20190724120809.undo.remove-speech-synthesis-col.sql
  admin/data/sql/seeds/20181116123710.custom.devtest-pupil-school.sql
  admin/data/sql/seeds/20181116125658.custom.sample-pupils.js
  admin/services/config.service.js
  admin/services/data-access/config.data.service.js
  admin/spec/back-end/mocks/completed-check-with-results.js
  admin/spec/back-end/mocks/config.js
  admin/spec/back-end/mocks/pupil.js
  admin/spec/back-end/service/config.service.spec.js
  functions/lib/prepared-check-schema-validator.js
  test/pupil-hpa/features/login_page.feature
  test/pupil-hpa/features/step_definitions/login_page_steps.rb
  test/pupil-hpa/features/support/helpers.rb
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested
