Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2019-06, with the labels that each got.

#1201 feature/32966-persist-check-payload-to-check-when-generating-pins
  admin/config.js
  admin/data/sql/migrations/20190523144807.do.store-check-config.sql
  admin/data/sql/migrations/20190523144807.undo.store-check-config.sql
  admin/services/check-start.service.js
  admin/services/data-access/check-start.data.service.js
  admin/spec/back-end/service/check-start.service.spec.js
  functions/completed-checks/index.js
  functions/completed-checks/message-schema/message.v2.json
  functions/completed-checks/v1.js
  functions/completed-checks/v2.js
  functions/lib/compression.service.js
  functions/lib/compression.service.spec.js
  functions/package.json
  functions/yarn.lock
  pupil-spa/Dockerfile
  pupil-spa/package.json
  pupil-spa/src/app/services/check-complete/check-complete.service.ts
  pupil-spa/src/app/services/compressor/compressor.service.spec.ts
  pupil-spa/src/app/services/compressor/compressor.service.ts
  pupil-spa/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1221 Feature/33149 Hdf v2 changes
  admin/controllers/attendance.js
  admin/helpers/hdf-presenter.js
  admin/services/data-access/headteacher-declaration.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/headteacher-declaration.service.js
  admin/spec/back-end/controllers/attendance.spec.js
  admin/spec/back-end/helpers/hdf-presenter.spec.js
  admin/spec/back-end/service/headteacher-declaration.service.spec.js
  admin/views/hdf/review-pupil-details.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1230 automation/fixed-pupil-spa-failing-test
  test/pupil-hpa/features/pupil_api.feature
  test/pupil-hpa/features/step_definitions/check_steps.rb
  test/pupil-hpa/features/support/hooks.rb
Labels: CI Enabled, Ready for review

#1232 Changed isAuthenticated failure to use warn and added username
  admin/authentication/middleware.js
Labels: CI NOT Required, Ready for review, Requires Tech Sign Off, Signed Off

#1235 automation/fix-check-complete-message-payload
  test/admin-hpa/features/support/request_helper.rb
Labels: CI Enabled

#1228 Spike/33238 nginx spa proxy to azure
  pupil-spa/Dockerfile
  pupil-spa/docker-start.sh
  pupil-spa/gen_config.sh
  pupil-spa/nginx/default.conf
  pupil-spa/src/app/services/azure-queue/azure-queue.service.spec.ts
  pupil-spa/src/app/services/azure-queue/azure-queue.service.ts
  pupil-spa/src/app/services/config/config.service.ts
Labels: CI Enabled, Ready for review, Signed Off, Tested, Urgent

#1238 automation/fix-admin-test
  admin/services/data-access/pupils-not-taking-check.data.service.js
  test/admin-hpa/features/step_definitions/declaration_review_pupil_steps.rb
  test/admin-hpa/features/step_definitions/groups_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/support/hooks.rb
Labels: CI Enabled, Reviewed & approved

#1239 Bug/33550 Hdf review list attendance reason fix
  admin/views/hdf/review-pupil-details.ejs
  test/admin-hpa/features/generate_pupil_pins.feature
Labels: CI Enabled, Reviewed & approved, Tested

#1233 Feature/33507 content changes voluntary pilot
  admin/authentication/middleware.js
  admin/helpers/index.js
  admin/views/access-arrangements/overview.ejs
  admin/views/availability/admin-window-unavailable.ejs
  admin/views/check-form/view-form.ejs
  admin/views/check-window/manage-check-windows.ejs
  admin/views/groups/groups.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/view-and-custom-print-pins.ejs
  admin/views/pupil-pin/view-and-print-pins.ejs
  admin/views/pupil-register/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/school/school-home.ejs
  admin/views/service-manager/check-windows.ejs
  admin/views/service-manager/sce-settings.ejs
  admin/views/service-manager/service-manager-home.ejs
  admin/views/test-developer/assign-check-forms-to-windows.ejs
  admin/views/test-developer/test-developer-home.ejs
  admin/views/test-developer/upload-and-view-forms.ejs
  admin/views/test-developer/view-check-form.ejs
  pupil-spa/src/app/out-of-time/out-of-time.component.html
  pupil-spa/src/app/out-of-time/out-of-time.component.scss
  pupil-spa/src/app/session-expired/session-expired.component.html
  pupil-spa/src/app/submission-failed/submission-failed.component.html
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested, Urgent

#1227 Bug/33200 ps report processing failures after load test
  functions-app/report-psychometrician-create-download/service/data-access/psychometrician-report.data.service.js
  functions-app/report-psychometrician-create-download/service/psychometrician-report.service.js
Labels: Reviewed & approved, Urgent

#1231 33366 - Changed query getting groups for not taking page to exclude pupils with an allocated check
  admin/services/data-access/group.data.service.js
  test/admin-hpa/features/step_definitions/declaration_review_pupil_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested, Urgent

#1218 32727 - Fixed localstorage retrieval methods failing with non-JSON values
  pupil-spa/src/app/services/storage/storage.service.spec.ts
  pupil-spa/src/app/services/storage/storage.service.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Urgent

#1202 Feature/32950 Sign in error page
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/login-failure/login-failure.component.html
  pupil-spa/src/app/login-failure/login-failure.component.scss
  pupil-spa/src/app/login-failure/login-failure.component.spec.ts
  pupil-spa/src/app/login-failure/login-failure.component.ts
  pupil-spa/src/app/login/login.component.html
  pupil-spa/src/app/login/login.component.spec.ts
  pupil-spa/src/app/login/login.component.ts
  pupil-spa/src/app/services/login-error-diagnostics/login-error-diagnostics.service.spec.ts
  pupil-spa/src/app/services/login-error-diagnostics/login-error-diagnostics.service.ts
  pupil-spa/src/app/services/login-error/login-error.service.spec.ts
  pupil-spa/src/app/services/login-error/login-error.service.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested, Urgent

#1212 Feature/32934 admin app offline
  admin/README.md
  admin/app.js
  admin/config.js
  admin/controllers/website-offline.js
  admin/routes/website-offline.js
  admin/views/partials/_support_column.ejs
  admin/views/school/school-home.ejs
  admin/views/website-offline.ejs
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested, Urgent

#1244 Bug/33659 pin generation queue messages are too large
  admin/config.js
  admin/services/check-start.service.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested, Urgent

#1219 33152- Added migrations to drop `vewCompletedCheckCount` and `vewIncompleteCheckCount`
  admin/data/sql/migrations/20190528131913.do.alter-vewcompletedcheckcount.sql
  admin/data/sql/migrations/20190528132142.do.alter-vewincompletecheckcount.sql
  admin/data/sql/migrations/20190606103745.do.drop-vewnotstartedcheckcount.sql
  admin/data/sql/migrations/20190606104931.do.drop-vewpupilactivity.sql
  admin/data/sql/migrations/20190606111659.do.drop-vewcheckdiagnostic.sql
  admin/data/sql/migrations/20190606111659.undo.drop-vewcheckdiagnostic.sql
Labels: Ready for review, Signed Off

#1243 Bug/33598 edit group with trailing space in name
  admin/data/sql/migrations/20190606111659.undo.drop-vewcheckdiagnostic.sql
  admin/lib/validator/group-validator.js
  admin/services/group.service.js
  admin/spec/back-end/service/group.service.spec.js
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1241 bug/33210-fix pupil spa CSP policy for app insights
  pupil-spa/nginx/default.conf
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1222 Feature/32916 test developer views raw payload
  admin/controllers/pupil-payload-viewer.js
  admin/routes/test-developer.js
  admin/services/data-access/payload.data.service.js
  admin/services/payload.service.js
  admin/spec/back-end/service/payload.service.spec.js
  admin/views/test-developer/test-developer-home.ejs
  admin/views/test-developer/view-pupil-payload-form.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1251 Changed admin version number to 1.0.0
  admin/package.json
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1250 Changed text for incomplete status on pupil register page
  admin/views/pupil-register/pupils-list.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1252 33808 - functions-app - fix ps report error
  functions-app/report-psychometrician/service/psychometrician-report.service.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1253 Bug/33838 process v1 completed checks as default case
  functions-app/package.json
  functions/completed-checks/index.js
  functions/completed-checks/v1.js
  functions/completed-checks/v2.js
  functions/expire-prepared-check/function.json
  functions/expire-prepared-check/v1.js
  test/admin-hpa/features/pupil_status.feature
  test/pupil-hpa/features/step_definitions/access_arrangement_steps.rb
Labels: CI Enabled, Ready for review, Signed Off, Tested

#1254 Feature/replay poison checks
  functions-app/lib/azure-storage-helper.js
  functions-app/package.json
  functions-app/poison-replay-completed-checks/function.json
  functions-app/poison-replay-completed-checks/ideas.js
  functions-app/poison-replay-completed-checks/index.js
  functions-app/poison-replay-completed-checks/v1.js
  functions-app/yarn.lock
Labels: CI Enabled, Ready for review, Signed Off

#1257 Added school timezone to NCA auth session data - and logging of each logged in user's timezone
  admin/authentication/nca-tools-authentication-strategy.js
  admin/controllers/authentication.js
Labels: CI Enabled, Reviewed & approved

#1258 Bug/34069 implement banned words list
  admin/services/pin-generation.service.js
  admin/services/upn.service.js
Labels: CI Enabled, Ready for review, Tested, Urgent

#1242 Bug/33601 Sign in error reporting
  pupil-spa/gen_config.sh
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/services/login-error-diagnostics/login-error-diagnostics.service.ts
Labels: CI Enabled, Reviewed & approved

#1267 add space to logger output
  admin/models/logger.js
Labels: CI Enabled, Ready for review, Signed Off, Tested

#1255 Added migration to restore vewcheckdiagnostic
  admin/data/sql/migrations/20190620172547.do.restore-vewcheckdiagnostic.sql
  admin/data/sql/migrations/20190620172547.undo.restore-vewcheckdiagnostic.sql
Labels: CI Enabled, Signed Off, Tested

#1262 Bug/34039 add unique index
  admin/data/sql/migrations/20190620154620.do.create-unique-index-create-holding-table.sql
  admin/data/sql/migrations/20190620154620.undo.create-unique-index-create-holding-table.sql
  admin/data/sql/migrations/20190620154625.do.create-unique-index-delete-duplicates.sql
  admin/data/sql/migrations/20190620154625.undo.create-unique-index-delete-duplicates.sql
  admin/data/sql/migrations/20190620154630.do.add-unique-index.sql
  admin/data/sql/migrations/20190620154630.undo.add-unique-index.sql
  admin/services/upn.service.js
Labels: CI Enabled, Ready to merge, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1245 Feature/33107 results v3
  admin/assets/stylesheets/elements/_results.scss
  admin/controllers/attendance.js
  admin/controllers/pupils-not-taking-the-check.js
  admin/controllers/results.js
  admin/data/sql/migrations/20190621143742.do.create-spGetPupilResults.sql
  admin/data/sql/migrations/20190621143742.undo.create-spGetPupilResults.sql
  admin/helpers/result-presenter.js
  admin/helpers/table-sorting.js
  admin/services/data-access/result.data.service.js
  admin/services/headteacher-declaration.service.js
  admin/services/result.service.js
  admin/spec/back-end/controllers/results.spec.js
  admin/spec/back-end/helpers/result-presenter.spec.js
  admin/spec/back-end/helpers/table-sorting.spec.js
  admin/spec/back-end/service/headteacher-declaration.service.spec.js
  admin/spec/back-end/service/result.service.spec.js
  admin/views/results/view-incomplete-hdf.ejs
  admin/views/results/view-results.ejs
  load-test/scenarios/teacher-view-result/teacher-view-results.jmx
  test/admin-hpa/features/step_definitions/results_steps.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1240 Bug/33572 Retrieve only latest pupils checks on hdf review pupils list
  admin/services/data-access/headteacher-declaration.data.service.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested, Urgent

#1259 34090 - Test suite improvements
  test/admin-hpa/Rakefile
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/features/support/page_objects/generate_pins_overview_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/pupil-hpa/Rakefile
  test/pupil-hpa/features/step_definitions/check_steps.rb
  test/pupil-hpa/features/step_definitions/pupil_api.rb
  test/pupil-hpa/features/step_definitions/registered_inputs_steps.rb
  test/pupil-hpa/features/support/azure_table_helper.rb
  test/pupil-hpa/features/support/env.rb
  test/pupil-hpa/features/support/hooks.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Tested, Urgent, ruby

#1256 Feature/33961 Updated check expiry to use pupil status v2 message
  functions/check-expiry/v2.js
  functions/pupil-status/pupil-status.service.js
  functions/pupil-status/pupil-status.service.spec.js
Labels: CI Enabled, Ready for review, Urgent

#1260 Bug/33948 Inconsistent pupil id type after submitting more than 20 restarts
  admin/controllers/restart.js
  admin/spec/back-end/controllers/restart.spec.js
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/restarts.feature
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/support/page_objects/add_multiple_pupil_page.rb
  test/admin-hpa/features/support/page_objects/restarts_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Urgent

#1269 [admin] bump version
  admin/package.json
Labels: CI NOT Required, Ready for review, Signed Off

#1271 adding various changes to tests
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_overview_page.rb
  test/pupil-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/pupil-hpa/features/support/page_objects/generate_pins_overview_page.rb
Labels: CI Enabled, Reviewed & approved, Tested, ruby

#1268 Feature/34282 results improvements
  admin/controllers/results.js
  admin/data/sql/migrations/20190625143519.do.create-pupil-results-diagnostic-cache.sql
  admin/data/sql/migrations/20190625143519.undo.create-pupil-results-diagnostic-cache.sql
  admin/data/sql/migrations/20190625144138.do.grant-delete-pupil-results-diagnostic-cache.js
  admin/data/sql/migrations/20190625144138.undo.grant-delete-pupil-results-diagnostic-cache.js
  admin/helpers/result-presenter.js
  admin/services/data-access/result.data.service.js
  admin/services/result.service.js
  admin/spec/back-end/controllers/results.spec.js
  admin/spec/back-end/service/result.service.spec.js
  admin/views/results/view-results-not-found.ejs
  admin/views/results/view-results.ejs
  functions-app/calculate-score-v2/check-window.data.service.js
  functions-app/calculate-score-v2/function.json
  functions-app/calculate-score-v2/index.js
  functions-app/calculate-score-v2/pupil-results-diagnostic-cache.data.service.js
  functions-app/calculate-score-v2/schools-scores.data.service.js
  functions-app/calculate-score-v2/v1.js
  functions-app/calculate-score-v2/v1.spec.js
  functions-app/config.js
  functions-app/lib/redis-cache.service.js
  functions-app/mock-context.js
  functions-app/package.json
  functions-app/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested, Urgent

#1275 Bug/34405 School home page allowed access to results link right after check end date
  admin/controllers/school.js
  admin/spec/back-end/controllers/school.spec.js
Labels: CI Enabled, Reviewed & approved, Tested, Urgent

#1274 34404 Changed results availability time to 6 am UTC
  admin/helpers/hdf-presenter.js
  admin/helpers/school-home-feature-eligibility-presenter.js
  admin/services/results-page-availability.service.js
  admin/spec/back-end/service/results-page-availability.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested, Urgent

#1277 bug/34409-add defaults for sql connections and requests to functions app
  functions-app/config.js
  functions-app/lib/sql/pool-config.js
Labels: CI NOT Required, Ready for review
