Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2019-03, with the labels that each got.

#1038 Enable hdf link constantly on school home page
  admin/views/school/school-home.ejs
Labels: CI Enabled, Ready for review, Urgent

#1039 Update trial support branch with HDF hotfix from master
  admin/views/school/school-home.ejs
Labels: Ready for review

#1040 Changed score decimal precision
  admin/data/sql/migrations/20190302100213.do.alter-school-score-and-check-window-score-decimal-precision.sql
  admin/data/sql/migrations/20190302100213.undo.alter-school-score-and-check-window-score-decimal-precision.sql
  admin/data/sql/migrations/20190302100414.do.alter-sp-refresh-score-data-change-decimal-precision.sql
  admin/data/sql/migrations/20190302100414.undo.alter-sp-refresh-score-data-change-decimal-precision.sql
Labels: CI Enabled, Ready for review, Urgent

#1033 Feature/29523 aa readonly check complete
  admin/controllers/access-arrangements.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/services/pupil-access-arrangements.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/service/pupil-access-arrangements.service.spec.js
  admin/views/access-arrangements/overview.ejs
Labels: CI Enabled, Ready for review, Sign off, Tested

#1037 Feature/30139 add multiple pupil enhancements
  admin/assets/javascripts/custom-file-upload.js
  admin/assets/stylesheets/elements/_pupils.scss
  admin/controllers/pupil.js
  admin/services/uploaded-file.service.js
  admin/spec/back-end/controllers/pupil.spec.js
  admin/spec/back-end/service/uploaded-file.service.spec.js
  admin/views/check-form/upload-new-forms.ejs
  admin/views/school/add-multiple-pupils.ejs
  admin/views/service-manager/upload-pupil-census.ejs
  test/admin-hpa/data/multiple_pupils_errors.csv
  test/admin-hpa/features/add_multiple_pupil_validation_error.feature
  test/admin-hpa/features/step_definitions/add_multiple_pupil_steps.rb
  test/admin-hpa/features/step_definitions/add_multiple_pupil_validation_steps.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1034 Feature/29950 new pupil validation and enhancements
  admin/assets/javascripts/pupil-form.js
  admin/assets/stylesheets/elements/_labels.scss
  admin/assets/stylesheets/elements/_pupils.scss
  admin/controllers/pupil.js
  admin/data/sql/migrations/20190221174823.do.add-age-reason-pupil-table.sql
  admin/data/sql/migrations/20190221174823.undo.add-age-reason-pupil-table.sql
  admin/data/sql/migrations/20190301131423.do.grant-delete-on-pupil-age-reason.js
  admin/data/sql/migrations/20190301131423.undo.grant-delete-on-pupil-age-reason.js
  admin/gulpfile.js
  admin/lib/errors/csv-pupil-upload.js
  admin/lib/errors/file-csv.js
  admin/lib/errors/pupil.js
  admin/lib/validator/file-validator.js
  admin/lib/validator/pupil-validator.js
  admin/services/data-access/pupil-age-reason.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/pupil-add-service.js
  admin/services/pupil-age-reason.service.js
  admin/services/single-pupil-validation.service.js
  admin/services/validate-csv.service.js
  admin/spec/back-end/controllers/pupil.spec.js
  admin/spec/back-end/lib/validator/csv-validator.spec.js
  admin/spec/back-end/lib/validator/file-validator.spec.js
  admin/spec/back-end/lib/validator/pupil-validator.spec.js
  admin/spec/back-end/service/pupil-add-service.spec.js
  admin/spec/back-end/service/pupil-age-reason.service.spec.js
  admin/spec/back-end/service/single-pupil-validation.service.spec.js
  admin/spec/front-end/pupil-form.spec.js
  admin/views/pupil-register/add-pupil.ejs
  admin/views/school/_pupil-form.ejs
  admin/views/school/add-multiple-pupils.ejs
  test/admin-hpa/config/cucumber.yml
  test/admin-hpa/data/multiple_pupils_column_order.csv
  test/admin-hpa/data/multiple_pupils_duplicate_upn.csv
  test/admin-hpa/data/multiple_pupils_errors.csv
  test/admin-hpa/data/multiple_pupils_incorrect_format.txt
  test/admin-hpa/data/multiple_pupils_wrong_check_letter.csv
  test/admin-hpa/features/add_multiple_pupil_validation_error.feature
  test/admin-hpa/features/add_pupil.feature
  test/admin-hpa/features/edit_pupil.feature
  test/admin-hpa/features/step_definitions/add_multiple_pupil_steps.rb
  test/admin-hpa/features/step_definitions/add_multiple_pupil_validation_steps.rb
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/edit_pupil_steps.rb
  test/admin-hpa/features/step_definitions/landing_page_steps.rb
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/features/support/helpers.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/add_multiple_pupil_page.rb
  test/admin-hpa/features/support/page_objects/add_pupil_page.rb
  test/admin-hpa/features/support/page_objects/edit_pupil_page.rb
  test/admin-hpa/features/support/page_objects/error_summary_section.rb
  test/admin-hpa/features/support/page_objects/reason_section.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/admin-hpa/rerun.txt
  test/pupil-hpa/features/step_definitions/login_page_steps.rb
  test/pupil-hpa/features/support/env.rb
  test/pupil-hpa/features/support/helpers.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1043 Update pupils eligible for a restart view
  admin/data/sql/migrations/20190306160234.do.fix-pupils-eligible-for-restart-view.sql
  admin/data/sql/migrations/20190306160234.undo.fix-pupils-eligible-for-restart-view.sql
  test/admin-hpa/features/restarts.feature
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/support/page_objects/restarts_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1044 Feature/30431 exclude pupils from attendace selection list
  admin/services/data-access/pupil.data.service.js
  admin/services/data-access/pupils-not-taking-check.data.service.js
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1047 Feature/30379 school staff updates
  admin/controllers/pupil-pin.js
  admin/helpers/school-home-feature-eligibility-presenter.js
  admin/spec/back-end/helpers/school-home-feature-eligibility-presenter.spec.js
  admin/views/partials/_attendance_code_reasons.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/restart/select-restart-list.ejs
  admin/views/school/_pupil-form.ejs
  admin/views/school/school-home.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1042 Spike/azure batch service
  _spikes-poc/batch-service/README.md
  _spikes-poc/batch-service/docker-worker/Dockerfile
  _spikes-poc/batch-service/docker-worker/app/.dockerignore
  _spikes-poc/batch-service/docker-worker/app/config/sql.config.js
  _spikes-poc/batch-service/docker-worker/app/index.js
  _spikes-poc/batch-service/docker-worker/app/package.json
  _spikes-poc/batch-service/docker-worker/app/yarn.lock
Labels: CI NOT Required, Reviewed & approved, Signed Off

#1046 bump docker images to lower vulnerabilities
  admin-assets/Dockerfile
  admin/Dockerfile
  pupil-api/Dockerfile
  pupil-spa/Dockerfile
Labels: CI Enabled, Reviewed & approved

#1045 Pupil Status Not Updating After Restart
  admin/data/sql/migrations/20190308175205.do.fix-view-vewpupillivecheckstakencount.sql
  admin/data/sql/migrations/20190308175205.undo.fix-view-vewpupillivecheckstakencount.sql
  admin/services/attendance.service.js
  admin/services/data-access/attendance-code.data.service.js
  admin/services/pupil-register.service.js
  admin/spec/back-end/service/attendance-service.spec.js
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1048 Bug/30443 access arrangements alignment
  admin/assets/stylesheets/elements/_access-arrangements.scss
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1036 Feature/29970 school staff unavailable
  admin/availability/middleware.js
  admin/config.js
  admin/controllers/access-arrangements.js
  admin/controllers/group.js
  admin/controllers/pupil-pin.js
  admin/controllers/pupil-register.js
  admin/controllers/restart.js
  admin/helpers/school-home-feature-eligibility-presenter.js
  admin/routes/access-arrangements.js
  admin/routes/attendance.js
  admin/routes/group.js
  admin/routes/pupil-pin.js
  admin/routes/pupil-register.js
  admin/routes/pupils-not-taking-the-check.js
  admin/routes/restart.js
  admin/routes/school.js
  admin/services/business-availability.service.js
  admin/services/check-window-v2.service.js
  admin/services/data-access/check-window.data.service.js
  admin/services/date.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/controllers/group.spec.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/spec/back-end/controllers/pupils-not-taking-the-check.spec.js
  admin/spec/back-end/controllers/restart.spec.js
  admin/spec/back-end/service/business-availability.service.spec.js
  admin/spec/back-end/service/date.service.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/availability/admin-window-unavailable.ejs
  admin/views/availability/section-unavailable.ejs
  admin/views/pupil-register/pupils-list.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1050 Bug/25135 delete button image not showing in windows 7 in the latest chrome
  pupil-spa/gen_config.sh
  pupil-spa/src/assets/shared-styles/elements/_virtual-keyboard.scss
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1049 Bug/30338 Display unavailable page when school score does not exist
  admin/controllers/results.js
  admin/data/sql/migrations/20190312122530.do.alter-sp-refresh-score-data-allow-null-school-scores.sql
  admin/data/sql/migrations/20190312122530.undo.alter-sp-refresh-score-data-allow-null-school-scores.sql
  admin/data/sql/migrations/20190312123257.do.alter-school-score-allow-null-score.sql
  admin/data/sql/migrations/20190312123257.undo.alter-school-score-allow-null-score.sql
  admin/helpers/result-presenter.js
  admin/services/result.service.js
  admin/spec/back-end/controllers/results.spec.js
  admin/spec/back-end/helpers/result-presenter.spec.js
  admin/spec/back-end/service/result.service.spec.js
  admin/views/results/view-results.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1052 Print URL on its own line (in print pins)
  admin/assets/stylesheets/elements/_printing.scss
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off

#1055 Feature/30703 - Fixes for the nightly pupil app build.
  .gitignore
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/features/support/env.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  test/pupil-hpa/features/step_definitions/access_arrangement_steps.rb
  test/pupil-hpa/features/step_definitions/login_page_steps.rb
  test/pupil-hpa/features/support/env.rb
Labels: CI Enabled, Ready for review, Tested

#1056 updated failing test for admin app
  test/admin-hpa/features/breadcrumbs.feature
  test/admin-hpa/features/download_pupil_check_data.feature
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/download_pupil_check_data_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/groups_steps.rb
  test/admin-hpa/features/support/page_objects/access_arrangements_page.rb
  test/admin-hpa/features/support/page_objects/add_pupil_page.rb
  test/admin-hpa/features/support/page_objects/assign_form_to_window_v2_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_overview_page.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/admin-hpa/features/upload_view_forms_v2.feature
Labels: CI Enabled

#1051 Feature/30569 Exclude not taking the check pupil status from familiarisation pin gen list
  admin/data/sql/migrations/20190309114324.do.alter-pupils-eligible-for-familiarisation-pin-gen-view.sql
  admin/data/sql/migrations/20190309114324.undo.alter-pupils-eligible-for-familiarisation-pin-gen-view.sql
  test/admin-hpa/features/generate_pupil_pin_familiarisation.feature
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1053 Bug/29227 Allow try-out form uploading when one is already assigned to a past check window
  admin/assets/javascripts/check-forms.js
  admin/helpers/check-form-presenter.js
  admin/lib/validator/check-form/multiple-check-forms-validator.js
  admin/services/data-access/check-form-v2.data.service.js
  admin/spec/back-end/helpers/check-form-presenter.spec.js
  admin/spec/back-end/lib/validator/check-form/multiple-check-forms-validator.spec.js
  admin/spec/front-end/check-forms.spec.js
  admin/views/check-form/view-select-forms.ejs
  test/admin-hpa/features/upload_view_forms_v2.feature
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1058 Feature/30489 Fix nightly failures
  .gitignore
  test/admin-hpa/features/step_definitions/add_multiple_pupil_validation_steps.rb
Labels: CI Enabled, Ready for review, Testing

#1060 automation/fix-nightly-build-admin-app
  test/admin-hpa/features/generate_pupil_pin_familiarisation.feature
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
Labels: CI Enabled

#1062 automation/nightly-build
  test/admin-hpa/features/pupil_not_taking_check.feature
  test/pupil-hpa/features/access_arrangements.feature
  test/pupil-hpa/features/step_definitions/access_arrangement_steps.rb
Labels: CI Enabled

#1065 automation/fix-nighlty-build
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
Labels: CI Enabled

#1067 Automation/fix nightly build
  test/admin-hpa/features/step_definitions/generate_pupil_pin_familiarisation_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
Labels: CI Enabled

#1066 Feature/30981 Census import function
  admin/config.js
  admin/data/sql/migrations/20190320145000.do.create-census-import-user.js
  admin/data/sql/migrations/20190320145000.undo.create-census-import-user.js
  admin/data/sql/migrations/20190320145618.do.grant-census-import-user-permissions.js
  admin/data/sql/migrations/20190320145618.undo.grant-census-import-user-permissions.js
  functions/census-import/census-import.data.service.js
  functions/census-import/function.json
  functions/census-import/index.js
  functions/census-import/v1.js
  functions/census-import/v1.spec.js
  functions/config.js
  functions/package.json
  functions/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off

#1061 Task/30809 create 600k pupil census csv
  design/census-import/README.md
  design/census-import/config.js
  design/census-import/config/sql.config.js
  design/census-import/generate-census-records.js
  design/census-import/generate-school-records.js
  design/census-import/models/logger.js
  design/census-import/package.json
  design/census-import/services/data-access/sql.pool.service.js
  design/census-import/services/data-access/sql.service.js
  design/census-import/services/date.service.js
  design/census-import/services/log.service.js
  design/census-import/services/upn.service.js
  design/census-import/yarn.lock
Labels: CI NOT Required, Ready for review, Signed Off, Tested

#1070 Feature/30120 pupil api load test
  README.md
  load-test/.gitignore
  load-test/scenarios/pupil-login-check/0-pupilLogins.csv
  load-test/scenarios/pupil-login-check/1-pupilLogins.csv
  load-test/scenarios/pupil-login-check/10-pupilLogins.csv
  load-test/scenarios/pupil-login-check/11-pupilLogins.csv
  load-test/scenarios/pupil-login-check/12-pupilLogins.csv
  load-test/scenarios/pupil-login-check/13-pupilLogins.csv
  load-test/scenarios/pupil-login-check/14-pupilLogins.csv
  load-test/scenarios/pupil-login-check/15-pupilLogins.csv
  load-test/scenarios/pupil-login-check/16-pupilLogins.csv
  load-test/scenarios/pupil-login-check/2-pupilLogins.csv
  load-test/scenarios/pupil-login-check/3-pupilLogins.csv
  load-test/scenarios/pupil-login-check/4-pupilLogins.csv
  load-test/scenarios/pupil-login-check/5-pupilLogins.csv
  load-test/scenarios/pupil-login-check/6-pupilLogins.csv
  load-test/scenarios/pupil-login-check/7-pupilLogins.csv
  load-test/scenarios/pupil-login-check/8-pupilLogins.csv
  load-test/scenarios/pupil-login-check/9-pupilLogins.csv
  load-test/scenarios/pupil-login-check/pupil-login-check-using-db.jmx
  load-test/scenarios/pupil-login-check/pupil-login-check.jmx
  load-test/scenarios/pupil-login-check/pupil-login-using-teacher-pin-generation.jmx
  load-test/scenarios/pupil-login-check/undo-generate-pupil-load-test-data.txt
Labels: CI NOT Required, Ready for review, Signed Off

#1071 update practice questions
  pupil-spa/src/app/services/question/warmup-question.service.ts
Labels: CI Enabled, Ready for review, Signed Off, Tested

#1072 bug/31018 - add diagnostics output to pupil status function
  functions/pupil-status/pupil-status-batch.service.js
  functions/readme.md
Labels: CI Enabled, Ready for review

#1063 Bug/30834 Unable to generate try it out pins when no live form are assigned
  admin/controllers/pupil-pin.js
  admin/services/check-window-sanity-check.service.js
  admin/spec/back-end/service/check-window-sanity-check.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1069 Bug/remove pupil census user defaults
  .travis.yml
  admin/_example.env.txt
  admin/config.js
  admin/data/sql/migrations/20190320145000.do.create-census-import-user.js
  admin/data/sql/migrations/20190320145000.undo.create-census-import-user.js
  admin/data/sql/migrations/20190321143505.do.fix-census-import-user-permissions.js
  admin/data/sql/migrations/20190321143505.undo.fix-census-import-user-permissions.js
  admin/yarn.lock
  functions/census-import/census-import.data.service.js
  functions/config.js
Labels: CI Enabled, Reviewed & approved, Signed Off

#1074 automation/test-for-restart-bug
  test/admin-hpa/features/pupil_status.feature
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled

#1076 Fix census user
  admin/data/sql/migrations/20190320145001.do.fix-create-census-import-user.js
  admin/data/sql/migrations/20190320145001.undo.create-census-import-user.js
  admin/data/sql/migrations/20190320145619.do.grant-census-import-user-permissions.js
  admin/data/sql/migrations/20190320145619.undo.grant-census-import-user-permissions.js
Labels: CI Enabled, Reviewed & approved

#1077 Increase function timeout to 10 minutes
  functions/host.json
Labels: CI Enabled, Ready for review

#1068 Feature/31008 Census function data insertion
  admin/data/sql/migrations/20190323000001.do.add-pupil-census-import-type.sql
  admin/data/sql/migrations/20190323000001.undo.add-pupil-census-import-type.sql
  admin/data/sql/migrations/20190323000005.do.pupil-census-upsert.sql
  admin/data/sql/migrations/20190323000005.undo.pupil-census-upsert.sql
  admin/data/sql/migrations/20190323164523.do.add-job-update-permissions-census-user.js
  admin/data/sql/migrations/20190323164523.undo.add-job-update-permissions-census-user.js
  functions/census-import/census-import.data.service.js
  functions/census-import/job.data.service.js
  functions/census-import/v1.js
  functions/lib/azure-storage-helper.js
Labels: CI Enabled, Ready for review, Reviewed & approved

#1078 Remove delete block when inserting pupils
  admin/data/sql/migrations/20190324141230.do.alter-pupil-upsert.sql
  admin/data/sql/migrations/20190324141230.undo.alter-pupil-upsert.sql
Labels: CI NOT Required, Ready for review

#1073 Feature/31067 Service manager pupil census changes
  admin/controllers/service-manager.js
  admin/data/sql/migrations/20190324115129.do.add-job-status-select-permissions-census-user.js
  admin/data/sql/migrations/20190324115129.undo.add-job-status-select-permissions-census-user.js
  admin/data/sql/migrations/20190324171724.do.alter-pupil-upsert-proc.sql
  admin/data/sql/migrations/20190324171724.undo.alter-pupil-upsert-proc.sql
  admin/package.json
  admin/services/data-access/job.data.service.js
  admin/services/pupil-census.service.js
  admin/spec/back-end/controllers/service-manager.spec.js
  admin/spec/back-end/service/pupil-census.service.spec.js
  admin/views/service-manager/upload-pupil-census.ejs
  admin/yarn.lock
  functions/census-import/job.data.service.js
  functions/census-import/v1.js
Labels: CI Enabled, Ready for review

#1075 Bug/31020 duplicate form submission
  admin/app.js
  admin/helpers/prevent-duplicate-submit.js
  admin/views/pupil-pin/generate-pins-list.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1081 automation/fix-census-test
  test/admin-hpa/features/step_definitions/upload_pupil_census_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/upload_pupil_census_page.rb
  test/admin-hpa/features/upload_pupil_census.feature
Labels: CI Enabled

#1088 bump docker functions image build image version
  functions/Dockerfile
Labels: CI Enabled, Ready for review

#1082 add new role SchoolNomAAMTC and mapping to teacher
  admin/services/role.service.js
  admin/spec/back-end/service/role.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off

#1079 Feature/31170 Include job id the pupil loading procedure
  admin/data/sql/migrations/20190325103327.do.add-job-id-pupil-upsert-proc.sql
  admin/data/sql/migrations/20190325103327.undo.add-job-id-pupil-upsert-proc.sql
  functions/census-import/census-import.data.service.js
  functions/census-import/job.data.service.js
  functions/census-import/v1.js
Labels: CI Enabled, Reviewed & approved, Signed Off

#1080 Bug/30818 Remove pupils with applied AAs from AA selection list
  admin/services/data-access/pupil-access-arrangements.data.service.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1083 Removed the reason column from the pupilsList table
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1087 Added width to the rotated span so that it will show correctly in Firefox
  admin/assets/stylesheets/elements/_printing.scss
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1090 Feature/31230 school data
  admin/data/sql/manual/20190129102415.school-data-jan-2019.sql
  admin/data/sql/manual/20190326163443.school-update-26-mar-19.sql
Labels: CI Enabled, Signed Off

#1091 automation/fix_pupil_not_taking_check_page_failure
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
  test/admin-hpa/features/upload_pupil_census.feature
Labels: CI Enabled

#1064 Feature/30130 service manager
  admin/assets/javascripts/autocomplete.js
  admin/assets/stylesheets/application.scss
  admin/authentication/local-strategy.js
  admin/config.js
  admin/controllers/access-arrangements.js
  admin/controllers/group.js
  admin/controllers/pupil-pin.js
  admin/controllers/pupils-not-taking-the-check.js
  admin/controllers/restart.js
  admin/controllers/results.js
  admin/controllers/school.js
  admin/controllers/service-manager.js
  admin/data/sql/migrations/20190308122704.do.add-sce-table.sql
  admin/data/sql/migrations/20190308122704.undo.add-sce-table.sql
  admin/data/sql/migrations/20190315103700.do.add-sce-table-type.sql
  admin/data/sql/migrations/20190315103700.undo.add-sce-table-type.sql
  admin/data/sql/migrations/20190315104300.do.add-procedure-upsertSceSchools.sql
  admin/data/sql/migrations/20190315104300.undo.add-procedure-upsertSceSchools.sql
  admin/data/sql/migrations/20190321073836.do.sce-country-code.sql
  admin/data/sql/migrations/20190321073836.undo.sce-country-code.sql
  admin/data/sql/migrations/20190321080557.do.sce-table-type-country.sql
  admin/data/sql/migrations/20190321080557.undo.sce-table-type-country.sql
  admin/helpers/sce.js
  admin/helpers/school-home-feature-eligibility-presenter.js
  admin/lib/errors/sce.js
  admin/lib/validator/sce-school-validator.js
  admin/package.json
  admin/routes/service-manager.js
  admin/services/business-availability.service.js
  admin/services/check-start.service.js
  admin/services/data-access/check-form-allocation.data.service.js
  admin/services/data-access/sce.data.service.js
  admin/services/data-access/school.data.service.js
  admin/services/date.service.js
  admin/services/pin-generation.service.js
  admin/services/sce.service.js
  admin/spec/back-end/controllers/service-manager.spec.js
  admin/spec/back-end/helpers/school-home-feature-eligibility-presenter.spec.js
  admin/spec/back-end/service/business-availability.service.spec.js
  admin/spec/back-end/service/date.service.spec.js
  admin/spec/front-end/typeahead.spec.js
  admin/views/access-arrangements/select-access-arrangements.ejs
  admin/views/service-manager/sce-add-school.ejs
  admin/views/service-manager/sce-settings.ejs
  admin/views/service-manager/service-manager-home.ejs
  admin/yarn.lock
  test/admin-hpa/features/mod_schools.feature
  test/admin-hpa/features/step_definitions/mod_schools_steps.rb
  test/admin-hpa/features/step_definitions/service_manager_landing_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/admin_page.rb
  test/admin-hpa/features/support/page_objects/mod_schools_page.rb
  test/admin-hpa/features/support/page_objects/update_school_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Tested

#1093 Update the guidance document
  admin/assets/pdfs/mtc-administration-guidance-2019-03-27.pdf
  admin/helpers/index.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1096 Bug/31318 UPN validation changes
  admin/lib/validator/pupil-validator.js
  admin/spec/back-end/lib/validator/pupil-validator.spec.js
  admin/views/pupil-register/add-pupil.ejs
  admin/views/pupil-register/edit-pupil.ejs
  admin/views/school/_pupil-form.ejs
  test/admin-hpa/features/add_multiple_pupil_validation_error.feature
  test/admin-hpa/features/step_definitions/add_multiple_pupil_validation_steps.rb
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/support/page_objects/error_summary_section.rb
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested, Urgent

#1094 Updated the admin survey link
  admin/views/partials/_content.ejs
  test/admin-hpa/features/step_definitions/phase_banner_steps.rb
  test/admin-hpa/features/support/page_objects/phase_banner_section.rb
Labels: CI NOT Required, Reviewed & approved, Signed Off, Tested
