Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2019-04, with the labels that each got.

#1097 Task/28505 accessibility statement accessible from footer
  admin/controllers/accessibility-statement.js
  admin/routes/index.js
  admin/spec/back-end/controllers/accessibility-statement.spec.js
  admin/views/accessibility-statement.ejs
  admin/views/cookies.ejs
  admin/views/partials/_footer_support_links.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1089 Feature/30561 Pupil spa footer
  pupil-spa/src/app/accessibility-statement/accessibility-statement.component.html
  pupil-spa/src/app/accessibility-statement/accessibility-statement.component.scss
  pupil-spa/src/app/accessibility-statement/accessibility-statement.component.spec.ts
  pupil-spa/src/app/accessibility-statement/accessibility-statement.component.ts
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/breadcrumbs/breadcrumbs.component.html
  pupil-spa/src/app/breadcrumbs/breadcrumbs.component.scss
  pupil-spa/src/app/breadcrumbs/breadcrumbs.component.spec.ts
  pupil-spa/src/app/breadcrumbs/breadcrumbs.component.ts
  pupil-spa/src/app/contact/contact.component.html
  pupil-spa/src/app/contact/contact.component.scss
  pupil-spa/src/app/contact/contact.component.spec.ts
  pupil-spa/src/app/contact/contact.component.ts
  pupil-spa/src/app/footer/footer.component.html
  pupil-spa/src/app/footer/footer.component.scss
  pupil-spa/src/app/footer/footer.component.spec.ts
  pupil-spa/src/app/footer/footer.component.ts
  pupil-spa/src/app/login/login.component.html
  pupil-spa/src/app/privacy/privacy.component.html
  pupil-spa/src/app/privacy/privacy.component.scss
  pupil-spa/src/app/privacy/privacy.component.spec.ts
  pupil-spa/src/app/privacy/privacy.component.ts
  pupil-spa/src/assets/images/icon-link.png
  pupil-spa/src/assets/shared-styles/styles.scss
  pupil-spa/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1099 Added migrations for the eligible for familiarisation pin generation
  admin/data/sql/migrations/20190328114855.do.alter-pupils-eligible-for-familiarisation-pin-gen-view.sql
  admin/data/sql/migrations/20190328114855.undo.alter-pupils-eligible-for-familiarisation-pin-gen-view.sql
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1095 Bug/31221 Enable AA link in pupils not taking the check overview page
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1103 Changed the default non-MoD school timezone to London
  admin/config.js
Labels: CI Enabled, Reviewed & approved, Tested

#1106 Feature/31510 Search for duplicate UPN within school
  admin/data/sql/migrations/20190402121931.do.add-unique-undex-pupil-table-upn-and-school-id.sql
  admin/data/sql/migrations/20190402121931.undo.add-unique-undex-pupil-table-upn-and-school-id.sql
  admin/lib/validator/pupil-validator.js
  admin/services/data-access/pupil.data.service.js
  admin/services/pupil-add-service.js
  admin/services/single-pupil-validation.service.js
  admin/spec/back-end/lib/validator/pupil-validator.spec.js
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested, Urgent

#1108 Pass school id parameter when editing pupil
  admin/controllers/pupil.js
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested, Urgent

#1107 index on check table to support hot query vewPupilRegister
  admin/data/sql/migrations/20190402152114.do.check-index.sql
  admin/data/sql/migrations/20190402152114.undo.check-index.sql
Labels: CI Enabled, Ready for review

#1109 Fix failures in the nightly build
  test/admin-hpa/data/multiple_pupils_errors.csv
  test/admin-hpa/features/assign_to_check_window_v2.feature
  test/admin-hpa/features/create_check_window_v2.feature
  test/admin-hpa/features/csrf.feature
  test/admin-hpa/features/edit_check_window_v2.feature
  test/admin-hpa/features/manage_check_window.feature
  test/admin-hpa/features/mod_schools.feature
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/phase_banner_steps.rb
  test/admin-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_overview_page.rb
  test/admin-hpa/features/support/page_objects/pupils_not_taking_check_page.rb
Labels: CI Enabled, Ready for review, Tested

#1092 update build server setup docs
  vsoBuildServer.md
Labels: CI NOT Required, Reviewed & approved

#1102 Hotfix/30130 service manager
  admin/controllers/results.js
  admin/views/service-manager/sce-settings.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1105 Feature/31021 pupil mtc journey load test
  load-test/scenarios/pupil-check-journey/0-pupilLogins.csv
  load-test/scenarios/pupil-check-journey/pupil-mtc-journey-using-db.jmx
  load-test/scenarios/pupil-check-journey/pupil-mtc-journey.jmx
Labels: CI NOT Required, Ready for review, Reviewed & approved, Signed Off

#1100 Task/30359 consolidate function storage connection string setting into one value
  docker-compose.functions.yml
  functions/check-started/function.json
  functions/completed-checks/function.json
  functions/feedback/function.json
  functions/prepare-check/function.json
  functions/prepared-check-delete/function.json
  functions/prepared-check-sync/function.json
  functions/pupil-login/function.json
  functions/pupil-prefs/function.json
  functions/pupil-status/function.json
  functions/readme.md
Labels: CI Enabled, Reviewed & approved, Signed Off

#1104 Add a script to generate sql to move pupils
  admin/bin/gen-move-pupil-sql.js
  admin/package.json
  admin/yarn.lock
Labels: CI NOT Required, Reviewed & approved, Signed Off

#1098 Feature/30979 Restart overview description change
  admin/views/restart/restart-overview.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1085 Bug/30637 Pages availability issues
  admin/controllers/access-arrangements.js
  admin/controllers/attendance.js
  admin/controllers/group.js
  admin/controllers/pupil-pin.js
  admin/controllers/pupil.js
  admin/controllers/pupils-not-taking-the-check.js
  admin/controllers/restart.js
  admin/services/business-availability.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/controllers/attendance.spec.js
  admin/spec/back-end/controllers/group.spec.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/spec/back-end/controllers/pupil.spec.js
  admin/spec/back-end/controllers/pupils-not-taking-the-check.spec.js
  admin/spec/back-end/controllers/restart.spec.js
Labels: CI Enabled, Ready for review, Signed Off, Tested

#1113 fix the way we rerun our failures
  test/admin-hpa/Rakefile
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/rerun0.txt
  test/pupil-hpa/Rakefile
  test/pupil-hpa/rerun0.txt
Labels: CI Enabled, Reviewed & approved, Tested

#1111 Bug/31565 check expiry
  functions/check-expiry/v1.js
Labels: CI Enabled, Ready for review, Signed Off

#1115 Added refetching of user record after updating school
  admin/services/nca-tools-user.service.js
  admin/spec/back-end/service/nca-tools-user.service.spec.js
Labels: CI NOT Required, Ready for review, Signed Off

#1112 Reversed order of forename and surname in the import table type
  admin/data/sql/migrations/20190403120001.do.alter-pupil-census-import-type-order.sql
  admin/data/sql/migrations/20190403120001.undo.alter-pupil-census-import-type-order.sql
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1121 Fallback to overridePinExpiry instead of OVERRIDE_AVAILABILITY_CHECKS config variable
  admin/services/business-availability.service.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1110 Feature/27845 pupilapi winston ai upgrades
  pupil-api/package.json
  pupil-api/src/App.ts
  pupil-api/src/controllers/auth.controller.ts
  pupil-api/src/helpers/app-insights.ts
  pupil-api/src/helpers/logger.ts
  pupil-api/src/index.ts
  pupil-api/src/services/azure-queue.service.ts
  pupil-api/src/services/log.service.ts
  pupil-api/src/services/pupil-authentication.service.ts
  pupil-api/src/spec/controller/auth.controller.spec.ts
  pupil-api/src/spec/services/log.service.spec.ts
  pupil-api/yarn.lock
Labels: CI Enabled, Reviewed & approved, Sign off

#1101 Feature/31231 Display appropriate markup on out of time screen for try out checks
  pupil-spa/src/app/out-of-time/out-of-time.component.html
  pupil-spa/src/app/out-of-time/out-of-time.component.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1117 Bug/31596 Change displayed title during check questions
  pupil-spa/src/assets/shared-styles/elements/_check.scss
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1084 Feature/20461 endpoint rate limiting
  .travis.yml
  README.md
  admin/app.js
  admin/config.js
  admin/config/sql.config.js
  docker-compose.yml
  pupil-api/package.json
  pupil-api/src/App.ts
  pupil-api/src/config.ts
  pupil-api/src/helpers/cors-options.ts
  pupil-api/src/helpers/rate-limit.ts
  pupil-api/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off

#1122 Add anonymization IP support for admin and pupil apps
  admin/views/partials/_body_start.ejs
  pupil-spa/package.json
  pupil-spa/src/app/app.component.ts
  pupil-spa/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1124 Feature/27768 retire prepare check messaging
  admin/config/feature-toggles.Azure-DEV.json
  admin/config/feature-toggles.Azure-Demo.json
  admin/config/feature-toggles.Azure-EE-Prod.json
  admin/config/feature-toggles.Azure-PP.json
  admin/config/feature-toggles.Azure-Proto.json
  admin/config/feature-toggles.default.json
  admin/config/feature-toggles.eazure-demo.json
  admin/config/feature-toggles.eazure-dev.json
  admin/config/feature-toggles.eazure-live.json
  admin/config/feature-toggles.eazure-preprod.json
  admin/config/feature-toggles.eazure-proto.json
  admin/config/feature-toggles.eazure-test.json
  admin/config/feature-toggles.hpa-dev.json
  admin/config/feature-toggles.hpa-travis.json
  admin/controllers/pupil-pin.js
  admin/controllers/pupil-register.js
  admin/controllers/pupils-not-taking-the-check.js
  admin/controllers/restart.js
  admin/services/check-start.service.js
  admin/services/pupil-register.service.js
  admin/services/pupil.service.js
  admin/services/restart.service.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/spec/back-end/controllers/restart.spec.js
  admin/spec/back-end/service/check-start.service.spec.js
  admin/spec/back-end/service/pupil.service.spec.js
  admin/spec/back-end/service/restart.service.spec.js
  pupil-spa/gen_config.sh
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/check/check.component.spec.ts
  pupil-spa/src/app/check/check.component.ts
  pupil-spa/src/app/login.userService.response.mock.json
  pupil-spa/src/app/questions-intro/questions-intro.component.spec.ts
  pupil-spa/src/app/services/check-complete/check-complete.service.spec.ts
  pupil-spa/src/app/services/check-complete/check-complete.service.ts
  pupil-spa/src/app/services/check-start/check-start.service.spec.ts
  pupil-spa/src/app/services/check-start/check-start.service.ts
  pupil-spa/src/app/services/config/config.service.spec.ts
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/services/feedback/feedback.service.spec.ts
  pupil-spa/src/app/services/feedback/feedback.service.ts
  pupil-spa/src/app/services/pupil-prefs-submission/pupil-prefs-submission.service.spec.ts
  pupil-spa/src/app/services/pupil-prefs-submission/pupil-prefs-submission.service.ts
  pupil-spa/src/app/services/pupil-prefs/pupil-prefs.service.spec.ts
  pupil-spa/src/app/services/pupil-prefs/pupil-prefs.service.ts
  pupil-spa/src/app/services/register-input/registerInput.service.spec.ts
  pupil-spa/src/app/services/submission/submission.service.mock.ts
  pupil-spa/src/app/services/submission/submission.service.spec.ts
  pupil-spa/src/app/services/submission/submission.service.ts
  pupil-spa/src/app/services/user/user.service.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.spec.ts
  pupil-spa/src/app/warmup-complete/warmup-complete.component.spec.ts
  pupil-spa/src/app/warmup-complete/warmup-complete.component.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off

#1126 feature/31684-nightly - Fix nightly build
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Requires Tech Sign Off, Signed Off, Tested

#1125 Feature/31570 Check Expiry Improvements (part 1)
  functions/check-expiry/index.js
  functions/check-expiry/v2.js
  functions/check-not-received/index.js
  functions/check-not-received/v2.js
  functions/lib/azure-storage-helper.js
Labels: CI Enabled, Reviewed & approved, Signed Off

#1118 Feature/27404 remove api cors from admin
  admin/app.js
  admin/config.js
  admin/controllers/api-response.js
  admin/controllers/check-started.js
  admin/controllers/pupil-feedback.js
  admin/helpers/cors-options.js
  admin/package.json
  admin/routes/check-started.js
  admin/routes/pupil-feedback.js
  admin/spec/back-end/controllers/check-started.spec.js
  admin/spec/back-end/controllers/pupil-feedback.spec.js
  admin/yarn.lock
Labels: CI Enabled, Ready for review, Signed Off

#1114 Bug/31218 Display pins that correspond to pupils that are not flagged as NTTC
  admin/data/sql/migrations/20190403204401.do.alter-vew-pupils-with-active-live-pins.sql
  admin/data/sql/migrations/20190403204401.undo.alter-vew-pupils-with-active-live-pins.sql
  admin/data/sql/migrations/20190403204411.do.alter-vew-pupils-with-active-familiarisation-pins.sql
  admin/data/sql/migrations/20190403204411.undo.alter-vew-pupils-with-active-familiarisation-pins.sql
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1127 Feature/31222 school staff text changes
  admin/views/partials/_attendance_code_reasons.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  test/admin-hpa/Gemfile
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_overview_page.rb
  test/admin-hpa/features/support/page_objects/pupil_reason_page.rb
  test/pupil-hpa/features/support/env.rb
  test/pupil-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/pupil-hpa/features/support/page_objects/generate_pins_overview_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1132 Feature/31837 - Nightly failures
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/Rakefile
  test/admin-hpa/rerun.txt
Labels: CI Enabled, Requires sign off, Tested

#1123 Fixed time check on results page to check the opening hour with timezone
  admin/controllers/results.js
  admin/helpers/school-home-feature-eligibility-presenter.js
  admin/services/data-access/sql.service.js
Labels: CI Enabled, Ready for review, Signed Off, Tested

#1134 Feature/31356 - Update copy on update failed page
  pupil-spa/src/app/submission-failed/submission-failed.component.html
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1133 Feature/30945 - Fix issue with try it out being displayed on Live pin gen page
  admin/views/pupil-pin/generate-pins-overview.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1128 Feature/27036 change add message to add message async
  admin/services/prepared-check-sync.service.js
  admin/services/pupil.status.service.js
  admin/services/restart.service.js
  admin/spec/back-end/service/azure-queue.service.spec.js
  admin/spec/back-end/service/prepared-check-sync.service.spec.js
Labels: Requires Tech Sign Off, Reviewed & approved, Signed Off

#1135 Feature/30621 updatedAt table triggers
  admin/data/sql/migrations/20190411172714.do.create-updatedat-column-triggers.sql
  admin/data/sql/migrations/20190411172714.undo.create-updatedat-column-triggers.sql
Labels: CI Enabled, Reviewed & approved

#1140 Feature/31715 Revoke specific mtc admin user permissions on pupil table
  admin/data/sql/migrations/20190412151916.do.revoke-alter-and-delete-permissions-mtc-admin-user.js
  admin/data/sql/migrations/20190412151916.undo.revoke-alter-and-delete-permissions-mtc-admin-user.js
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off

#1144 Bug/fix not updated unit tests
  admin/spec/back-end/helpers/school-home-feature-eligibility-presenter.spec.js
  admin/spec/back-end/service/restart.service.spec.js
Labels: CI Enabled, Ready for review, hot fix

#1131 28591 - Added migration to add group_id to vewPupilsEligibleForRestart
  admin/data/sql/migrations/20190410113141.do.add-group-id-vew-pupils-eligible-for-restart.sql
  admin/data/sql/migrations/20190410113141.undo.add-group-id-vew-pupils-eligible-for-restart.sql
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1138 bug/21406 - Added listener to fix position of sticky banner on browser zoom in/out
  admin/assets/javascripts/global-scripts.js
  admin/assets/javascripts/pupil-filter-name.js
  admin/assets/javascripts/util-checkbox.js
  admin/assets/stylesheets/elements/_sticky-confirmation-banner.scss
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1137 feature/29500 - Added pupil middlename to HDF review details page
  admin/views/hdf/review-pupil-details.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1143 31718 - Added timer reset on sign out, so it's ready for next sign in
  pupil-spa/src/app/check/check.component.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1145 Added migration to restore "(reason required)" text to next button AA
  admin/data/sql/migrations/20190417091050.do.add-reason-required-to-next-button-aa.sql
  admin/data/sql/migrations/20190417091050.undo.add-reason-required-to-next-button-aa.sql
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1136 31748 - Changed pupil status message adding to use v2
  admin/services/pupil.status.service.js
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved

#1146 Feature/31975 Incomplete status display
  admin/assets/stylesheets/elements/_custom_banners.scss
  admin/assets/stylesheets/elements/_flash-messages.scss
  admin/controllers/pupil-register.js
  admin/controllers/school.js
  admin/helpers/incomplete-checks-presenter.js
  admin/services/data-access/pupil-register.data.service.js
  admin/services/pupil-register.service.js
  admin/spec/back-end/controllers/school.spec.js
  admin/spec/back-end/helpers/incomplete-checks-presenter.spec.js
  admin/spec/back-end/service/pupil-register.service.spec.js
  admin/views/pupil-register/pupils-list.ejs
  admin/views/school/school-home.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1152 feature/31975 - adding tests for incomplete feature
  test/admin-hpa/features/pupil_register.feature
  test/admin-hpa/features/restarts.feature
  test/admin-hpa/features/school_landing.feature
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
  test/admin-hpa/features/step_definitions/school_landing_page_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/pupil_register_page.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1155 Feature/32093 - Changed tag from p to span
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1151 Added prevention of reading main content, when a modal is open
  pupil-spa/src/app/loading/loading.component.ts
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1147 Changed speakElement to remove ending new line, rather than replacing with comma
  pupil-spa/src/app/services/speech/speech.service.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1141 Bug/31224 username on new line on group pupils page
  admin/views/access-arrangements/overview.ejs
  admin/views/access-arrangements/select-access-arrangements.ejs
  admin/views/accessibility-statement.ejs
  admin/views/availability/section-unavailable.ejs
  admin/views/check-form/upload-new-forms.ejs
  admin/views/check-form/view-assign-forms-to-check-windows.ejs
  admin/views/check-form/view-form.ejs
  admin/views/check-form/view-forms.ejs
  admin/views/check-form/view-select-forms.ejs
  admin/views/check-window/create-check-window.ejs
  admin/views/check-window/manage-check-windows.ejs
  admin/views/contact.ejs
  admin/views/cookies.ejs
  admin/views/groups/groups.ejs
  admin/views/groups/manage-group.ejs
  admin/views/hdf/attendance-edit-reason.ejs
  admin/views/hdf/confirm-and-submit.ejs
  admin/views/hdf/declaration-form.ejs
  admin/views/hdf/review-pupil-details.ejs
  admin/views/hdf/submitted-form.ejs
  admin/views/hdf/submitted.ejs
  admin/views/partials/_breadcrumbs.ejs
  admin/views/partials/_breadcrumbs_and_sign_out.ejs
  admin/views/privacy.ejs
  admin/views/pupil-pin/generate-pins-list.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/view-and-custom-print-pins.ejs
  admin/views/pupil-pin/view-and-print-pins.ejs
  admin/views/pupil-register/add-pupil.ejs
  admin/views/pupil-register/edit-pupil.ejs
  admin/views/pupil-register/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/restart/select-restart-list.ejs
  admin/views/results/view-results.ejs
  admin/views/results/view-unavailable-results.ejs
  admin/views/school/add-multiple-pupils.ejs
  admin/views/school/no-results.ejs
  admin/views/school/results.ejs
  admin/views/service-manager/check-settings.ejs
  admin/views/service-manager/check-window-form.ejs
  admin/views/service-manager/check-windows.ejs
  admin/views/service-manager/choose-check-window.ejs
  admin/views/service-manager/sce-add-school.ejs
  admin/views/service-manager/sce-settings.ejs
  admin/views/service-manager/upload-pupil-census.ejs
  admin/views/test-developer/assign-check-forms-to-windows.ejs
  admin/views/test-developer/assign-forms.ejs
  admin/views/test-developer/download-pupil-check-data.ejs
  admin/views/test-developer/test-developer-home.ejs
  admin/views/test-developer/unassign-check-forms.ejs
  admin/views/test-developer/upload-and-view-forms.ejs
  admin/views/test-developer/upload-new-form.ejs
  admin/views/test-developer/view-check-form.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1153 Feature/31609 connect tedious & pool service removal
  admin/bin/dump-browser-stats.js
  admin/bin/generate-pupil-data-for-all-schools.js
  admin/bin/generate-pupil-data-for-one-school.js
  admin/bin/inspect-spa-data.js
  admin/package.json
  admin/services/data-access/pupil-census-import.data.service.js
  admin/services/data-access/sql.pool.service.js
  admin/yarn.lock
  design/census-import/package.json
  design/census-import/services/data-access/sql.pool.service.js
  design/census-import/yarn.lock
  load-test/bin/extract-pins-to-csv.js
  load-test/bin/generate-pupil-load-test-data.js
Labels: CI Enabled, Ready for review

#1156 default to empty object when no azure connectivity
  admin/services/data-access/azure-blob.data.service.js
Labels: CI Enabled, Ready for review

#1159 feature/32169 - Added method to clean any blob containers that are 3 or more days old
  .gitignore
  test/admin-hpa/features/support/azure_blob_helper.rb
  test/admin-hpa/features/support/env.rb
  test/pupil-hpa/features/support/azure_blob_helper.rb
  test/pupil-hpa/features/support/env.rb
Labels: CI Enabled, Signed Off, Tested

#1160 Feature.32250 - updated wait time
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
Labels: CI Enabled, Ready for review, Tested

#1161 log async retries as default level
  admin/services/data-access/retry-async.js
Labels: CI Enabled, Reviewed & approved

#1158 Feature/31893 configure pupil feedback function to run out of school hours when in azure
  admin/bin/generate-pupil-data-for-all-schools.js
  admin/data/sql/migrations/20190425180653.do.drop-feedback-table.sql
  admin/data/sql/migrations/20190425180653.undo.drop-feedback-table.sql
  admin/services/data-access/pupil-feedback.data.service.js
  admin/services/pin-generation-v2.service.js
  admin/spec/back-end/service/data-access/pupil-feedback.data.service.spec.js
  deploy/storage/tables-queues.json
  functions/feedback/_util/injector.js
  functions/feedback/function.json
  functions/feedback/index.js
  functions/feedback/message-schema/message.v2.json
  functions/host.json
  functions/pupil-status/pupil-status-batch.service.js
  load-test/bin/prepare-checks.js
  pupil-spa/src/app/services/feedback/feedback.service.ts
  test/pupil-hpa/features/step_definitions/check_steps.rb
  test/pupil-hpa/features/step_definitions/feedback_steps.rb
  test/pupil-hpa/features/support/azure_table_helper.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1163 azure recommended index - pupil.school
  admin/data/sql/migrations/20190426162624.do.pupil-schoolid-index.sql
  admin/data/sql/migrations/20190426162624.undo.pupil-schoolid-index.sql
Labels: CI Enabled, Ready for review

#1157 Feature/31999 parse migrations csv
  admin/README.md
  admin/bin/parse-school-changes-csv.js
  admin/package.json
Labels: CI NOT Required, Ready for review, Signed Off

#1169 Bug/32360 Deleted all updatedAt triggers under pupil and recreated them for each table
  admin/data/sql/migrations/20190430145532.do.create-updatedat-column-triggers-on-tables.sql
  admin/data/sql/migrations/20190430145532.undo.create-updatedat-column-triggers-on-tables.sql
Labels: CI Enabled, Ready for review, Signed Off, Tested
