Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2019-11, with the labels that each got.

#1390 Chore/functions upgrade deps
  functions/census-import/v1.js
  functions/check-expiry/v1.js
  functions/check-expiry/v2.js
  functions/completed-checks/marking.service.js
  functions/completed-checks/v1.js
  functions/completed-checks/v2.js
  functions/config.js
  functions/feedback/_util/injector.js
  functions/lib/sql/date.service.js
  functions/lib/sql/retry-async.js
  functions/lib/sql/sql.service.js
  functions/package.json
  functions/prepare-check/index.js
  functions/prepare-check/v2.js
  functions/prepared-check-delete/v1.js
  functions/prepared-check-sync/access-arrangements-sql-util.js
  functions/prepared-check-sync/v1.js
  functions/pupil-status/index.js
  functions/pupil-status/pupil-status.service.spec.js
  functions/pupil-status/v1.js
  functions/yarn.lock
Labels: CI Enabled, DNM - Requires Testing, Reviewed & approved, Tested

#1392 Feature/37499 TS function infrastructure
  .travis.yml
  caching.md
  func-consumption/gulpfile.js
  tslib/package.json
  tslib/src/caching/RedisCacheItemMetadata.ts
  tslib/src/caching/redis-service.mock.ts
  tslib/src/caching/redis-service.ts
  tslib/src/functions/check-allocator/check-allocation.data.service.ts
  tslib/src/functions/check-allocator/check-allocator.spec.ts
  tslib/src/functions/check-allocator/check-allocator.ts
  tslib/src/functions/check-allocator/check-form-allocation.service.ts
  tslib/src/functions/check-allocator/check-window.data.service.ts
  tslib/src/functions/check-allocator/pupil-allocation.service.ts
  tslib/src/functions/check-marker/check-marker.v1.ts
  tslib/src/functions/check-validator/check-validator.v1.ts
  tslib/src/schemas/check-window.ts
  tslib/src/services/check-window.service.spec.ts
  tslib/src/services/check-window.service.ts
  tslib/src/services/data/check-window.data.service.ts
  tslib/src/services/readme.md
  tslib/src/sql/sql.service.ts
  tslib/src/tests-integration/jest.integration.config.js
  tslib/src/tests-integration/redis-service.integration.spec.ts
  tslib/src/tests-integration/sql.service.integration.spec.ts
  tslib/yarn.lock
Labels: CI Enabled, Ready for review

#1397 Various cleanups and bugfixes
  functions-app/calculate-score-v2/pupil-results-diagnostic-cache.data.service.js
  functions-app/calculate-score-v2/schools-scores.data.service.js
  functions-app/calculate-score-v2/v1.js
  functions-app/lib/sql/pool-config.js
  functions-app/lib/sql/sql.service.js
  functions-app/package.json
  functions-app/report-psychometrician-create-download/service/data-access/psychometrician-report.data.service.js
  functions-app/report-psychometrician-create-download/service/psychometrician-report.service.js
  functions-app/report-psychometrician-generate-input-files/service/data-access/psychometrician.data.service.js
  functions-app/report-psychometrician-generate-input-files/service/data.service.js
  functions-app/report-psychometrician-generate-input-files/v1.js
  functions-app/report-psychometrician/manual-run.js
  functions-app/report-psychometrician/service/check-processing.service.js
  functions-app/report-psychometrician/service/data-service/anomaly-report-cache.data.service.js
  functions-app/report-psychometrician/service/data-service/psychometrician-report-cache.data.service.js
  functions-app/report-psychometrician/service/data-service/psychometrician.data.service.js
  functions-app/report-psychometrician/service/detections/report.js
  functions-app/report-psychometrician/service/psychometrician-util.service.js
  functions-app/report-psychometrician/spec/anomaly-file-report.service.spec.js
  functions-app/report-psychometrician/spec/check-processing.service.spec.js
  functions-app/report-psychometrician/spec/detections/answer-responses-after-cutoff.spec.js
  functions-app/report-psychometrician/spec/detections/detect-check-took-too-long.spec.js
  functions-app/report-psychometrician/spec/detections/filter-input-for-questions.spec.js
  functions-app/report-psychometrician/spec/detections/get-answer.spec.js
  functions-app/report-psychometrician/spec/detections/input-after-the-timer-has-completed.spec.js
  functions-app/report-psychometrician/spec/detections/low-battery.spec.js
  functions-app/report-psychometrician/spec/detections/page-refresh.spec.js
  functions-app/report-psychometrician/spec/detections/wrong-number-of-answers.spec.js
  functions-app/report-psychometrician/spec/psychometrician-report.service.spec.js
  functions-app/report-psychometrician/v2.js
  functions-app/yarn.lock
  pupil-spa/gen_config.sh
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1398 Check window service - cache window, but don't await
  tslib/src/services/check-window.service.spec.ts
  tslib/src/services/check-window.service.ts
Labels: CI NOT Required, Reviewed & approved

#1391 Feature/37595 add two new anomaly report detections
  admin/package.json
  admin/server.js
  admin/services/data-access/sql.service.js
  admin/yarn.lock
  functions-app/report-psychometrician-generate-input-files/manual-run.js
  functions-app/report-psychometrician/manual-run.js
  functions-app/report-psychometrician/service/anomaly-file-report.service.js
  functions-app/report-psychometrician/service/detections/detect-duplicate-answer-events.js
  functions-app/report-psychometrician/service/detections/detect-pupil-prefs-after-check-start.js
  functions-app/report-psychometrician/spec/detections/duplicate-answers.spec.js
  functions-app/report-psychometrician/spec/detections/pupil-prefs-api-success-during-check.spec.js
Labels: CI Enabled, Reviewed & approved, Tested

#1399 Feature/37817 prepare checks for redis
  admin/config/feature-toggles.default.json
  admin/config/feature-toggles.eazure-demo.json
  admin/config/feature-toggles.eazure-dev.json
  admin/config/feature-toggles.eazure-live.json
  admin/config/feature-toggles.eazure-preprod.json
  admin/config/feature-toggles.eazure-proto.json
  admin/config/feature-toggles.eazure-test.json
  admin/package.json
  admin/services/check-start.service.js
  admin/services/prepare-check.service.js
  admin/services/redis-cache.service.js
  admin/spec/back-end/service/check-start.service.spec.js
  admin/spec/back-end/service/prepare-check.service.spec.js
  admin/yarn.lock
  pupil-api/.dockerignore
  pupil-api/.nvmrc
  pupil-api/Dockerfile
  pupil-api/src/index.ts
Labels: CI Enabled, Reviewed & approved, Tested

#1393 Feature/37638 check window and forms unused dependencies removal
  admin/controllers/check-form.js
  admin/controllers/service-manager.js
  admin/controllers/test-developer.js
  admin/lib/errors/check-window.js
  admin/lib/validator/check-window/check-window-add-validator.js
  admin/lib/validator/check-window/check-window-admin-start-date-validator.js
  admin/lib/validator/check-window/check-window-check-end-date-validator.js
  admin/lib/validator/check-window/check-window-check-start-date-validator.js
  admin/lib/validator/check-window/check-window-edit-validator.js
  admin/lib/validator/check-window/check-window-name-validator.js
  admin/routes/index.js
  admin/routes/service-manager.js
  admin/routes/test-developer.js
  admin/services/check-form.service.js
  admin/services/check-window-add.service.js
  admin/services/check-window-edit.service.js
  admin/services/check-window.service.js
  admin/services/sorting-attributes.service.js
  admin/spec/back-end/controllers/check-form.spec.js
  admin/spec/back-end/controllers/service-manager.spec.js
  admin/spec/back-end/controllers/test-developer.spec.js
  admin/spec/back-end/lib/validator/check-window/check-window-add-validator.spec.js
  admin/spec/back-end/lib/validator/check-window/check-window-admin-start-date-validator.spec.js
  admin/spec/back-end/lib/validator/check-window/check-window-check-end-date-validator.spec.js
  admin/spec/back-end/lib/validator/check-window/check-window-check-start-date-validator.spec.js
  admin/spec/back-end/lib/validator/check-window/check-window-edit-validator.spec.js
  admin/spec/back-end/lib/validator/check-window/check-window-name-validator.spec.js
  admin/spec/back-end/service/check-window-add.service.spec.js
  admin/spec/back-end/service/check-window-edit.service.spec.js
  admin/spec/back-end/service/check-window.service.spec.js
  admin/views/service-manager/check-window-form.ejs
  admin/views/service-manager/check-windows.ejs
  admin/views/service-manager/choose-check-window.ejs
  admin/views/test-developer/test-developer-home.ejs
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1401 bug/37856: dfe signon - fix casing on view lookup
  admin/controllers/authentication.js
Labels: CI Enabled, Ready for review

#1395 Feature/37614 New school home
  admin/.babelrc
  admin/assets/javascripts/step-by-step-navigation.js
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_step-by-step-navigation.scss
  admin/config/feature-toggles.default.json
  admin/config/feature-toggles.eazure-demo.json
  admin/config/feature-toggles.eazure-dev.json
  admin/config/feature-toggles.eazure-live.json
  admin/config/feature-toggles.eazure-preprod.json
  admin/config/feature-toggles.eazure-proto.json
  admin/config/feature-toggles.eazure-test.json
  admin/controllers/school.js
  admin/gulpfile.js
  admin/package.json
  admin/spec/front-end/step-by-step-nav.spec.js
  admin/views/school/school-home-v2.ejs
  admin/views/school/school-home.ejs
  admin/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1403 Bug/37911 - fix dfe sign in bugs
  admin/authentication/dfe-signin-strategy.js
  admin/services/dfe-signin.service.js
  admin/spec/back-end/service/dfe-signin.service.spec.js
Labels: CI NOT Required, Ready for review, Requires Tech Sign Off, Signed Off

#1400 Feature/37819 pupil api redis
  admin/config/feature-toggles.Local-Dev.json
  functions/check-started/index.js
  functions/config.js
  functions/disable-functions.env
  pupil-api/.gitignore
  pupil-api/gulpfile.js
  pupil-api/jest.config.js
  pupil-api/package.json
  pupil-api/run-jasmine.js
  pupil-api/src/App.ts
  pupil-api/src/controllers/auth.controller.spec.ts
  pupil-api/src/controllers/auth.controller.ts
  pupil-api/src/feature-toggles/feature-toggles.Local-Dev.json
  pupil-api/src/feature-toggles/feature-toggles.default.json
  pupil-api/src/feature-toggles/feature-toggles.eazure-demo.json
  pupil-api/src/feature-toggles/feature-toggles.eazure-dev.json
  pupil-api/src/feature-toggles/feature-toggles.eazure-live.json
  pupil-api/src/feature-toggles/feature-toggles.eazure-preprod.json
  pupil-api/src/feature-toggles/feature-toggles.eazure-proto.json
  pupil-api/src/feature-toggles/feature-toggles.eazure-test.json
  pupil-api/src/routes/auth.ts
  pupil-api/src/services/feature.service.ts
  pupil-api/src/services/log.service.spec.ts
  pupil-api/src/services/pupil-auth.service.spec.ts
  pupil-api/src/services/pupil-auth.service.ts
  pupil-api/src/services/redis-pupil-auth.service.spec.ts
  pupil-api/src/services/redis-pupil-auth.service.ts
  pupil-api/src/services/redis.service.ts
  pupil-api/src/spec/support/jasmine.json
  pupil-api/tsconfig.json
  pupil-api/yarn.lock
Labels: CI Enabled, Reviewed & approved, Tested

#1396 Feature/37673 check window guidance information
  admin/views/check-window/create-check-window.ejs
Labels: CI Enabled, Reviewed & approved, Sign off, Signed Off, Tested

#1402 Try it out and mtc(live) pin slip changes
  admin/assets/stylesheets/elements/_printing.scss
  admin/views/partials/_print_pupils.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1410 automation/update-automation-for-new-check-process
  test/admin-hpa/features/support/azure_table_helper.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/features/support/azure_table_helper.rb
  test/pupil-hpa/features/support/env.rb
Labels: CI Enabled

#1407 feature/37957 set expiry on prepared check after pickup
  pupil-api/src/config.ts
  pupil-api/src/services/redis-pupil-auth.service.spec.ts
  pupil-api/src/services/redis-pupil-auth.service.ts
  test/pupil-hpa/Gemfile.lock
  test/pupil-hpa/features/pupil_api.feature
  test/pupil-hpa/features/step_definitions/pupil_api.rb
  test/pupil-hpa/features/support/env.rb
  test/pupil-hpa/features/support/hooks.rb
Labels: CI Enabled, Ready to merge, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1405 feature/36759-check-notifier
  func-consumption/check-notifier/function.json
  func-consumption/package.json
  tslib/src/functions/check-marker/check-marker.v1.spec.ts
  tslib/src/functions/check-marker/check-marker.v1.ts
  tslib/src/functions/check-notifier/check-notification-message.ts
  tslib/src/functions/check-notifier/check-notifier.data.service.ts
  tslib/src/functions/check-notifier/check-notifier.v1.spec.ts
  tslib/src/functions/check-notifier/check-notifier.v1.ts
  tslib/src/functions/check-notifier/index.ts
  tslib/src/sql/sql.service.ts
  tslib/src/tests-integration/sql.service.integration.spec.ts
Labels: CI Enabled, QA Not required, Requires Tech Sign Off, Reviewed & approved

#1406 Chore/upgrade pupil spa to angular 8
  pupil-spa/.nvmrc
  pupil-spa/Dockerfile
  pupil-spa/browserslist
  pupil-spa/gulpfile.js
  pupil-spa/package.json
  pupil-spa/src/app/aa-settings/aa-settings.component.ts
  pupil-spa/src/app/accessibility-statement/accessibility-statement.component.spec.ts
  pupil-spa/src/app/app.component.spec.ts
  pupil-spa/src/app/app.component.ts
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/check/check.component.spec.ts
  pupil-spa/src/app/contact/contact.component.spec.ts
  pupil-spa/src/app/feedback/feedback.component.spec.ts
  pupil-spa/src/app/privacy/privacy.component.spec.ts
  pupil-spa/src/app/question/question.component.spec.ts
  pupil-spa/src/app/services/answer/answer.service.spec.ts
  pupil-spa/src/app/services/audit/audit.service.spec.ts
  pupil-spa/src/app/services/azure-queue/azure-queue.service.spec.ts
  pupil-spa/src/app/services/check-complete/check-complete.service.spec.ts
  pupil-spa/src/app/services/check-start/check-start.service.spec.ts
  pupil-spa/src/app/services/config/config.service.spec.ts
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/services/feedback/feedback.service.spec.ts
  pupil-spa/src/app/services/feedback/feedback.service.ts
  pupil-spa/src/app/services/pupil-prefs-submission/pupil-prefs-submission.service.spec.ts
  pupil-spa/src/app/services/pupil-prefs-submission/pupil-prefs-submission.service.ts
  pupil-spa/src/app/services/pupil-prefs/pupil-prefs.service.spec.ts
  pupil-spa/src/app/services/pupil-prefs/pupil-prefs.service.ts
  pupil-spa/src/app/services/question/question.service.spec.ts
  pupil-spa/src/app/services/register-input/registerInput.service.spec.ts
  pupil-spa/src/app/services/route/route.service.spec.ts
  pupil-spa/src/app/services/speech/speech.service.mock.ts
  pupil-spa/src/app/services/speech/speech.service.spec.ts
  pupil-spa/src/app/services/speech/speech.service.ts
  pupil-spa/src/app/services/storage/storage.service.spec.ts
  pupil-spa/src/app/services/timer/timer.service.mock.ts
  pupil-spa/src/app/services/user/user.service.spec.ts
  pupil-spa/src/app/services/user/user.service.ts
  pupil-spa/src/app/sound/sound.component.ts
  pupil-spa/src/app/spoken-practice-question/spoken-practice-question.component.ts
  pupil-spa/src/app/spoken-question/spoken-question.component.ts
  pupil-spa/src/app/website-offline/website-offline.component.spec.ts
  pupil-spa/src/app/website-offline/website-offline.component.ts
  pupil-spa/src/polyfills.ts
  pupil-spa/src/tsconfig.app.json
  pupil-spa/src/tsconfig.spec.json
  pupil-spa/tsconfig.json
  pupil-spa/tslint.json
  pupil-spa/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1408 feature/37916-check-started v2
  admin/bin/parse-school-changes-csv.js
  admin/services/administration-message.service.js
  admin/services/data-access/check-window.data.service.js
  admin/services/data-access/group.data.service.js
  admin/services/data-access/redis-cache.service.js
  admin/services/data-access/sce.data.service.js
  admin/services/data-access/school.data.service.js
  admin/services/data-access/sql.service.js
  admin/services/prepare-check.service.js
  admin/services/redis-cache.service.js
  admin/services/result.service.js
  admin/spec/back-end/service/administration-message.service.spec.js
  admin/spec/back-end/service/data-access/school.data.service.spec.js
  admin/spec/back-end/service/prepare-check.service.spec.js
  admin/spec/back-end/service/result.service.spec.js
  func-consumption/check-started/function.json
  functions-app/lib/redis-cache.service.js
  pupil-api/src/controllers/auth.controller.spec.ts
  pupil-api/src/controllers/auth.controller.ts
  pupil-api/src/services/azure-pupil-auth.service.spec.ts
  pupil-api/src/services/azure-pupil-auth.service.ts
  pupil-api/src/services/redis-pupil-auth.service.spec.ts
  pupil-api/src/services/redis-pupil-auth.service.ts
  pupil-api/src/services/redis.service.ts
  pupil-spa/src/app/services/check-start/check-start.service.spec.ts
  pupil-spa/src/app/services/check-start/check-start.service.ts
  tslib/src/caching/redis-service.ts
  tslib/src/functions/check-started/check-started.service.spec.ts
  tslib/src/functions/check-started/check-started.service.ts
  tslib/src/functions/check-started/index.ts
  tslib/src/tests-integration/redis-service.integration.spec.ts
Labels: CI Enabled, Reviewed & approved

#1409 Feature/36584 pupil aliases
  admin/controllers/pupil.js
  admin/data/sql/migrations/20191112222703.do.add-aliases-pupil-table.sql
  admin/data/sql/migrations/20191112222703.undo.add-aliases-pupil-table.sql
  admin/lib/errors/pupil.js
  admin/lib/validator/pupil-validator.js
  admin/services/pupil-add-service.js
  admin/spec/back-end/lib/validator/pupil-validator.spec.js
  admin/spec/back-end/service/pupil-add-service.spec.js
  admin/views/pupil-register/_pupil-form.ejs
  admin/views/pupil-register/pupils-list.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1415 Bug/38070 tio checks expiring
  pupil-api/src/services/redis-pupil-auth.service.spec.ts
  pupil-api/src/services/redis-pupil-auth.service.ts
  tslib/src/functions/check-started/check-started.service.spec.ts
  tslib/src/functions/check-started/check-started.service.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1411 Feature/37907 check sync
  admin/config.js
  admin/config/feature-toggles.Local-Dev.json
  admin/package.json
  admin/services/data-access/pin-generation.data.service.js
  admin/services/prepared-check-sync.service.js
  admin/services/pupil-access-arrangements.service.js
  admin/spec/back-end/service/prepared-check-sync.service.spec.js
  admin/yarn.lock
  deploy/service-bus/queues-topics.json
  func-consumption/check-sync/function.json
  pupil-api/package.json
  pupil-api/src/config.ts
  pupil-api/src/feature-toggles/feature-toggles.Local-Dev.json
  pupil-api/src/helpers/rate-limit.ts
  pupil-api/src/services/azure-queue.service.ts
  pupil-api/src/services/feature.service.ts
  pupil-api/src/services/redis-pupil-auth.service.spec.ts
  pupil-api/src/services/redis-pupil-auth.service.ts
  pupil-api/src/services/redis.service.ts
  pupil-api/yarn.lock
  tslib/src/caching/redis-service.mock.ts
  tslib/src/caching/redis-service.ts
  tslib/src/functions/check-sync/index.ts
  tslib/src/functions/check-sync/prepared-check-merge.service.spec.ts
  tslib/src/functions/check-sync/prepared-check-merge.service.ts
  tslib/src/functions/check-sync/prepared-check-sync.data.service.ts
  tslib/src/functions/check-sync/prepared-check-sync.service.spec.ts
  tslib/src/functions/check-sync/prepared-check-sync.service.ts
  tslib/src/tests-integration/redis-service.integration.spec.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1412 Feature/37980 remove status from pupil register
  admin/.gitignore
  admin/assets/javascripts/pupil-register.js
  admin/config/feature-toggles.default.json
  admin/config/feature-toggles.eazure-demo.json
  admin/config/feature-toggles.eazure-dev.json
  admin/config/feature-toggles.eazure-live.json
  admin/config/feature-toggles.eazure-preprod.json
  admin/config/feature-toggles.eazure-proto.json
  admin/config/feature-toggles.eazure-test.json
  admin/controllers/pupil-register.js
  admin/gulpfile.js
  admin/services/data-access/pupil-register-v2.data.service.js
  admin/services/pupil-register-v2.service.js
  admin/services/result.service.js
  admin/spec/back-end/service/pupil-register-v2.service.spec.js
  admin/spec/back-end/service/result.service.spec.js
  admin/views/pupil-register/pupils-list-v2.ejs
  test/admin-hpa/features/pupil_register.feature
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/edit_pupil_steps.rb
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
  test/admin-hpa/features/step_definitions/service_message.rb
  test/admin-hpa/features/support/page_objects/add_pupil_page.rb
  test/admin-hpa/features/support/page_objects/edit_pupil_page.rb
  test/admin-hpa/features/support/page_objects/error_summary_section.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1417 add missing selector and var
  test/admin-hpa/features/step_definitions/sign_in_steps.rb
  test/admin-hpa/features/support/page_objects/pupil_register_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Tested, ruby

#1414 Prioritise aliases on pupil spa welcome screen
  admin/controllers/pupil-pin.js
  admin/data/sql/migrations/20191118121038.do.add-aliases-tryout-pin-generation-view.sql
  admin/data/sql/migrations/20191118121038.undo.add-aliases-tryout-pin-generation-view.sql
  admin/data/sql/migrations/20191118121046.do.add-aliases-live-pin-generation-view.sql
  admin/data/sql/migrations/20191118121046.undo.add-aliases-live-pin-generation-view.sql
  admin/data/sql/migrations/20191118161239.do.add-aliases-live-active-pin-view.sql
  admin/data/sql/migrations/20191118161239.undo.add-aliases-live-active-pin-view.sql
  admin/data/sql/migrations/20191118161247.do.add-aliases-tryout-active-pin-view.sql
  admin/data/sql/migrations/20191118161247.undo.add-aliases-tryout-active-pin-view.sql
  admin/helpers/pupil-name-presenter.js
  admin/services/check-start.service.js
  admin/services/data-access/check-form-allocation.data.service.js
  admin/spec/back-end/helpers/pupil-name-presenter.spec.js
  admin/views/partials/_print_pupils.ejs
  admin/views/pupil-register/_pupil-form.ejs
  pupil-spa/src/app/login-success/login-success.component.html
  pupil-spa/src/app/login-success/login-success.component.spec.ts
  pupil-spa/src/app/login-success/login-success.component.ts
  pupil-spa/src/app/pupil.ts
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1416 Feature/38093 feature toggle files -> config
  admin/app.js
  admin/config.js
  admin/config/feature-toggles.default.json
  admin/config/feature-toggles.eazure-demo.json
  admin/config/feature-toggles.eazure-dev.json
  admin/config/feature-toggles.eazure-live.json
  admin/config/feature-toggles.eazure-preprod.json
  admin/config/feature-toggles.eazure-proto.json
  admin/config/feature-toggles.eazure-test.json
  admin/services/check-start.service.js
  admin/services/prepared-check-sync.service.js
  pupil-api/src/config.ts
  pupil-api/src/feature-toggles/feature-toggles.default.json
  pupil-api/src/feature-toggles/feature-toggles.eazure-demo.json
  pupil-api/src/feature-toggles/feature-toggles.eazure-dev.json
  pupil-api/src/feature-toggles/feature-toggles.eazure-live.json
  pupil-api/src/feature-toggles/feature-toggles.eazure-preprod.json
  pupil-api/src/feature-toggles/feature-toggles.eazure-proto.json
  pupil-api/src/feature-toggles/feature-toggles.eazure-test.json
  pupil-api/src/services/feature.service.ts
Labels: CI Enabled, Ready for review, Signed Off, Tested

#1413 Feature/38056 pupil prefs
  func-consumption/pupil-prefs/function.json
  pupil-spa/src/app/services/pupil-prefs-submission/pupil-prefs-submission.service.spec.ts
  pupil-spa/src/app/services/pupil-prefs-submission/pupil-prefs-submission.service.ts
  tslib/src/functions/check-marker/models.ts
  tslib/src/functions/check-sync/IPreparedCheckSyncMessage.ts
  tslib/src/functions/check-sync/index.ts
  tslib/src/functions/check-sync/prepared-check-merge.service.spec.ts
  tslib/src/functions/check-sync/prepared-check-merge.service.ts
  tslib/src/functions/check-sync/prepared-check-sync.data.service.ts
  tslib/src/functions/check-sync/prepared-check-sync.service.spec.ts
  tslib/src/functions/check-sync/prepared-check-sync.service.ts
  tslib/src/functions/check-sync/readme.md
  tslib/src/functions/pupil-prefs/IPupilPrefsFunctionBindings.ts
  tslib/src/functions/pupil-prefs/index.ts
  tslib/src/functions/pupil-prefs/pupil-prefs.service.spec.ts
  tslib/src/functions/pupil-prefs/pupil-prefs.service.ts
  tslib/src/sql/sql.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1419 fix pupil api tests and logic
  pupil-api/src/controllers/auth.controller.spec.ts
  pupil-api/src/controllers/auth.controller.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1418 Feature/38092 load test pupil api
  deploy/pr-label-check.sh
  deploy/service-bus/queues-topics.json
  func-consumption/.nvmrc
  func-consumption/host.json
  func-consumption/package.json
  func-consumption/pupil-auth/function.json
  functions/check-started/index.js
  functions/config.js
  load-test/bin/generate-pupil-data.js
  load-test/bin/redis-purge.js
  load-test/config.js
  load-test/notes/jmeter-pupil-pin-post-snip.xml
  load-test/notes/sample-2019-pin-gen-page.html
  load-test/notes/tips.md
  load-test/notes/tips.txt
  load-test/package.json
  load-test/pupil-api/preparedCheck.js
  load-test/pupil-api/redis-create-prepared-checks.js
  load-test/scenarios/100k-morning/readme.md
  load-test/scenarios/_2020/pupil-api/pupil-api.jmx
  load-test/scenarios/pupil-login-check/undo-generate-pupil-load-test-data.sql
  load-test/services/redis.service.js
  load-test/yarn.lock
  tslib/package.json
  tslib/src/caching/redis-service.mock.ts
  tslib/src/caching/redis-service.ts
  tslib/src/config.ts
  tslib/src/functions/pupil-auth/index.ts
  tslib/src/functions/pupil-auth/pupil-auth.service.spec.ts
  tslib/src/functions/pupil-auth/pupil-auth.service.ts
Labels: CI Enabled, Ready for review, Requires Tech Sign Off

#1423 Feature/38148 check look up redis key
  admin/services/prepare-check.service.js
  admin/spec/back-end/service/prepare-check.service.spec.js
  func-consumption/readme.md
  pupil-api/src/services/redis-pupil-auth.service.spec.ts
  pupil-api/src/services/redis-pupil-auth.service.ts
  test/pupil-hpa/features/pupil_api.feature
  test/pupil-hpa/features/step_definitions/pupil_api.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
  tslib/src/functions/check-started/check-started.service.spec.ts
  tslib/src/functions/check-started/check-started.service.ts
  tslib/src/functions/pupil-auth/pupil-auth.service.spec.ts
  tslib/src/functions/pupil-auth/pupil-auth.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Tested

#1420 Feature/37977 Pupil filter
  admin/assets/javascripts/pupil-filter-name.js
  admin/assets/javascripts/pupil-pin.js
  admin/assets/javascripts/pupil-register.js
  admin/data/sql/migrations/20191121131446.do.add-upn-to-vew-pupil-register.sql
  admin/data/sql/migrations/20191121131446.undo.add-upn-to-vew-pupil-register.sql
  admin/data/sql/migrations/20191121145935.do.add-upn-to-vew-pupils-with-active-live-pins.sql
  admin/data/sql/migrations/20191121145935.undo.add-upn-to-vew-pupils-with-active-live-pins.sql
  admin/data/sql/migrations/20191121145945.do.add-upn-to-vew-pupils-with-active-tryout-pins.sql
  admin/data/sql/migrations/20191121145945.undo.add-upn-to-vew-pupils-with-active-tryout-pins.sql
  admin/data/sql/migrations/20191121150942.do.add-upn-to-vew-pupils-eligible-for-live-pin-generation.sql
  admin/data/sql/migrations/20191121150942.undo.add-upn-to-vew-pupils-eligible-for-live-pin-generation.sql
  admin/data/sql/migrations/20191121150950.do.add-upn-to-vew-pupils-eligible-for-tryout-pin-generation.sql
  admin/data/sql/migrations/20191121150950.undo.add-upn-to-vew-pupils-eligible-for-tryout-pin-generation.sql
  admin/gulpfile.js
  admin/package.json
  admin/services/data-access/pupil-register-v2.data.service.js
  admin/services/pupil-register-v2.service.js
  admin/services/pupil-register.service.js
  admin/spec/front-end/pupil-filter-name.spec.js
  admin/views/pupil-pin/generate-pins-list.ejs
  admin/views/pupil-pin/view-and-custom-print-pins.ejs
  admin/views/pupil-register/pupils-list.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1422 upgrade sql linux to 2019 edition
  docker-compose.yml
Labels: CI Enabled, Full Ruby Suite Run Required, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1421 Bug/38215 Group name missing from pin slips
  admin/assets/stylesheets/elements/_printing.scss
  admin/controllers/pupil-pin.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
Labels: CI Enabled, Ready for review, Signed Off, Tested

#1425 Bug/38143 wait for sql pool
  tslib/src/sql/sql.service.ts
Labels: CI Enabled, Ready for review, Requires Tech Sign Off, Tested
