Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2019-10, with the labels that each got.

#1360 Feature/add new anomaly report detection check took too long
  functions-app/report-psychometrician/service/anomaly-file-report.service.js
  functions-app/report-psychometrician/service/detections/detect-check-took-too-long.js
  functions-app/report-psychometrician/service/detections/get-check-complete-date.js
  functions-app/report-psychometrician/spec/detections/detect-check-took-too-long.spec.js
  functions-app/report-psychometrician/spec/detections/get-check-complete-date.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1363 Feature/36262 add school UUID to check submission
  admin/services/check-start.service.js
  admin/services/data-access/check-form-allocation.data.service.js
  admin/services/queue-name-service.js
  admin/spec/back-end/service/check-start.service.spec.js
  admin/yarn.lock
  pupil-api/readme.md
  pupil-spa/gen_config.sh
  pupil-spa/src/app/services/check-complete/check-complete.service.spec.ts
  pupil-spa/src/app/services/check-complete/check-complete.service.ts
  pupil-spa/src/app/services/config/config.service.ts
Labels: CI Enabled, Reviewed & approved

#1350 Design/pupil state flags
  admin/data/sql/migrations/20190918140848.do.pupil-state.sql
  admin/data/sql/migrations/20190918140848.undo.pupil-state.sql
  admin/data/sql/migrations/20190918140901.do.check-state.sql
  admin/data/sql/migrations/20190918140901.undo.check-state.sql
  design/2019-challenges.md
  design/2020.md
  design/design-ideas.md
  design/pupil-state.md
  design/pupil-state/Check - Complete and Restart.png
  design/pupil-state/Check - Happy Path.png
  design/pupil-state/Check - Invalid received check.png
  design/pupil-state/Check - not attending.png
  design/pupil-state/Check - not received after submission.png
  design/pupil-state/readme.md
  design/sql drafts/pupil-state.sql
  design/storage-options.md
Labels: CI Enabled, Ready for review

#1359 feature/36389 check marker
  func-complete-check/check-marker/check-marker.v1.ts
  func-complete-check/check-marker/function.json
  func-complete-check/check-marker/index.ts
  func-complete-check/check-receiver/index.ts
  func-complete-check/check-receiver/v3.ts
  func-complete-check/check-validator/check-validator.v1.ts
  func-complete-check/check-validator/index.ts
  func-complete-check/check-validator/v1.ts
  func-complete-check/config.ts
  func-complete-check/lib/check-form.service.ts
  func-complete-check/lib/storage-helper.ts
  func-complete-check/lib/to-bool.ts
  func-complete-check/messages/complete-check-message-template.json
  func-complete-check/package.json
  func-complete-check/spec/check-marker/check-marker.v1.spec.ts
  func-complete-check/spec/check-validator/check-validator.v1.spec.ts
  func-complete-check/spec/lib/compression-service.spec.ts
  func-complete-check/typings/message-schemas.ts
  func-complete-check/util-msg-gen/index.ts
  func-complete-check/yarn.lock
Labels: CI Enabled, Ready for review

#1366 updated failing test
  test/pupil-hpa/features/support/helpers.rb
Labels: CI Enabled, ruby

#1361 Feature/36963 Helpdesk impersonation & home page
  admin/app.js
  admin/assets/stylesheets/elements/_forms.scss
  admin/authentication/local-strategy.js
  admin/authentication/middleware.js
  admin/controllers/authentication.js
  admin/controllers/helpdesk.js
  admin/controllers/school.js
  admin/helpers/index.js
  admin/lib/consts/roles.js
  admin/lib/errors/school-impersonation.js
  admin/lib/validator/school-impersonation-validator.js
  admin/roles-config.js
  admin/routes/helpdesk.js
  admin/routes/index.js
  admin/routes/school.js
  admin/services/data-access/user.data.service.js
  admin/services/helpdesk.service.js
  admin/services/school-impersonation.service.js
  admin/spec/back-end/authentication/local-strategy.spec.js
  admin/spec/back-end/authentication/middleware.spec.js
  admin/spec/back-end/controllers/helpdesk.spec.js
  admin/spec/back-end/controllers/school.spec.js
  admin/spec/back-end/lib/validator/school-impersonation-validator.spec.js
  admin/spec/back-end/service/helpdesk.service.spec.js
  admin/spec/back-end/service/school-impersonation.service.spec.js
  admin/views/helpdesk/school-impersonation.ejs
  admin/views/school/school-home.ejs
  test/admin-hpa/features/school_landing.feature
  test/admin-hpa/features/step_definitions/school_landing_page_steps.rb
  test/admin-hpa/features/support/page_objects/helpdesk_impersonation_page.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Tested

#1367 Feature/36964 school helpdesk common features access
  admin/controllers/authentication.js
  admin/controllers/helpdesk.js
  admin/helpers/index.js
  admin/lib/consts/home-routes.js
  admin/roles-config.js
  admin/routes/access-arrangements.js
  admin/routes/attendance.js
  admin/routes/check-form.js
  admin/routes/check-window.js
  admin/routes/group.js
  admin/routes/helpdesk.js
  admin/routes/index.js
  admin/routes/pupil-pin.js
  admin/routes/pupil-register.js
  admin/routes/pupils-not-taking-the-check.js
  admin/routes/restart.js
  admin/routes/results.js
  admin/routes/school.js
  admin/routes/service-manager.js
  admin/routes/test-developer.js
  admin/views/partials/_name_and_sign_out.ejs
  admin/views/school/school-home.ejs
  test/admin-hpa/features/school_landing.feature
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
  test/admin-hpa/features/step_definitions/school_landing_page_steps.rb
  test/admin-hpa/features/support/page_objects/declaration_page.rb
  test/admin-hpa/features/support/page_objects/pupils_not_taking_check_page.rb
  test/admin-hpa/features/support/page_objects/unauthorized_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off

#1368 Feature/add new anomaly detection input after the question timer has timed out
  functions-app/report-psychometrician/service/anomaly-file-report.service.js
  functions-app/report-psychometrician/service/check-processing.service.js
  functions-app/report-psychometrician/service/detections/detect-check-took-too-long.js
  functions-app/report-psychometrician/service/detections/detect-input-after-the-timer-has-completed.js
  functions-app/report-psychometrician/service/detections/detect-input-before-question-is-shown.js
  functions-app/report-psychometrician/service/detections/filter-inputs-for-question.js
  functions-app/report-psychometrician/service/detections/get-question-timer-end-event.js
  functions-app/report-psychometrician/service/detections/report.js
  functions-app/report-psychometrician/spec/anomaly-file-report.service.spec.js
  functions-app/report-psychometrician/spec/detections/detect-check-took-too-long.spec.js
  functions-app/report-psychometrician/spec/detections/filter-input-for-questions.spec.js
  functions-app/report-psychometrician/spec/detections/get-question-timer-end-date.spec.js
  functions-app/report-psychometrician/spec/detections/input-after-the-timer-has-completed.spec.js
  functions-app/report-psychometrician/spec/detections/input-before-question-is-shown.spec.js
  functions-app/report-psychometrician/spec/detections/page-refresh.spec.js
  functions-app/report-psychometrician/v2.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1370 Bug/37203 update admin package fast csv 3
  admin/controllers/check-form.js
  admin/data/fixtures/check-form-5.csv
  admin/data/sql/seed-sql.js
  admin/lib/validator/check-form/single-check-form-validator.js
  admin/package.json
  admin/services/check-form-v2.service.js
  admin/services/check-form.service.js
  admin/services/generate-error-csv.service.js
  admin/services/pupil-census.service.js
  admin/services/pupil-upload.service.js
  admin/spec/back-end/controllers/check-form.spec.js
  admin/spec/back-end/service/check-form.service.populateFromFile.spec.js
  admin/spec/back-end/service/check-form.service.spec.js
  admin/spec/back-end/service/generate-error-csv.service.spec.js
  admin/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1372 [admin-app] Add script to check for corrupt data in PS report
  admin/bin/check-ps-report-for-corrupt-data.js
  admin/package.json
  admin/spec/back-end/controllers/restart.spec.js
  admin/yarn.lock
  functions-app/report-psychometrician/service/detections/get-check-started-date.js
  functions-app/report-psychometrician/service/psychometrician-report.service.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1369 Feature/37186 sign on
  .circleci/config.yml
  .travis.yml
  admin/.nvmrc
  admin/Dockerfile
  admin/app.js
  admin/authentication/dfe-signin-strategy.js
  admin/authentication/dfe-signin.md
  admin/config.js
  admin/controllers/authentication.js
  admin/controllers/ping.js
  admin/jsconfig.json
  admin/lib/consts/auth-modes.js
  admin/lib/consts/roles.js
  admin/models/logger.js
  admin/package.json
  admin/routes/index.js
  admin/server.js
  admin/services/data-access/dfe-signin.data.service.js
  admin/services/data-access/school.data.service.js
  admin/services/data-access/sql.service.js
  admin/services/dfe-signin.service.js
  admin/services/role.service.js
  admin/spec/back-end/service/dfe-signin.service.spec.js
  admin/yarn.lock
  pupil-spa/package.json
  pupil-spa/yarn.lock
Labels: CI Enabled, Ready for review, Signed Off

#1376 [load-test] upgrade some of the outdated dependencies
  load-test/bin/generate-pupil-data.js
  load-test/bin/generate-teacher-for-each-school.js
  load-test/load-18k-teacher-pupils.sh
  load-test/package-lock.json
  load-test/package.json
  load-test/yarn.lock
Labels: CI NOT Required, Reviewed & approved, Signed Off

#1371 Feature/31785 Service message overview and crud operations
  admin/app.js
  admin/assets/stylesheets/elements/_forms.scss
  admin/controllers/service-message.js
  admin/data/sql/migrations/20191011004727.do.create-service-message-table.sql
  admin/data/sql/migrations/20191011004727.undo.create-service-message-table.sql
  admin/data/sql/migrations/20191015153956.do.add-delete-permissions-service-message.js
  admin/data/sql/migrations/20191015153956.undo.add-delete-permissions-service-message.js
  admin/helpers/service-message-presenter.js
  admin/lib/errors/service-message.js
  admin/lib/validator/common/empty-fields-validators.js
  admin/routes/service-message.js
  admin/services/administration-message.service.js
  admin/services/data-access/administration-message.data.service.js
  admin/spec/back-end/controllers/service-message.spec.js
  admin/spec/back-end/helpers/service-message-presenter.spec.js
  admin/spec/back-end/lib/validator/common/empty-fields-validator.spec.js
  admin/spec/back-end/service/administration-message.service.spec.js
  admin/views/hdf/declaration-form.ejs
  admin/views/service-manager/service-manager-home.ejs
  admin/views/service-message/service-message-form.ejs
  admin/views/service-message/service-message-overview.ejs
  test/admin-hpa/features/service_manager_message.feature
  test/admin-hpa/features/step_definitions/service_manager_landing_steps.rb
  test/admin-hpa/features/step_definitions/service_message.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/admin_page.rb
  test/admin-hpa/features/support/page_objects/create_message_page.rb
  test/admin-hpa/features/support/page_objects/manage_service_message_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1377 dfe signin - sign out experience
  admin/config.js
  admin/controllers/authentication.js
  admin/package.json
  admin/routes/index.js
  admin/views/signedout.ejs
  admin/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off

#1375 Feature/upgrade pupil api dependencies
  pupil-api/gulpfile.js
  pupil-api/package.json
  pupil-api/src/App.ts
  pupil-api/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1374 [admin] chore: upgrade dependencies
  admin/package.json
  admin/yarn.lock
Labels: CI Enabled, Reviewed & approved

#1381 Update missing dev dependencies
  admin/package.json
  admin/server.js
  admin/yarn.lock
Labels: CI Enabled, Reviewed & approved

#1380 [admin-app] upgrade to gulp v4
  admin/Dockerfile
  admin/gulpfile.js
  admin/package.json
  admin/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off

#1378 Feature/37183 school service message
  admin/assets/javascripts/jquery-modal.js
  admin/controllers/school.js
  admin/spec/back-end/controllers/school.spec.js
  admin/views/school/school-home.ejs
  admin/views/service-message/service-message-overview.ejs
  test/admin-hpa/features/service_manager_message.feature
  test/admin-hpa/features/step_definitions/service_message.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/manage_service_message_page.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1385 automation/update-nokogiri-gem
  test/admin-hpa/Gemfile.lock
  test/pupil-hpa/Gemfile.lock
Labels: CI Enabled, Signed Off, ruby

#1382 feature/36677 check allocation/tslib
  .circleci/config.yml
  .travis.yml
  tslib/.gitignore
  tslib/.nvmrc
  tslib/jest.config.js
  tslib/package.json
  tslib/src/azure/async-table-service.ts
  tslib/src/azure/sas-token-service.spec.ts
  tslib/src/azure/sas-token-service.ts
  tslib/src/caching/redis-service.ts
  tslib/src/common/DateTimeService.ts
  tslib/src/common/ILogger.ts
  tslib/src/common/compression-service.spec.ts
  tslib/src/common/compression-service.ts
  tslib/src/common/csprng.d.ts
  tslib/src/common/json.ts
  tslib/src/common/to-bool.spec.ts
  tslib/src/common/to-bool.ts
  tslib/src/config.ts
  tslib/src/functions/check-allocator/CheckAllocationDataService.ts
  tslib/src/functions/check-allocator/CheckFormAllocationService.ts
  tslib/src/functions/check-allocator/CheckWindowDataService.ts
  tslib/src/functions/check-allocator/Models.ts
  tslib/src/functions/check-allocator/PupilAllocationService.spec.ts
  tslib/src/functions/check-allocator/PupilAllocationService.ts
  tslib/src/functions/check-allocator/PupilPinGenerationService.ts
  tslib/src/functions/check-allocator/check-allocator.spec.ts
  tslib/src/functions/check-allocator/check-allocator.ts
  tslib/src/functions/check-marker/Models.ts
  tslib/src/functions/check-marker/check-form.service.ts
  tslib/src/functions/check-marker/check-marker.v1.spec.ts
  tslib/src/functions/check-marker/check-marker.v1.ts
  tslib/src/functions/check-marker/index.ts
  tslib/src/functions/check-receiver/index.ts
  tslib/src/functions/check-receiver/v3.ts
  tslib/src/functions/check-validator/check-validator.v1.spec.ts
  tslib/src/functions/check-validator/check-validator.v1.ts
  tslib/src/functions/check-validator/index.ts
  tslib/src/functions/util-submit-check/index.ts
  tslib/src/index.ts
  tslib/src/schemas/complete-check-message-template.json
  tslib/src/schemas/complete-check.v1.json
  tslib/src/schemas/index.ts
  tslib/src/schemas/large-complete-check.json
  tslib/src/sql/async-retry.spec.ts
  tslib/src/sql/async-retry.ts
  tslib/src/sql/sql.service.integration.spec.ts
  tslib/src/sql/sql.service.ts
  tslib/tsconfig.json
  tslib/tslint.json
  tslib/yarn.lock
Labels: CI Enabled, Ready for review

#1383 Feature/37277 add new anomaly report detection responses after the time limit
  functions-app/lib/date.service.js
  functions-app/lib/date.service.spec.js
  functions-app/lib/get-duration.js
  functions-app/lib/get-duration.spec.js
  functions-app/package.json
  functions-app/report-psychometrician/service/anomaly-file-report.service.js
  functions-app/report-psychometrician/service/detections/detect-answer-responses-after-cutoff.js
  functions-app/report-psychometrician/service/detections/detect-input-after-the-timer-has-completed.js
  functions-app/report-psychometrician/service/detections/get-answer.js
  functions-app/report-psychometrician/service/detections/get-question-timer-start-event.js
  functions-app/report-psychometrician/service/detections/report.js
  functions-app/report-psychometrician/spec/anomaly-file-report.service.spec.js
  functions-app/report-psychometrician/spec/detections/answer-responses-after-cutoff.spec.js
  functions-app/report-psychometrician/spec/detections/get-answer.spec.js
  functions-app/report-psychometrician/spec/detections/get-question-timer-start-date.spec.js
  functions-app/report-psychometrician/spec/detections/input-after-the-timer-has-completed.spec.js
  functions-app/report-psychometrician/spec/detections/page-refresh.spec.js
  functions-app/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1386 automation/fix-service-message-test
  test/admin-hpa/features/service_manager_message.feature
  test/admin-hpa/features/support/page_objects/admin_page.rb
Labels: CI Enabled, Reviewed & approved, ruby

#1387 add retry-async tests and return on retry fix
  admin/services/data-access/retry-async.js
  admin/spec/back-end/service/data-access/retry-async.spec.js
  functions-app/lib/sql/retry-async.js
Labels: CI Enabled, Reviewed & approved, Signed Off

#1394 Bug/Map datetimeoffset to mssql datetimeoffset instead of datetime
  admin/data/sql/migrations/20191029105915.do.add-datetime-to-integration-test.sql
  admin/data/sql/migrations/20191029105915.undo.add-datetime-to-integration-test.sql
  admin/services/data-access/sql.service.js
  admin/tests-integration/sql.service.spec.js
  functions/Dockerfile
Labels: CI Enabled, Reviewed & approved, Tested

#1384 Feature/37472 check window form validation enhancements
  admin/helpers/check-window-presenter.js
  admin/lib/errors/check-window-v2.js
  admin/lib/validator/check-window-v2/active-check-window-validator.js
  admin/lib/validator/check-window-v2/check-window-add-validator.js
  admin/lib/validator/common/date-validator.js
  admin/services/check-window-v2-add.service.js
  admin/services/check-window-v2-update.service.js
  admin/services/check-window-v2.service.js
  admin/services/date.service.js
  admin/spec/back-end/helpers/check-window-presenter.spec.js
  admin/spec/back-end/lib/validator/check-window-v2/active-check-window-validator.spec.js
  admin/spec/back-end/lib/validator/check-window-v2/check-window-add-validator.spec.js
  admin/spec/back-end/lib/validator/common/date-validator.spec.js
  admin/spec/back-end/service/check-window-v2-add.service.spec.js
  admin/spec/back-end/service/check-window-v2-update.service.spec.js
  admin/spec/back-end/service/check-window-v2.service.spec.js
  admin/spec/back-end/service/date.service.spec.js
  admin/views/check-window/create-check-window.ejs
  test/admin-hpa/features/create_check_window_v2.feature
  test/admin-hpa/features/edit_check_window_v2.feature
  test/admin-hpa/features/step_definitions/check_window_validation_steps.rb
  test/admin-hpa/features/step_definitions/edit_check_window_steps.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1389 [admin] upgrade tedious to v6
  admin/data/sql/createDatabase.js
  admin/package.json
  admin/yarn.lock
Labels: CI Enabled, DNM - Requires Testing, Reviewed & approved, Signed Off, Tested
