Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2019-05, with the labels that each got.

#1168 Feature/32355 removed minutes assertion
  test/pupil-hpa/features/step_definitions/pupil_auth_steps.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Tested

#1170 Fixed sticky banner not being sticky in Safari
  admin/assets/stylesheets/elements/_sticky-confirmation-banner.scss
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1171 Changed width of answer box to fit largest font
  pupil-spa/src/assets/shared-styles/elements/_aa-variables.scss
  pupil-spa/src/assets/shared-styles/elements/_virtual-keyboard.scss
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1166 Bug/32246 aa pupil name on two lines
  admin/assets/stylesheets/elements/_access-arrangements.scss
  admin/views/access-arrangements/overview.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1164 Changed header elements and sticky banner to be hidden when printing pins
  admin/assets/stylesheets/elements/_printing.scss
  admin/views/partials/_breadcrumbs_and_sign_out.ejs
  admin/views/partials/_sticky_confirmation_banner.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1173 refactor table storage method
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
  test/admin-hpa/features/support/azure_table_helper.rb
  test/pupil-hpa/features/support/azure_table_helper.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Tested

#1178 added waits where needed
  test/pupil-hpa/features/step_definitions/check_steps.rb
  test/pupil-hpa/features/step_definitions/pupil_api.rb
Labels: CI Enabled, Ready for review, Ready to merge, Tested

#1177 Feature/32402 - optimise try it out pins view
  admin/data/sql/migrations/20190502111056.do.delete-tryitout-pins-view.sql
  admin/data/sql/migrations/20190502111056.undo.delete-tryitout-pins-view.sql
  admin/data/sql/migrations/20190502111953.do.create-new-tryitout-pin-view.sql
  admin/data/sql/migrations/20190502111953.undo.create-new-tryitout-pin-view.sql
  admin/services/data-access/pin-generation.data.service.js
Labels: CI Enabled, Ready for review

#1172 Bug/32408 Present DoB in utc format prior to pupil batch submission
  admin/services/single-pupil-validation.service.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1175 Added new seed to override passwordHash of user records inserted during seeding
  admin/README.md
  admin/data/sql/migrations/054.do.update-admin-passwords.js
  admin/data/sql/migrations/054.undo.update-admin-passwords.js
  admin/data/sql/seeds/20190502090959.custom.update-admin-passwords.js
Labels: CI Enabled, Reviewed & approved, Signed Off

#1174 Bug/32245 Duplicate records on pin generated list
  admin/data/sql/migrations/20190501174958.do.alter-vew-pupils-with-active-familiarisation-pins.sql
  admin/data/sql/migrations/20190501174958.undo.alter-vew-pupils-with-active-familiarisation-pins.sql
  admin/data/sql/migrations/20190501175006.do.alter-vew-pupils-with-active-live-pins.sql
  admin/data/sql/migrations/20190501175006.undo.alter-vew-pupils-with-active-live-pins.sql
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1181 Bug/32453 Incomplete status home page issue
  admin/services/data-access/pupil-register.data.service.js
  admin/services/pupil-register.service.js
  admin/spec/back-end/service/pupil-register.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested, Testing

#1182 Spike/32341 spike azure functions filesystem access
  _spikes-poc/function-fs-access/createZip.sh
  _spikes-poc/function-fs-access/functions/.gitignore
  _spikes-poc/function-fs-access/functions/check-disk-space/function.json
  _spikes-poc/function-fs-access/functions/check-disk-space/index.js
  _spikes-poc/function-fs-access/functions/check-disk-space/v1.js
  _spikes-poc/function-fs-access/functions/host.json
  _spikes-poc/function-fs-access/functions/long-runner/function.json
  _spikes-poc/function-fs-access/functions/long-runner/index.js
  _spikes-poc/function-fs-access/functions/long-runner/v1.js
  _spikes-poc/function-fs-access/functions/package.json
  _spikes-poc/function-fs-access/functions/test-fs-access/function.json
  _spikes-poc/function-fs-access/functions/test-fs-access/index.js
  _spikes-poc/function-fs-access/functions/test-fs-access/v1.js
  _spikes-poc/function-fs-access/functions/yarn.lock
  _spikes-poc/function-fs-access/readme
Labels: CI Enabled, Reviewed & approved, Signed Off

#1179 Feature/32442 Pupil status explanation panel
  admin/assets/stylesheets/application.scss
  admin/views/pupil-register/pupils-list.ejs
  test/admin-hpa/features/pupil_register.feature
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
  test/admin-hpa/features/support/page_objects/pupil_register_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1185 remove assertion
  test/pupil-hpa/features/step_definitions/pupil_api.rb
Labels: CI Enabled, Ready for review, Tested

#1184 Bug/32454 Incorrect alignment on pupil register
  admin/assets/stylesheets/elements/_pupils.scss
  admin/views/pupil-register/pupils-list.ejs
Labels: CI Enabled, Ready for review, Signed Off, Tested

#1187 Scenarios that can be added back to the test run
  test/admin-hpa/features/assign_to_check_window_v2.feature
  test/admin-hpa/features/breadcrumbs.feature
  test/admin-hpa/features/create_check_window_v2.feature
  test/admin-hpa/features/csrf.feature
  test/admin-hpa/features/edit_check_window_v2.feature
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/groups.feature
  test/admin-hpa/features/manage_check_window.feature
  test/admin-hpa/features/manage_pupil.feature
  test/admin-hpa/features/mod_schools.feature
  test/admin-hpa/features/phase_banner.feature
  test/admin-hpa/features/restarts.feature
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/manage_check_forms_steps.rb
  test/admin-hpa/features/step_definitions/manage_pupil_steps.rb
  test/admin-hpa/features/step_definitions/result_page_steps.rb
  test/admin-hpa/features/step_definitions/sign_in_steps.rb
  test/admin-hpa/features/support/page_objects/manage_pupil_page.rb
  test/admin-hpa/features/view_check.feature
Labels: CI Enabled, Testing

#1186 Feature/32530 Sas token expiry handling
  admin/config.js
  admin/services/sas-token.service.js
  admin/tests-integration/sas-token-expiry.spec.js
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/services/audit/auditEntry.ts
  pupil-spa/src/app/services/check-complete/check-complete.service.spec.ts
  pupil-spa/src/app/services/check-complete/check-complete.service.ts
  pupil-spa/src/app/session-expired/session-expired.component.html
  pupil-spa/src/app/session-expired/session-expired.component.scss
  pupil-spa/src/app/session-expired/session-expired.component.spec.ts
  pupil-spa/src/app/session-expired/session-expired.component.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1183 change upper limit of queue polling interval to 20 secs
  functions/host.json
Labels: CI Enabled, Ready for review

#1191 Feature/32705 Out of time changes
  pupil-spa/src/app/out-of-time/out-of-time.component.html
  pupil-spa/src/app/out-of-time/out-of-time.component.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1194 automation/pupil_census_tech_debt
  test/admin-hpa/features/step_definitions/upload_pupil_census_steps.rb
  test/admin-hpa/features/support/page_objects/upload_pupil_census_page.rb
  test/admin-hpa/features/upload_pupil_census.feature
Labels: Reviewed & approved

#1196 fix failing tests
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
Labels: CI Enabled, Tested

#1193 Bug/32391 Admin console error
  admin/views/partials/_cookie_message.ejs
Labels: CI Enabled, DNM - Requires Testing, Reviewed & approved, Signed Off, Tested

#1189 Task/32696 integration test failures
  .travis.yml
  admin/tests-integration/sql.service.spec.js
Labels: CI Enabled, Ready for review, Signed Off

#1197 mask sensitive data columns and grant database user unmasking permission
  admin/data/sql/migrations/20190517101548.do.grant-unmask.js
  admin/data/sql/migrations/20190517101548.grant-unmask.js
  admin/data/sql/migrations/20190517104134.do.mask-psreport.sql
  admin/data/sql/migrations/20190517104134.undo.mask-psreport.sql
  admin/data/sql/migrations/20190517104628.do.mask-hdf.sql
  admin/data/sql/migrations/20190517104628.undo.mask-hdf.sql
  admin/data/sql/migrations/20190517104732.do.mask-user.sql
  admin/data/sql/migrations/20190517104732.undo.mask-user.sql
  admin/data/sql/migrations/20190517111616.do.mask-pupil.sql
  admin/data/sql/migrations/20190517111616.undo.mask-pupil.sql
Labels: CI Enabled, Ready for review

#1198 drop obsolete tables and columns
  admin/data/sql/migrations/20190517144520.do.drop-check.data.sql
  admin/data/sql/migrations/20190517144520.undo.drop-check.data.sql
  admin/data/sql/migrations/20190517144729.do.drop-sessions.sql
  admin/data/sql/migrations/20190517144729.undo.drop-sessions.sql
  admin/data/sql/migrations/20190517144735.do.drop-pupillogonevent.sql
  admin/data/sql/migrations/20190517144735.undo.drop-pupillogonevent.sql
  admin/data/sql/migrations/20190517145506.do.drop-pupilstatuscode-trigger.sql
  admin/data/sql/migrations/20190517145506.undo.drop-pupilstatuscode-trigger.sql
  admin/data/sql/migrations/20190517145510.do.drop-pupilstatuscode-table.sql
  admin/data/sql/migrations/20190517145510.undo.drop-pupilstatuscode-table.sql
Labels: CI Enabled, Reviewed & approved

#1200 functions: more frequent queue polling and longer wait times between failures
  functions/host.json
Labels: CI Enabled, Ready for review

#1195 Feature/32791 Override hdf submission on results view
  admin/controllers/results.js
  admin/controllers/school.js
  admin/helpers/result-presenter.js
  admin/helpers/school-home-feature-eligibility-presenter.js
  admin/services/results-page-availability.service.js
  admin/spec/back-end/controllers/results.spec.js
  admin/spec/back-end/controllers/school.spec.js
  admin/spec/back-end/helpers/result-presenter.spec.js
  admin/spec/back-end/helpers/school-home-feature-eligibility-presenter.spec.js
  admin/spec/back-end/service/results-page-availability.service.spec.js
  admin/views/results/view-incomplete-hdf.ejs
  admin/views/school/school-home.ejs
Labels: CI Enabled, Ready for review, Signed Off, Tested

#1199 Bug/27021 Access arrangements overview table layout issues
  admin/assets/stylesheets/elements/_access-arrangements.scss
  admin/controllers/access-arrangements.js
  admin/helpers/access-arrangements-overview-presenter.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/helpers/access-arrangements-overview-presenter.spec.js
  admin/views/access-arrangements/overview.ejs
Labels: CI Enabled, Signed Off, Tested

#1192 Feature/32415 redis caching
  admin/README.md
  admin/bin/parse-school-changes-csv.js
  admin/config.js
  admin/package.json
  admin/services/data-access/check-window.data.service.js
  admin/services/data-access/group.data.service.js
  admin/services/data-access/sce.data.service.js
  admin/services/data-access/school.data.service.js
  admin/services/data-access/sql.service.js
  admin/services/group.service.js
  admin/services/queue-name-service.js
  admin/services/redis-cache.service.js
  admin/spec/back-end/mocks/group.js
  admin/spec/back-end/service/data-access/school.data.service.spec.js
  admin/spec/back-end/service/group.service.spec.js
  admin/yarn.lock
  functions/config.js
  functions/readme.md
Labels: CI Enabled, Ready for review, Signed Off

#1215 Updated gem version
  test/admin-hpa/Gemfile.lock
  test/pupil-hpa/Gemfile.lock
Labels: CI Enabled, Tested

#1217 Changed sqlFindPupilsWithoutReasons query to not include pupils with a completed check
  admin/controllers/pupils-not-taking-the-check.js
  admin/services/data-access/pupils-not-taking-check.data.service.js
  test/admin-hpa/features/pupil_not_taking_check.feature
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
Labels: CI Enabled, Ready for review, Tested

#1223 fix failure on the nightly
  test/admin-hpa/features/support/page_objects/access_arrangements_page.rb
Labels: CI Enabled, Tested

#1213 Feature/32935 pupil spa offline
  pupil-spa/README.md
  pupil-spa/gen_config.sh
  pupil-spa/src/app/app.component.ts
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/website-offline/website-offline.component.html
  pupil-spa/src/app/website-offline/website-offline.component.scss
  pupil-spa/src/app/website-offline/website-offline.component.spec.ts
  pupil-spa/src/app/website-offline/website-offline.component.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1216 Added migrations to fix active/familiarisation pin views
  admin/data/sql/migrations/20190513163404.do.alter-vew-pupils-with-active-live-pins.sql
  admin/data/sql/migrations/20190513163404.undo.alter-vew-pupils-with-active-live-pins.sql
  admin/data/sql/migrations/20190513163432.do.alter-vew-pupils-with-active-familiarisation-pins.sql
  admin/data/sql/migrations/20190513163432.undo.alter-vew-pupils-with-active-familiarisation-pins.sql
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1224 Fixed group update method to work with pupils sent as object
  admin/services/group.service.js
  admin/spec/back-end/service/group.service.spec.js
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/groups_steps.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested
