Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2019-09, with the labels that each got.

#1337 design/complete check process 2020
  deploy/storage/tables-queues.json
  design/2020/cosmos-sql/.gitignore
  design/2020/cosmos-sql/config.js
  design/2020/cosmos-sql/index.js
  design/2020/cosmos-sql/large-check.lz
  design/2020/cosmos-sql/package.json
  design/2020/cosmos-sql/yarn.lock
  design/2020/design-ideas.md
  design/2020/example-large-complete-check.json
  func-complete-check/.funcignore
  func-complete-check/.gitignore
  func-complete-check/.vscode/extensions.json
  func-complete-check/check-marker/function.json
  func-complete-check/check-marker/index.ts
  func-complete-check/check-receiver/function.json
  func-complete-check/check-receiver/index.ts
  func-complete-check/check-receiver/readme.md
  func-complete-check/check-receiver/v3.ts
  func-complete-check/check-validator/function.json
  func-complete-check/check-validator/index.ts
  func-complete-check/check-validator/v1.ts
  func-complete-check/extensions.csproj
  func-complete-check/host.json
  func-complete-check/lib/azure-storage-helper.ts
  func-complete-check/lib/compression-service.ts
  func-complete-check/messages/complete-check-message-template.json
  func-complete-check/messages/complete-check.v1.json
  func-complete-check/messages/large-complete-check.json
  func-complete-check/package.json
  func-complete-check/tsconfig.json
  func-complete-check/tslint.json
  func-complete-check/typings/message-schemas.ts
  func-complete-check/typings/types.d.ts
  func-complete-check/util-msg-gen/function.json
  func-complete-check/util-msg-gen/index.ts
  func-complete-check/yarn.lock
  functions/completed-checks/function.json
  functions/disable-functions.env
  functions/package.json
Labels: CI Enabled, Ready for review, Signed Off

#1341 Feature/36182 PS Report - add feature to analyse from file
  functions-app/report-psychometrician-generate-input-files/service/data.service.js
  functions-app/report-psychometrician-generate-input-files/v1.js
  functions-app/report-psychometrician/service/check-processing.service.js
  functions-app/report-psychometrician/service/psychometrician-report.service.js
  functions-app/report-psychometrician/service/psychometrician-util.service.js
  functions-app/report-psychometrician/spec/anomaly-report.service.spec.js
  functions-app/report-psychometrician/spec/mocks/completed-check-with-results.js
  functions-app/report-psychometrician/spec/psychometrician-report.service.spec.js
  functions-app/report-psychometrician/spec/psychometrician-util.service.spec.js
  functions-app/report-psychometrician/v2.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1342 feature/3638 func-complete-check: add unit test framework
  .circleci/config.yml
  func-complete-check/lib/compression-service.ts
  func-complete-check/package.json
  func-complete-check/spec/helpers/ts_console.ts
  func-complete-check/spec/lib/compression-service.spec.ts
  func-complete-check/spec/support/jasmine.json
  func-complete-check/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off

#1336 Feature/35911 pin generation feature toolkit update
  admin/assets/javascripts/util-checkbox.js
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_filters.scss
  admin/assets/stylesheets/elements/_gds-filters.scss
  admin/assets/stylesheets/elements/_printing.scss
  admin/assets/stylesheets/elements/_pupil-pin.scss
  admin/controllers/pupil-pin.js
  admin/views/partials/_gds_body_footer.ejs
  admin/views/partials/_gds_body_header.ejs
  admin/views/partials/_gds_content.ejs
  admin/views/partials/_gds_sticky_confirmation_banner.ejs
  admin/views/partials/_print_pupils.ejs
  admin/views/pupil-pin/generate-pins-list.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/view-and-custom-print-pins.ejs
  admin/views/pupil-pin/view-and-print-pins.ejs
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/breadcrumbs_steps.rb
  test/admin-hpa/features/step_definitions/edit_pupil_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
  test/admin-hpa/features/support/page_objects/add_multiple_pupil_page.rb
  test/admin-hpa/features/support/page_objects/custom_pins_familiarisation_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_overview_page.rb
  test/admin-hpa/features/support/page_objects/view_and_custom_print_live_check_page.rb
  test/admin-hpa/features/support/page_objects/view_and_print_pins_page.rb
  test/pupil-hpa/features/step_definitions/pupil_api.rb
  test/pupil-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/pupil-hpa/features/support/page_objects/generate_pins_overview_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1339 Feature/36196 fix jsdoc issues on admin/services/data-access
  admin/.gitignore
  admin/newrelic.js
  admin/package.json
  admin/services/data-access/access-arrangements.data.service.js
  admin/services/data-access/check-form-v2.data.service.js
  admin/services/data-access/check-form.data.service.js
  admin/services/data-access/check-status.data.service.js
  admin/services/data-access/check-window.data.service.js
  admin/services/data-access/check.data.service.js
  admin/services/data-access/completed-check.data.service.js
  admin/services/data-access/group.data.service.js
  admin/services/data-access/headteacher-declaration.data.service.js
  admin/services/data-access/job-status.data.service.js
  admin/services/data-access/job-type.data.service.js
  admin/services/data-access/job.data.service.js
  admin/services/data-access/pin-generation.data.service.js
  admin/services/data-access/psychometrician-report.data.service.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/services/data-access/pupil-attendance.data.service.js
  admin/services/data-access/pupil-register.data.service.js
  admin/services/data-access/pupil-restart.data.service.js
  admin/services/data-access/pupil-status-code.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/data-access/question-reader-reasons.data.service.js
  admin/services/data-access/sce.data.service.js
  admin/services/data-access/school.data.service.js
  admin/services/data-access/sql.service.js
  admin/services/redis-cache.service.js
  admin/tsconfig.json
  admin/yarn.lock
Labels: CI Enabled

#1338 Feature/35912 HDF toolkit update
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_filters.scss
  admin/assets/stylesheets/elements/_hdf.scss
  admin/assets/stylesheets/elements/_not-taking-check.scss
  admin/controllers/attendance.js
  admin/spec/back-end/controllers/attendance.spec.js
  admin/views/hdf/attendance-edit-reason.ejs
  admin/views/hdf/confirm-and-submit.ejs
  admin/views/hdf/declaration-form.ejs
  admin/views/hdf/review-pupil-details.ejs
  admin/views/hdf/submitted-form.ejs
  admin/views/hdf/submitted.ejs
  admin/views/partials/_name_and_sign_out.ejs
  admin/views/school/school-home.ejs
  test/admin-hpa/features/step_definitions/declaration_submitted_steps.rb
  test/admin-hpa/features/step_definitions/result_page_steps.rb
  test/admin-hpa/features/support/page_objects/declaration_confirm_page.rb
  test/admin-hpa/features/support/page_objects/declaration_edit_reason_page.rb
  test/admin-hpa/features/support/page_objects/declaration_page.rb
  test/admin-hpa/features/support/page_objects/declaration_review_pupils_page.rb
  test/admin-hpa/features/support/page_objects/declaration_submitted_form_page.rb
  test/admin-hpa/features/support/page_objects/declaration_submitted_page.rb
  test/admin-hpa/features/support/page_objects/hdf_form_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1344 Feature/35917 Test Dev Toolkit update pt2
  admin/controllers/pupil-payload-viewer.js
  admin/views/test-developer/download-pupil-check-data.ejs
  admin/views/test-developer/view-pupil-payload-form.ejs
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1349 updated download pupil check data test changes for GDS toolkit
  test/admin-hpa/features/support/page_objects/download_pupil_check_data_page.rb
Labels: CI Enabled

#1345 Feature/35914 Service manager toolkit update pt.1
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_check-windows.scss
  admin/assets/stylesheets/elements/_pupil-census.scss
  admin/controllers/check-window.js
  admin/controllers/service-manager.js
  admin/helpers/check-window-presenter.js
  admin/views/check-window/create-check-window.ejs
  admin/views/check-window/manage-check-windows.ejs
  admin/views/partials/_gds_modal_box.ejs
  admin/views/service-manager/service-manager-home.ejs
  admin/views/service-manager/upload-pupil-census.ejs
  test/admin-hpa/data/multiple_pupils_errors.csv
  test/admin-hpa/features/step_definitions/breadcrumbs_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/support/page_objects/add_edit_check_window_v2_page.rb
  test/admin-hpa/features/support/page_objects/admin_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_overview_page.rb
  test/admin-hpa/features/support/page_objects/manage_check_window_page.rb
  test/admin-hpa/features/support/page_objects/pupil_reason_page.rb
  test/admin-hpa/features/support/page_objects/restarts_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1351 Feature/36409 analyse files for anomaly report
  functions-app/createZip.sh
  functions-app/package.json
  functions-app/report-psychometrician/manual-run.js
  functions-app/report-psychometrician/service/anomaly-file-report.service.js
  functions-app/report-psychometrician/service/check-processing.service.js
  functions-app/report-psychometrician/service/detections/detect-low-battery.js
  functions-app/report-psychometrician/service/detections/detect-page-refresh.js
  functions-app/report-psychometrician/service/detections/detect-wrong-number-of-answers.js
  functions-app/report-psychometrician/service/detections/get-check-started-date.js
  functions-app/report-psychometrician/service/detections/input-before-question-is-shown.js
  functions-app/report-psychometrician/service/detections/remove-duplicate-anomaly-reports.js
  functions-app/report-psychometrician/service/detections/report.js
  functions-app/report-psychometrician/spec/anomaly-file-report.service.spec.js
  functions-app/report-psychometrician/spec/check-processing.service.spec.js
  functions-app/report-psychometrician/spec/detections/get-check-started-date.spec.js
  functions-app/report-psychometrician/spec/detections/input-before-question-is-shown.spec.js
  functions-app/report-psychometrician/spec/detections/low-battery.spec.js
  functions-app/report-psychometrician/spec/detections/page-refresh.spec.js
  functions-app/report-psychometrician/spec/detections/remove-duplicate-anomaly-reports.spec.js
  functions-app/report-psychometrician/spec/detections/wrong-number-of-answers.spec.js
  functions-app/report-psychometrician/spec/mocks/completed-check-with-results-and-anomalies.js
  functions-app/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1348 Feature/35915 Service manager pt2 toolkit update
  admin/app.js
  admin/assets/stylesheets/elements/_gds-tables.scss
  admin/controllers/service-manager.js
  admin/views/error.ejs
  admin/views/service-manager/check-settings.ejs
  admin/views/service-manager/sce-add-school.ejs
  admin/views/service-manager/sce-settings.ejs
  functions/prepared-check-delete/function.json
  test/admin-hpa/features/phase_banner.feature
  test/admin-hpa/features/step_definitions/breadcrumbs_steps.rb
  test/admin-hpa/features/step_definitions/mod_schools_steps.rb
  test/admin-hpa/features/support/page_objects/check_settings_page.rb
  test/admin-hpa/features/support/page_objects/mod_schools_page.rb
  test/admin-hpa/features/support/page_objects/update_school_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1353 rework some tests that are marked @wup
  test/admin-hpa/features/add_multiple_pupil_validation_error.feature
  test/admin-hpa/features/restarts.feature
  test/admin-hpa/features/step_definitions/add_multiple_pupil_validation_steps.rb
  test/pupil-hpa/features/step_definitions/pupil_api.rb
Labels: CI Enabled, Tested, ruby

#1358 fix dot net version
  functions/Dockerfile
Labels: CI Enabled, Requires Tech Sign Off, Signed Off, Tested

#1357 Feature/36387 check validator
  func-complete-check/check-receiver/function.json
  func-complete-check/check-receiver/index.ts
  func-complete-check/check-validator/check-validator.v1.ts
  func-complete-check/check-validator/index.ts
  func-complete-check/jest.config.js
  func-complete-check/lib/ILogger.ts
  func-complete-check/lib/compression-service.ts
  func-complete-check/lib/storage-helper.ts
  func-complete-check/package.json
  func-complete-check/readme.md
  func-complete-check/spec/check-validator/check-validator.v1.spec.ts
  func-complete-check/spec/helpers/ts_console.ts
  func-complete-check/spec/support/jasmine.json
  func-complete-check/yarn.lock
Labels: CI Enabled, Reviewed & approved

#1355 Feature/36273 service bus queue creation util script
  .travis.yml
  deploy/service-bus/create.js
  deploy/service-bus/delete.js
  deploy/service-bus/package.json
  deploy/service-bus/queues-topics.json
  deploy/service-bus/readme.md
  deploy/service-bus/yarn.lock
  deploy/storage/create-items.sh
  deploy/storage/tables-queues.json
  design/design-ideas.md
  func-check-gen/check-activator/index.ts
  start.sh
  stop.sh
  tslint.json
Labels: CI Enabled, Reviewed & approved

#1356 Feature/add detection to anomaly report 1
  functions-app/report-psychometrician/service/anomaly-file-report.service.js
  functions-app/report-psychometrician/service/check-processing.service.js
  functions-app/report-psychometrician/service/detections/detect-input-before-question-is-shown.js
  functions-app/report-psychometrician/spec/detections/input-before-question-is-shown.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1354 Automation/fix result test
  test/admin-hpa/features/step_definitions/result_page_steps.rb
Labels: CI Enabled, ruby

#1362 37064 - updated css selector for failing test
  test/admin-hpa/features/support/page_objects/view_and_custom_print_live_check_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Tested, ruby
