Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2019-01, with the labels that each got.

#962 freeze lockfiles and add app insight default config settings
  admin/Dockerfile
  admin/config.js
  pupil-api/Dockerfile
Labels: CI Enabled, Reviewed & approved

#953 Bug/21659 no connection error message
  pupil-spa/src/app/login/login.component.html
  pupil-spa/src/app/login/login.component.spec.ts
  pupil-spa/src/app/login/login.component.ts
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#957 27842 - Fix operator that was allowing an extra restart to take place
  admin/services/data-access/restart-v2.data.service.js
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested

#963 fixes from production deployment
  admin/authentication/local-strategy.js
  admin/authentication/middleware.js
  admin/authentication/nca-tools-authentication-strategy.js
  admin/config.js
  admin/config/feature-toggles.Azure-EE-Prod.json
  admin/models/logger.js
  admin/services/azure-queue.service.js
  admin/services/data-access/azure-blob.data.service.js
  admin/services/nca-tools-auth.service.js
  admin/tests-integration/sql.service.spec.js
Labels: CI Enabled, Reviewed & approved

#960 Feature/27839 remove auditlog trigger system from sql database
  admin/data/sql/migrations/20181221145022.do.remove-audit-log-triggers.sql
  admin/data/sql/migrations/20181221145022.undo.remove-audit-log-triggers.sql
  admin/services/check-start.service.js
  admin/services/log.service.js
  admin/spec/back-end/helpers/check-form-presenter.spec.js
  admin/spec/back-end/lib/validator/check-form/multiple-check-forms-validator.spec.js
  functions/Dockerfile
Labels: CI Enabled, Reviewed & approved, Signed Off

#966 19521 - reintroduce hash verification
  admin/bin/generate-pupil-data.js
  admin/services/nca-tools-auth.service.js
Labels: CI NOT Required, Ready for review

#944 Feature/27445 service manager check settings
  admin/config.js
  admin/controllers/service-manager.js
  admin/data/sql/migrations/20181212170211.do.add-check-time-limit-settings.sql
  admin/data/sql/migrations/20181212170211.undo.add-check-time-limit-settings.sql
  admin/lib/errors/settings.js
  admin/lib/validator/settings-validator.js
  admin/services/config.service.js
  admin/services/data-access/setting-log.data.service.js
  admin/services/data-access/setting.data.service.js
  admin/services/setting.service.js
  admin/spec/back-end/controllers/service-manager.spec.js
  admin/spec/back-end/lib/validator/settings-validator.spec.js
  admin/spec/back-end/mocks/setting.js
  admin/spec/back-end/service/config.service.spec.js
  admin/spec/back-end/service/data-access/setting.data.service.spec.js
  admin/spec/back-end/service/setting.service.spec.js
  admin/views/service-manager/check-settings.ejs
  functions/check-not-received/v1.js
  functions/config.js
  test/admin-hpa/features/check_time_limits.feature
  test/admin-hpa/features/step_definitions/question_time_limit_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/check_settings_page.rb
  test/admin/features/check_time_limits.feature
  test/admin/features/step_definitions/question_time_limit_steps.rb
  test/admin/features/support/hooks.rb
  test/admin/features/support/page_objects/check_settings_page.rb
Labels: CI Enabled, Reviewed & approved, Testing

#965 Feature/27837 Assign forms UI scaffolding
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_assign-forms.scss
  admin/controllers/check-form-v2.js
  admin/data/sql/migrations/20190110132657.do.create-view-check-windows-with-status-and-form-count-by-type.sql
  admin/data/sql/migrations/20190110132657.undo.create-view-check-windows-with-status-and-form-count-by-type.sql
  admin/helpers/check-form-presenter.js
  admin/routes/check-form.js
  admin/services/check-form-v2.service.js
  admin/services/check-window-v2.service.js
  admin/services/data-access/check-form-v2.data.service.js
  admin/services/data-access/check-window.data.service.js
  admin/spec/back-end/controllers/check-form-v2.spec.js
  admin/spec/back-end/helpers/check-form-presenter.spec.js
  admin/spec/back-end/service/check-form-v2.service.spec.js
  admin/spec/back-end/service/check-window-v2.service.spec.js
  admin/views/check-form/view-assign-forms-to-check-windows.ejs
  admin/views/check-form/view-select-forms.ejs
  admin/views/test-developer/test-developer-home.ejs
  test/admin-hpa/features/assign_to_check_window_v2.feature
  test/admin-hpa/features/step_definitions/assign_to_check_window_v2_steps.rb
  test/admin-hpa/features/support/page_objects/assign_form_to_window_v2_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#969 Feature/28114 Change pupil spa banner title from Familiarisation check to Try it out
  pupil-spa/src/app/header/header.component.html
  pupil-spa/src/assets/shared-styles/elements/_check.scss
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#974 Bug/28351 pupil restart ids not being found
  admin/views/access-arrangements/select-access-arrangements.ejs
  admin/views/pupil-pin/view-and-custom-print-pins.ejs
  admin/views/restart/select-restart-list.ejs
  admin/views/school/submit-attendance-register.ejs
  docs/developer.md
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested, bug

#968 Feature/23634 Admin app content changes for teacher user level
  admin/assets/stylesheets/elements/_printing.scss
  admin/controllers/pupil-pin.js
  admin/controllers/pupil.js
  admin/helpers/pupil-presenter.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/spec/back-end/helpers/pupil-presenter.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/access-arrangements/select-access-arrangements.ejs
  admin/views/check-form/view-form.ejs
  admin/views/check-window/manage-check-windows.ejs
  admin/views/groups/groups.ejs
  admin/views/partials/_print_pupils.ejs
  admin/views/partials/_sticky_confirmation_banner.ejs
  admin/views/pupil-pin/generate-pins-list.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/view-and-custom-print-pins.ejs
  admin/views/pupil-pin/view-and-print-pins.ejs
  admin/views/pupil-register/add-pupil.ejs
  admin/views/pupil-register/edit-pupil.ejs
  admin/views/pupil-register/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/restart/select-restart-list.ejs
  admin/views/school/_pupil-form.ejs
  admin/views/school/school-home.ejs
  admin/views/service-manager/check-windows.ejs
  admin/views/service-manager/service-manager-home.ejs
  admin/views/test-developer/assign-check-forms-to-windows.ejs
  admin/views/test-developer/test-developer-home.ejs
  admin/views/test-developer/upload-and-view-forms.ejs
  admin/views/test-developer/view-check-form.ejs
  test/admin-hpa/features/add_multiple_pupil_validation_error.feature
  test/admin-hpa/features/breadcrumbs.feature
  test/admin-hpa/features/school_landing.feature
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
  test/admin-hpa/features/support/page_objects/access_arrangements_page.rb
  test/admin-hpa/features/support/page_objects/custom_pins_familiarisation_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_overview_page.rb
  test/admin-hpa/features/support/page_objects/group_pupils_page.rb
  test/admin-hpa/features/support/page_objects/pupil_reason_page.rb
  test/admin-hpa/features/support/page_objects/pupils_not_taking_check_page.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
  test/admin-hpa/features/support/page_objects/view_and_custom_print_live_check_page.rb
  test/admin-hpa/features/support/page_objects/view_and_print_pins_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#979 updated failing test for admin app for nightly build
  test/admin-hpa/features/assign_to_check_window_v2.feature
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
  test/admin-hpa/features/support/page_objects/assign_form_to_window_v2_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
Labels: CI Enabled, Reviewed & approved

#981 Feature/28551 deployment updates
  admin/config/feature-toggles.eazure-demo.json
  admin/config/feature-toggles.eazure-dev.json
  admin/config/feature-toggles.eazure-live.json
  admin/config/feature-toggles.eazure-preprod.json
  admin/config/feature-toggles.eazure-proto.json
  admin/config/feature-toggles.eazure-test.json
  deploy/arm/auth-web.json
  deploy/arm/template-basics.json
  vso-build.yml
Labels: CI NOT Required, Ready for review

#964 Feature/22029 hdf page
  admin/controllers/attendance.js
  admin/lib/errors/hdf.js
  admin/lib/validator/hdf-validator.js
  admin/services/data-access/pupil.data.service.js
  admin/services/headteacher-declaration.service.js
  admin/services/pupil.status.service.js
  admin/spec/back-end/controllers/attendance.spec.js
  admin/spec/back-end/lib/validator/hdf-validation.spec.js
  admin/views/hdf/declaration-form.ejs
  admin/views/school/declaration-form.ejs
  admin/views/school/school-home.ejs
  test/admin-hpa/features/declaration_form.feature
  test/admin-hpa/features/step_definitions/declaration_form_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/error_summary_section.rb
  test/admin-hpa/features/support/page_objects/hdf_form_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/admin/features/declaration_form.feature
  test/admin/features/step_definitions/declaration_form_steps.rb
  test/admin/features/support/page_objects/error_summary_section.rb
  test/admin/features/support/page_objects/hdf_form_page.rb
  test/admin/features/support/sql_db_helper.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#973 Feature/28113 Service manager content changes
  admin/lib/errors/check-window-v2.js
  admin/views/check-window/create-check-window.ejs
  test/admin-hpa/features/step_definitions/check_window_validation_steps.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#976 Feature/27838 Assign check forms v2
  admin/assets/stylesheets/elements/_assign-forms.scss
  admin/config.js
  admin/controllers/check-form-v2.js
  admin/data/sql/seeds/20190123182010.custom.familiarisation-check-form-dev-data.sql
  admin/data/sql/seeds/20190123182328.custom.assign-dev-familiarisation-check-form-to-check-window.js
  admin/helpers/check-form-presenter.js
  admin/routes/check-form.js
  admin/services/check-form-v2.service.js
  admin/services/check-form.service.js
  admin/services/check-start.service.js
  admin/services/data-access/check-form-v2.data.service.js
  admin/services/data-access/check-form.data.service.js
  admin/spec/back-end/controllers/check-form-v2.spec.js
  admin/spec/back-end/helpers/check-form-presenter.spec.js
  admin/spec/back-end/service/check-form-v2.service.spec.js
  admin/spec/back-end/service/check-start.service.spec.js
  admin/views/check-form/view-assign-forms-to-check-windows.ejs
  admin/views/check-form/view-select-forms.ejs
  admin/views/contact.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/view-and-custom-print-pins.ejs
  admin/views/pupil-pin/view-and-print-pins.ejs
  pupil-spa/gen_config.sh
  pupil-spa/src/app/submission-failed/submission-failed.component.html
  test/admin-hpa/features/assign_to_check_window_v2.feature
  test/admin-hpa/features/step_definitions/assign_to_check_window_v2_steps.rb
  test/admin-hpa/features/step_definitions/create_window_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/assign_form_to_window_v2_page.rb
  test/admin-hpa/features/support/page_objects/contact_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_overview_page.rb
  test/admin-hpa/features/support/page_objects/select_check_forms_to_assign_page.rb
  test/admin-hpa/features/support/page_objects/sticky_banner_section.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/admin/features/support/page_objects/contact_page.rb
  test/admin/features/support/page_objects/generate_pins_overview_page.rb
  test/pupil-hpa/features/support/page_objects/generate_pins_overview_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested, Urgent

#980 feature/28706 update HSTS headers
  admin/helpers/browserSecurity.js
  admin/package.json
  admin/yarn.lock
  api_tests/helpers/request_helper.rb
  api_tests/spec/check_started_spec.rb
  api_tests/spec/question_spec.rb
  api_tests/spec/security_spec.rb
  pupil-api/src/App.ts
  test/pupil-hpa/features/pupil_api.feature
  test/pupil-hpa/features/step_definitions/pupil_api.rb
  test/pupil-hpa/features/support/helpers.rb
Labels: CI Enabled, Reviewed & approved, Tested

#986 28735 - Add link to related links section
  admin/views/pupil-register/pupils-list.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#985 remove newrelic as no longer used
  admin/app.js
  admin/config.js
  admin/package.json
  admin/yarn.lock
Labels: CI Enabled, Reviewed & approved

#988 add new helpdesk role mapping
  admin/services/role.service.js
Labels: CI Enabled, Ready for review, Urgent

#991 fix cancel href
  admin/spec/front-end/check-forms.spec.js
  admin/views/check-form/upload-new-forms.ejs
Labels: CI Enabled, Ready to merge, Tested

#983 Feature/23633 Test developer content changes
  admin/helpers/check-form-presenter.js
  admin/lib/errors/check-form.js
  admin/spec/back-end/helpers/check-form-presenter.spec.js
  admin/views/access-arrangements/select-access-arrangements.ejs
  admin/views/check-form/upload-new-forms.ejs
  admin/views/test-developer/download-pupil-check-data.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#970 Bug/27121 Throw bulk import error instead of displaying it in table
  admin/services/data-access/pupil-census-import.data.service.js
  test/admin-hpa/features/upload_pupil_census.feature
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#992 Feature/29001 - Fix nightly build copy changes
  test/admin-hpa/features/step_definitions/upload_view_forms_v2_steps.rb
  test/admin-hpa/features/support/page_objects/download_pupil_check_data_page.rb
  test/admin-hpa/features/upload_pupil_census.feature
Labels: CI Enabled, Reviewed & approved, Tested

#993 Feature/28937 school data jan 2019
  admin/config.js
  admin/data/sql/migrations/100.do.add-school-dataset.js
  admin/data/sql/migrations/100.undo.add-school-dataset.sql
  admin/data/sql/migrations/20190128160154.do.delete-old-schools.sql
  admin/data/sql/migrations/20190128160154.undo.delete-old-schools.sql
  admin/data/sql/seeds/20190128145958.custom.school-data-jan-2019.sql
Labels: CI Enabled, Ready for review

#982 Feature/23279 view edit hdf pupil details
  admin/controllers/attendance.js
  admin/helpers/pupil-presenter.js
  admin/routes/attendance.js
  admin/services/data-access/attendance-code.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/data-access/school.data.service.js
  admin/services/headteacher-declaration.service.js
  admin/spec/back-end/controllers/attendance.spec.js
  admin/spec/back-end/helpers/pupil-presenter.spec.js
  admin/spec/back-end/service/headteacher-declaration.service.spec.js
  admin/views/hdf/attendance-edit-reason.ejs
  admin/views/hdf/review-pupil-details.ejs
  admin/views/partials/_attendance_code_reasons.ejs
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
  admin/views/school/submit-attendance-register.ejs
  test/admin-hpa/features/attendance_register.feature
  test/admin-hpa/features/declaration_edit_reason.feature
  test/admin-hpa/features/declaration_form.feature
  test/admin-hpa/features/declaration_review_pupils.feature
  test/admin-hpa/features/step_definitions/attendance_register_steps.rb
  test/admin-hpa/features/step_definitions/attendance_steps.rb
  test/admin-hpa/features/step_definitions/declaration_edit_reason_steps.rb
  test/admin-hpa/features/step_definitions/declaration_form_steps.rb
  test/admin-hpa/features/step_definitions/declaration_review_pupil_steps.rb
  test/admin-hpa/features/support/page_objects/attendance_register_page.rb
  test/admin-hpa/features/support/page_objects/declaration_edit_reason_page.rb
  test/admin-hpa/features/support/page_objects/declaration_page.rb
  test/admin-hpa/features/support/page_objects/declaration_review_pupils_page.rb
  test/admin-hpa/features/support/page_objects/edit_reason_for_hdf_pupil_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#984 Feature/28217 optimise config calls in check preparation
  admin/app.js
  admin/config.js
  admin/controllers/questions.js
  admin/data/sql/migrations/20190118112928.do.remove-group-time-limits.sql
  admin/data/sql/migrations/20190118112928.undo.remove-group-time-limits.sql
  admin/routes/questions.js
  admin/services/check-start.service.js
  admin/services/config.service.js
  admin/services/data-access/config.data.service.js
  admin/spec/back-end/controllers/questions.spec.js
  admin/spec/back-end/service/check-start.service.spec.js
  admin/spec/back-end/service/config.service.spec.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#995 school dataset - estabCode missing
  admin/bin/generate-pupil-data-for-all-schools.js
  admin/bin/generate-pupil-data-for-one-school.js
  admin/config.js
  admin/data/sql/migrate-sql.js
  admin/data/sql/migrations/20190128160154.do.delete-old-schools.sql
  admin/data/sql/migrations/20190128160154.undo.delete-old-schools.sql
  admin/data/sql/seed-sql.js
  admin/data/sql/seeds/20190128145958.custom.school-data-jan-2019.sql
  admin/data/sql/seeds/20190129102415.custom.school-data-jan-2019.sql
Labels: CI Enabled, Reviewed & approved

#997 fix nightly build
  test/admin-hpa/features/csrf.feature
  test/admin-hpa/features/manage_check_window.feature
  test/admin-hpa/features/step_definitions/csrf_steps.rb
  test/admin-hpa/features/step_definitions/school_landing_page_steps.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
Labels: CI Enabled

#1000 Feature/29054 nightly fixes
  admin/views/check-form/view-form.ejs
  admin/views/check-form/view-forms.ejs
  admin/views/test-developer/upload-and-view-forms.ejs
  admin/views/test-developer/view-check-form.ejs
  test/admin-hpa/features/step_definitions/manage_check_forms_steps.rb
  test/admin-hpa/features/step_definitions/upload_view_forms_steps.rb
  test/admin-hpa/features/step_definitions/upload_view_forms_v2_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/upload_new_forms_page.rb
  test/admin-hpa/features/support/page_objects/view_form_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/admin-hpa/features/upload_view_forms_v2.feature
  test/admin-hpa/features/view_check.feature
Labels: CI Enabled, Ready for review, Tested

#999 Bug/29049 familiarisation check are behaving as live check
  admin/bin/generate-pupil-data-for-one-school.js
  admin/services/check-form-v2.service.js
  admin/services/check-start.service.js
  admin/services/config.service.js
  admin/services/pupil.status.service.js
  admin/spec/back-end/helpers/pupil-presenter.spec.js
  admin/spec/back-end/service/check-form-v2.service.spec.js
  admin/spec/back-end/service/check-start.service.spec.js
  admin/spec/back-end/service/config.service.spec.js
Labels: CI Enabled, Ready to merge, Reviewed & approved, Tested

#989 Feature/28838 Execute marking as part of completed checks function
  admin/README.md
  admin/bin/detect-anomalies.js
  admin/bin/psychometricians-report-v2.js
  admin/config.js
  admin/services/check-complete.service.js
  admin/services/marking.service.js
  admin/spec/back-end/service/check-complete.service.spec.js
  admin/spec/back-end/service/marking.service.spec.js
  functions/completed-checks/index.js
  functions/completed-checks/marking.service.js
  functions/completed-checks/marking.service.spec.js
  functions/completed-checks/mocks/check-form.js
  functions/completed-checks/mocks/completed-check-with-results.js
  functions/completed-checks/v1.js
  functions/lib/sql-helper.js
  test/admin-hpa/features/declaration_edit_reason.feature
  test/admin-hpa/features/step_definitions/declaration_form_steps.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#998 Prevented enter key on loading screen until next button displayed
  pupil-spa/src/app/loading/loading.component.ts
Labels: CI Enabled, Ready to merge, Reviewed & approved, Tested

#1003 Add migration to exclude pupils who have a familiarisation pin
  admin/data/sql/migrations/20190131044243.do.fix-fam-pin-generation-bug.sql
  admin/data/sql/migrations/20190131044243.undo.fix-fam-pin-generation-bug.sql
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1005 Update cookie page
  admin/views/cookies.ejs
  admin/views/privacy.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested
