Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2019-08, with the labels that each got.

#1312 Feature/35413 - added a sleep of 2 seconds for the local storage to be populated
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/features/add_multiple_pupil_validation_error.feature
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/step_definitions/add_multiple_pupil_steps.rb
  test/admin-hpa/features/step_definitions/add_multiple_pupil_validation_steps.rb
  test/admin-hpa/features/step_definitions/manage_check_windows.rb
  test/admin-hpa/features/step_definitions/mod_schools_steps.rb
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/features/support/page_objects/access_arrangements_page.rb
  test/admin-hpa/features/support/page_objects/manage_check_window_page.rb
  test/admin-hpa/features/support/page_objects/mod_schools_page.rb
  test/admin-hpa/features/support/page_objects/warm_up_page.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  test/pupil-hpa/features/step_definitions/access_arrangement_steps.rb
  test/pupil-hpa/features/step_definitions/check_steps.rb
  test/pupil-hpa/features/step_definitions/event_auditing_steps.rb
  test/pupil-hpa/features/step_definitions/login_page_steps.rb
  test/pupil-hpa/features/step_definitions/state_steps.rb
  test/pupil-hpa/features/support/env.rb
  test/pupil-hpa/features/support/page_objects/check_page.rb
  test/pupil-hpa/features/support/page_objects/warm_up_page.rb
  test/pupil-hpa/features/support/site_prism_config.rb
Labels: CI Enabled, Tested, ruby

#1308 Feature/35226 Sign in page govuk toolkit update
  admin/assets/images/org_crest_13px.png
  admin/assets/images/org_crest_18px.png
  admin/assets/images/org_crest_27px.png
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_sta-organisation-logo.scss
  admin/gulpfile.js
  admin/package.json
  admin/views/partials/_gds_body_header.ejs
  admin/views/sign-in.ejs
  admin/yarn.lock
  test/admin-hpa/features/support/page_objects/sign_in_page.rb
  test/pupil-hpa/features/step_definitions/pupil_api.rb
  test/pupil-hpa/features/support/page_objects/admin_sign_in_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1229 Feature/33237 Pupil SPA Connectivity Check
  deploy/storage/tables-queues.json
  functions/disable-functions.env
  pupil-spa/README.md
  pupil-spa/gen_config.sh
  pupil-spa/gulpfile.js
  pupil-spa/package.json
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/connectivity-check.guard.spec.ts
  pupil-spa/src/app/connectivity-check.guard.ts
  pupil-spa/src/app/connectivity-check/connectivity-check.component.html
  pupil-spa/src/app/connectivity-check/connectivity-check.component.scss
  pupil-spa/src/app/connectivity-check/connectivity-check.component.spec.ts
  pupil-spa/src/app/connectivity-check/connectivity-check.component.ts
  pupil-spa/src/app/connectivity-error/connectivity-error.component.html
  pupil-spa/src/app/connectivity-error/connectivity-error.component.scss
  pupil-spa/src/app/connectivity-error/connectivity-error.component.spec.ts
  pupil-spa/src/app/connectivity-error/connectivity-error.component.ts
  pupil-spa/src/app/logout/logout.component.spec.ts
  pupil-spa/src/app/logout/logout.component.ts
  pupil-spa/src/app/services/azure-queue/azure-queue.service.ts
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/services/connectivity-service/connectivity-error-messages.ts
  pupil-spa/src/app/services/connectivity-service/connectivity-service.spec.ts
  pupil-spa/src/app/services/connectivity-service/connectivity-service.ts
  pupil-spa/yarn.lock
  test/pupil-hpa/features/login_page.feature
  test/pupil-hpa/features/step_definitions/complete_page_steps.rb
  test/pupil-hpa/features/step_definitions/device_steps.rb
  test/pupil-hpa/features/step_definitions/login_page_steps.rb
  test/pupil-hpa/features/support/page_objects/connectivity_check_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1313 added capybara max wait time
  test/pupil-hpa/features/support/env.rb
Labels: CI Enabled, Tested, ruby

#1309 Feature/35313 School home page govuk toolkit update
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_gds-app-cookie-banner.scss
  admin/assets/stylesheets/elements/_gds-app-related-items.scss
  admin/assets/stylesheets/elements/_gds-custom-fonts.scss
  admin/assets/stylesheets/elements/_gds-custom-links.scss
  admin/assets/stylesheets/elements/_gds-session-expiry.scss
  admin/assets/stylesheets/elements/_sign-out.scss
  admin/controllers/authentication.js
  admin/controllers/school.js
  admin/views/partials/_name_and_sign_out.ejs
  admin/views/partials/_session_expiry.ejs
  admin/views/school/school-home.ejs
  admin/views/sign-in-failure.ejs
  test/admin-hpa/features/step_definitions/phase_banner_steps.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
  test/admin-hpa/features/support/page_objects/sign_in_failure_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1311 Feature/35332 new govuk pupil register
  admin/assets/javascripts/details.polyfill.js
  admin/assets/javascripts/gds-cookie-banner.js
  admin/assets/javascripts/gds-table-sorting.js
  admin/assets/javascripts/pupil-form.js
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_gds-back-to-top.scss
  admin/assets/stylesheets/elements/_gds-custom-icons.scss
  admin/assets/stylesheets/elements/_gds-custom-links.scss
  admin/assets/stylesheets/elements/_gds-flash-messages.scss
  admin/assets/stylesheets/elements/_gds-forms.scss
  admin/assets/stylesheets/elements/_gds-links.scss
  admin/assets/stylesheets/elements/_gds-panel-list.scss
  admin/assets/stylesheets/elements/_gds-sorting.scss
  admin/assets/stylesheets/elements/_gds-tables.scss
  admin/assets/stylesheets/elements/_printing.scss
  admin/assets/stylesheets/elements/_pupils.scss
  admin/controllers/pupil-register.js
  admin/controllers/pupil.js
  admin/gulpfile.js
  admin/spec/front-end/gds-table-sorting.spec.js
  admin/spec/front-end/pupil-form.spec.js
  admin/views/partials/_breadcrumbs_and_sign_out.ejs
  admin/views/partials/_gds_breadcrumbs_and_sign_out.ejs
  admin/views/partials/_name_and_sign_out.ejs
  admin/views/partials/_readonly.ejs
  admin/views/pupil-register/add-multiple-pupils.ejs
  admin/views/pupil-register/add-pupil.ejs
  admin/views/pupil-register/edit-pupil.ejs
  admin/views/pupil-register/pupils-list.ejs
  admin/views/school/_pupil-form.ejs
  admin/views/school/add-multiple-pupils.ejs
  test/admin-hpa/features/breadcrumbs.feature
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/breadcrumbs_steps.rb
  test/admin-hpa/features/step_definitions/phase_banner_steps.rb
  test/admin-hpa/features/support/page_objects/add_multiple_pupil_page.rb
  test/admin-hpa/features/support/page_objects/add_pupil_page.rb
  test/admin-hpa/features/support/page_objects/edit_pupil_page.rb
  test/admin-hpa/features/support/page_objects/profile_page.rb
  test/admin-hpa/features/support/page_objects/pupil_register_page.rb
  test/pupil-hpa/features/support/page_objects/add_pupil_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1316 remove commited binding.pry
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
Labels: CI Enabled, Tested

#1318 Feature/35754 - full screen screenshots
  test/admin-hpa/features/support/hooks.rb
  test/pupil-hpa/features/support/hooks.rb
Labels: CI Enabled, Reviewed & approved, Tested

#1314 Feature/35578 new govuk groups view update
  admin/assets/javascripts/jquery-modal.js
  admin/assets/javascripts/util-checkbox.js
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_gds-links.scss
  admin/assets/stylesheets/elements/_gds-modal.scss
  admin/assets/stylesheets/elements/_gds-mtc-checkboxes.scss
  admin/assets/stylesheets/elements/_gds-sticky-confirmation-banner.scss
  admin/controllers/group.js
  admin/views/availability/section-unavailable.ejs
  admin/views/groups/groups.ejs
  admin/views/groups/manage-group.ejs
  admin/views/partials/_gds_body_footer.ejs
  admin/views/partials/_gds_breadcrumbs_and_sign_out.ejs
  admin/views/partials/_gds_modal_box.ejs
  admin/views/partials/_gds_session_expiry.ejs
  admin/views/partials/_gds_sticky_confirmation_banner.ejs
  admin/views/partials/_session_expiry.ejs
  admin/views/pupil-register/pupils-list.ejs
  admin/views/school/school-home.ejs
  test/admin-hpa/features/step_definitions/groups_steps.rb
  test/admin-hpa/features/support/page_objects/add_edit_groups_page.rb
  test/admin-hpa/features/support/page_objects/group_pupils_page.rb
  test/admin-hpa/features/support/page_objects/sticky_banner_section.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1315 feature/automate-result-page
  test/admin-hpa/features/results.feature
  test/admin-hpa/features/step_definitions/result_page_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/results_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled

#1317 Feature/35668 new govuk pupils not taking the check update
  admin/assets/javascripts/gds-print-popup.js
  admin/assets/javascripts/util-checkbox.js
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_gds-filters.scss
  admin/assets/stylesheets/elements/_gds-sticky-confirmation-banner.scss
  admin/assets/stylesheets/elements/_not-taking-check.scss
  admin/controllers/pupils-not-taking-the-check.js
  admin/gulpfile.js
  admin/views/partials/_attendance_code_reasons.ejs
  admin/views/partials/_gds_body_footer.ejs
  admin/views/partials/_gds_groups_filter.ejs
  admin/views/partials/_gds_sticky_confirmation_banner.ejs
  admin/views/pupil-register/add-multiple-pupils.ejs
  admin/views/pupil-register/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  admin/views/school/_pupil-form.ejs
  test/admin-hpa/features/step_definitions/assign_to_check_window_v2_steps.rb
  test/admin-hpa/features/step_definitions/breadcrumbs_steps.rb
  test/admin-hpa/features/step_definitions/manage_check_forms_steps.rb
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
  test/admin-hpa/features/support/page_objects/add_multiple_pupil_page.rb
  test/admin-hpa/features/support/page_objects/add_pupil_page.rb
  test/admin-hpa/features/support/page_objects/group_filter_section.rb
  test/admin-hpa/features/support/page_objects/pupil_reason_page.rb
  test/admin-hpa/features/support/page_objects/pupil_register_page.rb
  test/admin-hpa/features/support/page_objects/pupils_not_taking_check_page.rb
  test/admin-hpa/features/support/page_objects/sticky_banner_section.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1323 35931 - make upn tests more reliable
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/support/page_objects/add_pupil_page.rb
  test/admin-hpa/features/support/page_objects/edit_pupil_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Tested

#1319 Feature/35753 new govuk access arrangements update
  admin/assets/javascripts/mtc-autocomplete.js
  admin/assets/javascripts/pupil-access-arrangements-selection.js
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_access-arrangements.scss
  admin/assets/stylesheets/elements/_gds-accessible-autocomplete.scss
  admin/assets/stylesheets/elements/_gds-lists.scss
  admin/controllers/access-arrangements.js
  admin/gulpfile.js
  admin/spec/front-end/pupil-access-arrangements-selection.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/access-arrangements/select-access-arrangements.ejs
  admin/views/groups/manage-group.ejs
  admin/views/partials/_gds_session_expiry.ejs
  admin/views/partials/_groups_filter.ejs
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
  test/admin-hpa/features/support/page_objects/access_arrangements_page.rb
  test/admin-hpa/features/support/page_objects/select_access_arrangements_page.rb
  test/pupil-hpa/features/support/page_objects/access_arrangements_page.rb
  test/pupil-hpa/features/support/page_objects/select_access_arrangements_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1321 Feature/35910 new govuk restarts update
  admin/assets/stylesheets/application.scss
  admin/assets/stylesheets/elements/_restarts.scss
  admin/controllers/restart.js
  admin/views/groups/manage-group.ejs
  admin/views/pupil-register/_pupil-form.ejs
  admin/views/pupil-register/add-multiple-pupils.ejs
  admin/views/pupil-register/add-pupil.ejs
  admin/views/pupil-register/edit-pupil.ejs
  admin/views/pupil-register/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  admin/views/restart/restart-overview.ejs
  admin/views/restart/select-restart-list.ejs
  test/admin-hpa/features/step_definitions/breadcrumbs_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/support/page_objects/restarts_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1322 Feature/35929 pupil group database changes
  admin/assets/javascripts/pupil-filter-group.js
  admin/data/sql/manual/migrate-pupil-groups-to-pupil-table.sql
  admin/data/sql/migrations/20190815114552.do.pupil-group-column.sql
  admin/data/sql/migrations/20190815114552.undo.pupil-group-column.sql
  admin/data/sql/migrations/20190815144902.do.pupilgroup-spgetpupilsresults.sql
  admin/data/sql/migrations/20190815144902.undo.pupilgroup-spgetpupilsresults.sql
  admin/data/sql/migrations/20190815150016.do.pupilgroup-vewpupilregister.sql
  admin/data/sql/migrations/20190815150016.undo.pupilgroup-vewpupilregister.sql
  admin/data/sql/migrations/20190815150258.do.pupilgroup-vewpupilseligibleforlivepingeneration.sql
  admin/data/sql/migrations/20190815150258.undo.pupilgroup-vewpupilseligibleforlivepingeneration.sql
  admin/data/sql/migrations/20190815150854.do.pupilgroup-vewpupilseligibleforrestart.sql
  admin/data/sql/migrations/20190815150854.undo.pupilgroup-vewpupilseligibleforrestart.sql
  admin/data/sql/migrations/20190815151032.do.pupilgroup-vewpupilseligiblefortryitoutpin.sql
  admin/data/sql/migrations/20190815151032.undo.pupilgroup-vewpupilseligiblefortryitoutpin.sql
  admin/data/sql/migrations/20190815151201.do.pupilgroup-vewpupilswithactivefamiliarisationpins.sql
  admin/data/sql/migrations/20190815151201.undo.pupilgroup-vewpupilswithactivefamiliarisationpins.sql
  admin/data/sql/migrations/20190815151308.do.pupilgroup-vewpupilswithactivelivepins.sql
  admin/data/sql/migrations/20190815151308.undo.pupilgroup-vewpupilswithactivelivepins.sql
  admin/data/sql/migrations/20190815151441.do.pupilgroup-vewpupilswithactivepins.sql
  admin/data/sql/migrations/20190815151441.undo.pupilgroup-vewpupilswithactivepins.sql
  admin/data/sql/migrations/20190816091640.do.migrate-groups.sql
  admin/data/sql/migrations/20190816091640.undo.migrate-groups.sql
  admin/data/sql/migrations/20190816091709.do.migrate-pupilgroup-to-archive.sql
  admin/data/sql/migrations/20190816091709.undo.migrate-pupilgroup-to-archive.sql
  admin/data/sql/migrations/20190816091715.do.drop-pupilgroup.sql
  admin/data/sql/migrations/20190816091715.undo.drop-pupilgroup.sql
  admin/data/sql/migrations/20190816115008.do.migrate-group-to-archive.sql
  admin/data/sql/migrations/20190816115008.undo.migrate-group-to-archive.sql
  admin/data/sql/migrations/20190816115438.do.delete-deleted-groups.sql
  admin/data/sql/migrations/20190816115438.undo.delete-deleted-groups.sql
  admin/data/sql/migrations/20190816115850.do.group-drop-isdeleted.sql
  admin/data/sql/migrations/20190816115850.undo.group-drop-isdeleted.sql
  admin/data/sql/migrations/20190816131539.do.grant-delete-group.js
  admin/data/sql/migrations/20190816131539.undo.grant-delete-group.js
  admin/package.json
  admin/services/data-access/group.data.service.js
  admin/services/data-access/headteacher-declaration.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/data-access/pupils-not-taking-check.data.service.js
  admin/services/group.service.js
  admin/spec/back-end/service/group.service.spec.js
  admin/views/partials/_gds_groups_filter.ejs
  admin/views/partials/_groups_filter.ejs
  test/admin-hpa/features/groups.feature
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Ready for review, Signed Off, Tested

#1333 Design/2020
  design/2020/design-ideas.md
  design/2020/pupil-state.md
  design/2020/sql drafts/pupil-state.sql
  design/2020/sql drafts/pupilregisterv2.sql
  design/calculate-score-v1/check-window.data.service.js
  design/calculate-score-v1/function.json
  design/calculate-score-v1/index.js
  design/calculate-score-v1/readme.md
  design/calculate-score-v1/score-calculation.data.service.js
  design/calculate-score-v1/v1.js
  design/calculate-score-v1/v1.spec.js
  functions/disable-functions.env
Labels: CI Enabled, Reviewed & approved

#1332 Feature/35944 generate input files for anomaly report
  functions-app/config.js
  functions-app/lib/mtc-fs-utils.js
  functions-app/lib/mtc-fs-utils.spec.js
  functions-app/lib/redis-cache.service.js
  functions-app/lib/sql/date.service.js
  functions-app/lib/sql/retry-async.js
  functions-app/lib/sql/sql.service.js
  functions-app/poison-replay-completed-checks/v1.js
  functions-app/report-psychometrician-create-download/service/psychometrician-report.service.js
  functions-app/report-psychometrician-generate-input-files/function.json
  functions-app/report-psychometrician-generate-input-files/index.js
  functions-app/report-psychometrician-generate-input-files/service/data-access/psychometrician.data.service.js
  functions-app/report-psychometrician-generate-input-files/service/data.service.js
  functions-app/report-psychometrician-generate-input-files/service/date.service.js
  functions-app/report-psychometrician-generate-input-files/v1.js
  functions-app/report-psychometrician/service/anomaly-report.service.js
  functions-app/report-psychometrician/service/data-service/psychometrician.data.service.js
  functions-app/report-psychometrician/service/psychometrician-report.service.js
  functions-app/report-psychometrician/service/psychometrician-util.service.js
  functions-app/report-psychometrician/spec/anomaly-report.service.spec.js
  functions-app/report-psychometrician/spec/mocks/check-with-results.js
  functions-app/report-psychometrician/spec/mocks/completed-check-with-results.js
  functions-app/report-psychometrician/spec/mocks/keyboard-input-2.js
  functions-app/report-psychometrician/spec/mocks/keyboard-input-3.js
  functions-app/report-psychometrician/spec/mocks/keyboard-input-4.js
  functions-app/report-psychometrician/spec/mocks/keyboard-input-5.js
  functions-app/report-psychometrician/spec/mocks/keyboard-input.js
  functions-app/report-psychometrician/spec/mocks/mouse-input.js
  functions-app/report-psychometrician/spec/mocks/touch-input.js
  functions-app/report-psychometrician/spec/psychometrician-report.service.spec.js
  functions-app/report-psychometrician/spec/psychometrician-util.service.spec.js
Labels: CI NOT Required, Requires Tech Sign Off, Reviewed & approved, Signed Off

#1331 Feature/35913 new govuk results
  admin/controllers/results.js
  admin/helpers/result-presenter.js
  admin/spec/back-end/controllers/results.spec.js
  admin/views/results/view-incomplete-hdf.ejs
  admin/views/results/view-results-not-found.ejs
  admin/views/results/view-results.ejs
  admin/views/results/view-unavailable-results.ejs
  test/admin-hpa/features/support/page_objects/results_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1334 Bug/35993 Safari: Table caption relocates after clicking on table checkboxes
  admin/assets/stylesheets/elements/_gds-tables.scss
Labels: Ready to merge, Reviewed & approved, Signed Off, Tested
