Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2020-07, with the labels that each got.

#1674 Automated Load Test in Pipeline
  deploy/sql/.nvmrc
  deploy/sql/dummy-data/all.js
  deploy/sql/dummy-data/upn.service.js
  deploy/sql/package.json
  deploy/sql/yarn.lock
  load-test/exec-flood-api.sh
  load-test/exec-flood.sh
  load-test/exec-local.sh
  load-test/package.json
  load-test/yarn.lock
  tslib/readme.md
Labels: CI NOT Required, QA Not required, Requires Tech Sign Off, Reviewed & approved, Signed Off

#1680 updated rake tasks to support the running of features in groups
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/Rakefile
  test/admin-hpa/features/support/env.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  test/pupil-hpa/Rakefile
  test/pupil-hpa/features/support/env.rb
Labels: CI Enabled, Ready for review, Requires Tech Sign Off, Tested, ruby

#1679 Azure Data Factory ARM templates
  _spikes-poc/ps-report-sql-tactical/create-mtc_analysis-schema.sql
  deploy/azure/data-factory-alt/dataset/MTC_SqlAzure_Database.json
  deploy/azure/data-factory-alt/dataset/PsReportBlob.json
  deploy/azure/data-factory-alt/linkedService/blobstorage.json
  deploy/azure/data-factory-alt/linkedService/sqlazuredb.json
  deploy/azure/data-factory-alt/pipeline/psreport-csv-to-sql.json
  deploy/azure/data-factory/ArmTemplateParameters_master.json
  deploy/azure/data-factory/ArmTemplate_0.json
  deploy/azure/data-factory/ArmTemplate_master.json
  deploy/azure/data-factory/arm_template.json
  deploy/azure/data-factory/arm_template_parameters.json
  deploy/azure/data-factory/linkedTemplates/ArmTemplateParameters_master.json
  deploy/azure/data-factory/linkedTemplates/ArmTemplate_0.json
  deploy/azure/data-factory/linkedTemplates/ArmTemplate_master.json
  deploy/azure/data-factory/readme.md
Labels: CI NOT Required, QA Not required, Ready for review, Requires Tech Sign Off, Signed Off

#1678 Feature/42055 ctf file download
  admin/app.js
  admin/assets/images/custom-download-2.svg
  admin/assets/stylesheets/elements/_custom-icons.scss
  admin/assets/stylesheets/elements/_links.scss
  admin/controllers/hdf.js
  admin/controllers/results.js
  admin/error-types/not-available.js
  admin/lib/consts/ctf-results.js
  admin/lib/consts/mtc-results.js
  admin/lib/consts/pupil-attendance-codes.js
  admin/package.json
  admin/routes/results.js
  admin/services/attendance.service.js
  admin/services/ctf-service/ctf.service.js
  admin/services/ctf-service/ctf.service.spec.js
  admin/services/ctf-service/data-access/ctf.data.service.js
  admin/services/data-access/pupil-restart.data.service.js
  admin/services/data-access/redis-cache.service.js
  admin/services/data-access/result.data.service.js
  admin/services/data-access/sql.service.js
  admin/services/headteacher-declaration.service.js
  admin/services/result.service.js
  admin/services/results-page-availability.service.js
  admin/spec/back-end/controllers/hdf.spec.js
  admin/spec/back-end/controllers/results.spec.js
  admin/spec/back-end/lib/deep-freeze.spec.js
  admin/spec/back-end/service/attendance.service.spec.js
  admin/spec/back-end/service/headteacher-declaration.service.spec.js
  admin/spec/back-end/service/result.service.spec.js
  admin/tests-integration/redis-cache.data.service.spec.js
  admin/views/results/view-results.ejs
  admin/yarn.lock
  test/admin-hpa/Gemfile
  test/admin-hpa/Rakefile
  test/admin-hpa/features/support/env.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Rakefile
  test/pupil-hpa/features/pupil_access_arrangements.feature
  test/pupil-hpa/features/support/env.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1682 Feature/41488 upgrade admin app node to v12
  .circleci/config.yml
  .nvmrc
  .travis.yml
  admin/.nvmrc
  admin/Dockerfile
  admin/app.js
  admin/db-check.js
  admin/dev.Dockerfile
  admin/docker-start-dev.sh
  admin/package.json
  admin/run-dev-migrations.sh
  admin/wait-for-db.sh
  admin/wait-for-it.sh
  admin/wait-sqldb.sh
  deploy/docker/circleci/Dockerfile
  deploy/docker/circleci/README.md
  deploy/docker/functions-base/Dockerfile
  deploy/wait-for-it.sh
  docker-compose.yml
  func-consumption/Dockerfile
  func-consumption/db-check.js
  func-consumption/dev.Dockerfile
  func-consumption/package.json
  func-consumption/wait-for-db.sh
  functions-app/db-check.js
  functions-app/dev.Dockerfile
  functions-app/package.json
  functions-app/wait-for-db.sh
  pupil-api/.nvmrc
  pupil-api/Dockerfile
  pupil-api/dev.Dockerfile
  pupil-api/docker-start-dev.sh
  pupil-api/package.json
  pupil-spa/.nvmrc
  pupil-spa/dev.Dockerfile
  pupil-spa/docker-start-dev.sh
  start.sh
  stop.sh
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1687 Feature/minimal docker compose by default
  README.md
  docker-compose-apps.yml
  docker-compose.yml
  pupil-spa/.nvmrc
  start.sh
  stop.sh
Labels: CI Enabled, CI NOT Required, Requires Tech Sign Off, Reviewed & approved, Signed Off

#1683 changes for local id and exit code
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/Rakefile
  test/admin-hpa/features/step_definitions/assign_to_check_window_v2_steps.rb
  test/admin-hpa/features/support/browserstack_driver_helper.rb
  test/admin-hpa/features/support/env.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  test/pupil-hpa/Rakefile
  test/pupil-hpa/features/support/browserstack_driver_helper.rb
  test/pupil-hpa/features/support/env.rb
Labels: CI Enabled, Ready for review, Reviewed & approved, Tested, ruby

#1694 edge config
  test/admin-hpa/config/browserstack.yml
  test/pupil-hpa/config/browserstack.yml
Labels: CI Enabled, Reviewed & approved, Tested, ruby

#1695 updating rack to 2.2.3
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/features/support/env.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested, ruby

#1688 update lodash indirect dependencies in dependent apps
  _spikes-poc/function-fs-access/functions/package.json
  _spikes-poc/function-fs-access/functions/yarn.lock
  _spikes-poc/key-vault/README.md
  _spikes-poc/key-vault/index.js
  _spikes-poc/key-vault/key-vault.service.js
  _spikes-poc/key-vault/package.json
  _spikes-poc/key-vault/yarn.lock
  _spikes-poc/mssql-test/package.json
  _spikes-poc/mssql-test/yarn.lock
  admin/package.json
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  functions-app/package.json
  functions-app/yarn.lock
  load-test/package.json
  load-test/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  pupil-spa/package.json
  pupil-spa/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1696 Feature/42496 add restarts to load testing fix pupil edit issues
  example.env.txt
  functions-app/sync-results-to-sql/v1.js
  load-test/README.md
  load-test/bin/complete-db-reset.sql
  load-test/scenarios/_2020/live-long-teacher-journey-with-check-submit.jmx
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1697 Feature/42530 drop school result cache when syncing from table storage
  functions-app/lib/redis-key.service.js
  functions-app/sync-results-to-sql/function.json
  functions-app/sync-results-to-sql/service/results.service.js
  functions-app/sync-results-to-sql/v1.js
  functions-app/sync-results-to-sql/v1.spec.js
Labels: CI Enabled, Reviewed & approved, Tested

#1681 feature/41244 retro input assistant persistence
  README.md
  admin/assets/javascripts/pupil-retro-input-assistant.js
  admin/controllers/access-arrangements.js
  admin/controllers/retro-input-assistant.js
  admin/data/sql/migrations/20200710140422.do.aa-retro-input-assistant.sql
  admin/data/sql/migrations/20200710140422.undo.aa-retro-input-assistant.sql
  admin/data/sql/migrations/20200710143820.do.check-retro-input-assistant.sql
  admin/data/sql/migrations/20200710143820.undo.check-retro-input-assistant.sql
  admin/gulpfile.js
  admin/lib/errors/retro-input-assistant.js
  admin/lib/validator/retro-input-assistant-validator.js
  admin/package.json
  admin/routes/access-arrangements.js
  admin/services/access-arrangements.service.js
  admin/services/data-access/access-arrangements.data.service.js
  admin/services/data-access/retro-input-assistant.data.service.js
  admin/services/retro-input-assistant.service.js
  admin/spec/back-end/controllers/retro-input-assistant.spec.js
  admin/spec/back-end/lib/validator/retro-input-assistant-validator.spec.js
  admin/spec/back-end/service/access-arrangements.service.spec.js
  admin/spec/back-end/service/retro-input-assistant.service.spec.js
  admin/views/access-arrangements/retro-add-input-assistant.ejs
  deploy/yarn.lock
  func-consumption/package.json
  test/admin-hpa/features/retro_input_assistance.feature
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/step_definitions/retro_input_steps.rb
  test/admin-hpa/features/support/page_objects/access_arrangements_page.rb
  test/admin-hpa/features/support/page_objects/retro_input_page.rb
  test/admin-hpa/features/support/page_objects/select_access_arrangements_page.rb
  test/pupil-hpa/features/retro_input_assistance.feature
  test/pupil-hpa/features/step_definitions/retro_input_steps.rb
  test/pupil-hpa/features/support/page_objects/access_arrangements_page.rb
  test/pupil-hpa/features/support/page_objects/restarts_page.rb
  test/pupil-hpa/features/support/page_objects/retro_input_page.rb
  test/pupil-hpa/features/support/page_objects/select_access_arrangements_page.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested
