Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2020-09, with the labels that each got.

#1707 [tslib] support sql option `enableArithAbort`
  admin/spec/back-end/lib/validator/pupil-validator.spec.js
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  tslib/src/config.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1702 Feature/39712 GIAS API integration
  .gitignore
  _spikes-poc/gias/GetEstab.js
  _spikes-poc/gias/GiasExtractService.js
  _spikes-poc/gias/MultipartMessage.js
  _spikes-poc/gias/SoapMessage.js
  _spikes-poc/gias/easy-soap-request.js
  _spikes-poc/gias/package.json
  _spikes-poc/gias/yarn.lock
  func-consumption/gias-sync/function.json
  func-consumption/package.json
  func-consumption/yarn.lock
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  tslib/package.json
  tslib/src/config.ts
  tslib/src/functions/gias-sync/attachmentId.parser.spec.ts
  tslib/src/functions/gias-sync/attachmentId.parser.ts
  tslib/src/functions/gias-sync/gias.service.spec.ts
  tslib/src/functions/gias-sync/gias.service.ts
  tslib/src/functions/gias-sync/index.ts
  tslib/src/functions/gias-sync/multipart-message-parser.spec.ts
  tslib/src/functions/gias-sync/multipart-message-parser.ts
  tslib/src/functions/gias-sync/soap-message-builder.spec.ts
  tslib/src/functions/gias-sync/soap-message-builder.ts
  tslib/src/functions/gias-sync/soap-request.service.ts
  tslib/src/functions/gias-sync/xml-parser.ts
  tslib/src/functions/gias-sync/zip.service.ts
  tslib/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1708 add entities for payload storage in sql db
  admin/data/sql/migrations/20200904110942.do.create-results-schema.sql
  admin/data/sql/migrations/20200904110942.undo.create-results-schema.sql
  admin/data/sql/migrations/20200904113433.do.create-user-input-type-table.sql
  admin/data/sql/migrations/20200904113433.undo.create-user-input-type-table.sql
  admin/data/sql/migrations/20200904134412.do.create-results-user-agent-lookup.sql
  admin/data/sql/migrations/20200904134412.undo.create-results-user-agent-lookup.sql
  admin/data/sql/migrations/20200904134652.do.create-results-navigator-language-lookup.sql
  admin/data/sql/migrations/20200904134652.undo.create-results-navigator-language-lookup.sql
  admin/data/sql/migrations/20200904145221.do.create-results-navigator-platform-lookup.sql
  admin/data/sql/migrations/20200904145221.undo.create-results-navigator-platform-lookup.sql
  admin/data/sql/migrations/20200904145504.do.create-results-net-con-eff-type-lookup.sql
  admin/data/sql/migrations/20200904145504.undo.create-results-net-con-eff-type-lookup.sql
  admin/data/sql/migrations/20200904145510.do.create-results-browser-family-lookup.sql
  admin/data/sql/migrations/20200904145510.undo.create-results-browser-family-lookup.sql
  admin/data/sql/migrations/20200904145520.do.create-results-os-lookup.sql
  admin/data/sql/migrations/20200904145520.undo.create-results-os-lookup.sql
  admin/data/sql/migrations/20200904145620.do.create-results-device-orientation-lookup.sql
  admin/data/sql/migrations/20200904145620.undo.create-results-device-orientation-lookup.sql
  admin/data/sql/migrations/20200904145650.do.create-results-user-device.sql
  admin/data/sql/migrations/20200904145650.undo.create-results-user-device.sql
  admin/data/sql/migrations/20200904146650.do.create-check-result-table.sql
  admin/data/sql/migrations/20200904146650.undo.create-check-result-table.sql
  admin/data/sql/migrations/20200904146750.do.create-answers-table.sql
  admin/data/sql/migrations/20200904146750.undo.create-answers-table.sql
  admin/data/sql/migrations/20200904146850.do.create-user-input-table.sql
  admin/data/sql/migrations/20200904146850.undo.create-user-input-table.sql
  admin/data/sql/migrations/20200910145708.do.create-event-table.sql
  admin/data/sql/migrations/20200910145708.undo.create-event-table.sql
  admin/data/sql/migrations/20200911160700.do.add-results-documentation.sql
  admin/data/sql/migrations/20200911160700.undo.add-results-documentation.sql
  admin/data/sql/migrations/20200911160710.do.add-results-triggers.sql
  admin/data/sql/migrations/20200911160710.undo.add-results-triggers.sql
  admin/data/sql/migrations/ZZZZ0904135743.do.populate-user-input-type-lookup.sql
  admin/data/sql/migrations/ZZZZ0904135743.undo.populate-user-input-type-lookup.sql
Labels: CI Enabled, QA Not required, Requires Tech Sign Off, Reviewed & approved, Signed Off

#1719 Bug/43510 retro input assistant pt3
  admin/data/sql/migrations/20200914170755.do.merge-input-assistant-info.sql
  admin/data/sql/migrations/20200914170755.undo.merge-input-assistant-info.sql
  admin/data/sql/migrations/20200914170801.do.drop-column-retro-input-assistant-reason.sql
  admin/data/sql/migrations/20200914170801.undo.drop-column-retro-input-assistant-reason.sql
  admin/services/data-access/retro-input-assistant.data.service.js
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/step_definitions/retro_input_steps.rb
  test/pupil-hpa/features/step_definitions/retro_input_steps.rb
  test/pupil-hpa/features/support/received_check_decompressor.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Tested

#1720 updated invalid check sequence diagram
  design/pupil-state/Check - Invalid received check.png
Labels: CI NOT Required, QA Not required, Signed Off

#1723 Feature/43537 ps report data sync answers
  admin/config.js
  admin/data/sql/migrations/20200914205743.do.populate-user-input-type-lookup.sql
  admin/data/sql/migrations/20200914205743.undo.populate-user-input-type-lookup.sql
  admin/data/sql/migrations/20200921154153.do.add-functions-user.js
  admin/data/sql/migrations/20200921154153.undo.add-functions-user.js
  admin/data/sql/migrations/20200921155139.do.func-user-permissions.js
  admin/data/sql/migrations/20200921155139.undo.func-user-permissions.js
  deploy/sql/config.js
  func-consumption/check-marker/function.json
  func-consumption/disable-functions.env
  functions-app/config.js
  functions-app/sync-results-to-sql/function.json
  functions-app/sync-results-to-sql/index.js
  functions-app/sync-results-to-sql/service/data-access/data.service.js
  functions-app/sync-results-to-sql/service/results.service.js
  functions-app/sync-results-to-sql/service/results.service.spec.js
  functions-app/sync-results-to-sql/v1.js
  functions-app/sync-results-to-sql/v1.spec.js
  tslib/src/functions/check-marker/check-marker.v1.spec.ts
  tslib/src/functions/check-marker/check-marker.v1.ts
  tslib/src/functions/check-marker/models.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1726 feature/43523 mtc_admin.hdf indexes
  admin/data/sql/migrations/20200928103917.do.hdf-indexes.sql
  admin/data/sql/migrations/20200928103917.undo.hdf-indexes.sql
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested
