Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2020-12, with the labels that each got.

#1753 Feature/44430 ps report update status on hard failure
  admin/package.json
  docs/environment-variables.md
  func-consumption/package.json
  func-consumption/school-results-cache/function.json
  func-consumption/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/check-complete/check-complete.component.ts
  pupil-spa/src/app/instructions/instructions.component.ts
  pupil-spa/src/app/out-of-time/out-of-time.component.ts
  pupil-spa/src/app/session-expired/session-expired.component.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.ts
  pupil-spa/src/app/warmup-intro/warmup-intro.component.ts
  test/admin-hpa/features/data_sync.feature
  test/admin-hpa/features/step_definitions/data_sync_steps.rb
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/pupil-hpa/features/complete_page.feature
  test/pupil-hpa/features/feedback.feature
  test/pupil-hpa/features/step_definitions/complete_page_steps.rb
  tslib/package.json
  tslib/src/common/logger.ts
  tslib/src/config.ts
  tslib/src/functions-throttled/sync-results-to-sql/index.ts
  tslib/src/functions-throttled/sync-results-to-sql/processing-failure.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/processing-failure.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.factory.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.ts
  tslib/src/functions/check-started/check-started.service.ts
  tslib/src/functions/pupil-feedback/feedback.service.spec.ts
  tslib/src/functions/pupil-feedback/feedback.service.ts
  tslib/src/functions/school-pin-generator/max-attempts-calculator.spec.ts
  tslib/src/functions/util-submit-check/index.ts
  tslib/src/sql/sql.service.ts
  tslib/src/tests-integration/redis-service.integration.spec.ts
  tslib/src/tests-integration/sql.service.integration.spec.ts
  tslib/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1754 Feature/44593 App Insights - add functions and support for one instance per system
  admin/config.js
  admin/helpers/app-insights.js
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-api/src/config.ts
  pupil-api/src/helpers/app-insights.ts
  pupil-api/yarn.lock
  tslib/package.json
  tslib/src/azure/app-insights.ts
  tslib/src/config.ts
  tslib/src/functions-throttled/school-import/school-mapper.spec.ts
  tslib/src/functions/check-marker/index.ts
  tslib/src/functions/check-notifier-batch/index.ts
  tslib/src/functions/check-receiver/index.ts
  tslib/src/functions/check-validator/index.ts
  tslib/src/functions/pupil-feedback/index.ts
  tslib/src/functions/pupil-login/index.ts
  tslib/src/functions/pupil-prefs/index.ts
  tslib/src/functions/school-pin-generator/index.ts
  tslib/src/functions/util-diag/index.ts
  tslib/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1757 Add docker build jobs to circleci
  .circleci/config.yml
  .disabled.travis.yml
  admin-assets/copy-assets.sh
Labels: CI Enabled, Requires Tech Sign Off, Signed Off

#1756 feature/44064 update cookie table
  admin/views/cookies-mtc.ejs
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  test/pupil-hpa/features/cookies.feature
  test/pupil-hpa/features/step_definitions/cookies_steps.rb
  test/pupil-hpa/features/support/env.rb
  test/pupil-hpa/features/support/functions_helper.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1760 Increase request timeout when asking Azure to create a database
  db/config.js
  db/engine/createDatabase.js
Labels: CI Enabled, Reviewed & approved

#1766 Feature/44763 setup users schools for demo | Architecture diagrams in draw.io format
  admin/bin/generate-pupil-data-for-all-schools.js
  docs/architecture/MTC ETL & Analysis DB.drawio
  docs/architecture/MTC Functional Architecture.drawio
Labels: CI NOT Required, QA Not required, Requires Tech Sign Off, Reviewed & approved

#1758 bug/44702 add node version support to service bus deploy util
  deploy/service-bus/.nvmrc
  deploy/service-bus/package.json
Labels: CI Enabled, QA Not required, Requires Tech Sign Off, Signed Off

#1771 Feature/44776 test support api
  func-consumption/package.json
  func-consumption/util-test-support-api/function.json
  func-consumption/yarn.lock
  func-throttled/package.json
  tslib/package.json
  tslib/src/config.ts
  tslib/src/functions/util-test-support-api/README.md
  tslib/src/functions/util-test-support-api/index.ts
  tslib/src/functions/util-test-support-api/school-api.ts
  tslib/src/functions/util-test-support-api/user-api.ts
  tslib/yarn.lock
Labels: CI Enabled, QA Not required, Requires Tech Sign Off, Signed Off, Testing

#1776 Fix
  func-throttled/ps-report-1-list-schools/function.json
  tslib/src/functions-throttled/ps-report-1-list-schools/index.ts
Labels: CI Enabled, Requires Tech Sign Off, Signed Off

#1770 feature/44764 - analysis schema, role and permissions
  db/migrations/schema/20201210133428.do.analysis-schema.sql
  db/migrations/schema/20201210133428.undo.analysis-schema.sql
  db/migrations/user-permissions/20201210142954.do.analysis-role-permissions.sql
  db/migrations/user-permissions/20201210142954.undo.analysis-role-permissions.sql
  db/migrations/user/20201210142926.do.create-analysis-role.sql
  db/migrations/user/20201210142926.undo.create-analysis-role.sql
  db/misc/20201210144200.create-analysis-users.sql
  db/misc/readme.md
Labels: CI Enabled, Requires Tech Sign Off, Signed Off, Tested

#1782 Feature/44856 chore patch rollup
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  load-test/yarn.lock
  pupil-api/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: CI Enabled, QA: regression only, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1781 feature/44679 app insights tweaks
  tslib/src/functions/check-marker/index.ts
  tslib/src/functions/check-notifier-batch/index.ts
  tslib/src/functions/check-receiver/index.ts
  tslib/src/functions/check-validator/index.ts
  tslib/src/functions/pupil-feedback/index.ts
  tslib/src/functions/pupil-login/index.ts
  tslib/src/functions/pupil-prefs/index.ts
  tslib/src/functions/school-pin-generator/index.ts
  tslib/src/functions/util-diag/index.ts
  tslib/src/functions/util-school-pin-sampler/index.ts
Labels: CI Enabled, QA: regression only, Requires Tech Sign Off, Signed Off, Tested
