Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2020-08, with the labels that each got.

#1700 Feature/42672 remove db check started at
  admin/data/sql/migrations/20200726095136.do.update-check-diagnostic-view.sql
  admin/data/sql/migrations/20200726095136.undo.update-check-diagnostic-view.sql
  admin/data/sql/migrations/20200727150905.do.drop-check-startedat.sql
  admin/data/sql/migrations/20200727150905.undo.drop-check-startedat.sql
  functions-app/calculate-score-v2/check-window.data.service.js
  functions-app/calculate-score-v2/function.json
  functions-app/calculate-score-v2/index.js
  functions-app/calculate-score-v2/pupil-results-diagnostic-cache.data.service.js
  functions-app/calculate-score-v2/schools-scores.data.service.js
  functions-app/calculate-score-v2/v1.js
  functions-app/calculate-score-v2/v1.spec.js
Labels: CI Enabled, Ready for review, Requires Tech Sign Off, Signed Off, Tested

#1699 Feature/42566 retro input assist pt2
  admin/controllers/access-arrangements.js
  admin/controllers/retro-input-assistant.js
  admin/error-types/access-arrangements-not-editable-error.js
  admin/lib/consts/access-arrangements-view-mode.js
  admin/lib/errors/retro-input-assistant.js
  admin/lib/validator/retro-input-assistant-validator.js
  admin/services/access-arrangements.service.js
  admin/services/check-window-v2.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/controllers/retro-input-assistant.spec.js
  admin/spec/back-end/lib/validator/retro-input-assistant-validator.spec.js
  admin/spec/back-end/service/access-arrangements.service.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/access-arrangements/retro-add-input-assistant.ejs
  admin/views/access-arrangements/select-access-arrangements.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1703 add missing retro tests
  test/admin-hpa/features/retro_input_assistance.feature
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/step_definitions/retro_input_steps.rb
  test/admin-hpa/features/support/page_objects/access_arrangements_page.rb
  test/admin-hpa/features/support/page_objects/retro_input_page.rb
  test/admin-hpa/features/support/page_objects/select_access_arrangements_page.rb
  test/pupil-hpa/features/step_definitions/retro_input_steps.rb
  test/pupil-hpa/features/support/page_objects/access_arrangements_page.rb
  test/pupil-hpa/features/support/page_objects/select_access_arrangements_page.rb
Labels: CI Enabled, Tested, ruby

#1705 fix broken group test
  test/admin-hpa/features/step_definitions/groups_steps.rb
Labels: CI Enabled, Ready for review, Tested, ruby

#1706 Chore/update deps
  admin/package.json
  admin/spec/front-end/print-popup.spec.js
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  functions-app/package.json
  functions-app/yarn.lock
  load-test/package.json
  load-test/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  pupil-spa/package.json
  pupil-spa/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Signed Off, Tested
