Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2020-01, with the labels that each got.

#1459 fixed failing test
  admin/spec/back-end/lib/validator/pupil-validator.spec.js
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
Labels: CI Enabled, ruby

#1460 automation/fix-failing-test
  test/admin-hpa/features/generate_pupil_pins.feature
Labels: CI Enabled, ruby

#1455 Feature/38591 pupiluuid lookup
  admin/services/check-start.service/check-start.service.js
  admin/services/data-access/check-form-allocation.data.service.js
  admin/services/prepare-check.service.js
  admin/services/redis-key.service.js
  admin/spec/back-end/service/prepare-check.service.spec.js
  functions/lib/prepared-check-schema-validator.js
  test/pupil-hpa/features/pupil_api.feature
  test/pupil-hpa/features/step_definitions/pupil_api.rb
  tslib/src/functions/pupil-prefs/pupil-prefs.service.ts
Labels: CI Enabled, Reviewed & approved, Tested

#1462 Add uuid and remove id
  test/pupil-hpa/features/support/helpers.rb
Labels: CI Enabled, Tested, ruby

#1463 automation/fix-group-test
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/support/page_objects/generate_pins_overview_page.rb
  test/admin-hpa/features/support/page_objects/view_and_custom_print_live_check_page.rb
Labels: CI Enabled, ruby

#1456 Feature/38670 bulk load test data
  admin/data/sql/seed-sql.js
  deploy/load-test/do.sh
  deploy/load-test/vso-build.yml
  deploy/sql/.gitignore
  deploy/sql/config.js
  deploy/sql/dummy-data/pupil.js
  deploy/sql/dummy-data/school.js
  deploy/sql/dummy-data/teacher.js
  deploy/sql/log.service.js
  deploy/sql/logger.js
  deploy/sql/old-shell-scripts/migrate-db.sh
  deploy/sql/old-shell-scripts/readme.md
  deploy/sql/old-shell-scripts/seed-db.sh
  deploy/sql/old-shell-scripts/vso-migrate-down.sh
  deploy/sql/old-shell-scripts/vso-migrate-up.sh
  deploy/sql/package.json
  deploy/sql/readme.md
  deploy/sql/schema-WIP/create-database.js
  deploy/sql/schema-WIP/create-migration.js
  deploy/sql/schema-WIP/create-seed.js
  deploy/sql/schema-WIP/migrate.js
  deploy/sql/schema-WIP/migrations/20191218162903.do.example-baseline.sql
  deploy/sql/schema-WIP/migrations/20191218162903.undo.example-baseline.sql
  deploy/sql/schema-WIP/migrations/20191219084400.do.data-defaults.sql
  deploy/sql/schema-WIP/readme.md
  deploy/sql/schema-WIP/seed.js
  deploy/sql/schema-WIP/sql.service.js
  deploy/sql/yarn.lock
  infra/readme.md
  load-test/prep-up.sh
  load-test/scenarios/generate-pins-try-it-out/01-teacherLogins.csv
  load-test/scenarios/generate-pins-try-it-out/teacher-generate-pins-try-it-out.jmx
  tslib/src/functions/util-submit-check/index.ts
Labels: DNM - WIP

#1467 Declared eslint file only for admin and functions project
  admin/.eslintrc
  functions/.eslintrc
Labels: CI Enabled, Ready for review, Requires Tech Sign Off, Signed Off

#1465 Spike/38838 Add SSH support to azure docker images
  admin/Dockerfile
  admin/docker-start.sh
  admin/server.js
  admin/sshd_config
  deploy/sql/old-shell-scripts/readme.md
  deploy/sql/vso-validate-migrations/migrate-db.sh
  deploy/sql/vso-validate-migrations/seed-db.sh
  deploy/sql/vso-validate-migrations/vso-migrate-down.sh
  deploy/sql/vso-validate-migrations/vso-migrate-up.sh
  docker-compose-rabbit.yml
  docker-compose.admin-test.yml
  docker-compose.pupil-test.yml
  docker-compose.web.yml
  pupil-api/Dockerfile
  pupil-api/docker-start.sh
  pupil-api/sshd_config
  pupil-spa/Dockerfile
  pupil-spa/docker-start.sh
  pupil-spa/sshd_config
Labels: CI Enabled, Ready for review

#1464 automation/fix-group-test
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
Labels: CI Enabled, ruby

#1469 chore - remove old test scripts associated to docker
  run-compose-admin-test-suite.sh
  run-compose-pupil-test-suite.sh
Labels: CI Enabled, Ready for review

#1473 removing test as it needs more investigation
  test/pupil-hpa/features/event_auditing.feature
  test/pupil-hpa/features/step_definitions/event_auditing_steps.rb
Labels: CI Enabled, Tested

#1475 Bug/39043 Removed teacher tio link from school homepage
  admin/config.js
  admin/views/school/school-home-v2.ejs
  test/admin-hpa/features/school_landing.feature
  test/admin-hpa/features/step_definitions/school_landing_page_steps.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1468 Feature/37904 Pupil spa component deactivation guard
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/check/check.component.spec.ts
  pupil-spa/src/app/check/check.component.ts
  pupil-spa/src/app/routes/can-exit/can-exit.guard.spec.ts
  pupil-spa/src/app/routes/can-exit/can-exit.guard.ts
  pupil-spa/src/app/routes/logged-in/logged-in.guard.spec.ts
  pupil-spa/src/app/routes/logged-in/logged-in.guard.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1477 Update pin_expiry_steps.rb
  test/pupil-hpa/features/step_definitions/pin_expiry_steps.rb
Labels: CI Enabled, Tested

#1466 Feature/37901 register input question data
  func-consumption/extensions.csproj
  func-consumption/package.json
  pupil-spa/src/app/question/question.component.ts
  pupil-spa/src/app/services/register-input/registerInput.service.spec.ts
  pupil-spa/src/app/services/register-input/registerInput.service.ts
  pupil-spa/src/app/spoken-question/spoken-question.component.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1479 Test support
  admin/controllers/school.js
Labels: CI Enabled, Requires Tech Sign Off, Testing

#1470 Feature/37898 Utilise event timestamp for register input event
  pupil-spa/src/app/practice-question/practice-question.component.spec.ts
  pupil-spa/src/app/practice-question/practice-question.component.ts
  pupil-spa/src/app/question/question.component.html
  pupil-spa/src/app/question/question.component.spec.ts
  pupil-spa/src/app/question/question.component.ts
  pupil-spa/src/app/services/register-input/registerInput.service.spec.ts
  pupil-spa/src/app/services/register-input/registerInput.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1474 bug/39032 check started function - add null guard on prepared check lookup
  tslib/src/functions/check-started/check-started.service.spec.ts
  tslib/src/functions/check-started/check-started.service.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1484 feature/39138 name pin elements on pin list
  admin/views/pupil-pin/view-and-custom-print-pins.ejs
Labels: CI Enabled, Reviewed & approved, Tested

#1471 feature/38990 remove old queues, old function stub app and finish docker script
  deploy/docker/functions-base/push.sh
  functions/package.json
  functions/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off

#1481 Feature/38489 Added audit events for document visibility change
  pupil-spa/src/app/app.component.html
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/page-visibility/page-visibility.component.html
  pupil-spa/src/app/page-visibility/page-visibility.component.scss
  pupil-spa/src/app/page-visibility/page-visibility.component.spec.ts
  pupil-spa/src/app/page-visibility/page-visibility.component.ts
  pupil-spa/src/app/services/audit/auditEntry.ts
  test/pupil-hpa/features/state.feature
  test/pupil-hpa/features/step_definitions/state_steps.rb
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1482 improvements and decompression helper
  test/admin-hpa/README.md
  test/admin-hpa/features/pupil_register.feature
  test/admin-hpa/features/school_landing.feature
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
  test/admin-hpa/features/step_definitions/school_landing_page_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
  test/admin-hpa/features/support/received_check_decompressor.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/pupil-hpa/README.md
  test/pupil-hpa/features/step_definitions/check_steps.rb
  test/pupil-hpa/features/step_definitions/pin_expiry_steps.rb
Labels: CI Enabled, Reviewed & approved, Tested

#1485 feature/39188 - fixing issue with always looking for .env
  test/admin-hpa/README.md
  test/admin-hpa/features/support/received_check_decompressor.rb
Labels: CI Enabled, Ready for review, Tested

#1488 Bug/39235 - fix check form lookup in check marker function
  test/pupil-hpa/features/pin_expiry.feature
  test/pupil-hpa/features/step_definitions/pupil_api.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
  tslib/src/functions/check-marker/check-form.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1490 feature/39241 run local load test from script
  load-test/README.md
  load-test/exec-local.sh
  load-test/scenarios/_2020/live-pin-gen-with-check.jmx
  load-test/scenarios/z_poc/live-pin-gen-with-check.jmx
  load-test/scenarios/z_poc/pin-gen/live-pin-gen.only.jmx
  load-test/scenarios/z_poc/pin-gen/tio-pin-gen.only.jmx
  load-test/scenarios/z_poc/pupil-api.jmx
  load-test/scenarios/z_poc/pupil-auth-function.jmx
  load-test/scenarios/z_poc/pupil-login/_jm5.live.get-pin.login-start-submit.jmx
  load-test/scenarios/z_poc/pupil-login/check-login-start-submit.jmx
Labels: CI Enabled, Ready for review

#1486 39150 - pupil is not removed from pin list
  admin/data/sql/migrations/20200127112400.do.alter-view-vewpupilswithactivelivepins.sql
  admin/data/sql/migrations/20200127112400.undo.alter-view-vewpupilswithactivelivepins.sql
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1489 feature/39240 - reduce speech reader audit entry size
  pupil-spa/src/app/services/speech/speech.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested
