Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2020-11, with the labels that each got.

#1738 feature/44207 - fix pipeline fails
  test/admin-hpa/features/school_import.feature
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/upload_pupil_census.feature
Labels: CI Enabled, Ready to merge, Reviewed & approved, Tested, ruby

#1733 Feature/43342 ps report data sync
  admin/data/sql/migrations/20201013162002.do.update-function-user-permissions.js
  admin/data/sql/migrations/20201013162002.undo.update-function-user-permissions.js
  admin/data/sql/migrations/20201015195026.do.update-userdevice-table.sql
  admin/data/sql/migrations/20201015195026.undo.update-userdevice-table.sql
  admin/views/tech-support/check-view.ejs
  bin/run-all-unit-tests.sh
  bin/utf16-sha256sum/index.js
  bin/utf16-sha256sum/package.json
  bin/utf16-sha256sum/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-spa/package.json
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/login/login.component.spec.ts
  pupil-spa/src/app/login/login.component.ts
  pupil-spa/src/app/services/device/device.service.spec.ts
  pupil-spa/src/app/services/device/device.service.ts
  pupil-spa/yarn.lock
  tslib/.snyk
  tslib/package.json
  tslib/src/functions-throttled/sync-results-to-sql/index.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.sync.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/user-agent-parser.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/user-agent-parser.ts
  tslib/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1735 feature/44112 switch census function to use functions sql user
  admin/README.md
  admin/data/sql/migrations/20201026153716.do.remove-census-user.js
  admin/data/sql/migrations/20201026153716.undo.remove-census-user.js
  admin/data/sql/migrations/20201026161418.do.grant-function-user-census-perms.js
  admin/data/sql/migrations/20201026161418.undo.grant-function-user-census-perms.js
  tslib/src/functions-throttled/census-import/index.ts
  tslib/src/functions-throttled/school-import/index.ts
  tslib/src/sql/pool.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Signed Off, Tested

#1734 school table - make leaCode & estabCode non nullable integers
  admin/bin/generate-migration-from-schooldata.js
  admin/bin/generate-pupil-data-for-one-school.js
  admin/data/sql/manual/20200211-add-test-school-data.sql
  admin/data/sql/migrations/20201019132931.do.school.leacode-estabcode-non-null.sql
  admin/data/sql/migrations/20201019132931.undo.school.leacode-estabcode-non-null.sql
  admin/data/sql/migrations/20201019141448.do.remove-gias-staging-table.sql
  admin/data/sql/migrations/20201019141448.undo.remove-gias-staging-table.sql
  deploy/sql/dummy-data/all.js
  functions-app/report-psychometrician/spec/anomaly-file-report.service.spec.js
  functions-app/report-psychometrician/spec/mocks/school.js
  functions-app/report-psychometrician/spec/psychometrician-report.service.spec.js
  test/admin-hpa/data/null-estab-data.csv
  test/admin-hpa/data/null-leacode-data.csv
  test/admin-hpa/data/null-names-data.csv
  test/admin-hpa/data/null-urn-data.csv
  test/admin-hpa/features/school_import.feature
  test/admin-hpa/features/step_definitions/school_import_steps.rb.rb
  tslib/src/functions-throttled/school-import/data-access/ISchoolRecord.ts
  tslib/src/functions-throttled/school-import/data-access/school.data.service.ts
  tslib/src/functions-throttled/school-import/predicates.spec.ts
  tslib/src/functions-throttled/school-import/predicates.ts
  tslib/src/functions-throttled/school-import/school-import.service.spec.ts
  tslib/src/functions-throttled/school-import/school-import.service.ts
  tslib/src/functions-throttled/school-import/school-mapper.spec.ts
  tslib/src/functions-throttled/school-import/school-mapper.ts
  tslib/src/functions/gias-sync/gias-bulk-import.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1742 Feature/44247 yaml validate migrations build
  deploy/build-defs/validate-pr-db-migrations.yml
  deploy/sql/vso-validate-migrations/migrate-db.sh
  deploy/sql/vso-validate-migrations/seed-db.sh
  deploy/sql/vso-validate-migrations/vso-migrate-down.sh
  deploy/sql/vso-validate-migrations/vso-migrate-up.sh
Labels: CI Enabled

#1725 feature/40901-ie11 browserstack integration
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/Rakefile
  test/admin-hpa/config/browserstack.yml
  test/admin-hpa/config/cucumber.yml
  test/admin-hpa/features/add_pupil.feature
  test/admin-hpa/features/declaration_submitted.feature
  test/admin-hpa/features/phase_banner.feature
  test/admin-hpa/features/restarts.feature
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/breadcrumbs_steps.rb
  test/admin-hpa/features/support/browserstack_driver_helper.rb
  test/admin-hpa/features/support/hooks.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  test/pupil-hpa/Rakefile
  test/pupil-hpa/config/cucumber.yml
  test/pupil-hpa/features/support/browserstack_driver_helper.rb
  test/pupil-hpa/features/support/hooks.rb
Labels: CI Enabled, Tested, ruby

#1746 removing unused gem
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
Labels: CI Enabled, Ready for review, Requires Tech Sign Off, Signed Off, Tested, ruby

#1748 remove references
  test/admin-hpa/Rakefile
  test/pupil-hpa/Rakefile
Labels: CI Enabled, Reviewed & approved, Tested, ruby

#1743 Bug/44168 function log outputs connectionPool instance object
  tslib/src/functions-throttled/census-import/index.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1744 bug/44173 delete blob after upload, not container
  admin/services/pupil-census-processing.service.js
  admin/services/pupil-census.service.js
  admin/spec/back-end/service/pupil-census-processing.service.spec.js
  admin/spec/back-end/service/pupil-census.service.spec.js
  test/admin-hpa/features/upload_pupil_census.feature
  tslib/src/azure/storage-helper.ts
  tslib/src/functions-throttled/census-import/v1.spec.ts
  tslib/src/functions-throttled/census-import/v1.ts
Labels: CI Enabled, Ready to merge, Requires Tech Sign Off, Reviewed & approved, Tested

#1749 bug/44343 db not deleting via Azure CLI for PR migration checks
  .gitignore
  deploy/build-defs/validate-pr-db-migrations.yml
Labels: CI Enabled, QA Not required, Requires Tech Sign Off, Signed Off

#1737 Feature/43538 data sync user input
  admin/bin/dump-browser-stats.js
  admin/package.json
  admin/spec/front-end/session-expiry.spec.js
  admin/tests-integration/sql.service.spec.js
  admin/yarn.lock
  db/migrations/core-data/20201030104251.do.add-pen-input-type.sql
  db/migrations/core-data/20201030104251.undo.add-pen-input-type.sql
  db/migrations/user-permissions/20201109145419.do.grant-update-to-functions-user.js
  db/migrations/user-permissions/20201109145419.undo.grant-update-to-functions-user.js
  pupil-spa/gen_config.sh
  pupil-spa/package.json
  pupil-spa/src/app/check/check.component.ts
  pupil-spa/src/app/loading/loading.component.ts
  pupil-spa/src/app/practice-question/practice-question.component.spec.ts
  pupil-spa/src/app/practice-question/practice-question.component.ts
  pupil-spa/src/app/question/question.component.html
  pupil-spa/src/app/question/question.component.spec.ts
  pupil-spa/src/app/question/question.component.ts
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/services/pupil-prefs/pupil-prefs.service.ts
  pupil-spa/src/app/services/register-input/registerInput.service.spec.ts
  pupil-spa/src/app/services/register-input/registerInput.service.ts
  pupil-spa/src/app/spoken-practice-question/spoken-practice-question.component.spec.ts
  pupil-spa/src/app/spoken-practice-question/spoken-practice-question.component.ts
  pupil-spa/src/app/spoken-question/spoken-question.component.spec.ts
  pupil-spa/src/app/spoken-question/spoken-question.component.ts
  pupil-spa/src/app/warmup-loading/warmup-loading.component.ts
  pupil-spa/src/assets/shared-styles/elements/_virtual-keyboard.scss
  test/admin-hpa/features/data_sync.feature
  test/admin-hpa/features/step_definitions/data_sync_steps.rb
  test/admin-hpa/features/step_definitions/declaration_submitted_steps.rb
  test/admin-hpa/features/step_definitions/pupil_status_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/features/support/functions_helper.rb
  test/admin-hpa/features/support/request_helper.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/pupil-hpa/features/registered_inputs.feature
  test/pupil-hpa/features/step_definitions/registered_inputs_steps.rb
  test/pupil-hpa/features/support/page_objects/check_page.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
  tslib/src/functions-throttled/sync-results-to-sql/event.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/event.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/index.ts
  tslib/src/functions-throttled/sync-results-to-sql/models.ts
  tslib/src/functions-throttled/sync-results-to-sql/prepare-answers-and-inputs.data.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/prepare-answers-and-inputs.data.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/prepare-event.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/prepare-event.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/question.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/question.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results-data.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/user-input.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/user-input.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1751 feature/44159 switch to default of typescript in admin app
  admin/package.json
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1752 ci: validate ruby gems
  .circleci/config.yml
  deploy/docker/circleci-node-multi/Dockerfile
  deploy/docker/circleci-node-multi/README.md
  deploy/docker/circleci-ruby/Dockerfile
  deploy/docker/circleci-ruby/README.md
  test/admin-hpa/Rakefile
  test/admin-hpa/features/support/sql_db_helper.rb
  test/admin-hpa/rerun.txt
  test/pupil-hpa/Rakefile
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Tested
