Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2020-06, with the labels that each got.

#1649 Bug/3643 csp error for loading font
  admin-assets/Dockerfile
  admin-assets/nginx/default.conf
  admin/helpers/browserSecurity.js
Labels: CI Enabled, Ready for review, Requires Tech Sign Off, Signed Off, Tested

#1654 Update security_spec.rb
  api_tests/spec/security_spec.rb
Labels: CI Enabled, Ready for review, Reviewed & approved, Tested

#1655 Feature/41755 update github api credential method
  .travis.yml
  deploy/should-it-build.js
Labels: CI Enabled, QA Not required, Requires Tech Sign Off, Reviewed & approved, Signed Off

#1658 update required ruby version
  api_tests/Gemfile
  api_tests/Gemfile.lock
  api_tests/README.md
  test/admin-hpa/Dockerfile
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/README.md
  test/pupil-hpa/Dockerfile
  test/pupil-hpa/Gemfile
  test/pupil-hpa/README.md
Labels: CI Enabled, Ready for review, Requires Tech Sign Off, Signed Off, Tested, ruby

#1644 Feature/39556 tech support check summary
  admin/README.md
  admin/config.js
  admin/controllers/tech-support-home.js
  admin/controllers/tech-support.js
  admin/data/sql/migrations/003.do.create-admin-app-user.js
  admin/data/sql/migrations/003.undo.create-admin-app-user.js
  admin/data/sql/migrations/20200422145720.undo.create-techsupport-role.sql
  admin/data/sql/migrations/20200519164700.do.create-techsupport-sql-user.js
  admin/data/sql/migrations/20200519164700.undo.create-techsupport-sql-user.js
  admin/data/sql/migrations/20200521141936.do.grant-select-techsupport.js
  admin/data/sql/migrations/20200521141936.undo.grant-select-techsupport.js
  admin/data/sql/migrations/20200601114033.do.alter-vewcheckdiagnostic.sql
  admin/data/sql/migrations/20200601114033.undo.alter-vewcheckdiagnostic.sql
  admin/lib/deep-freeze.js
  admin/lib/validator/common/uuid-validator.js
  admin/package.json
  admin/routes/tech-support.js
  admin/services/check-diagnostic.service.js
  admin/services/data-access/check-diagnostic.data.service.js
  admin/services/data-access/payload.data.service.js
  admin/services/data-access/sql.pool.service.js
  admin/services/data-access/sql.role-connection.builder.js
  admin/services/data-access/sql.service.js
  admin/spec/back-end/controllers/tech-support.spec.js
  admin/spec/back-end/lib/deep-freeze.js
  admin/spec/back-end/lib/validator/common/uuid-validator.spec.js
  admin/spec/back-end/service/check-diagnostic.service.spec.js
  admin/tests-integration/sql.pool.service.spec.js
  admin/tests-integration/sql.role-connection.builder.spec.js
  admin/tests-integration/sql.service.spec.js
  admin/tests-integration/test-support/create-check.js
  admin/tests-integration/vew-check-diagnostic.spec.js
  admin/views/tech-support/check-view.ejs
  admin/views/tech-support/home.ejs
  test/admin-hpa/features/step_definitions/tech_support_steps.rb
  test/admin-hpa/features/support/page_objects/check_view_page.rb
  test/admin-hpa/features/support/page_objects/tech_support_page.rb
  test/admin-hpa/features/support/received_check_decompressor.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/admin-hpa/features/tech_support.feature
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1665 Snyk ruby updates
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
Labels: CI Enabled, Tested, ruby

#1667 bug/lint fixes for master
  admin/tests-integration/test-support/create-check.js
  admin/tests-integration/vew-check-diagnostic.spec.js
Labels: CI Enabled, Reviewed & approved, expedited

#1666 [admin] fix typography
  admin/views/service-manager/sce-add-school.ejs
Labels: CI Enabled, Ready for review

#1663 Bug/39577 ie11 pupil status page fix
  admin/assets/javascripts/pupil-filter-name.js
  admin/assets/javascripts/pupil-status-selection.js
  admin/assets/javascripts/pupil-status.js
  admin/config/sql.config.js
  admin/config/sql.readonly.config.js
  admin/package.json
  admin/services/headteacher-declaration.service.js
  admin/spec/front-end/pupil-filter-name.spec.js
  admin/views/pupil-pin/generate-pins-list.ejs
  admin/views/pupil-pin/view-and-custom-print-pins.ejs
  admin/views/pupil-register/pupils-list.ejs
  admin/views/pupil-status/view-pupil-status.ejs
  admin/yarn.lock
  test/pupil-hpa/Gemfile.lock
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1664 Bug/39438 edit link whitespace
  admin/views/hdf/review-pupil-details.ejs
  pupil-api/yarn.lock
Labels: CI Enabled, Reviewed & approved, Signed Off

#1669 Feature/41926 Run admin docker app from tsc output
  admin/Dockerfile
  admin/NCATools_EduBase_20180604.txt
  admin/pm2.json
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1668 Feature/40948 results generator refactor for 2020 dataset changes 3 of 3
  admin/controllers/school.js
  functions-app/census-import/v1.js
  functions-app/config.js
  functions-app/disable-functions.env
  functions-app/lib/get-env.js
  functions-app/lib/get-env.spec.js
  functions-app/lib/redis-cache.service.js
  functions-app/lib/table-sorting.js
  functions-app/package.json
  functions-app/poison-replay-completed-checks/ideas.js
  functions-app/report-psychometrician-generate-staging-file/service/data.service.js
  functions-app/school-results-load-cache/function.json
  functions-app/school-results-load-cache/index.js
  functions-app/school-results-load-cache/readme.md
  functions-app/school-results-load-cache/services/data-access/result.data.service.js
  functions-app/school-results-load-cache/services/pupil-identification-flag.service.js
  functions-app/school-results-load-cache/services/redis-key.service.js
  functions-app/school-results-load-cache/services/result.service.js
  functions-app/school-results-load-cache/services/result.service.spec.js
  functions-app/school-results-load-cache/services/school.service.js
  functions-app/school-results-load-cache/v1.js
  functions-app/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1673 Bug/41962 missing check breaks json payload rendering
  admin/controllers/tech-support.js
  admin/services/data-access/payload.data.service.js
  admin/services/payload.service.js
  admin/spec/back-end/service/payload.service.spec.js
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1671 Feature/31577 school staff view updated unavailable hdf message
  admin/views/school/school-home.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1677 commit changes to gemfile.lock
  test/admin-hpa/Gemfile.lock
  test/pupil-hpa/Gemfile.lock
Labels: CI Enabled, Ready for review, Tested, ruby
