Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2021-01, with the labels that each got.

#1790 Chore/44946 axios bump
  admin/package.json
  admin/spec/back-end/lib/validator/pupil-validator.spec.js
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  load-test/package.json
  tslib/package.json
  tslib/yarn.lock
Labels: CI Enabled, QA: regression only, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1777 bug/44805 add masking permission for function user
  db/migrations/user-permissions/20201211161750.do.unmask-function-user.js
  db/migrations/user-permissions/20201211161750.undo.unmask-function-user.js
  test/admin-hpa/Rakefile
  test/pupil-hpa/Rakefile
Labels: CI Enabled, QA: regression only, Requires Tech Sign Off, Reviewed & approved, Tested

#1775 feature/44806 - rename function, consolidate util flag into one setting
  func-consumption/util-school-pin-http-service/function.json
  tslib/src/config.ts
  tslib/src/functions/util-school-pin-http-service/index.ts
  tslib/src/functions/util-school-pin-sampler/index.ts
  tslib/src/functions/util-submit-check/index.ts
Labels: CI Enabled, QA: regression only, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1759 44721 Complete port to new check result table
  admin/services/ctf-service/ctf.service.js
  admin/services/ctf-service/ctf.service.spec.js
  admin/services/data-access/result.data.service.js
  admin/services/result.service.js
  db/migrations/core-data/20201206072327.do.drop-mtc-admin-check-score-trigger.sql
  db/migrations/core-data/20201206072327.undo.drop-mtc-admin-check-score-trigger.sql
  db/migrations/core-data/20201206072328.do.drop-mtc-admin-check-score.sql
  db/migrations/core-data/20201206072328.undo.drop-mtc-admin-check-score.sql
  db/migrations/user-permissions/20201206070709.do.allow-admin-app-user-to-see-results.js
  db/migrations/user-permissions/20201206070709.undo.allow-admin-app-user-to-see-results.js
  load-test/scenarios/2019/pupil-login-check/undo-generate-pupil-load-test-data.sql
  test/admin-hpa/Rakefile
  test/admin-hpa/features/data_sync.feature
  test/admin-hpa/features/results.feature
  test/admin-hpa/features/step_definitions/check_window_validation_steps.rb
  test/admin-hpa/features/step_definitions/result_page_steps.rb
  test/admin-hpa/features/step_definitions/school_landing_page_steps.rb
  test/admin-hpa/features/step_definitions/sign_in_steps.rb
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/features/support/functions_helper.rb
  test/admin-hpa/features/support/helpers.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/complete_page.rb
  test/admin-hpa/features/support/page_objects/declaration_confirm_page.rb
  test/admin-hpa/features/support/page_objects/declaration_review_pupils_page.rb
  test/admin-hpa/features/support/page_objects/results_page.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
  test/admin-hpa/features/support/request_helper.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/pupil-hpa/Rakefile
  test/pupil-hpa/features/registered_inputs.feature
  test/pupil-hpa/features/step_definitions/registered_inputs_steps.rb
  test/pupil-hpa/features/support/azure_table_helper.rb
  test/pupil-hpa/features/support/env.rb
  test/pupil-hpa/features/support/page_objects/complete_page.rb
  tslib/src/caching/redis-key.service.ts
  tslib/src/caching/redis-service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.ts
  tslib/src/functions/school-results-cache/services/result.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Signed Off, Tested

#1783 Feature/44783 ps report func 2
  admin/services/data-access/pupil-restart.data.service.js
  admin/spec/back-end/lib/validator/check-window-v2/check-window-add-validator.spec.js
  admin/spec/back-end/service/data-access/pupil-restart.data.service.spec.js
  deploy/service-bus/queues-topics.json
  docs/diagrams/psychometric-report-generation.png
  docs/messaging/message-schemas.md
  docs/psychometric-report-data-sourcing.md
  func-consumption/gulpfile.js
  func-consumption/package.json
  func-consumption/yarn.lock
  func-throttled/disable-functions.env
  func-throttled/gulpfile.js
  func-throttled/package.json
  func-throttled/ps-report-2-pupil-data/function.json
  func-throttled/sync-results-to-sql/function.json
  func-throttled/yarn.lock
  tslib/package.json
  tslib/src/functions-throttled/ps-report-2-pupil-data/index.ts
  tslib/src/functions-throttled/ps-report-2-pupil-data/models.ts
  tslib/src/functions-throttled/ps-report-2-pupil-data/ps-report.data.service.spec.ts
  tslib/src/functions-throttled/ps-report-2-pupil-data/ps-report.data.service.ts
  tslib/src/functions-throttled/ps-report-2-pupil-data/ps-report.service.spec.ts
  tslib/src/functions-throttled/ps-report-2-pupil-data/ps-report.service.ts
  tslib/src/functions-throttled/ps-report-2-pupil-data/readme.md
  tslib/src/functions/check-marker/index.ts
  tslib/src/functions/util-school-pin-http-service/index.ts
  tslib/yarn.lock
Labels: CI Enabled, QA: regression only, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1784 Feature/44820 document check payload and check events
  docs/messaging/check-submission/check-payload.json
  docs/messaging/check-submission/readme.md
  docs/messaging/message-schemas.md
  func-consumption/.gitignore
  func-consumption/extensions.csproj
  func-consumption/util-received-check-viewer/function.json
  tslib/src/azure/storage-helper.ts
  tslib/src/functions/check-marker/check-marker.v1.spec.ts
  tslib/src/functions/check-validator/check-validator.v1.spec.ts
  tslib/src/functions/util-received-check-viewer/index.ts
Labels: CI Enabled, QA: regression only, Ready to merge, Requires Tech Sign Off, Reviewed & approved, Signed Off, Testing

#1796 Pupil-api: Update dependencies
  pupil-api/package.json
  pupil-api/src/App.ts
  pupil-api/yarn.lock
  test/pupil-hpa/features/step_definitions/pupil_api.rb
Labels: CI Enabled, QA: regression only, Reviewed & approved, Tested

#1799 [42003] sticky-banner-and-pupil-inconsistent
  admin/assets/javascripts/pupil-filter-name.js
  admin/package.json
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1801 feature/45099 - fixes for the pipeline
  .gitignore
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/features/support/functions_helper.rb
  test/pupil-hpa/features/support/env.rb
Labels: CI Enabled, Ready to merge, Tested, ruby

#1798 Chore/admin deps
  admin/app.js
  admin/assets/javascripts/custom-file-upload.js
  admin/assets/javascripts/gds-cookie-banner.js
  admin/assets/javascripts/gds-cookie-functions.js
  admin/assets/javascripts/gds-cookie-settings.js
  admin/assets/javascripts/gds-print-popup.js
  admin/assets/javascripts/gds-table-sorting.js
  admin/assets/javascripts/global-scripts.js
  admin/assets/javascripts/jquery-modal.js
  admin/assets/javascripts/mtc-autocomplete.js
  admin/assets/javascripts/mtc-check-forms.js
  admin/assets/javascripts/print-popup.js
  admin/assets/javascripts/pupil-access-arrangements-selection.js
  admin/assets/javascripts/pupil-filter-group.js
  admin/assets/javascripts/pupil-filter-name.js
  admin/assets/javascripts/pupil-form.js
  admin/assets/javascripts/pupil-retro-input-assistant.js
  admin/assets/javascripts/pupil-status-selection.js
  admin/assets/javascripts/session-expiry.js
  admin/assets/javascripts/util-checkbox.js
  admin/bin/generate-migration-from-schooldata.js
  admin/controllers/group.js
  admin/helpers/check-form-presenter.js
  admin/helpers/healthcheck.js
  admin/helpers/index.js
  admin/helpers/sce.js
  admin/helpers/table-sorting.js
  admin/helpers/whitelist-dev.js
  admin/lib/azure-upload.js
  admin/lib/deep-freeze.js
  admin/lib/validator/common/date-validator.js
  admin/lib/validator/pupil-validator.js
  admin/lib/validator/sce-school-validator.js
  admin/lib/validator/school-impersonation-validator.js
  admin/package.json
  admin/services/data-access/access-arrangements.data.service.js
  admin/services/data-access/azure-file.data.service.js
  admin/services/data-access/pin-generation.data.service.js
  admin/services/data-access/question-reader-reasons.data.service.js
  admin/services/data-access/redis-cache.service.js
  admin/services/data-access/sce.data.service.js
  admin/services/data-access/sql.service.js
  admin/services/generate-error-csv.service.js
  admin/services/group.service.js
  admin/services/jwt.service.js
  admin/services/pupil-access-arrangements.service.js
  admin/services/sas-token.service.js
  admin/services/score.service.js
  admin/spec/back-end/helpers/check-window-presenter.spec.js
  admin/spec/back-end/lib/error-converter.spec.js
  admin/spec/back-end/service/check-window-v2-update.service.spec.js
  admin/spec/back-end/service/check-window-v2.service.spec.js
  admin/spec/back-end/service/date.service.spec.js
  admin/spec/front-end/pupil-form.spec.js
  admin/spec/front-end/typeahead.spec.js
  admin/tests-integration/sql.service.spec.js
  admin/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1795 feature/44602 replace obsolete app insights package with new one
  pupil-spa/package.json
  pupil-spa/src/app/app.component.ts
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/check-complete/check-complete.component.ts
  pupil-spa/src/app/check/check.component.ts
  pupil-spa/src/app/error-handler.ts
  pupil-spa/src/app/instructions/instructions.component.ts
  pupil-spa/src/app/out-of-time/out-of-time.component.ts
  pupil-spa/src/app/services/app-insights/app-insights.service.ts
  pupil-spa/src/app/session-expired/session-expired.component.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.ts
  pupil-spa/src/app/warmup-intro/warmup-intro.component.ts
  pupil-spa/yarn.lock
Labels: CI Enabled, QA: regression only, Ready to merge, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1797 feature/44680 add build number to func-consumption util diagnostics endpoint
  tslib/src/functions/util-diag/index.ts
Labels: CI Enabled, Requires Tech Sign Off, Signed Off

#1804 feature/45115 - Data team scenarios
  .gitignore
  test/admin-hpa/features/data_sync.feature
  test/pupil-hpa/features/pupil_data_sync.feature
  test/pupil-hpa/features/step_definitions/pupil_data_sync_steps.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, QA: regression only, Ready for review, Requires Tech Sign Off, Signed Off, Tested, ruby

#1803 bug/44250 PR validation databases not being deleted via Azure CLI
  deploy/build-defs/validate-pr-db-migrations.yml
Labels: CI Enabled, QA Not required, Requires Tech Sign Off, Signed Off

#1805 bug/45188 remove app insights wrapper from util-diag function
  tslib/src/functions/util-diag/index.ts
Labels: CI Enabled, QA Not required, Requires Tech Sign Off, Signed Off

#1806 Feature/45159 - Data Team - Inputs scenario
  test/pupil-hpa/features/pupil_data_sync.feature
  test/pupil-hpa/features/step_definitions/pupil_data_sync_steps.rb
Labels: CI Enabled, QA: regression only, Requires Tech Sign Off, Reviewed & approved, Tested, ruby

#1807 bug/45255 - cross platform script for app insights API call to write data annotation
  deploy/app-insights/CreateReleaseAnnotation.ps1
Labels: CI NOT Required, QA Not required, Requires Tech Sign Off, Signed Off

#1809 feature/45307 update data annotation script to include build number and release number/name
  deploy/app-insights/CreateReleaseAnnotation.ps1
Labels: CI NOT Required, QA Not required, Requires Tech Sign Off, Signed Off

#1802 Feature/43328 ps report transformation
  admin/assets/javascripts/session-expiry.js
  admin/spec/front-end/session-expiry.spec.js
  admin/tests-integration/check-form.service.spec.js
  db/migrations/schema-objects/20210128093754.do.drop-mtc-admin-answer.sql
  db/migrations/schema-objects/20210128093754.undo.drop-mtc-admin-answer.sql
  db/migrations/schema-objects/20210128112413.do.drop-table-mtc-admin-psychometrician-report-cache.sql
  db/migrations/schema-objects/20210128112413.undo.drop-table-mtc-admin-psychometrician-report-cache.sql
  db/migrations/schema-objects/20210128113040.do.drop-table-mtc-admin-anomaly-report-cache.sql
  db/migrations/schema-objects/20210128113040.undo.drop-table-mtc-admin-anomaly-report-cache.sql
  deploy/service-bus/queues-topics.json
  docs/diagrams/psychometric-report-generation.graffle
  docs/psychometric-report-data-sourcing.md
  func-consumption/disable-functions.env
  func-consumption/ps-report-transformer/function.json
  tslib/src/common/deep-freeze.ts
  tslib/src/common/json-reviver.ts
  tslib/src/functions-throttled/ps-report-2-pupil-data/models.ts
  tslib/src/functions-throttled/ps-report-2-pupil-data/ps-report.data.service.spec.ts
  tslib/src/functions-throttled/ps-report-2-pupil-data/ps-report.data.service.ts
  tslib/src/functions/ps-report-transformer/index.ts
  tslib/src/functions/ps-report-transformer/mocks/answers.ts
  tslib/src/functions/ps-report-transformer/mocks/check-config.ts
  tslib/src/functions/ps-report-transformer/mocks/check-form.ts
  tslib/src/functions/ps-report-transformer/mocks/check-incomplete.ts
  tslib/src/functions/ps-report-transformer/mocks/check.ts
  tslib/src/functions/ps-report-transformer/mocks/device.ts
  tslib/src/functions/ps-report-transformer/mocks/events.ts
  tslib/src/functions/ps-report-transformer/mocks/pupil-not-attending.ts
  tslib/src/functions/ps-report-transformer/mocks/pupil-who-completed-a-check.ts
  tslib/src/functions/ps-report-transformer/mocks/pupil-with-incomplete-check.ts
  tslib/src/functions/ps-report-transformer/mocks/school.ts
  tslib/src/functions/ps-report-transformer/models.ts
  tslib/src/functions/ps-report-transformer/report-line-answer.class.spec.ts
  tslib/src/functions/ps-report-transformer/report-line-answer.class.ts
  tslib/src/functions/ps-report-transformer/report-line.class.spec.ts
  tslib/src/functions/ps-report-transformer/report-line.class.ts
Labels: CI Enabled, QA: regression only, Reviewed & approved, Tested
