Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2021-06, with the labels that each got.

#1920 spike/47006 queue message lifetime
  _spikes-poc/storage-queue-message-ttl/.funcignore
  _spikes-poc/storage-queue-message-ttl/.gitignore
  _spikes-poc/storage-queue-message-ttl/.vscode/extensions.json
  _spikes-poc/storage-queue-message-ttl/host.json
  _spikes-poc/storage-queue-message-ttl/package.json
  _spikes-poc/storage-queue-message-ttl/tsconfig.json
  _spikes-poc/storage-queue-message-ttl/update-ttl/function.json
  _spikes-poc/storage-queue-message-ttl/update-ttl/index.ts
  _spikes-poc/storage-queue-message-ttl/yarn.lock
  pupil-spa/src/app/services/azure-queue/azure-queue.service.ts
  pupil-spa/src/app/services/azure-queue/azureStorage.ts
Labels: CI Enabled, QA Not required

#1913 Feature/42537 homepage copy changes post live
  admin/controllers/school.js
  admin/helpers/school-home-feature-eligibility-presenter.js
  admin/lib/ejs-util.js
  admin/services/results-page-availability.service.js
  admin/services/school-home-page/school-home-page.service.js
  admin/services/school-home-page/school-home-page.service.spec.js
  admin/spec/back-end/controllers/school.spec.js
  admin/spec/back-end/helpers/school-home-feature-eligibility-presenter.spec.js
  admin/spec/back-end/lib/ejs-util.spec.js
  admin/spec/back-end/mocks/check-window.js
  admin/spec/back-end/service/check-window-sanity-check.service.spec.js
  admin/spec/back-end/service/headteacher-declaration.service.spec.js
  admin/views/partials/school/home-page/active-link.ejs
  admin/views/partials/school/home-page/inactive-link.ejs
  admin/views/results/view-results.ejs
  admin/views/school/school-home.ejs
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
  test/pupil-hpa/Gemfile.lock
Labels: CI Enabled, Signed Off, Tested

#1924 Reinstating work in progress tests
  test/admin-hpa/features/add_multiple_pupil.feature
  test/admin-hpa/features/assign_to_check_window_v2.feature
  test/admin-hpa/features/groups.feature
  test/admin-hpa/features/mod_schools.feature
  test/admin-hpa/features/results.feature
  test/admin-hpa/features/school_landing.feature
  test/admin-hpa/features/step_definitions/assign_to_check_window_v2_steps.rb
  test/admin-hpa/features/step_definitions/result_page_steps.rb
  test/admin-hpa/features/support/helpers.rb
  test/admin-hpa/features/view_custom_pins_familiarisation.feature
  test/pupil-hpa/features/event_auditing.feature
  test/pupil-hpa/features/feedback.feature
  test/pupil-hpa/features/header_footer.feature
  test/pupil-hpa/features/loading_page.feature
  test/pupil-hpa/features/pin_expiry.feature
  test/pupil-hpa/features/registered_inputs.feature
  test/pupil-hpa/features/step_definitions/registered_inputs_steps.rb
  test/pupil-hpa/features/support/page_objects/check_page.rb
  test/pupil-hpa/features/support/page_objects/select_access_arrangements_page.rb
Labels: CI Enabled, QA: regression only, Ready for review, Tested

#1923 feature/47176 results sync
  admin/config.js
  admin/controllers/tech-support.js
  admin/routes/tech-support.js
  admin/services/data-access/sync-results-resync.data.service.js
  admin/services/tech-support/sync-results-resync.service.js
  admin/spec/back-end/controllers/tech-support.spec.js
  admin/views/tech-support/home.ejs
  admin/views/tech-support/results-resync-all.ejs
  admin/views/tech-support/results-resync-check.ejs
  admin/views/tech-support/results-resync-school.ejs
  db/migrations/schema-objects/20210610123731.do.check.resultssynchronised.sql
  db/migrations/schema-objects/20210610123731.undo.check.resultssynchronised.sql
  db/migrations/schema-objects/20210610125721.do.checkresultsyncerror-table.sql
  db/migrations/schema-objects/20210610125721.undo.checkresultsyncerror-table.sql
  db/migrations/user-permissions/20210611120050.do.function-user-delete-mtc_results.js
  db/migrations/user-permissions/20210611120050.undo.function-user-delete-mtc_results.js
  docs/environment-variables.md
  func-consumption/check-marker/function.json
  func-consumption/package.json
  func-consumption/yarn.lock
  func-throttled/package.json
  func-throttled/sync-results-init/function.json
  func-throttled/sync-results-to-sql/function.json
  func-throttled/yarn.lock
  test/admin-hpa/features/step_definitions/data_sync_steps.rb
  test/admin-hpa/features/support/functions_helper.rb
  test/pupil-hpa/features/pupil_data_sync.feature
  test/pupil-hpa/features/step_definitions/cookies_steps.rb
  test/pupil-hpa/features/support/functions_helper.rb
  tslib/package.json
  tslib/src/config.ts
  tslib/src/functions-throttled/sync-results-init/README.md
  tslib/src/functions-throttled/sync-results-init/index.ts
  tslib/src/functions-throttled/sync-results-init/models.ts
  tslib/src/functions-throttled/sync-results-init/sync-results-init-data.service.ts
  tslib/src/functions-throttled/sync-results-init/sync-results-init.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/index.ts
  tslib/src/functions-throttled/sync-results-to-sql/processing-failure.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/processing-failure.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.ts
  tslib/src/functions/check-marker/check-marker.v1.spec.ts
  tslib/src/functions/check-marker/check-marker.v1.ts
  tslib/src/functions/check-marker/models.ts
  tslib/src/schemas/models.ts
  tslib/src/sql/sql.service.ts
  tslib/src/tests-integration/mock-payload.class.ts
  tslib/yarn.lock
Labels: CI Enabled, Tested

#1927 47286 - Sync results to sql - rollback issue
  db/migrations/schema-objects/20210621004933.do.alter-table-user-device-remove-tinyint.sql
  db/migrations/schema-objects/20210621004933.undo.alter-table-user-device-remove-tinyint.sql
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Signed Off, Tested

#1930 Bug/47373 large checks exceeding max parameters
  tslib/src/functions-throttled/sync-results-to-sql/prepare-answers-and-inputs.data.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1931 Set the `sync-results` function off an hour earlier - 6pm BST
  func-throttled/sync-results-init/function.json
Labels: CI NOT Required, Requires Tech Sign Off, Signed Off

#1932 Bug/47418 sync results parameters
  tslib/src/functions-throttled/sync-results-to-sql/prepare-answers-and-inputs.data.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/prepare-answers-and-inputs.data.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.spec.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1928 Test suite fix
  test/admin-hpa/features/step_definitions/data_sync_steps.rb
  test/admin-hpa/features/support/functions_helper.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/pupil-hpa/features/a_ps_report.feature
  test/pupil-hpa/features/step_definitions/access_arrangement_steps.rb
  test/pupil-hpa/features/step_definitions/check_steps.rb
  test/pupil-hpa/features/step_definitions/cookies_steps.rb
  test/pupil-hpa/features/step_definitions/pin_expiry_steps.rb
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/pupil-hpa/features/step_definitions/pupil_data_sync_steps.rb
  test/pupil-hpa/features/support/functions_helper.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, QA: regression only, Tested, ruby

#1929 Feature/42515 pupil status page content changes
  admin/views/partials/pupil-register/_check-window-has-closed.ejs
  admin/views/pupil-status/view-pupil-status.ejs
  tslib/src/functions-throttled/ps-report-1-list-schools/index.ts
  tslib/src/functions-throttled/sync-results-init/index.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1938 [tslib/sync-results-to-sql] allow unusually large battery discharge v…
  db/migrations/schema-objects/20210625181633.do.alter-table-userdevice-batterydisachrgingtimesecs.sql
  db/migrations/schema-objects/20210625181633.undo.alter-table-userdevice-batterydisachrgingtimesecs.sql
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off

#1935 Feature/47452 loosen pupil attendance rules
  admin/controllers/pupils-not-taking-the-check.js
  admin/services/business-availability.service.js
  admin/services/data-access/pupils-not-taking-check.data.service.js
  admin/services/pupils-not-taking-check.service.js
  admin/spec/back-end/service/business-availability.service.spec.js
Labels: CI Enabled, Reviewed & approved, Tested

#1939 Feature/wip tests
  test/admin-hpa/features/add_multiple_pupil.feature
  test/admin-hpa/features/assign_to_check_window_v2.feature
  test/admin-hpa/features/groups.feature
  test/admin-hpa/features/mod_schools.feature
  test/admin-hpa/features/results.feature
  test/admin-hpa/features/school_landing.feature
  test/admin-hpa/features/step_definitions/assign_to_check_window_v2_steps.rb
  test/admin-hpa/features/step_definitions/result_page_steps.rb
  test/admin-hpa/features/support/helpers.rb
  test/admin-hpa/features/view_custom_pins_familiarisation.feature
  test/pupil-hpa/features/event_auditing.feature
  test/pupil-hpa/features/feedback.feature
  test/pupil-hpa/features/header_footer.feature
  test/pupil-hpa/features/loading_page.feature
  test/pupil-hpa/features/pin_expiry.feature
  test/pupil-hpa/features/registered_inputs.feature
  test/pupil-hpa/features/step_definitions/registered_inputs_steps.rb
  test/pupil-hpa/features/support/page_objects/check_page.rb
  test/pupil-hpa/features/support/page_objects/select_access_arrangements_page.rb
Labels: CI Enabled, Tested

#1940 Feature/security rollup
  admin/yarn.lock
  load-test/yarn.lock
  pupil-spa/yarn.lock
Labels: CI Enabled, Tested
