Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2021-07, with the labels that each got.

#1941 Bug/47473 modify results page
  admin/services/data-access/result.data.service.js
  admin/services/result.service.js
  admin/spec/back-end/service/result.service.spec.js
  func-consumption/disable-functions.env
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1942 [admin/results] ctf filename change
  admin/controllers/results.js
  admin/spec/back-end/controllers/results.spec.js
  test/admin-hpa/features/step_definitions/result_page_steps.rb
Labels: CI Enabled, Reviewed & approved, Tested

#1945 Bug/47492 ps report keystrokes data length
  _util/chaos-proxy/chaos-proxy.js
  _util/chaos-proxy/config.js
  _util/chaos-proxy/index.js
  _util/chaos-proxy/package.json
  _util/chaos-proxy/yarn.lock
  db/migrations/schema-objects/20210701215919.do.alter-mtc-results-psychometric-report.sql
  db/migrations/schema-objects/20210701215919.undo.alter-mtc-results-psychometric-report.sql
  tslib/src/functions-throttled/ps-report-4-writer/ps-report-writer.service.ts
Labels: CI Enabled, Reviewed & approved, Testing

#1943 [tslib] fix timers running after due
  tslib/src/azure/functions.ts
  tslib/src/functions-throttled/ps-report-1-list-schools/index.ts
  tslib/src/functions-throttled/sync-results-init/index.ts
  tslib/src/functions/check-notifier-batch/index.ts
  tslib/src/functions/school-results-cache/index.ts
Labels: CI Enabled, Requires Tech Sign Off, Signed Off

#1946 [db] add index
  db/migrations/schema-objects/20210702130349.do.mtc-results-userinput-answer-id-index-drop.sql
  db/migrations/schema-objects/20210702130349.undo.mtc-results-userinput-answer-id-index-drop.sql
  db/migrations/schema-objects/20210702130354.do.mtc-results-userinput-answer-id-index.sql
  db/migrations/schema-objects/20210702130354.undo.mtc-results-userinput-answer-id-index.sql
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off

#1947 47429 - [db] mask checkResult.mark with a better default
  db/migrations/schema-objects/20210707115242.do.alter-mtc-results-checkresult-mark.sql
  db/migrations/schema-objects/20210707115242.undo.alter-mtc-results-checkresult-mark.sql
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1933 Feature/41593 util-submit-check enhancements
  func-consumption/extensions.csproj
  func-consumption/package.json
  func-consumption/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  tslib/.vscode/settings.json
  tslib/package.json
  tslib/src/caching/prepared-check.service.spec.ts
  tslib/src/caching/prepared-check.service.ts
  tslib/src/caching/redis-key.service.ts
  tslib/src/config.ts
  tslib/src/functions-unused/pupil-auth/index.ts
  tslib/src/functions-unused/pupil-auth/pupil-auth.service.spec.ts
  tslib/src/functions-unused/pupil-auth/pupil-auth.service.ts
  tslib/src/functions-unused/pupil-auth/readme.md
  tslib/src/functions/check-started/check-started.service.ts
  tslib/src/functions/util-submit-check/fake-check-audit-generator.service.ts
  tslib/src/functions/util-submit-check/fake-check-inputs-generator.service.ts
  tslib/src/functions/util-submit-check/fake-completed-check-generator.service.spec.ts
  tslib/src/functions/util-submit-check/fake-completed-check-generator.service.ts
  tslib/src/functions/util-submit-check/fake-submitted-check-generator.service.spec.ts
  tslib/src/functions/util-submit-check/fake-submitted-check-generator.service.ts
  tslib/src/functions/util-submit-check/index.ts
  tslib/src/functions/util-submit-check/school-checks.data.service.ts
  tslib/src/schemas/check-schemas/mock-complete-check-2021.json
  tslib/src/schemas/check-schemas/mock-prepared-check-2021.json
  tslib/src/schemas/check-schemas/prepared-check.ts
  tslib/src/schemas/check-schemas/submitted-check.ts
  tslib/src/schemas/complete-check-payload.ts
  tslib/src/schemas/models.ts
  tslib/src/schemas/prepared-check-partial.ts
  tslib/src/schemas/submitted-check-message-template.json
  tslib/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Signed Off, Tested

#1948 feature/47548 dockerize build server
  deploy/build-server/Dockerfile
  deploy/build-server/build-push-docker-hub.sh
  deploy/build-server/create-instance.sh
  deploy/build-server/start.sh
  func-consumption/.gitignore
  func-consumption/extensions.csproj
  func-throttled/.gitignore
Labels: QA Not required, Requires Tech Sign Off, Signed Off

#1955 test updates
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/features/step_definitions/declaration_submitted_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/step_definitions/tech_support_steps.rb
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/features/support/functions_helper.rb
  test/admin-hpa/features/support/helpers.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  test/pupil-hpa/features/a_ps_report.feature
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/pupil-hpa/features/support/env.rb
  test/pupil-hpa/features/support/functions_helper.rb
Labels: CI Enabled, Reviewed & approved, Tested

#1953 Feature/47662 docker build agent pt.2
  deploy/build-agent-ruby/Dockerfile
  deploy/build-agent-ruby/build-push-docker-hub.sh
  deploy/build-agent-ruby/readme.md
  deploy/build-agent-ruby/ruby-base.Dockerfile
  deploy/build-agent/Dockerfile
  deploy/build-agent/build-push-docker-hub.sh
  deploy/build-agent/cleanup.sh
  deploy/build-agent/create-instance.sh
  deploy/build-agent/start.sh
Labels: CI Enabled

#1954 Bug/47447 not attending can select completed check pupils
  admin/services/data-access/pupils-not-taking-check.data.service.js
  admin/tests-integration/pupils-not-taking-check.data.service.spec.js
  pupil-api/yarn.lock
  tslib/src/tests-integration/mock-payload.class.ts
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1957 Feature/47610 util submit check docs
  docs/support utils/util-submit-check.md
Labels: CI NOT Required, QA Not required

#1951 [bug/47549] Dfe Signin Error
  admin/authentication/dfe-signin-strategy.js
  admin/gulpfile.js
  admin/package.json
  admin/routes/index.js
  admin/yarn.lock
  test/pupil-hpa/features/support/env.rb
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1958 Feature/47720 new agent pool switch
  api_tests/browser-security-tests.sh
  deploy/build-agent/create-instance.sh
  deploy/build-defs/full-deploy.yml
  deploy/build-defs/rotate-azure-keys.yml
  deploy/build-defs/validate-pr-db-migrations.yml
Labels: CI Enabled

#1959 Feature/ruby security fixes
  test/admin-hpa/Gemfile.lock
  test/pupil-hpa/Gemfile.lock
Labels: CI Enabled, Tested, ruby

#1956 Feature/46157 remove columns from ps report table
  db/migrations/schema-objects/20210719173854.do.alter-ps-report-drop-unused-cols.sql
  db/migrations/schema-objects/20210719173854.undo.alter-ps-report-drop-unused-cols.sql
  db/yarn.lock
  tslib/src/functions-throttled/ps-report-4-writer/models.ts
  tslib/src/functions-throttled/ps-report-4-writer/ps-report-writer.service.ts
  tslib/src/functions/ps-report-3-transformer/models.ts
  tslib/src/functions/ps-report-3-transformer/report-line.class.spec.ts
  tslib/src/functions/ps-report-3-transformer/report-line.class.ts
  tslib/src/tests-integration/mock-payload.class.ts
  tslib/src/tests-integration/ps-report-writer.service.spec.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1962 feature/47102 - update check-completion queue config
  deploy/service-bus/deploy.config.js
Labels: CI Enabled, QA Not required, Requires Tech Sign Off, Reviewed & approved, Signed Off

#1961 chore - remove unused check window service from tslib
  tslib/src/services/check-window.service.spec.ts
  tslib/src/services/check-window.service.ts
Labels: CI Enabled, Reviewed & approved, Tested

#1964 [admin] update service unavailable message
  admin/views/availability/admin-window-unavailable.ejs
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested
