Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2021-03, with the labels that each got.

#1830 feature/45652 vso release pipeline app settings
  deploy/release-config/admin.base.txt
  deploy/release-config/admin.dev.test.demo.load.txt
  deploy/release-config/admin.preprod.prod.txt
  deploy/release-config/func-cons.base.txt
  deploy/release-config/func-cons.dev.test.demo.load.txt
  deploy/release-config/func-cons.preprod.prod.txt
  deploy/release-config/func-throttled.base.txt
  deploy/release-config/func-throttled.preprod.prod.txt
  deploy/release-config/pupil-api.base.txt
  deploy/release-config/pupil-spa.base.txt
  deploy/release-config/readme.md
  deploy/release-config/z_original-archive/dev-test-demo-load/admin.txt
  deploy/release-config/z_original-archive/dev-test-demo-load/func-consumption.txt
  deploy/release-config/z_original-archive/dev-test-demo-load/func-throttled.txt
  deploy/release-config/z_original-archive/dev-test-demo-load/pupil-api.txt
  deploy/release-config/z_original-archive/dev-test-demo-load/pupil-spa.txt
  deploy/release-config/z_original-archive/preprod-prod/admin.txt
  deploy/release-config/z_original-archive/preprod-prod/func-consumption.txt
  deploy/release-config/z_original-archive/preprod-prod/func-throttled.txt
  deploy/release-config/z_original-archive/preprod-prod/pupil-api.txt
  deploy/release-config/z_original-archive/preprod-prod/pupil-spa.txt
Labels: CI Enabled, QA Not required

#1829 Feature/45376 flush redis cache item manually
  admin/controllers/tech-support.js
  admin/gulpfile.js
  admin/lib/errors/redis.js
  admin/package.json
  admin/routes/tech-support.js
  admin/services/data-access/redis-cache.service.js
  admin/services/tech-support/redis.service.js
  admin/spec/back-end/controllers/tech-support.spec.js
  admin/tests-integration/pin-generation.service.spec.js
  admin/tests-integration/redis-cache.data.service.spec.js
  admin/tests-integration/redis-service.spec.js
  admin/tests-integration/sas-token-expiry.spec.js
  admin/tests-integration/sql.service.spec.js
  admin/tests-integration/supertest.spec.js
  admin/tests-integration/udf-calc-check-status-id.spec.js
  admin/tests-integration/vew-check-diagnostic.spec.js
  admin/views/partials/_flash-messages.ejs
  admin/views/partials/_form-error.ejs
  admin/views/tech-support/_redis-key-search.ejs
  admin/views/tech-support/home.ejs
  admin/views/tech-support/redis-confirm-drop.ejs
  admin/views/tech-support/redis-drop-key.ejs
  admin/views/tech-support/redis-examine-key.ejs
  admin/views/tech-support/redis-multiple-drop-confirm.ejs
  admin/views/tech-support/redis-multiple-drop.ejs
  admin/views/tech-support/redis-overview.ejs
  admin/views/tech-support/redis-search.ejs
  admin/views/website-offline.ejs
  admin/yarn.lock
Labels: CI Enabled, Ready for review, Requires Tech Sign Off, Signed Off, Tested

#1831 Bug/33834 app insights
  admin/controllers/test-error.js
  admin/routes/index.js
  admin/views/test-error.ejs
  deploy/docker/functions-base/Dockerfile
  docs/caching.md
  docs/environment-variables.md
  docs/messaging.md
  pupil-api/src/controllers/api-response.ts
  pupil-api/src/controllers/redis.auth.controller.spec.ts
  pupil-api/src/controllers/redis.auth.controller.ts
  pupil-api/src/index.ts
  pupil-api/src/services/feature.service.ts
  pupil-api/src/services/queue-message.service.ts
  pupil-api/src/services/redis-pupil-auth.service.spec.ts
  pupil-api/src/services/redis.service.ts
  pupil-api/tsconfig.json
  pupil-api/yarn.lock
  pupil-spa/.nvmrc
  pupil-spa/Dockerfile
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/test-error/test-error.component.html
  pupil-spa/src/app/test-error/test-error.component.scss
  pupil-spa/src/app/test-error/test-error.component.spec.ts
  pupil-spa/src/app/test-error/test-error.component.ts
Labels: CI Enabled, Ready for review, Requires Tech Sign Off, Signed Off, Tested

#1838 Feature/37073 sign in error page copy change
  admin/gulpfile.js
  admin/package.json
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  load-test/package.json
  load-test/yarn.lock
  pupil-spa/package.json
  pupil-spa/src/app/login-failure/login-failure.component.html
  pupil-spa/yarn.lock
  setup.sh
  test/pupil-hpa/data/.gitignore
  tslib/package.json
  tslib/yarn.lock
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1837 feature/45671 add masking
  db/migrations/schema-objects/20210310093218.do.mask-ps-report.sql
  db/migrations/schema-objects/20210310093218.undo.mask-ps-report.sql
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1836 feature/45507 Azure key rotation
  admin/package.json
  deploy/azure/key-vault/_run.sh
  deploy/azure/key-vault/key-rotation/integration-test.sh
  deploy/azure/key-vault/key-rotation/redis.sh
  deploy/azure/key-vault/key-rotation/service-bus.sh
  deploy/azure/key-vault/key-rotation/storage.sh
Labels: CI Enabled, QA Not required, Requires Tech Sign Off, Reviewed & approved, Signed Off

#1832 Bug/42528 pupil results diagnostic cache table is superfluous
  db/migrations/schema-objects/20210302145211.do.drop-pupilresultsdiagnostic-table.sql
  db/migrations/schema-objects/20210302145211.undo.drop-pupilresultsdiagnostic-table.js
  deploy/storage/delete-items.sh
  test/admin-hpa/features/add_pupil.feature
  test/admin-hpa/features/declaration_form.feature
  test/admin-hpa/features/edit_pupil.feature
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/complete_page.rb
  test/admin-hpa/features/support/page_objects/warm_up_page.rb
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/pupil-hpa/features/support/hooks.rb
  test/pupil-hpa/features/support/page_objects/complete_page.rb
  test/pupil-hpa/features/support/page_objects/warm_up_page.rb
Labels: CI Enabled, Ready for review, Requires Tech Sign Off, Tested

#1842 Feature/46066 pipeline fix
  test/admin-hpa/features/add_multiple_pupil.feature
  test/admin-hpa/features/results.feature
  test/admin-hpa/features/support/hooks.rb
  test/pupil-hpa/features/a_ps_report.feature
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Tested, ruby

#1844 fix issue with tests
  test/admin-hpa/features/view_custom_pins_familiarisation.feature
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
Labels: CI Enabled, Tested, ruby

#1841 Feature/45931 service manager search for school
  admin/controllers/service-manager.js
  admin/routes/service-manager.js
  admin/services/data-access/school.data.service.js
  admin/services/school.service.js
  admin/spec/back-end/controllers/service-manager.spec.js
  admin/spec/back-end/service/school.service.spec.js
  admin/views/service-manager/manage-organisations-hub.ejs
  admin/views/service-manager/organisation-detail.ejs
  admin/views/service-manager/organisations-search.ejs
  admin/views/service-manager/service-manager-home.ejs
  test/admin-hpa/features/service_manager_school_search.feature
  test/admin-hpa/features/step_definitions/search_schools_steps.rb
  test/admin-hpa/features/step_definitions/service_manager_landing_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/admin_page.rb
  test/admin-hpa/features/support/page_objects/manage_organisations_page.rb
  test/admin-hpa/features/support/page_objects/school_search_results_page.rb
  test/admin-hpa/features/support/page_objects/search_organisations_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1847 chore - add ps report scaling notes
  docs/psychometric-report-scaling.md
Labels: CI NOT Required, QA Not required

#1846 Bug/46106 ps report school name field
  db/migrations/schema-objects/20210323113308.do.alter-psychometricreport-schoolname-length.sql
  db/migrations/schema-objects/20210323113308.undo.alter-psychometricreport-schoolname-length.sql
  db/seeds/20210323115125.custom.change-school-5-name-to-something-long.sql
  tslib/src/functions-throttled/ps-report-4-writer/ps-report-writer.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Signed Off, Tested, expedited

#1833 43250 - add migration to remove null from mtc_pupil.checkComplete
  admin/package.json
  db/migrations/core-data/20210303100905.do.convert-nulls-in-checkcomplete-to-0.sql
  db/migrations/core-data/20210303100905.undo.convert-nulls-in-checkcomplete-to-0.sql
  db/migrations/schema-objects/20210303101058.do.remove-null-from-checkcomplete.sql
  db/migrations/schema-objects/20210303101058.undo.remove-null-from-checkcomplete.sql
  load-test/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Signed Off, Tested

#1834 Feature/44617 env var admin app
  admin/config.js
  admin/views/website-offline.ejs
  docs/environment-variables.md
Labels: CI Enabled, Requires Tech Sign Off, Signed Off, Tested

#1849 feature/45472 pupil API HEAD request handler for root
  pupil-api/src/App.ts
  pupil-api/src/routes/auth.ts
  pupil-api/src/routes/head.ts
  pupil-api/src/routes/ping.ts
  test/pupil-hpa/features/step_definitions/pupil_data_sync_steps.rb
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested
