Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2021-11, with the labels that each got.

#2028 Feature/upgrade function extensions
  .gitignore
  admin/package.json
  func-consumption/.gitignore
  func-consumption/host.json
  func-consumption/package.json
  func-throttled/.gitignore
  func-throttled/host.json
  func-throttled/package.json
  pupil-spa/gulpfile.js
  restart.sh
  setup.sh
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2025 Feature/46036 load testing
  load-test/Create-Flood-IO-Load-Test-Agent-Azure-Windows-2019-Server.md
  load-test/exec-remote.sh
  load-test/scenarios/2021/live-checks-with-submit.jmx
Labels: Reviewed & approved, Signed Off, CI NOT Required, Requires Tech Sign Off

#1965 docker test changes
  test/admin-hpa/Rakefile
  test/admin-hpa/features/data_sync.feature
  test/admin-hpa/features/results.feature
  test/pupil-hpa/Rakefile
  test/pupil-hpa/features/a_ps_report.feature
Labels: Tested, Signed Off, CI Enabled

#2032 feature/50067 pupil app offline content update
  pupil-spa/src/app/website-offline/website-offline.component.html
Labels: Tested, Signed Off, CI Enabled

#2027 Feature/disallow login to pupil spa if localstorage is disabled
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/error-localstorage/error-local-storage.component.html
  pupil-spa/src/app/error-localstorage/error-local-storage.component.scss
  pupil-spa/src/app/error-localstorage/error-local-storage.component.spec.ts
  pupil-spa/src/app/error-localstorage/error-local-storage.component.ts
  pupil-spa/src/app/login/login.component.spec.ts
  pupil-spa/src/app/login/login.component.ts
  pupil-spa/src/app/services/device/device.service.spec.ts
  pupil-spa/src/app/services/device/device.service.ts
  pupil-spa/src/app/services/storage/storage.service.ts
  pupil-spa/src/app/warmup-loading/warmup-loading.component.spec.ts
  pupil-spa/src/app/warmup-loading/warmup-loading.component.ts
  pupil-spa/yarn.lock
Labels: Tested, Signed Off, CI Enabled

#2019 Feature/45930 add new school page
  admin/controllers/service-manager.js
  admin/lib/validator/school-validator.js
  admin/package.json
  admin/routes/service-manager.js
  admin/services/data-access/school.data.service.js
  admin/services/payload.service.js
  admin/services/pupil-census.service.js
  admin/services/school.service.js
  admin/spec/back-end/authentication/middleware.spec.js
  admin/spec/back-end/controllers/service-manager.spec.js
  admin/spec/back-end/service/school.service.spec.js
  admin/views/service-manager/add-school.ejs
  admin/views/service-manager/manage-organisations-hub.ejs
  admin/yarn.lock
  pupil-api/yarn.lock
  pupil-spa/yarn.lock
  test/admin-hpa/features/service_manager_add_school.feature
  test/admin-hpa/features/step_definitions/add_school_steps.rb
  test/admin-hpa/features/support/page_objects/add_school_page.rb
  test/admin-hpa/features/support/page_objects/manage_organisations_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/admin-hpa/service_manager_add_school.featrue
  tslib/yarn.lock
Labels: Tested, Ready to merge, Signed Off, CI Enabled

#2021 Fix: admin session timeout modal
  admin/app.js
  admin/assets/javascripts/cookie-form.js
  admin/assets/javascripts/session-expiry.js
  admin/assets/vendor-js/accessible-autocomplete.min.js
  admin/assets/vendor-js/accessible-autocomplete.min.js.map
  admin/assets/vendor-js/gds-cookie-banner.js
  admin/assets/vendor-js/gds-cookie-functions.js
  admin/assets/vendor-js/gds-cookie-settings.js
  admin/assets/vendor-js/jquery-3.5.1.js
  admin/controllers/keep-alive.js
  admin/gulpfile.js
  admin/karma.conf.js
  admin/package.json
  admin/routes/index.js
  admin/spec/front-end/session-expiry.spec.js
  admin/views/layout.ejs
  admin/yarn.lock
  pupil-spa/yarn.lock
  test/admin-hpa/config/cucumber.yml
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/service_manager_add_school.featrue
  test/pupil-hpa/config/cucumber.yml
  test/pupil-hpa/features/support/env.rb
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled, Requires Tech Sign Off

#2022 feature/46095 -remove inactive service manager settings link
  admin/views/service-manager/service-manager-home.ejs
  test/admin-hpa/features/step_definitions/service_manager_landing_steps.rb
  test/admin-hpa/features/support/page_objects/admin_page.rb
Labels: Tested, Ready to merge, Reviewed & approved, Signed Off, CI Enabled

#2026 [check-sync] Refactor for improved batch handling
  tslib/src/functions/check-sync/prepared-check-sync.service.spec.ts
  tslib/src/functions/check-sync/prepared-check-sync.service.ts
Labels: QA: regression only, Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2029 49509 Bug/pupils not showing after census import
  .gitignore
  test/admin-hpa/features/step_definitions/upload_pupil_census_steps.rb
  test/admin-hpa/features/upload_pupil_census.feature
  tslib/src/caching/redis-key.service.ts
  tslib/src/caching/redis-service.mock.ts
  tslib/src/caching/redis-service.ts
  tslib/src/functions-throttled/census-import/index.ts
  tslib/src/functions-throttled/census-import/v1.spec.ts
  tslib/src/functions-throttled/census-import/v1.ts
  tslib/src/functions-throttled/school-import/index.ts
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled, Requires sign off

#2039 Webdrivers Security roll up
  admin/gulpfile.js
  admin/package.json
  test/admin-hpa/Gemfile
  test/pupil-hpa/Gemfile
Labels: Tested, Ready to merge, CI Enabled, ruby

#2033 Add service message to service manager home page
  admin/assets/stylesheets/elements/_flash-messages.scss
  admin/controllers/service-manager.js
  admin/gulpfile.js
  admin/package.json
  admin/services/administration-message.service.js
  admin/services/data-access/administration-message.data.service.js
  admin/services/sanitise.service.js
  admin/services/school-home-page/school-home-page.service.spec.js
  admin/spec/back-end/controllers/service-manager.spec.js
  admin/spec/back-end/service/administration-message.service.spec.js
  admin/spec/back-end/service/sanitise.service.spec.js
  admin/views/partials/_service_message.ejs
  admin/views/school/school-home.ejs
  admin/views/service-manager/service-manager-home.ejs
  admin/views/service-message/service-message-form.ejs
  admin/views/service-message/service-message-overview.ejs
  admin/views/tech-support/home.ejs
  admin/yarn.lock
Labels: Tested, Ready to merge, Signed Off, CI Enabled

#2045 add tests for service message
  test/admin-hpa/config/cucumber.yml
  test/admin-hpa/features/service_manager_message.feature
  test/admin-hpa/features/step_definitions/service_message.rb
  test/admin-hpa/features/support/page_objects/create_message_page.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
  test/pupil-hpa/config/cucumber.yml
Labels: Tested, CI NOT Required, ruby

#2046 Update feedback_steps.rb
  test/pupil-hpa/features/step_definitions/feedback_steps.rb
Labels: Tested, Ready to merge, CI Enabled, ruby
