Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2021-04, with the labels that each got.

#1853 Feature/46162 load test scripts update
  deploy/sql/dummy-data/all.js
  func-consumption/util-submit-check/function.json
  load-test/bin/generate-teacher-for-each-school.js
  load-test/scenarios/_2020/live-long-teacher-journey-with-check-submit.jmx
  tslib/src/functions/util-submit-check/index.ts
Labels: CI Enabled, QA Not required, Requires Tech Sign Off, Signed Off

#1855 [doc] update test env to allow pupil login between midnight and 8am
  deploy/release-config/admin.dev.test.demo.load.txt
Labels: CI NOT Required

#1850 Fix #46179 - Bugfix for AA keypad removal
  pupil-spa/src/app/practice-question/practice-question.component.ts
  test/admin-hpa/features/step_definitions/declaration_submitted_steps.rb
  test/admin-hpa/features/step_definitions/retro_input_steps.rb
Labels: CI Enabled, Signed Off, Tested

#1856 Check window caching mod
  admin/app.js
  admin/services/check-window-v2.service.js
  admin/spec/back-end/service/check-window-v2.service.spec.js
Labels: CI Enabled, Tested

#1857 Bug/46725 ps report reasons for not taking check not mapping to correct values
  db/migrations/schema-objects/20210409104403.do.ps-report-alter-reason-not-taking-check.sql
  db/migrations/schema-objects/20210409104403.undo.ps-report-alter-reason-not-taking-check.sql
  test/pupil-hpa/features/a_ps_report.feature
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/pupil-hpa/features/support/helpers.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
  tslib/src/functions-throttled/ps-report-2-pupil-data/models.ts
  tslib/src/functions-throttled/ps-report-2-pupil-data/ps-report.data.service.spec.ts
  tslib/src/functions-throttled/ps-report-2-pupil-data/ps-report.data.service.ts
  tslib/src/functions-throttled/ps-report-4-writer/ps-report-writer.service.ts
  tslib/src/functions/ps-report-3-transformer/mocks/pupil-not-attending.ts
  tslib/src/functions/ps-report-3-transformer/mocks/pupil-who-completed-a-check.ts
  tslib/src/functions/ps-report-3-transformer/mocks/pupil-with-incomplete-check.ts
  tslib/src/functions/ps-report-3-transformer/models.ts
  tslib/src/functions/ps-report-3-transformer/report-line.class.spec.ts
  tslib/src/functions/ps-report-3-transformer/report-line.class.ts
  tslib/src/tests-integration/mock-payload.class.ts
Labels: CI Enabled, Ready to merge, Signed Off, Tested

#1862 Feature/admin copy changes 2021
  admin/controllers/pupils-not-taking-the-check.js
  admin/lib/errors/pupil.js
  admin/spec/back-end/controllers/pupils-not-taking-the-check.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/availability/admin-window-unavailable.ejs
  admin/views/groups/groups.ejs
  admin/views/pupil-register/pupils-list.ejs
  admin/views/pupil-status/view-pupil-status.ejs
  admin/views/pupils-not-taking-the-check/pupils-list.ejs
  admin/views/pupils-not-taking-the-check/select-pupils.ejs
  admin/views/school/school-home.ejs
  db/migrations/core-data/20210413071446.do.update-attendance-code-reason-2021-only.sql
  db/migrations/core-data/20210413071446.undo.update-attendance-code-reason-2021-only.sql
  test/admin-hpa/features/breadcrumbs.feature
  test/admin-hpa/features/generate_pupil_pin_familiarisation.feature
  test/admin-hpa/features/pupil_not_taking_check.feature
  test/admin-hpa/features/pupil_status.feature
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/declaration_review_pupil_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
  test/admin-hpa/features/support/page_objects/group_pupils_page.rb
  test/admin-hpa/features/support/page_objects/pupil_reason_page.rb
  test/admin-hpa/features/support/page_objects/pupils_not_taking_check_page.rb
Labels: CI Enabled, Tested

#1859 Bug/46358 pin expiry issue
  admin/services/check-start.service/check-start.service.js
  admin/services/date.service.js
  admin/services/pin-generation.service.js
  admin/services/pin.service.js
  admin/services/prepare-check.service.js
  admin/spec/back-end/service/date.service.spec.js
  admin/spec/back-end/service/pin.service.spec.js
Labels: CI Enabled, Reviewed & approved, Tested

#1864 Feature/46471 home screen updates to unavailable messages
  admin/assets/stylesheets/elements/_custom-banners.scss
  admin/helpers/school-home-feature-eligibility-presenter.js
  admin/package.json
  admin/services/date.service.js
  admin/spec/back-end/service/date.service.spec.js
  admin/views/privacy.ejs
  admin/views/school/school-home.ejs
  pupil-spa/src/app/privacy/privacy.component.html
  pupil-spa/src/app/privacy/privacy.component.scss
Labels: CI Enabled, Reviewed & approved, Tested

#1866 Feature/46036 load testing updates
  deploy/sql/dummy-data/readme.md
  func-consumption/util-submit-check/function.json
  load-test/bin/complete-db-reset.sql
  load-test/bin/undo-generate-pupil-load-test-data.sql
  load-test/exec-local.sh
  load-test/scenarios/2020/live-long-teacher-journey-with-check-submit.jmx
  load-test/scenarios/2020/live-pin-gen-only.jmx
  load-test/scenarios/2020/short-teacher-journey-with-check-submit.jmx
  load-test/scenarios/2020/tio-long-teacher-journey-with-check-submit.jmx
  load-test/scenarios/2021/live-long-teacher-journey-with-check-submit-v2.jmx
Labels: CI NOT Required, QA Not required, expedited

#1868 [admin, spa] copy change
  admin/views/accessibility-statement.ejs
  pupil-spa/src/app/accessibility-statement/accessibility-statement.component.html
Labels: CI Enabled, Reviewed & approved, Tested

#1869 Bug/46523 teachers unable to assign access arrangements
  admin/services/access-arrangements.service.js
  admin/spec/back-end/service/access-arrangements.service.spec.js
Labels: CI Enabled, Reviewed & approved

#1871 Feature/46529 spike dead letter service bus
  _spikes-poc/sb-queue-dead-letter/.funcignore
  _spikes-poc/sb-queue-dead-letter/.gitignore
  _spikes-poc/sb-queue-dead-letter/.vscode/extensions.json
  _spikes-poc/sb-queue-dead-letter/deadLetterQueueTest/function.json
  _spikes-poc/sb-queue-dead-letter/deadLetterQueueTest/index.ts
  _spikes-poc/sb-queue-dead-letter/host.json
  _spikes-poc/sb-queue-dead-letter/package.json
  _spikes-poc/sb-queue-dead-letter/tsconfig.json
  _spikes-poc/sb-queue-dead-letter/yarn.lock
Labels: CI NOT Required, QA Not required, Requires Tech Sign Off, Signed Off

#1867 Feature/46217 code z pupil not taking check
  admin/services/ctf-service/ctf.service.js
  admin/services/ctf-service/ctf.service.spec.js
  test/pupil-hpa/features/a_ps_report.feature
  test/pupil-hpa/features/support/helpers.rb
  test/pupil-hpa/features/support/page_objects/pupil_reason_page.rb
  tslib/src/functions/ps-report-3-transformer/report-line.class.spec.ts
  tslib/src/functions/ps-report-3-transformer/report-line.class.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1872 feature/46034 remove obsolete CORS_WHITELIST setting from admin app release config
  deploy/release-config/admin.base.txt
Labels: CI Enabled, QA Not required, Requires Tech Sign Off, Reviewed & approved, Signed Off

#1848 Feature/46006 key rotation build task
  deploy/build-defs/rotate-azure-keys.yml
Labels: CI NOT Required, QA Not required, Requires Tech Sign Off

#1863 [admin] feature/46211-pin-expiry-not-available-for-ntc-when-pin-expires
  admin/services/data-access/pupil-attendance.data.service.js
  admin/services/data-access/pupils-not-taking-check.data.service.js
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1845 Feature/46037 change checkwindow errors to warnings
  admin/controllers/check-window.js
  admin/helpers/check-window-presenter.js
  admin/lib/validation-error.js
  admin/lib/validator/check-window-v2/check-window-add-validator.js
  admin/lib/validator/common/date-validator.js
  admin/package.json
  admin/services/check-window-v2-add.service.js
  admin/services/check-window-v2-update.service.js
  admin/services/check-window-v2.service.js
  admin/spec/back-end/controllers/check-window.spec.js
  admin/spec/back-end/helpers/check-window-presenter.spec.js
  admin/spec/back-end/lib/validation-error.spec.js
  admin/spec/back-end/lib/validator/check-window-v2/check-window-add-validator.spec.js
  admin/views/check-window/create-check-window.ejs
  test/admin-hpa/features/edit_check_window_v2.feature
  test/admin-hpa/features/step_definitions/check_window_validation_steps.rb
  test/admin-hpa/features/step_definitions/edit_check_window_steps.rb
  test/admin-hpa/features/support/page_objects/add_edit_check_window_v2_page.rb
Labels: CI Enabled, Signed Off, Tested

#1873 feature/46558 - TIO pin test
  test/admin-hpa/features/generate_pupil_pin_familiarisation.feature
  test/admin-hpa/features/generate_pupil_pins.feature
Labels: CI Enabled, Reviewed & approved, Tested, ruby

#1874 Feature/45932 service manager edit school details
  admin/controllers/service-manager.js
  admin/lib/form-util.js
  admin/lib/validator/la-code-validator.js
  admin/lib/validator/school-validator.js
  admin/package.json
  admin/routes/service-manager.js
  admin/services/data-access/school.data.service.js
  admin/services/data-access/sql.service.js
  admin/services/school.service.js
  admin/spec/back-end/controllers/service-manager.spec.js
  admin/spec/back-end/lib/form-util.spec.js
  admin/spec/back-end/lib/validator/la-code-validator.spec.js
  admin/spec/back-end/lib/validator/school-validator.spec.js
  admin/spec/back-end/service/school.service.spec.js
  admin/views/service-manager/organisation-detail-edit.ejs
  admin/views/service-manager/organisation-detail.ejs
  admin/yarn.lock
  test/admin-hpa/features/service_manager_edit_school.feature
  test/admin-hpa/features/step_definitions/edit_school_steps.rb
  test/admin-hpa/features/support/page_objects/edit_school_page.rb
  test/admin-hpa/features/support/page_objects/school_search_results_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1875 Feature/46532 the retro input assistant link does not display until official check
  admin/controllers/access-arrangements.js
  admin/helpers/access-arrangements-overview-presenter.js
  admin/lib/ejs-util.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/lib/ejs-util.spec.js
  admin/views/access-arrangements/overview.ejs
  admin/views/access-arrangements/retro-input-assistant.ejs
Labels: CI Enabled, Testing
