Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2021-05, with the labels that each got.

#1877 Feature/31568 pupil login add retry mechanism
  chaos-proxy/chaos-proxy.js
  chaos-proxy/config.js
  chaos-proxy/index.js
  chaos-proxy/package.json
  chaos-proxy/yarn.lock
  pupil-spa/package.json
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/services/http/http.service.spec.ts
  pupil-spa/src/app/services/http/http.service.ts
  pupil-spa/src/app/services/user/user.service.spec.ts
  pupil-spa/src/app/services/user/user.service.ts
  pupil-spa/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1882 Feature/46618 save dynamic access arrangements
  admin/package.json
  admin/views/access-arrangements/select-access-arrangements.ejs
  test/pupil-hpa/features/a_ps_report.feature
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  tslib/src/functions/check-sync/prepared-check-sync.data.service.ts
  tslib/src/functions/check-sync/prepared-check-sync.service.spec.ts
  tslib/src/functions/check-sync/prepared-check-sync.service.ts
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1884 46287 [admin] bugfix retro access arrangement feature
  admin/services/data-access/retro-input-assistant.data.service.js
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1895 46252 [admin/gui] fix pupil upn search
  admin/assets/javascripts/pupil-filter-name.js
  admin/package.json
  admin/spec/front-end/pupil-filter-name.spec.js
  test/admin-hpa/features/pupil_register.feature
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
  test/admin-hpa/features/support/page_objects/pupil_register_page.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1900 Security fix roll up PR
  admin/yarn.lock
  functions-app/yarn.lock
  pupil-api/yarn.lock
  pupil-spa/yarn.lock
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1899 Feature/hdf copy changes 46614 46616 46623
  admin/views/hdf/confirm-and-submit.ejs
  admin/views/hdf/declaration-form.ejs
  admin/views/hdf/review-pupil-details.ejs
  admin/views/hdf/submitted-form.ejs
  test/admin-hpa/features/declaration_edit_reason.feature
  test/admin-hpa/features/step_definitions/declaration_edit_reason_steps.rb
  test/admin-hpa/features/step_definitions/declaration_review_pupil_steps.rb
  test/admin-hpa/features/step_definitions/declaration_submitted_steps.rb
  test/admin-hpa/features/support/page_objects/declaration_review_pupils_page.rb
  test/admin-hpa/features/support/page_objects/declaration_submitted_form_page.rb
  test/admin-hpa/features/support/page_objects/pupil_register_page.rb
Labels: CI Enabled, Ready to merge, Reviewed & approved, Signed Off, Tested

#1903 Feature/46815 add new role sta admin
  admin/controllers/authentication.js
  admin/controllers/pupil-pin.js
  admin/controllers/school.js
  admin/lib/consts/roles.js
  admin/routes/access-arrangements.js
  admin/routes/group.js
  admin/routes/hdf.js
  admin/routes/helpdesk.js
  admin/routes/pupil-pin.js
  admin/routes/pupil-register.js
  admin/routes/pupil-status.js
  admin/routes/pupils-not-taking-the-check.js
  admin/routes/restart.js
  admin/routes/results.js
  admin/routes/school.js
  admin/services/helpdesk.service.js
  admin/services/pin.service.js
  admin/services/role.service.js
  admin/spec/back-end/mocks/school.js
  admin/spec/back-end/service/pin-generation.service.spec.js
  admin/spec/back-end/service/pin.service.spec.js
  admin/spec/back-end/service/role.service.spec.js
  admin/tests-integration/sas-token-expiry.spec.js
  admin/views/partials/_name_and_sign_out.ejs
  admin/views/school/school-home.ejs
  db/migrations/core-data/20210513103435.do.add-new-role-sta-admin.sql
  db/migrations/core-data/20210513103435.undo.add-new-role-sta-admin.sql
  db/seeds/20210513103728.custom.add-new-user-sta-admin.sql
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested

#1912 Bug/46925 redis check started fix
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.service.ts
  tslib/src/functions/check-started/check-started.service.ts
  tslib/src/functions/check-started/index.ts
  tslib/src/functions/check-sync/prepared-check-sync.service.ts
  tslib/src/functions/pupil-prefs/pupil-prefs.service.spec.ts
  tslib/src/functions/pupil-prefs/pupil-prefs.service.ts
  tslib/src/functions/school-results-cache/index.ts
  tslib/src/functions/school-results-cache/services/result.service.ts
Labels: CI Enabled, Signed Off

#1901 bug/46827 - tech support service bus queue shows total count instead of active
  admin/services/data-access/service-bus-queue-metadata.service.js
Labels: CI Enabled, Requires Tech Sign Off, Signed Off, Tested

#1902 bug/46824 - per environment service bus configuration
  deploy/service-bus/create-or-update.js
  deploy/service-bus/create.js
  deploy/service-bus/delete.js
  deploy/service-bus/deploy.config.js
  deploy/service-bus/get.deploy.config.js
  deploy/service-bus/package.json
  deploy/service-bus/queues-topics.json
  deploy/service-bus/yarn.lock
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/features/helpdesk_pin_usage.feature
  test/admin-hpa/features/service_bus_queue_config.feature
  test/admin-hpa/features/step_definitions/helpdesk_pin_steps.rb
  test/admin-hpa/features/step_definitions/service_bus_queue_config_steps.rb
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/features/support/helpers.rb
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Signed Off, Tested

#1915 Feature/roll up security prs
  admin/package.json
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  load-test/package.json
  pupil-api/package.json
  pupil-api/yarn.lock
  test/admin-hpa/Gemfile
  test/pupil-hpa/Gemfile
  tslib/package.json
  tslib/yarn.lock
Labels: CI Enabled, Ready for review, Requires Tech Sign Off, Signed Off, Tested

#1916 skipping service bus tests until ready
  test/admin-hpa/features/service_bus_queue_config.feature
Labels: CI Enabled, Requires Tech Sign Off, Signed Off, Tested
