Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2021-02, with the labels that each got.

#1811 Fix date validator
  admin/lib/validator/common/date-validator.js
  admin/spec/back-end/lib/validator/common/date-validator.spec.js
Labels: CI Enabled, QA: regression only, Tested

#1812 feature/45265 - creating new schools and adding pupils for every scenario
  test/admin-hpa/features/access_arrangements.feature
  test/admin-hpa/features/add_multiple_pupil_validation_error.feature
  test/admin-hpa/features/breadcrumbs.feature
  test/admin-hpa/features/declaration_confirm.feature
  test/admin-hpa/features/declaration_edit_reason.feature
  test/admin-hpa/features/declaration_form.feature
  test/admin-hpa/features/declaration_review_pupils.feature
  test/admin-hpa/features/declaration_submitted.feature
  test/admin-hpa/features/generate_pupil_pin_familiarisation.feature
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/pupil_not_taking_check.feature
  test/admin-hpa/features/restarts.feature
  test/admin-hpa/features/results.feature
  test/admin-hpa/features/service_manager_message.feature
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/declaration_submitted_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/groups_steps.rb
  test/admin-hpa/features/step_definitions/helpdesk_pin_steps.rb
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
  test/admin-hpa/features/step_definitions/pupil_status_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/step_definitions/result_page_steps.rb
  test/admin-hpa/features/step_definitions/retro_input_steps.rb
  test/admin-hpa/features/step_definitions/service_message.rb
  test/admin-hpa/features/step_definitions/sign_in_steps.rb
  test/admin-hpa/features/step_definitions/unauthorized_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/add_multiple_pupil_page.rb
  test/admin-hpa/features/support/page_objects/restarts_page.rb
  test/admin-hpa/features/support/upn_generator.rb
  test/pupil-hpa/features/step_definitions/pupil_api.rb
Labels: CI Enabled, Reviewed & approved, Tested, ruby

#1808 [admin] Improve formatting for pupil search
  .gitignore
  admin/assets/javascripts/mtc-autocomplete.js
  admin/package.json
  admin/services/pupil-access-arrangements.service.js
  admin/services/retro-input-assistant.service.js
  admin/spec/back-end/service/pupil-access-arrangements.service.spec.js
  admin/views/access-arrangements/retro-add-input-assistant.ejs
  admin/views/access-arrangements/select-access-arrangements.ejs
  test/admin-hpa/data/multiple_pupils_errors.csv
  test/admin-hpa/features/restarts.feature
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/pupil-hpa/Rakefile
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved, Tested

#1810 bug/45311 disable xss protection for admin and pupil-spa
  admin-assets/nginx/default.conf
  pupil-spa/nginx/default.conf
Labels: CI Enabled, Requires Tech Sign Off, Reviewed & approved

#1814 Feature/44351 move pupil la codes to db
  admin/lib/validator/pupil-validator.js
  admin/services/data-access/la-code.data.service.js
  admin/services/la-code.service.js
  admin/services/redis-key.service.js
  admin/services/upn.service.js
  admin/spec/back-end/lib/validator/pupil-validator.spec.js
  admin/spec/back-end/service/la-code.service.spec.js
  db/migrations/core-data/20210129171943.do.populate-la-code-table.sql
  db/migrations/core-data/20210129171943.undo.populate-la-code-table.sql
  db/migrations/schema-objects/20210129162635.do.create-new-la-table.sql
  db/migrations/schema-objects/20210129162635.undo.create-new-la-table.sql
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/admin-hpa/features/support/upn_helper.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
  test/pupil-hpa/features/support/upn_helper.rb
Labels: CI Enabled, QA: regression only, Requires Tech Sign Off, Reviewed & approved, Tested

#1824 bug/45543 - verify API headers tests fix
  admin-assets/nginx/example.conf
  api_tests/spec/security_spec.rb
  func-consumption/host.json
  func-throttled/host.json
  pupil-spa/nginx/example.conf
Labels: CI Enabled, Requires Tech Sign Off, Signed Off

#1823 Feature/45538 security pr roll up
  admin/package.json
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: CI Enabled, QA: regression only, Tested

#1818 bug/45474 deleting access arrangement with invalid UUID crashes node
  admin/controllers/access-arrangements.js
  admin/services/pupil-access-arrangements.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/service/pupil-access-arrangements.service.spec.js
Labels: CI Enabled, Tested

#1828 Add sign-out link to the service unavailable page
  admin/views/availability/admin-window-unavailable.ejs
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/data_sync_steps.rb
  test/admin-hpa/features/step_definitions/declaration_submitted_steps.rb
  test/admin-hpa/features/step_definitions/edit_pupil_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
  test/admin-hpa/features/step_definitions/pupil_status_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/step_definitions/result_page_steps.rb
  test/admin-hpa/features/step_definitions/tech_support_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/pupil-hpa/features/step_definitions/pupil_data_sync_steps.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled, Reviewed & approved, Signed Off, Tested
