Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2021-12, with the labels that each got.

#2034 Feature/49964 regression test containers Part #1
  admin/config.js
  admin/db-check.js
  db/dev.Dockerfile
  db/run-dev-migrations.sh
  db/wait-for-it.sh
  deploy/docker/functions-base/push.sh
  deploy/regression-test-container/_run.sh
  deploy/regression-test-container/docker-compose.yml
  deploy/regression-test-container/readme.md
  docker-compose-apps.yml
  func-consumption/db-check.js
  func-consumption/dev.Dockerfile
  func-consumption/package.json
  func-consumption/test.Dockerfile
  func-throttled/Dockerfile
  func-throttled/db-check.js
  func-throttled/dev.Dockerfile
  func-throttled/package.json
  func-throttled/test.Dockerfile
  functions-app/db-check.js
  functions-app/dev.Dockerfile
  pupil-api/Dockerfile
Labels: QA: regression only, DNM - Requires Testing, Tested, Reviewed & approved, Signed Off, CI Enabled, Requires Tech Sign Off

#2047 Fix weekend run
  test/admin-hpa/Rakefile
  test/admin-hpa/config/cucumber.yml
  test/pupil-hpa/Rakefile
  test/pupil-hpa/config/cucumber.yml
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off, ruby

#2042 Feature/load test data gen
  admin/package.json
  admin/yarn.lock
  db/engine/create-seed.js
  db/migrations/schema-objects/20211125124332.do.create-udf-upn-check-letter.sql
  db/migrations/schema-objects/20211125124332.undo.create-udf-upn-check-letter.sql
  db/migrations/schema-objects/20211125144734.do.stored-procedure-generate-test-pupils.js
  db/migrations/schema-objects/20211125144734.undo.stored-procedure-generate-test-pupils.js
  db/sql.config.js
  db/yarn.lock
  pupil-spa/package.json
  pupil-spa/src/app/services/app-insights/app-insights.service.ts
  pupil-spa/yarn.lock
Labels: Tested, Reviewed & approved, CI Enabled, Requires Tech Sign Off

#2035 Feature/48948 2022 teacher pin gen scenario
  load-test/scenarios/2022/live-long-teacher-journey-with-check-submit-v3.jmx
  load-test/walkthrough-documents/Create-Full-Production-Size-Static-Test-Data-for-Load-Testing-v01-draft.md
  load-test/walkthrough-documents/Create-Full-Production-Size-Static-Test-Data-for-Load-Testing-v02-draft.md
Labels: Signed Off, CI NOT Required, Requires Tech Sign Off, QA Not required

#2049 Feature/44554 service bus v7 tslib
  func-consumption/package.json
  func-consumption/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  tslib/package.json
  tslib/src/functions-throttled/sync-results-init/sync-results-init.service.ts
  tslib/src/functions/check-notifier-batch/index.ts
  tslib/src/functions/school-results-cache/index.ts
  tslib/yarn.lock
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2051 Add service message edit feature
  admin/controllers/service-message.js
  admin/routes/service-message.js
  admin/services/administration-message.service.js
  admin/services/data-access/administration-message.data.service.js
  admin/spec/back-end/controllers/service-message.spec.js
  admin/spec/back-end/service/administration-message.service.spec.js
  admin/views/service-message/service-message-form.ejs
  admin/views/service-message/service-message-overview.ejs
  test/admin-hpa/features/service_manager_message.feature
  test/admin-hpa/features/step_definitions/service_message.rb
  test/admin-hpa/features/support/page_objects/manage_service_message_page.rb
Labels: Tested, Ready to merge, Reviewed & approved, Signed Off, CI Enabled
