Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2022-10, with the labels that each got.

#2279 feature/53058 - swap standard for eslint in admin app
  admin/.eslintrc
  admin/.eslintrc.js
  admin/assets/javascripts/mtc-autocomplete.js
  admin/config.js
  admin/controllers/hdf.js
  admin/controllers/pupil-status.js
  admin/controllers/retro-input-assistant.js
  admin/controllers/service-manager.js
  admin/controllers/service-message.js
  admin/controllers/tech-support.js
  admin/models/logger.js
  admin/package.json
  admin/server.js
  admin/services/azure-table-storage.service.js
  admin/services/check-start.service/check-start.service.js
  admin/services/check-window-phase/check-window-phase.service.spec.ts
  admin/services/check-window-phase/check-window-phase.service.ts
  admin/services/data-access/queue-sas-token.data.service.js
  admin/services/discretionary-restart.service/data-access/discretionary-restart.data.service.ts
  admin/services/discretionary-restart.service/discretionary-restart.service.spec.ts
  admin/services/job-service/data-access/job.data.service.ts
  admin/services/job-service/job.service.spec.ts
  admin/services/job-service/job.service.ts
  admin/services/prepare-check.service.js
  admin/services/pupil-frozen.service/pupil-frozen.data.service.ts
  admin/services/pupil-frozen.service/pupil-frozen.service.spec.ts
  admin/services/pupil-frozen.service/pupil-frozen.service.ts
  admin/services/pupil-history-service/data-access/pupil-history.data.service.spec.ts
  admin/services/pupil-history-service/data-access/pupil-history.data.service.ts
  admin/services/pupil-history-service/pupil-history-service.ts
  admin/services/pupil-history-service/pupil-history.service.spec.ts
  admin/services/result.service.js
  admin/services/sas-token.service.js
  admin/services/service-manager/pupil-annulment/pupil-annulment.service.spec.ts
  admin/services/service-manager/pupil-annulment/pupil-annulment.service.ts
  admin/services/service-manager/pupil-service/service-manager.pupil.data.service.ts
  admin/services/service-manager/pupil-service/service-manager.pupil.service.spec.ts
  admin/services/service-manager/pupil-service/service-manager.pupil.service.ts
  admin/services/tech-support/ps-report-logs.service/data-access/ps-report-logs.data.service.ts
  admin/services/tech-support/ps-report-logs.service/ps-report-logs.service.spec.ts
  admin/services/tech-support/ps-report-logs.service/ps-report-logs.service.ts
  admin/services/tech-support/sync-results-resync.service.js
  admin/services/type-of-establishment-service/type-of-establishment-service.ts
  admin/services/type-of-establishment-service/type-of-establishment.data.service.ts
  admin/spec/back-end/controllers/authentication.spec.js
  admin/spec/back-end/controllers/tech-support.spec.js
  admin/spec/back-end/service/config.service.spec.js
  admin/spec/back-end/service/dfe-signin.service.spec.js
  admin/spec/back-end/service/result.service.spec.js
  admin/spec/back-end/service/retro-input-assistant.service.spec.js
  admin/spec/back-end/service/school.service.spec.js
  admin/tests-integration/azure-table.data.service.spec.js
  admin/tests-integration/sql.service.spec.js
  admin/tsconfig.json
  admin/yarn.lock
  pupil-spa/yarn.lock
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2318 check started fix
  test/pupil-hpa/features/support/helpers.rb
  test/pupil-hpa/features/support/hooks.rb
Labels: bug, Tested, Signed Off, CI Enabled

#2319 Bug/55188 service unavailable page shows wrong academic year
  admin/availability/middleware.js
  admin/package.json
  admin/views/availability/admin-window-unavailable.ejs
  admin/yarn.lock
Labels: Tested, Signed Off, CI Enabled

#2321 add hooks to tests which are to assert for check started timestamp
  test/pupil-hpa/features/check.feature
  test/pupil-hpa/features/support/hooks.rb
Labels: Tested, CI Enabled, Requires Tech Sign Off, ruby

#2310 Feature/55006 upgrade jquery
  admin/assets/vendor-js/jquery-3.5.1.js
  admin/assets/vendor-js/jquery-3.6.1.min.js
  admin/gulpfile.js
  admin/package.json
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled, Requires Tech Sign Off

#2323 Update school_import_steps.rb
  test/admin-hpa/features/step_definitions/school_import_steps.rb
Labels: Tested, CI Enabled, ruby

#2315 bug/53493 restart deletion logic error
  admin/package.json
  admin/services/restart-v2.service.js
  admin/spec/back-end/service/restart-v2.service.spec.js
  test/pupil-hpa/features/pin_expiry.feature
  test/pupil-hpa/features/step_definitions/pin_expiry_steps.rb
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
Labels: Tested, Signed Off, CI Enabled
