Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2022-01, with the labels that each got.

#2057 Fix unit tests
  admin/lib/validator/check-window-v2/check-window-add-validator.js
  admin/spec/back-end/lib/validator/check-window-v2/check-window-add-validator.spec.js
  admin/spec/back-end/lib/validator/common/date-validator.spec.js
Labels: Reviewed & approved, CI Enabled

#2060 Update add_school_steps.rb
  test/admin-hpa/features/step_definitions/add_school_steps.rb
Labels: Tested, Ready to merge, Reviewed & approved, CI Enabled, ruby

#2043 Feature/48515 appinsights metadata enhancements
  pupil-spa/src/app/services/app-insights/app-insights.service.ts
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2056 Feature/50831 school record change auditing
  admin/controllers/service-manager.js
  admin/services/data-access/school.data.service.js
  admin/services/school.service.js
  admin/spec/back-end/controllers/service-manager.spec.js
  admin/spec/back-end/service/school.service.spec.js
  db/migrations/schema-objects/20211208124902.do.enable-change-data-capture.sql
  db/migrations/schema-objects/20211208124902.undo.enable-change-data-capture.sql
  db/migrations/schema-objects/20211208124914.do.track-school-changes-cdc.sql
  db/migrations/schema-objects/20211208124914.undo.track-school-changes-cdc.sql
  db/migrations/schema-objects/20211209150158.do.school-last-modified-by-user-id.sql
  db/migrations/schema-objects/20211209150158.undo.school-last-modified-by-user-id.sql
  deploy/build-defs/validate-pr-db-migrations.yml
  deploy/regression-test-container/docker-compose.yml
  docker-compose.yml
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled, Requires Tech Sign Off

#2058 Feature/50957 check replay
  _spikes-poc/anonymise-sql-data/create-dummy-schools.sql
  deploy/sql/anonymise-sql-data/pupil-anon.sql
  deploy/sql/anonymise-sql-data/school-anon.sql
  deploy/sql/anonymise-sql-data/user-anon.sql
  deploy/sql/check-replay/readme.md
  deploy/sql/check-replay/reset-state-pupils-checks.sql
  docs/support-utils/util-check-replay.md
  docs/support-utils/util-submit-check.md
  tslib/src/functions/check-marker/answers-mock.json
  tslib/src/functions/check-marker/check-marker.v1.spec.ts
  tslib/src/functions/util-replay-check/index.ts
  tslib/src/functions/util-replay-check/readme.md
  tslib/src/functions/util-replay-check/received-check-payload.data.service.ts
  tslib/src/functions/util-replay-check/received-check-payload.service.spec.ts
  tslib/src/functions/util-replay-check/received-check-payload.service.ts
  tslib/src/schemas/large-complete-check-V2.json
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled, Requires Tech Sign Off

#2059 Admin app: pin generation UX clarifications
  admin/controllers/pupil-pin.js
  admin/controllers/school.js
  admin/package.json
  admin/routes/pupil-pin.js
  admin/services/pupil-pin-presentation-service.js
  admin/services/school-home-page/school-home-page.service.js
  admin/services/school-home-page/school-home-page.service.spec.js
  admin/spec/back-end/service/pupil-pin-presentation-service.spec.js
  admin/views/partials/pupil-pin/active-button.ejs
  admin/views/partials/pupil-pin/inactive-button.ejs
  admin/views/pupil-pin/generate-pins-list.ejs
  admin/views/pupil-pin/generate-pins-overview.ejs
  admin/views/pupil-pin/select-official-or-try-it-out-pins.ejs
  admin/views/pupil-pin/view-and-custom-print-pins.ejs
  admin/views/school/school-home.ejs
  pupil-spa/src/app/instructions/instructions.component.html
  pupil-spa/src/app/instructions/instructions.component.spec.ts
  pupil-spa/src/app/instructions/instructions.component.ts
  pupil-spa/src/app/login-success/login-success.component.html
  pupil-spa/src/app/login-success/login-success.component.spec.ts
  pupil-spa/src/app/login-success/login-success.component.ts
  test/admin-hpa/features/breadcrumbs.feature
  test/admin-hpa/features/csrf.feature
  test/admin-hpa/features/generate_pupil_pin_familiarisation.feature
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/school_landing.feature
  test/admin-hpa/features/step_definitions/breadcrumbs_steps.rb
  test/admin-hpa/features/step_definitions/custom_pins_familiarisation_steps.rb
  test/admin-hpa/features/step_definitions/declaration_submitted_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pin_familiarisation_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/helpdesk_pin_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/step_definitions/school_landing_page_steps.rb
  test/admin-hpa/features/step_definitions/view_and_custom_print_for_live_check_steps.rb
  test/admin-hpa/features/support/helpers.rb
  test/admin-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/admin-hpa/features/support/page_objects/generate_pins_overview_page.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
  test/admin-hpa/features/support/page_objects/tio_or_live_pins_page.rb
  test/pupil-hpa/features/step_definitions/access_arrangement_steps.rb
  test/pupil-hpa/features/step_definitions/login_page_steps.rb
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/pupil-hpa/features/step_definitions/pupil_api.rb
  test/pupil-hpa/features/step_definitions/retro_input_steps.rb
  test/pupil-hpa/features/support/helpers.rb
  test/pupil-hpa/features/support/page_objects/generate_pins_familiarisation_overview_page.rb
  test/pupil-hpa/features/support/page_objects/generate_pins_overview_page.rb
  test/pupil-hpa/features/support/page_objects/start_page.rb
  test/pupil-hpa/features/support/page_objects/tio_or_live_pins_page.rb
  test/pupil-hpa/features/support/page_objects/view_and_custom_print_live_check_page.rb
  test/pupil-hpa/features/support/page_objects/view_and_print_pins_page.rb
Labels: Tested, Reviewed & approved, CI Enabled, Requires Tech Sign Off

#2070 Feature/security rollup ramda 0.27.2
  admin/package.json
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  load-test/package.json
  pupil-api/package.json
  pupil-api/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: Tested, Reviewed & approved, CI Enabled

#2090 Roll up security updates
  admin/package.json
  admin/yarn.lock
  db/yarn.lock
  func-consumption/yarn.lock
  func-throttled/yarn.lock
  load-test/yarn.lock
  pupil-api/yarn.lock
  pupil-spa/yarn.lock
Labels: Tested, Reviewed & approved, CI Enabled, security-roll-up

#2091 update page objects
  test/admin-hpa/features/step_definitions/breadcrumbs_steps.rb
  test/admin-hpa/features/step_definitions/csrf_steps.rb
  test/admin-hpa/features/step_definitions/custom_pins_familiarisation_steps.rb
  test/admin-hpa/features/step_definitions/declaration_submitted_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pin_familiarisation_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/helpdesk_pin_steps.rb
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
  test/admin-hpa/features/step_definitions/pupil_status_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/step_definitions/view_and_custom_print_for_live_check_steps.rb
  test/admin-hpa/features/support/helpers.rb
  test/admin-hpa/features/support/page_objects/generate_live_pins_overview_page.rb
  test/admin-hpa/features/support/page_objects/generate_tio_pins_overview_page.rb
  test/admin-hpa/features/support/page_objects/view_and_print_live_pins_page.rb
  test/admin-hpa/features/support/page_objects/view_and_print_tio_pins_page.rb
Labels: Tested, Ready for review, Reviewed & approved, CI Enabled, ruby

#2069 Feature/41055 allow removal of retro input assistant
  admin/controllers/access-arrangements.js
  admin/controllers/retro-input-assistant.js
  admin/routes/access-arrangements.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/services/data-access/retro-input-assistant.data.service.js
  admin/services/retro-input-assistant.service.js
  admin/spec/back-end/authentication/local-strategy.spec.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/controllers/accessibility-statement.spec.js
  admin/spec/back-end/controllers/authentication.spec.js
  admin/spec/back-end/controllers/check-window.spec.js
  admin/spec/back-end/controllers/contact.spec.js
  admin/spec/back-end/controllers/cookies.spec.js
  admin/spec/back-end/controllers/group.spec.js
  admin/spec/back-end/controllers/hdf.spec.js
  admin/spec/back-end/controllers/retro-input-assistant.spec.js
  admin/spec/back-end/controllers/tech-support.spec.js
  admin/spec/back-end/service/retro-input-assistant.service.spec.js
  admin/views/access-arrangements/overview.ejs
  test/admin-hpa/features/access_arrangements.feature
  test/admin-hpa/features/retro_input_assistance.feature
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/step_definitions/retro_input_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/access_arrangements_page.rb
  test/admin-hpa/features/support/page_objects/select_access_arrangements_page.rb
  test/pupil-hpa/features/pupil_access_arrangements.feature
  test/pupil-hpa/features/support/hooks.rb
  test/pupil-hpa/features/support/page_objects/access_arrangements_page.rb
  test/pupil-hpa/features/support/page_objects/select_access_arrangements_page.rb
Labels: Tested, Ready for review, Signed Off, CI Enabled
