Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2022-04, with the labels that each got.

#2173 Feature/52005 key vault ip update script
  deploy/build-defs/add-key-vault-ip.sh
  deploy/build-defs/add-key-vault-ip.yml
  deploy/build-defs/rotate-azure-keys.yml
Labels: CI Enabled

#2162 Feature/51974 ps report logging
  deploy/service-bus/deploy.config.js
  docs/support-utils/util-gen-ps-report-logs.md
  func-consumption/util-gen-ps-report-logs/function.json
  func-ps-report/ps-report-1-list-schools/function.json
  func-ps-report/ps-report-2-pupil-data/function.json
  func-ps-report/ps-report-3-transformer/function.json
  func-ps-report/ps-report-4-writer/function.json
  func-ps-report/ps-report-5-log-writer/function.json
  tslib/src/azure/blob-service.ts
  tslib/src/common/ContextLike.ts
  tslib/src/config.ts
  tslib/src/functions-ps-report/common/ps-report-log-entry.ts
  tslib/src/functions-ps-report/common/ps-report-logger.ts
  tslib/src/functions-ps-report/ps-report-1-list-schools/index.ts
  tslib/src/functions-ps-report/ps-report-1-list-schools/list-schools-service.spec.ts
  tslib/src/functions-ps-report/ps-report-1-list-schools/list-schools-service.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/index.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.data.service.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.service.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/index.ts
  tslib/src/functions-ps-report/ps-report-4-writer/index.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/index.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/log-entry-formatter.spec.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/log-entry-formatter.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/log-entry.converter.spec.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/log-entry.converter.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/log-generator.service.spec.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/log-generator.service.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/log-writer.spec.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/log-writer.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/log.service.spec.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/log.service.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/message-parser.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/mock-log-entries.json
  tslib/src/functions-ps-report/ps-report-5-log-writer/ps-report-log-set.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/service-bus-message-like.ts
  tslib/src/functions-throttled/census-import/v1.spec.ts
  tslib/src/functions/util-gen-ps-report-logs/index.ts
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2178 [Snyk] Rollup Security upgrade moment from 2.29.1 to 2.29.2
  admin/package.json
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: Tested, CI Enabled

#2193 52647 Security patches: bump moment from to 2.29.2 (dependabot rollup)
  db/package.json
  db/yarn.lock
  deploy/sql/package.json
  deploy/sql/yarn.lock
  design/spikes-poc/mssql-test/package.json
  design/spikes-poc/mssql-test/yarn.lock
  func-throttled/yarn.lock
  functions-app/package.json
  functions-app/yarn.lock
  load-test/yarn.lock
Labels: Tested, Ready to merge, CI Enabled, security-roll-up

#2186 Feature/52595 ps report log download
  admin/controllers/tech-support.js
  admin/routes/tech-support.js
  admin/services/tech-support/ps-report-logs.service/data-access/ps-report-logs.data.service.ts
  admin/services/tech-support/ps-report-logs.service/ps-report-logs.service.spec.ts
  admin/services/tech-support/ps-report-logs.service/ps-report-logs.service.ts
  admin/spec/back-end/controllers/tech-support.spec.js
  admin/views/tech-support/home.ejs
  admin/views/tech-support/ps-report-log-folder.ejs
  admin/views/tech-support/ps-report-logs.ejs
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2172 Feature/49323 service message border colour
  admin/assets/stylesheets/elements/_flash-messages.scss
  admin/controllers/service-message.js
  admin/lib/errors/service-message.js
  admin/package.json
  admin/services/administration-message.service.js
  admin/services/data-access/administration-message.data.service.js
  admin/services/school-home-page/school-home-page.service.spec.js
  admin/views/partials/_service_message.ejs
  admin/views/service-message/service-message-form.ejs
  db/migrations/schema-objects/20220325111343.do.alter-service-message-add-border-colour.sql
  db/migrations/schema-objects/20220325111343.undo.alter-service-message-add-border-colour.sql
  test/admin-hpa/features/service_manager_message.feature
  test/admin-hpa/features/step_definitions/service_message.rb
  test/admin-hpa/features/support/page_objects/create_message_page.rb
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
Labels: Tested, Ready to merge, Signed Off, CI Enabled

#2204 nokogiri update
  test/admin-hpa/Gemfile.lock
  test/pupil-hpa/Gemfile.lock
Labels: Tested, CI Enabled, ruby

#2208 Feature/52843 security
  func-ps-report/yarn.lock
  func-throttled/yarn.lock
  pupil-api/yarn.lock
Labels: Tested, CI Enabled, security-roll-up
