Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2022-09, with the labels that each got.

#2258 Feature/52150 school upload include toe8
  admin/controllers/service-manager.js
  admin/lib/validator/school-validator.js
  admin/package.json
  admin/services/data-access/school-audit.data.service.js
  admin/services/data-access/school.data.service.js
  admin/services/school.service.js
  admin/services/type-of-establishment-service/type-of-establishment-service.ts
  admin/services/type-of-establishment-service/type-of-establishment.data.service.ts
  admin/spec/back-end/controllers/service-manager.spec.js
  admin/spec/back-end/lib/validator/school-validator.spec.js
  admin/spec/back-end/service/school.service.spec.js
  admin/views/service-manager/add-school.ejs
  admin/views/service-manager/organisation-detail-edit.ejs
  admin/views/service-manager/organisation-detail.ejs
  admin/yarn.lock
  db/engine/create-migration.js
  db/migrations/schema-objects/20220812125232.do.add-type-of-establishment-lookup-table.sql
  db/migrations/schema-objects/20220812125232.undo.add-type-of-establishment-lookup-table.sql
  db/migrations/schema-objects/20220815051904.do.add-new-col-typeofestablishmentlookup_id-to-school-table.sql
  db/migrations/schema-objects/20220815051904.undo.add-new-col-typeofestablishmentlookup_id-to-school-table.sql
  test/admin-hpa/features/service_manager_school_audit.feature
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/add_school_steps.rb
  test/admin-hpa/features/step_definitions/edit_school_steps.rb
  test/admin-hpa/features/step_definitions/search_schools_steps.rb
  test/admin-hpa/features/step_definitions/service_manager_school_audit_steps.rb
  test/admin-hpa/features/support/page_objects/add_multiple_pupil_page.rb
  test/admin-hpa/features/support/page_objects/add_school_page.rb
  test/admin-hpa/features/support/page_objects/edit_school_page.rb
  test/admin-hpa/features/support/page_objects/school_search_results_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  tslib/src/functions-throttled/school-import/data-access/ISchoolRecord.ts
  tslib/src/functions-throttled/school-import/data-access/school.data.service.ts
  tslib/src/functions-throttled/school-import/predicates.spec.ts
  tslib/src/functions-throttled/school-import/predicates.ts
Labels: Tested, Ready to merge, Signed Off, CI Enabled

#2267 Feature/security rollup 02092022
  admin/package.json
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: Tested, CI Enabled, security-roll-up

#2257 Feature/54124 add created at to sm pupil search results
  admin/services/service-manager/pupil-service/service-manager.pupil.data.service.ts
  admin/services/service-manager/pupil-service/service-manager.pupil.service.spec.ts
  admin/services/service-manager/pupil-service/service-manager.pupil.service.ts
  admin/views/service-manager/pupil-search.ejs
  test/admin-hpa/features/service_manager_pupil_search.feature
  test/admin-hpa/features/step_definitions/service_manager_pupil_search_steps.rb
  test/admin-hpa/features/support/page_objects/pupil_search_page.rb
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled

#2256 Feature/54160 remove rate limiter from pupil-api
  admin/services/tech-support/redis.service.js
  deploy/release-config/pupil-api.base.txt
  deploy/release-config/z_original-archive/dev-test-demo-load/pupil-api.txt
  deploy/release-config/z_original-archive/preprod-prod/pupil-api.txt
  docs/environment-variables.md
  pupil-api/package.json
  pupil-api/src/App.ts
  pupil-api/src/config.ts
  pupil-api/src/helpers/rate-limit.ts
  pupil-api/src/typings/index.d.ts
  pupil-api/yarn.lock
  test/admin-hpa/Gemfile.lock
  test/pupil-hpa/Gemfile.lock
Labels: Tested, Signed Off, CI Enabled

#2278 Feature/080922 security roll up
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: Tested, CI Enabled, security-roll-up

#2259 feature/36197 - ensure production assets install runtime node modules only
  admin/Dockerfile
  admin/README.md
  admin/config.js
  admin/dev.Dockerfile
  admin/package.json
  db/dev.Dockerfile
  db/run-dev-migrations.sh
  deploy/build-defs/validate-pr-db-migrations.yml
  deploy/load-test/do.sh
  deploy/sql/config.js
  deploy/sql/package.json
  deploy/sql/vso-validate-migrations/migrate-db.sh
  deploy/sql/vso-validate-migrations/seed-db.sh
  deploy/sql/vso-validate-migrations/vso-migrate-up.sh
  design/spikes-poc/batch-service/docker-worker/Dockerfile
  docker-compose-apps.yml
  docker-compose.functions.yml
  load-test/load-18k-teacher-pupils.sh
  load-test/prep-local-db.sh
  pupil-api/Dockerfile
  pupil-api/dev.Dockerfile
  pupil-api/docker-start-dev.sh
  pupil-api/package.json
  pupil-spa/dev.Dockerfile
  run-docker-compose-travis.sh
  tslib/src/config.ts
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2295 bug/54798 assets image contains no assets
  admin-assets/copy-assets.sh
Labels: CI Enabled

#2285 Feature/12092022 security roll up
  admin/package.json
  admin/yarn.lock
  db/seeds/20181116152712.custom.sixty-pupils-per-school.js
  docker-compose.yml
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  tslib/package.json
  tslib/src/functions/check-sync/prepared-check-merge.service.ts
  tslib/yarn.lock
Labels: Tested, Ready to merge, CI Enabled, security-roll-up

#2302 bug/54886 pupil auth failing to start
  pupil-api/package.json
Labels: CI Enabled

#2260 Bug/53881 ps report initial non numeric key used as tfirstkey
  docs/psychometric-report-data-sourcing.md
  tslib/src/functions-ps-report/ps-report-3-transformer/report-line-answer.class.spec.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/report-line-answer.class.ts
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2266 Feature/54193 add check started timestamp to sql db
  db/migrations/schema-objects/20220901154203.do.check.startedat.sql
  db/migrations/schema-objects/20220901154203.undo.check.startedat.sql
  deploy/storage/tables-queues.json
  func-consumption/check-started/function.json
  pupil-spa/src/app/questions-intro/questions-intro.component.ts
  pupil-spa/src/app/services/audit/auditEntry.ts
  pupil-spa/src/app/services/check-start/check-start.service.spec.ts
  pupil-spa/src/app/services/check-start/check-start.service.ts
  test/pupil-hpa/features/step_definitions/check_steps.rb
  test/pupil-hpa/features/step_definitions/device_steps.rb
  test/pupil-hpa/features/step_definitions/familiarisation_check_steps.rb
  test/pupil-hpa/features/step_definitions/loading_page_steps.rb
  test/pupil-hpa/features/step_definitions/pin_expiry_steps.rb
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/pupil-hpa/features/step_definitions/retro_input_steps.rb
  test/pupil-hpa/features/step_definitions/state_steps.rb
  test/pupil-hpa/features/support/helpers.rb
  tslib/src/functions/check-started/check-started.data.service.ts
  tslib/src/functions/check-started/check-started.service.spec.ts
  tslib/src/functions/check-started/check-started.service.ts
  tslib/src/functions/check-started/index.ts
  tslib/src/functions/check-started/readme.md
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2304 Feature/security updates 20220921
  admin/package.json
  admin/yarn.lock
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled, Requires Tech Sign Off

#2268 Bug/54381 check marker treat azure errors as soft errors
  admin/services/data-access/retry-async.js
  admin/services/data-access/sql.service.js
  admin/spec/back-end/service/data-access/retry-async.spec.js
  admin/yarn.lock
  test/pupil-hpa/features/support/helpers.rb
  tslib/src/sql/async-retry.spec.ts
  tslib/src/sql/async-retry.ts
  tslib/src/sql/sql.service.ts
Labels: QA: regression only, Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2270 Bug/54653 build agent update
  deploy/build-agent/Dockerfile
  deploy/build-agent/readme.md
Labels: Tested, Reviewed & approved, Signed Off, CI NOT Required
