Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2022-03, with the labels that each got.

#2144 51816 restart wording change
  admin/services/restart-v2.service.js
  admin/spec/back-end/service/restart-v2.service.spec.js
Labels: Tested, CI Enabled, Requires sign off

#2143 Dependabot security rollup 2022-02-25
  db/yarn.lock
  func-throttled/yarn.lock
  pupil-spa/yarn.lock
Labels: Tested, CI Enabled

#2141 Feature/47152 tech support view marked check
  admin/controllers/tech-support.js
  admin/helpers/index.js
  admin/package.json
  admin/routes/tech-support.js
  admin/services/azure-table-storage.service.js
  admin/services/check-diagnostic.service.js
  admin/spec/back-end/controllers/tech-support.spec.js
  admin/spec/back-end/service/azure-table-storage.service.spec.js
  admin/spec/back-end/service/check-diagnostic.service.spec.js
  admin/views/tech-support/check-view.ejs
  admin/views/tech-support/home.ejs
  admin/views/tech-support/redis-drop-key.ejs
  test/admin-hpa/features/step_definitions/generate_pupil_pin_familiarisation_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/pupil_status_steps.rb
  test/admin-hpa/features/step_definitions/tech_support_steps.rb
  test/admin-hpa/features/support/page_objects/check_view_page.rb
  test/admin-hpa/features/support/page_objects/tech_support_page.rb
  test/admin-hpa/features/tech_support.feature
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2106 Feature/31386 add start and completed timestamps to jobs
  admin/controllers/service-manager.js
  admin/package.json
  admin/routes/service-manager.js
  admin/services/data-access/organisation-bulk-upload.data.service.js
  admin/services/job-service/data-access/job.data.service.ts
  admin/services/job-service/job.service.spec.ts
  admin/services/job-service/job.service.ts
  admin/services/organisation-bulk-upload.service.js
  admin/services/pupil-census.service.js
  admin/spec/back-end/controllers/service-manager.spec.js
  admin/spec/back-end/service/organisation-bulk-upload.service.spec.js
  admin/spec/back-end/service/pupil-census.service.spec.js
  admin/tsconfig.json
  admin/views/service-manager/bulk-upload-organisations.ejs
  admin/views/service-manager/jobs.ejs
  admin/views/service-manager/service-manager-home.ejs
  admin/views/service-manager/upload-pupil-census.ejs
  admin/yarn.lock
  db/migrations/schema-objects/20220203143948.do.job-startedat-completedat.sql
  db/migrations/schema-objects/20220203143948.undo.job-startedat-completedat.sql
  test/admin-hpa/features/step_definitions/school_import_steps.rb.rb
  test/admin-hpa/features/step_definitions/upload_pupil_census_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/view_jobs_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/admin-hpa/features/upload_pupil_census.feature
  tslib/src/common/job-status-code.ts
  tslib/src/functions-throttled/census-import/job.data.service.ts
  tslib/src/functions-throttled/census-import/v1.spec.ts
  tslib/src/functions-throttled/census-import/v1.ts
  tslib/src/functions-throttled/ps-report-4-writer/ps-report-writer.service.ts
  tslib/src/functions-throttled/school-import/SchoolImportError.ts
  tslib/src/functions-throttled/school-import/SchoolImportJobOutput.ts
  tslib/src/functions-throttled/school-import/SchoolmportJobOutput.spec.ts
  tslib/src/functions-throttled/school-import/data-access/school.data.service.ts
  tslib/src/functions-throttled/school-import/index.ts
  tslib/src/functions-throttled/school-import/school-import.service.spec.ts
  tslib/src/functions-throttled/school-import/school-import.service.ts
  tslib/src/functions-throttled/sync-results-to-sql/sync-results.data.service.ts
  tslib/src/functions/pupil-login/pupil-login.data.service.ts
  tslib/src/functions/pupil-login/pupil-login.service.ts
  tslib/src/functions/school-pin-generator/school-pin-replenishment.data.service.ts
  tslib/src/functions/school-pin-generator/school-pin-replenishment.service.spec.ts
  tslib/src/services/data/job.data.service.ts
  tslib/src/sql/sql.service.ts
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2150 bug/51933 fix AA edit validation bug
  admin/controllers/access-arrangements.js
  admin/services/pupil-access-arrangements-edit.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
Labels: Tested, Signed Off, CI Enabled

#2147 feature/51834 - remove usage of old service bus library from deploy/service-bus
  deploy/service-bus/create.js
  deploy/service-bus/delete.js
  deploy/service-bus/package.json
  deploy/service-bus/yarn.lock
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2157 feature/52149 update service bus queue size defaults
  deploy/service-bus/deploy.config.js
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2154 Bug 51948 update util submit check
  admin/package.json
  tslib/src/functions/util-submit-check/fake-check-inputs-generator.service.ts
  tslib/src/schemas/check-schemas/validated-check.ts
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2142 Update service-bus
  deploy/service-bus/yarn.lock
Labels: Tested, CI Enabled, Requires Tech Sign Off

#2155 bug 51879 / Clean up cookie-form html
  admin/assets/stylesheets/application.scss
  admin/package.json
  admin/views/cookies-form.ejs
  test/admin-hpa/features/step_definitions/cookies_steps.rb
  test/admin-hpa/features/support/page_objects/cookies_form_page.rb
Labels: Tested, Signed Off, CI Enabled

#2161 Feature/weekend test fix
  test/admin-hpa/features/support/functions_helper.rb
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/pupil-hpa/features/support/env.rb
  test/pupil-hpa/features/support/functions_helper.rb
Labels: Tested, CI Enabled, Requires Tech Sign Off, ruby

#2160 bug/52200-remove-download-link-from-testdev-homepage
  admin/package.json
  admin/views/test-developer/download-pupil-check-data.ejs
  admin/views/test-developer/test-developer-home.ejs
  test/admin-hpa/features/step_definitions/download_pupil_check_data_steps.rb
  test/admin-hpa/features/step_definitions/service_manager_landing_steps.rb
  test/admin-hpa/features/step_definitions/test_developer_homepage_steps.rb
Labels: Tested, Signed Off, CI Enabled

#2165 feature/52249-hide-feedback-link-in-page-header
  admin/views/partials/_gds_content.ejs
  test/admin-hpa/data/multiple_pupils_errors.csv
  test/admin-hpa/features/phase_banner.feature
  test/admin-hpa/rerun.txt
Labels: Tested, Signed Off, CI Enabled

#2164 Feature/52252 update 3 pages
  admin/views/accessibility-statement.ejs
  admin/views/cookies-form.ejs
  admin/views/cookies-mtc.ejs
  admin/views/privacy.ejs
Labels: Tested, Signed Off, CI Enabled

#2167 Feature/52315 la codes update
  db/migrations/schema-objects/20220325133310.do.update-la-codes.sql
  db/migrations/schema-objects/20220325133310.undo.update-la-codes.sql
  test/admin-hpa/features/support/upn_helper.rb
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled, expedited, Requires Tech Sign Off

#2163 Feature/52213 alignment incorrect on aa overview page
  admin/assets/stylesheets/elements/_pupils.scss
  admin/package.json
  admin/views/access-arrangements/overview.ejs
Labels: Tested, Signed Off, CI Enabled

#2159 Feature/51911 accessibility checkboxes
  admin/assets/stylesheets/application.scss
  admin/views/access-arrangements/select-access-arrangements.ejs
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off
