Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2022-11, with the labels that each got.

#2330 Update ps_report_steps.rb
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
Labels: bug, Ready to merge, CI Enabled, ruby, QA Not required

#2317 Feature/39703 pupil auditing
  admin/controllers/group.js
  admin/controllers/pupil.js
  admin/controllers/pupils-not-taking-the-check.js
  admin/controllers/restart.js
  admin/services/attendance.service.js
  admin/services/check-start.service/check-start.service.spec.js
  admin/services/data-access/group.data.service.js
  admin/services/data-access/pupil-attendance.data.service.js
  admin/services/data-access/pupil-restart.data.service.js
  admin/services/data-access/pupil.data.service.js
  admin/services/data-access/restart-v2.data.service.js
  admin/services/discretionary-restart.service/data-access/discretionary-restart.data.service.ts
  admin/services/discretionary-restart.service/discretionary-restart.service.spec.ts
  admin/services/discretionary-restart.service/discretionary-restart.service.ts
  admin/services/group.service.js
  admin/services/pupil-add-service.js
  admin/services/pupil-edit.service.js
  admin/services/pupil-frozen.service/pupil-frozen.data.service.ts
  admin/services/pupil-upload.service.js
  admin/services/pupil-validate-csv.service.js
  admin/services/service-manager/pupil-annulment/pupil-annulment.data.service.ts
  admin/spec/back-end/controllers/pupils-not-taking-the-check.spec.js
  admin/spec/back-end/controllers/restart.spec.js
  admin/spec/back-end/service/attendance.service.spec.js
  admin/spec/back-end/service/group.service.spec.js
  admin/spec/back-end/service/pupil-add-service.spec.js
  admin/spec/back-end/service/pupil-edit.service.spec.js
  admin/spec/back-end/service/pupil-upload.service.spec.js
  db/migrations/schema-objects/20220929142046.do.pupil-last-modified-by-user-id.sql
  db/migrations/schema-objects/20220929142046.undo.pupil-last-modified-by-user-id.sql
  db/migrations/schema-objects/20220929142116.do.pupil-audit-table.sql
  db/migrations/schema-objects/20220929142116.undo.pupil-audit-table.sql
  db/migrations/schema-objects/20220929142142.do.pupil-drop-updatedat-trigger.sql
  db/migrations/schema-objects/20220929142142.undo.pupil-drop-updatedat-trigger.sql
  db/migrations/schema-objects/20220929142357.do.pupil-audit-trigger.sql
  db/migrations/schema-objects/20220929142357.undo.pupil-audit-trigger.sql
  test/admin-hpa/features/pupil_audit.feature
  test/admin-hpa/features/step_definitions/edit_pupil_steps.rb
  test/admin-hpa/features/step_definitions/pupil_audit_steps.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
Labels: Tested, Signed Off, CI Enabled

#2332 Feature/55787 service unavailable wording
  admin/availability/middleware.js
  admin/package.json
  admin/views/availability/admin-window-unavailable.ejs
  test/admin-hpa/features/step_definitions/post_check_window_steps.rb
Labels: Tested, Signed Off, CI Enabled, expedited

#2339 Feature/55184 update school audit trigger
  admin/package.json
  db/migrations/schema-objects/20221122163818.do.fix-school-audit-trigger.sql
  db/migrations/schema-objects/20221122163818.undo.fix-school-audit-trigger.sql
  db/migrations/schema-objects/20221123132323.do.remove-fk-from-school-audit.sql
  db/migrations/schema-objects/20221123132323.undo.remove-fk-from-school-audit.sql
  db/migrations/schema-objects/20221125103800.do.alter-pupil-audit-remove-fk.sql
  db/migrations/schema-objects/20221125103800.undo.alter-pupil-audit-remove-fk.sql
  db/migrations/schema-objects/20221125104853.do.alter-pupil-audit-trigger.sql
  db/migrations/schema-objects/20221125104853.undo.alter-pupil-audit-trigger.sql
  docker-compose.yml
Labels: Tested, Signed Off, CI Enabled
