Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2023-01, with the labels that each got.

#2392 bug/56860 - fix data seeding SQL script issue
  db/seeds/20181116123710.custom.devtest-pupil-school.sql
Labels: CI Enabled, CI NOT Required

#2382 update ruby to v 2.7.7
  api_tests/Gemfile
  api_tests/Gemfile.lock
  api_tests/README.md
  deploy/build-agent-ruby/Dockerfile
  deploy/build-agent-ruby/build-push-docker-hub.sh
  deploy/build-agent-ruby/readme.md
  deploy/build-agent-ruby/ruby-base.Dockerfile
  deploy/build-agent/Dockerfile
  deploy/docker/circleci-ruby/Dockerfile
  deploy/docker/push-images-to-hub.sh
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/README.md
  test/admin-hpa/Rakefile
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  test/pupil-hpa/README.md
  test/pupil-hpa/Rakefile
  test/pupil-hpa/features/support/hooks.rb
Labels: Tested, CI Enabled, ruby

#2404 Feature/security 9 1 23
  admin/yarn.lock
  api_tests/Gemfile
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-api/yarn.lock
  pupil-spa/package.json
  pupil-spa/yarn.lock
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  tslib/package.json
  tslib/yarn.lock
Labels: Tested, CI Enabled, security-roll-up

#2406 feature/security-tests
  api_tests/browser-security-tests.sh
Labels: Tested, Ready to merge, Reviewed & approved, CI Enabled, ruby

#2407 App pupil gui - remove the add / edit buttons
  admin/app.js
  admin/availability/middleware.js
  admin/controllers/pupil-register.js
  admin/routes/access-arrangements.js
  admin/routes/group.js
  admin/routes/hdf.js
  admin/routes/pupil-pin.js
  admin/routes/pupil-register.js
  admin/routes/pupils-not-taking-the-check.js
  admin/routes/restart.js
  admin/routes/school.js
  admin/spec/back-end/controllers/pupil-register.spec.js
  test/admin-hpa/features/post_check_window_settings.feature
  test/admin-hpa/features/step_definitions/pupil_status_steps.rb
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled

#2415 Feature/security 23 1 23
  admin/package.json
  admin/yarn.lock
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
Labels: Tested, Ready for review, CI Enabled, security-roll-up

#2423 Feature/security 25 1 23
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  load-test/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: Tested, CI Enabled
