Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2023-10, with the labels that each got.

#2618 Feature/56368 csrf replacement
  admin/app.js
  admin/package.json
  admin/yarn.lock
  test/pupil-hpa/features/step_definitions/pupil_data_sync_steps.rb
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2628 Feature/security 4 10 23
  admin/package.json
  admin/yarn.lock
  design/spikes/batch-service/docker-worker/app/yarn.lock
  design/spikes/sb-queue-message-replay/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: Tested, CI Enabled, Requires Tech Sign Off, security-roll-up

#2620 Feature/60548 add school information header to roles
  admin/assets/stylesheets/application.scss
  admin/authentication/local-strategy.js
  admin/package.json
  admin/services/data-access/user.data.service.js
  admin/services/school-impersonation.service.js
  admin/views/partials/_name_and_sign_out.ejs
  admin/views/service-message/service-message-form.ejs
  test/admin-hpa/features/step_definitions/pupil_audit_steps.rb
  test/admin-hpa/features/step_definitions/school_landing_page_steps.rb
Labels: Tested, Ready to merge, Signed Off, CI Enabled

#2634 Feature/security roll up 17 10 23
  admin/package.json
  admin/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  pupil-spa/package.json
  pupil-spa/yarn.lock
  test/admin-hpa/features/step_definitions/pupil_audit_steps.rb
Labels: Tested, CI Enabled, Requires Tech Sign Off, security-roll-up

#2642 Feature/security 18 10 12
  admin/package.json
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  pupil-spa/package.json
  pupil-spa/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: Tested, CI Enabled, security-roll-up
