Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2023-07, with the labels that each got.

#2561 bug/59558 PS Report: set attemptId to null if never logged in
  test/pupil-hpa/features/a_ps_report.feature
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  tslib/src/functions-ps-report/ps-report-3-transformer/report-line.class.spec.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/report-line.class.ts
Labels: Tested, CI Enabled

#2564 Bug/59557 restart number null or int
  tslib/src/functions-ps-report/ps-report-3-transformer/mocks/check-incomplete.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/mocks/pupil-not-attending-annulled.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/report-line.class.spec.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/report-line.class.ts
Labels: Tested, CI Enabled, expedited

#2558 feature/59297 - log submission failed errors
  pupil-spa/nginx/default.conf
  pupil-spa/src/app/services/azure-queue/azure-queue.service.spec.ts
  pupil-spa/src/app/services/azure-queue/azure-queue.service.ts
  pupil-spa/src/app/services/check-complete/check-complete.service.spec.ts
  pupil-spa/src/app/services/check-complete/check-complete.service.ts
  test/admin-hpa/features/step_definitions/frozen_pupil_steps.rb
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2559 bug/53295 guard against errors when obtaining number of questions
  pupil-spa/src/app/services/question/question.service.spec.ts
  pupil-spa/src/app/services/question/question.service.ts
Labels: Tested, Reviewed & approved, CI Enabled, Requires Tech Sign Off

#2454 feature/54226 - Dfe Sign in Missing org info error distinction
  admin/error-types/DsiSchoolNotFoundError.js
  admin/services/dfe-signin.service.js
  admin/spec/back-end/service/dfe-signin.service.spec.js
Labels: CI Enabled

#2592 update env files
  test/admin-hpa/features/support/env.rb
  test/pupil-hpa/features/support/env.rb
Labels: Tested, CI Enabled, Requires Tech Sign Off
