Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2023-09, with the labels that each got.

#2611 bug/60482 Circle CI chromedriver failed install
  .circleci/config.yml
Labels: CI Enabled

#2612 Feature/security rollup 2023 9 11
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  load-test/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  pupil-spa/package.json
  pupil-spa/yarn.lock
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/features/support/page_objects/add_multiple_pupil_page.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  tslib/package.json
  tslib/src/caching/RedisCacheItemMetadata.ts
  tslib/src/common/compression-service.ts
  tslib/src/common/job-status-code.ts
  tslib/src/functions-ps-report/ps-report-5-log-writer/service-bus-message-like.ts
  tslib/src/functions/check-validator/validators/validator-types.ts
  tslib/src/functions/school-pin-generator/allowed-words.service.ts
  tslib/src/functions/school-pin-generator/job-log.data.service.ts
  tslib/src/functions/school-pin-generator/random-generator.spec.ts
  tslib/src/functions/school-pin-generator/school-pin-expiry-generator.ts
  tslib/src/functions/util-school-pin-http-service/index.ts
  tslib/src/schemas/check-notification-message.ts
  tslib/src/services/check-form.service.ts
  tslib/yarn.lock
Labels: Tested, Reviewed & approved, CI Enabled

#2607 bug/59511-late-payload-logic
  test/admin-hpa/features/step_definitions/pupil_audit_steps.rb
  tslib/src/functions/check-notifier-batch/batch-check-notifier.data.service.ts
  tslib/src/functions/check-notifier-batch/batch-check-notifier.service.spec.ts
  tslib/src/functions/check-notifier-batch/batch-check-notifier.service.ts
  tslib/src/functions/check-notifier-batch/index.ts
  tslib/src/functions/check-receiver/check-receiver.ts
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2609 feature/58506 restart refactor & consolidation
  admin/controllers/restart.js
  admin/services/data-access/pupil-restart.data.service.js
  admin/services/prepare-check.service.js
  admin/services/restart-v2.service.js
  admin/services/restart.service.js
  admin/spec/back-end/controllers/restart.spec.js
  admin/spec/back-end/service/data-access/pupil-restart.data.service.spec.js
  admin/spec/back-end/service/restart-v2.service.spec.js
  admin/spec/back-end/service/restart.service.spec.js
  test/pupil-hpa/features/a_ps_report.feature
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off
