Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2023-05, with the labels that each got.

#2501 bug/58963 - Gen 4 SQL Azure Retired. Switch to Gen 5 for PR validation
  deploy/build-defs/validate-pr-db-migrations.yml
Labels: CI Enabled

#2500 feature/58889 - Hide attendance codes
  admin/controllers/pupils-not-taking-the-check.js
  admin/services/data-access/attendance-code.data.service.js
  admin/services/data-access/pupil-attendance.data.service.js
  db/migrations/core-data/20230427142256.do.attendance-code-hide-absent.sql
  db/migrations/core-data/20230427142256.undo.attendance-code-hide-absent.sql
  db/migrations/schema-objects/20230427134557.do.attendance-code-visible-column.sql
  db/migrations/schema-objects/20230427134557.undo.attendance-code-visible-column.sql
  test/admin-hpa/features/pupil_audit.feature
  test/admin-hpa/features/pupil_not_taking_check.feature
  test/admin-hpa/features/pupil_status.feature
  test/admin-hpa/features/service_manager_pupil_search.feature
  test/admin-hpa/features/step_definitions/declaration_review_pupil_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
  test/admin-hpa/features/support/page_objects/pupil_reason_page.rb
  test/admin-hpa/features/support/sql_db_helper.rb
Labels: Tested, Ready to merge, Reviewed & approved, Signed Off, CI Enabled

#2503 feature/59001 grant additional schema permissions to analysis role
  db/migrations/user-permissions/20230503161141.do.analysis-schema-data-role-create-table-view.sql
  db/migrations/user-permissions/20230503161141.undo.analysis-schema-data-role-create-table-view.sql
Labels: CI Enabled, Requires Tech Sign Off, QA Not required

#2504 Feature/58445 freeze pupil 2
  admin/controllers/service-manager.js
  admin/package.json
  admin/routes/service-manager.js
  admin/services/service-manager/pupil-freeze/pupil-freeze.data.service.ts
  admin/services/service-manager/pupil-freeze/pupil-freeze.service.spec.ts
  admin/services/service-manager/pupil-freeze/pupil-freeze.service.ts
  admin/services/service-manager/pupil-service/service-manager.pupil.data.service.ts
  admin/services/service-manager/pupil-service/service-manager.pupil.service.spec.ts
  admin/services/service-manager/pupil-service/service-manager.pupil.service.ts
  admin/spec/back-end/controllers/service-manager.spec.js
  admin/views/partials/service-manager/pupil/_pupil-summary.ejs
  admin/views/service-manager/pupil-summary.ejs
  admin/views/service-manager/pupil/freeze.ejs
  admin/views/service-manager/pupil/thaw.ejs
  test/admin-hpa/features/frozen_pupil.feature
  test/admin-hpa/features/service_manager_pupil_search.feature
  test/admin-hpa/features/step_definitions/frozen_pupil_steps.rb
  test/admin-hpa/features/step_definitions/service_manager_pupil_search_steps.rb
  test/admin-hpa/features/support/helpers.rb
  test/admin-hpa/features/support/page_objects/admin_page.rb
  test/admin-hpa/features/support/page_objects/pupil_summary_page.rb
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled

#2506 Update pupil_audit_steps.rb
  test/admin-hpa/features/step_definitions/pupil_audit_steps.rb
Labels: Tested, CI Enabled, ruby

#2496 [58709] bug/58709-admin-cookies-breadcrumbs
  admin/views/cookies-form.ejs
  api_tests/Gemfile.lock
  api_tests/spec/security_spec.rb
  test/admin-hpa/features/breadcrumbs.feature
  test/admin-hpa/features/step_definitions/breadcrumbs_steps.rb
  test/admin-hpa/features/step_definitions/result_page_steps.rb
  test/pupil-hpa/features/a_ps_report.feature
Labels: Tested, Signed Off, CI Enabled

#2508 bug/56112 Fix Codacy Badge on Root Readme
  README.md
Labels: CI Enabled

#2499 Bug/58403 edge browser freezes
  pupil-spa/package.json
  pupil-spa/src/app/aa-colours/aa-colours.component.ts
  pupil-spa/src/app/aa-fonts/aa-fonts.component.ts
  pupil-spa/src/app/aa-settings/aa-settings.component.ts
  pupil-spa/src/app/check-complete/check-complete.component.ts
  pupil-spa/src/app/feedback-thanks/feedback-thanks.component.ts
  pupil-spa/src/app/feedback/feedback.component.ts
  pupil-spa/src/app/instructions/instructions.component.ts
  pupil-spa/src/app/loading/loading.component.spec.ts
  pupil-spa/src/app/loading/loading.component.ts
  pupil-spa/src/app/login-success/login-success.component.ts
  pupil-spa/src/app/modal/idle.modal.component.ts
  pupil-spa/src/app/out-of-time/out-of-time.component.ts
  pupil-spa/src/app/page-not-found/page-not-found.component.ts
  pupil-spa/src/app/practice-question/practice-question.component.spec.ts
  pupil-spa/src/app/qr-code-arrival/qr-code-arrival.component.spec.ts
  pupil-spa/src/app/qr-code-arrival/qr-code-arrival.component.ts
  pupil-spa/src/app/questions-intro/questions-intro.component.ts
  pupil-spa/src/app/services/speech/speech.service.ts
  pupil-spa/src/app/session-expired/session-expired.component.ts
  pupil-spa/src/app/spoken-practice-question/spoken-practice-question.component.spec.ts
  pupil-spa/src/app/submission-failed/submission-failed.component.ts
  pupil-spa/src/app/submission-pending/submission-pending.component.ts
  pupil-spa/src/app/warmup-complete/warmup-complete.component.ts
  pupil-spa/src/app/warmup-intro/warmup-intro.component.ts
  pupil-spa/yarn.lock
Labels: Reviewed & approved, Signed Off, CI Enabled

#2502 Feature/54228 hdf stop signing in relaxed view during the post check admin period
  admin/services/data-access/headteacher-declaration.data.service.js
  admin/services/headteacher-declaration.service.js
  admin/spec/back-end/service/headteacher-declaration.service.spec.js
  pupil-api/yarn.lock
  test/admin-hpa/features/declaration_form.feature
  test/admin-hpa/features/step_definitions/declaration_form_steps.rb
  test/admin-hpa/features/support/sql_db_helper.rb
Labels: Tested, CI Enabled, Requires Tech Sign Off, dependency updates
