Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2023-03, with the labels that each got.

#2459 Feature/57514 add test school flag to school
  admin/controllers/service-manager.js
  admin/package.json
  admin/services/data-access/school.data.service.js
  admin/services/school.service.js
  admin/views/service-manager/add-school.ejs
  admin/views/service-manager/organisation-detail-edit.ejs
  admin/views/service-manager/organisation-detail.ejs
  db/config.js
  db/engine/migrate.js
  db/package.json
  db/sql.config.js
  db/yarn.lock
  test/admin-hpa/features/service_manager_add_school.feature
  test/admin-hpa/features/service_manager_edit_school.feature
  test/admin-hpa/features/step_definitions/add_school_steps.rb
  test/admin-hpa/features/step_definitions/edit_school_steps.rb
  test/admin-hpa/features/step_definitions/helpdesk_pin_steps.rb
  test/admin-hpa/features/step_definitions/school_landing_page_steps.rb
  test/admin-hpa/features/step_definitions/service_manager_move_pupil_steps.rb
  test/admin-hpa/features/step_definitions/service_manager_pupil_search_steps.rb
  test/admin-hpa/features/support/functions_helper.rb
  test/admin-hpa/features/support/helpers.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/add_school_page.rb
  test/admin-hpa/features/support/page_objects/edit_school_page.rb
  test/pupil-hpa/features/a_ps_report.feature
  test/pupil-hpa/features/support/functions_helper.rb
  test/pupil-hpa/features/support/helpers.rb
  test/pupil-hpa/features/support/hooks.rb
Labels: Tested, Signed Off, CI Enabled, dependency updates

#2402 feature/56478 2nd PR for ITHC setup
  db/seeds/20181116131308.custom.sample-admin-users.sql
  deploy/build-defs/rotate-azure-keys.yml
  deploy/key-rotation/readme.md
  deploy/keys/express-session.sh
  deploy/keys/functions.sh
  deploy/keys/integration-test.sh
  deploy/keys/key-update.yml
  deploy/keys/keyvault-update.sh
  deploy/keys/readme.md
  deploy/keys/redis.sh
  deploy/keys/service-bus.sh
  deploy/keys/storage.sh
  docs/environment-variables.md
Labels: Tested, CI Enabled

#2458 feature/56369 unsupported browser app insights tracking
  pupil-spa/docker-start.sh
  pupil-spa/nginx/default.conf
  pupil-spa/unsupported/browser.html
Labels: Tested, Signed Off, CI Enabled

#2470 bug/58316 - NGINX try_files config issue on /sign-in
  pupil-spa/nginx/default.conf
Labels: Tested, CI Enabled, Requires Tech Sign Off

#2469 feature/58240 guidance content changes
  admin/views/restart/restart-overview.ejs
  admin/views/school/school-home.ejs
  test/admin-hpa/features/support/page_objects/school_landing_page.rb
Labels: Tested, CI Enabled, Requires Tech Sign Off

#2475 Feature/security 15 3 23
  admin/package.json
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-spa/package.json
  pupil-spa/yarn.lock
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/features/step_definitions/create_window_steps.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  tslib/package.json
  tslib/yarn.lock
Labels: Tested, Reviewed & approved, CI Enabled, security-roll-up

#2465 Feature/58072 mtc closed guard
  admin/app.js
  admin/error-types/system-unavailable-error.js
  admin/services/dfe-signin.service.js
  admin/spec/back-end/service/dfe-signin.service.spec.js
Labels: Tested, CI Enabled

#2477 feature/58378 dedicated school not found page
  admin/app.js
  admin/error-types/DsiSchoolNotFoundError.js
  admin/lib/errors/user.js
  admin/package.json
  admin/views/availability/school-not-found.ejs
Labels: Tested, CI Enabled, expedited

#2466 Feature/58073 tech support user
  admin/services/data-access/sql.pool.service.js
  admin/services/data-access/sql.role-connection.builder.js
  admin/tests-integration/sql.pool.service.spec.js
  admin/tests-integration/sql.role-connection.builder.spec.js
  db/config.js
  db/migrations/schema-objects/20211208124902.do.enable-change-data-capture.sql
  db/migrations/schema-objects/20211208124902.undo.enable-change-data-capture.sql
  db/migrations/schema-objects/20211208124914.do.track-school-changes-cdc.sql
  db/migrations/schema-objects/20211208124914.undo.track-school-changes-cdc.sql
  db/migrations/schema-objects/20220117154728.do.disable-cdc-for-db.sql
  db/migrations/schema-objects/20220117154728.undo.disable-cdc-for-db.sql
  db/migrations/user-permissions/20230309163938.do.sql-support-user-grants.js
  db/migrations/user-permissions/20230309163938.undo.sql-support-user-grants.js
  db/migrations/user/20230309163747.do.sql-support-user.js
  db/migrations/user/20230309163747.undo.sql-support-user.js
Labels: Tested, CI Enabled
