Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2023-04, with the labels that each got.

#2495 Feature/58712 accessibility statement update
  admin/views/accessibility-statement.ejs
  pupil-spa/src/app/accessibility-statement/accessibility-statement.component.html
Labels: Tested, Signed Off, CI Enabled

#2476 Feature/58241 HDF options & content changes
  admin/controllers/hdf.js
  admin/lib/consts/hdf-confirm-options.js
  admin/lib/errors/hdf-confirm.js
  admin/lib/validator/hdf-confirm-validator.js
  admin/services/check-window-v2.service.js
  admin/services/data-access/headteacher-declaration.data.service.js
  admin/services/date.service.js
  admin/services/headteacher-declaration.service.js
  admin/spec/back-end/controllers/hdf.spec.js
  admin/spec/back-end/lib/validator/hdf-confirm-validator.spec.js
  admin/spec/back-end/service/data-access/headteacher-declaration.data.service.spec.js
  admin/views/hdf/confirm-and-submit.ejs
  admin/views/hdf/declaration-form.ejs
  admin/views/hdf/submitted-form.ejs
  db/migrations/core-data/20230317152843.do.hdf-confirm-codes.sql
  db/migrations/core-data/20230317152843.undo.hdf-confirm-codes.sql
  db/migrations/schema-objects/20230317144404.do.hdf-status-lookup-table.sql
  db/migrations/schema-objects/20230317144404.undo.hdf-status-lookup-table.sql
  db/migrations/schema-objects/20230322165307.do.hdf-drop-confirmed-default.sql
  db/migrations/schema-objects/20230322165307.undo.hdf-drop-confirmed-default.sql
  db/migrations/schema-objects/20230322165333.do.hdf-create-status.sql
  db/migrations/schema-objects/20230322165333.undo.hdf-create-status.sql
  db/migrations/schema-objects/20230323155703.do.hdf-non-confirm-info-column.sql
  db/migrations/schema-objects/20230323155703.undo.hdf-non-confirm-info-column.sql
  db/migrations/schema-objects/20230324145608.do.hdfstatus-trigger.sql
  db/migrations/schema-objects/20230324145608.undo.hdfstatus-trigger.sql
  db/migrations/schema-objects/20230327152858.do.drop-hdf-confirmed-column.sql
  db/migrations/schema-objects/20230327152858.undo.drop-hdf-confirmed-column.sql
  test/admin-hpa/features/declaration_confirm.feature
  test/admin-hpa/features/step_definitions/declaration_confirm_steps.rb
  test/admin-hpa/features/support/page_objects/declaration_confirm_page.rb
Labels: Tested, CI Enabled

#2486 [55451] Feature/restart deletion record date and time
  admin/package.json
  admin/services/data-access/pupil-restart.data.service.js
  db/migrations/schema-objects/20230329100932.do.pupil-restart-new-col-deletedat.sql
  db/migrations/schema-objects/20230329100932.undo.pupil-restart-new-col-deletedat.sql
  test/admin-hpa/features/step_definitions/frozen_pupil_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/support/sql_db_helper.rb
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled, Requires Tech Sign Off

#2485 Feature/54236 ps report consumed restarts
  admin/services/check-start.service/check-start.service.js
  admin/yarn.lock
  func-consumption/yarn.lock
  func-ps-report/yarn.lock
  func-throttled/yarn.lock
  pupil-api/yarn.lock
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.data.service.ts
  tslib/yarn.lock
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled, Requires Tech Sign Off, dependency updates

#2492 Feature/58379 allow space in pupil password
  pupil-api/package.json
  pupil-api/src/controllers/redis.auth.controller.spec.ts
  pupil-api/src/controllers/redis.auth.controller.ts
  pupil-api/yarn.lock
  test/pupil-hpa/features/login_page.feature
  test/pupil-hpa/features/step_definitions/header_footer_steps.rb
  tslib/src/functions-throttled/school-import/predicates.ts
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off, dependency updates

#2487 Feature/58454 logon events and MI views
  admin/services/dfe-signin.service.js
  db/migrations/schema-objects/20230404110400.do.admin-logon-event-urn-column.sql
  db/migrations/schema-objects/20230404110400.undo.admin-logon-event-urn-column.sql
  db/migrations/schema-objects/20230404110716.do.admin-logon-event-mtcrole-column.sql
  db/migrations/schema-objects/20230404110716.undo.admin-logon-event-mtcrole-column.sql
  db/migrations/schema-objects/20230404111132.do.admin-logon-event-dferole-column.sql
  db/migrations/schema-objects/20230404111132.undo.admin-logon-event-dferole-column.sql
  db/migrations/schema-objects/20230404112801.do.vew-mi-checks-with-errors.sql
  db/migrations/schema-objects/20230404112801.undo.vew-mi-checks-with-errors.sql
  db/migrations/schema-objects/20230404113200.do.vew-mi-checks-not-started.sql
  db/migrations/schema-objects/20230404113200.undo.vew-mi-checks-not-started.sql
  db/migrations/schema-objects/20230404115415.do.vew-mi-schools-logged-on-at-least-once.sql
  db/migrations/schema-objects/20230404115415.undo.vew-mi-schools-logged-on-at-least-once.sql
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off
