Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2024-04, with the labels that each got.

#2747 feature/64034-copy-changes
  admin/views/pupil-pin/view-and-custom-print-pins.ejs
  test/admin-hpa/features/support/page_objects/view_and_print_tio_pins_page.rb
  test/pupil-hpa/features/support/page_objects/view_and_custom_print_live_check_page.rb
Labels: Tested, Signed Off, CI Enabled, expedited

#2748 Feature/64026 remove radio buttons and free text box from access arrangements
  .gitignore
  admin/assets/javascripts/pupil-access-arrangements-selection.js
  admin/controllers/access-arrangements.js
  admin/helpers/access-arrangements-descriptions-presenter.js
  admin/lib/validator/access-arrangements-validator.js
  admin/package.json
  admin/services/access-arrangements.service.js
  admin/services/data-access/pupil-access-arrangements.data.service.js
  admin/services/data-access/question-reader-reasons.data.service.js
  admin/services/pupil-access-arrangements.service.js
  admin/services/question-reader-reasons.service.js
  admin/spec/back-end/controllers/access-arrangements.spec.js
  admin/spec/back-end/helpers/access-arrangements-descriptions-presenter.spec.js
  admin/spec/back-end/lib/validator/access-arrangements-validator.spec.js
  admin/spec/back-end/service/access-arrangements.service.spec.js
  admin/spec/back-end/service/pupil-access-arrangements.service.spec.js
  admin/spec/back-end/service/question-reader-reasons.service.spec.js
  admin/spec/front-end/pupil-access-arrangements-selection.spec.js
  admin/views/access-arrangements/select-access-arrangements.ejs
  db/migrations/schema-objects/20240404140740.do.delete-question-reader-details.sql
  db/migrations/schema-objects/20240404140740.undo.delete-question-reader-details.sql
  func-consumption/relauncher.sh
  func-ps-report/relauncher.sh
  func-throttled/relauncher.sh
  test/admin-hpa/features/access_arrangements.feature
  test/admin-hpa/features/step_definitions/access_arrangements_steps.rb
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/features/support/page_objects/select_access_arrangements_page.rb
  test/pupil-hpa/features/login_page.feature
  test/pupil-hpa/features/pupil_access_arrangements.feature
  test/pupil-hpa/features/support/env.rb
  test/pupil-hpa/features/support/page_objects/select_access_arrangements_page.rb
  test/se_manager/.cache/selenium/se-metadata.json
Labels: Tested, Signed Off, CI Enabled, expedited

#2682 Feature/security roll up 211223
  _util/chaos-proxy/yarn.lock
  admin/package.json
  admin/yarn.lock
  deploy/sql/yarn.lock
  design/spikes/spike-durable-functions/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  load-test/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  pupil-spa/yarn.lock
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  tslib/package.json
  tslib/yarn.lock
Labels: CI Enabled, failing tests

#2770 Feature/64139 security rollup 2024 04 10
  deploy/sql/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  pupil-spa/package.json
  pupil-spa/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: Tested, Reviewed & approved, CI Enabled

#2771 feature/64152 add serial tag to non parallel feature files
  test/admin-hpa/features/1build_commit_and_ping.feature
  test/admin-hpa/features/assign_to_check_window_v2.feature
  test/admin-hpa/features/check_time_limits.feature
  test/admin-hpa/features/create_check_window_v2.feature
  test/admin-hpa/features/csrf.feature
  test/admin-hpa/features/declaration_form.feature
  test/admin-hpa/features/declaration_submitted.feature
  test/admin-hpa/features/edit_check_window_v2.feature
  test/admin-hpa/features/generate_pupil_pin_familiarisation.feature
  test/admin-hpa/features/generate_pupil_pins.feature
  test/admin-hpa/features/manage_check_window.feature
  test/admin-hpa/features/mod_schools.feature
  test/admin-hpa/features/phase_banner.feature
  test/admin-hpa/features/post_check_window_settings.feature
  test/admin-hpa/features/pupil_status.feature
  test/admin-hpa/features/restarts.feature
  test/admin-hpa/features/retro_input_assistance.feature
  test/admin-hpa/features/school_import.feature
  test/admin-hpa/features/service_manager_attendance_codes.feature
  test/admin-hpa/features/service_manager_edit_school.feature
  test/admin-hpa/features/service_manager_hdf.feature
  test/admin-hpa/features/service_manager_message.feature
  test/admin-hpa/features/service_manager_move_pupils.feature
  test/admin-hpa/features/service_manager_school_audit.feature
  test/admin-hpa/features/sta_admin_add_pupils.feature
  test/admin-hpa/features/time_between_questions.feature
  test/admin-hpa/features/upload_pupil_census.feature
  test/admin-hpa/features/upload_view_forms_v2.feature
  test/admin-hpa/features/view_and_custom_print_live_check_pin.feature
  test/admin-hpa/features/view_custom_pins_familiarisation.feature
Labels: CI Enabled, QA Not required

#2746 Feature/62241 404 should not raise an exception
  admin/app.js
  admin/views/availability/page-not-found.ejs
Labels: Signed Off, CI Enabled, Requires Tech Sign Off

#2779 Feature/64178 security update
  _util/chaos-proxy/yarn.lock
  admin/yarn.lock
  deploy/service-bus/yarn.lock
  deploy/sql/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  load-test/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  tslib/package.json
  tslib/src/caching/prepared-check.service.spec.ts
  tslib/src/functions/util-submit-check/fake-completed-check-generator.service.ts
  tslib/yarn.lock
Labels: Tested, CI Enabled

#2716 Feature/62546 maladmin codes 2024
  .gitignore
  admin/controllers/service-manager.js
  admin/services/service-manager/pupil-annulment/pupil-annulment.data.service.ts
  admin/services/service-manager/pupil-annulment/pupil-annulment.service.spec.ts
  admin/services/service-manager/pupil-annulment/pupil-annulment.service.ts
  admin/services/service-manager/pupil/service-manager.pupil.service.ts
  admin/views/service-manager/annul-pupil.ejs
  db/migrations/schema-objects/20240220135748.do.amend-annulment-reason.sql
  db/migrations/schema-objects/20240220135748.undo.amend-annulment-reason.sql
  db/migrations/schema-objects/20240220142903.do.pupil-cheat-attendance-code.sql
  db/migrations/schema-objects/20240220142903.undo.pupil-cheat-attendance-code.sql
  test/admin-hpa/features/frozen_pupil.feature
  test/admin-hpa/features/step_definitions/frozen_pupil_steps.rb
  test/admin-hpa/features/step_definitions/pupil_not_taking_check.rb
  test/admin-hpa/features/support/helpers.rb
  test/admin-hpa/features/support/page_objects/pupil_annulment_confirmation_page.rb
  test/pupil-hpa/features/a_ps_report.feature
  test/pupil-hpa/features/step_definitions/pin_expiry_steps.rb
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/pupil-hpa/features/support/helpers.rb
  test/pupil-hpa/features/support/hooks.rb
  test/pupil-hpa/features/support/page_objects/pupil_annulment_confirmation_page.rb
  test/se_manager/.cache/selenium/se-metadata.json
  tslib/src/functions-ps-report/ps-report-2-pupil-data/models.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.data.service.spec.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.data.service.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/mocks/pupil-not-attending-annulled.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/models.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/report-line.class.spec.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/report-line.class.ts
Labels: Tested, Ready to merge, Signed Off, CI Enabled

#2749 bug/63386-cannot-remove-specific-service-messages
  admin/views/service-message/service-message-overview.ejs
  test/admin-hpa/features/service_manager_message.feature
  test/admin-hpa/features/step_definitions/service_message.rb
  test/admin-hpa/features/support/helpers.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/page_objects/manage_service_message_page.rb
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled

#2751 Feature/64110 copy error date format on pin slips
  .gitignore
  admin/controllers/pupil-pin.js
  admin/spec/back-end/controllers/pupil-pin.spec.js
  admin/yarn.lock
  test/pupil-hpa/features/check.feature
  test/pupil-hpa/features/complete_page.feature
  test/pupil-hpa/features/cookies.feature
  test/pupil-hpa/features/device_information.feature
  test/pupil-hpa/features/familiarisation_check.feature
  test/pupil-hpa/features/feedback.feature
  test/pupil-hpa/features/header_footer.feature
  test/pupil-hpa/features/instructions_page.feature
  test/pupil-hpa/features/loading_page.feature
  test/pupil-hpa/features/login_page.feature
  test/pupil-hpa/features/page_not_found.feature
  test/pupil-hpa/features/pin_expiry.feature
  test/pupil-hpa/features/pupil_access_arrangements.feature
  test/pupil-hpa/features/pupil_api.feature
  test/pupil-hpa/features/pupil_authentication.feature
  test/pupil-hpa/features/pupil_data_sync.feature
  test/pupil-hpa/features/registered_inputs.feature
  test/pupil-hpa/features/retro_input_assistance.feature
  test/pupil-hpa/features/state.feature
  test/pupil-hpa/features/support/hooks.rb
  test/pupil-hpa/features/warm_up_questions.feature
  test/se_manager/.cache/selenium/se-metadata.json
Labels: Tested, Reviewed & approved, CI Enabled, Requires sign off

#2750 Feature/63135 better error message
  admin/app.js
  admin/error-types/form-already-submitted-error.js
  admin/helpers/prevent-duplicate-submit.js
  admin/views/form-already-submitted.ejs
  test/admin-hpa/features/generate_pupil_pins.feature
Labels: Tested, Signed Off, CI Enabled

#2782 Feature/64176 school pins & 10k seed fix
  _util/virtual-machines/mtc-test-vm/files/install_mtc.sh
  admin/config.js
  db/config.js
  db/migrations/core-data/20240417115737.do.school-pin-data.js
  db/migrations/schema-objects/20240417115541.do.school-pin-table.sql
  db/migrations/schema-objects/20240417115541.undo.school-pin-table.sql
  db/seeds/20240322111539.custom.10k-schools.sql
  deploy/release-config/admin.base.txt
  deploy/release-config/func-cons.base.txt
  deploy/release-config/func-throttled.base.txt
  docs/environment-variables.md
  example.env.txt
  test/admin-hpa/README.md
  test/se_manager/.cache/selenium/se-metadata.json
  tslib/src/config.ts
  tslib/src/functions/school-pin-generator/allowed-words.service.spec.ts
  tslib/src/functions/school-pin-generator/allowed-words.service.ts
  tslib/src/functions/school-pin-generator/pin-config-provider.ts
  tslib/src/functions/school-pin-generator/school-pin-data-service.ts
  tslib/src/functions/school-pin-generator/school-pin-expiry-generator.spec.ts
  tslib/src/functions/school-pin-generator/school-pin-expiry-generator.ts
  tslib/src/functions/school-pin-generator/school-pin-generator.spec.ts
  tslib/src/functions/school-pin-generator/school-pin-generator.ts
  tslib/src/functions/school-pin-generator/school-pin-replenishment.service.spec.ts
  tslib/src/functions/school-pin-generator/school-pin-replenishment.service.ts
  tslib/src/functions/util-school-pin-sampler/school-pin-sampler.spec.ts
  tslib/src/functions/util-school-pin-sampler/school-pin-sampler.ts
Labels: Tested, CI Enabled

#2780 Feature/64140 pupil tests in parallel
  test/admin-hpa/features/support/hooks.rb
  test/pupil-hpa/Gemfile.lock
  test/pupil-hpa/features/support/hooks.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
Labels: CI Enabled
