Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2024-02, with the labels that each got.

#2694 Update 20181116133337.custom.check-window-dev-data.sql
  db/seeds/20181116133337.custom.check-window-dev-data.sql
Labels: Tested, Ready for review, CI Enabled, Requires Tech Sign Off

#2695 Copy changes
  admin/views/accessibility-statement.ejs
  admin/views/partials/_attendance_code_reasons.ejs
  admin/views/partials/_gds_body_footer.ejs
  admin/views/pupil-pin/view-and-custom-print-pins.ejs
  test/admin-hpa/features/support/page_objects/pupil_reason_page.rb
Labels: Tested, Signed Off, CI Enabled

#2601 updates required for ruby 3.2.2
  .circleci/config.yml
  .gitignore
  deploy/docker/circleci-ruby/Dockerfile
  deploy/docker/circleci-ruby/README.md
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/config/cucumber.yml
  test/admin-hpa/features/step_definitions/add_multiple_pupil_steps.rb
  test/admin-hpa/features/step_definitions/check_validator_steps.rb
  test/admin-hpa/features/step_definitions/data_sync_steps.rb
  test/admin-hpa/features/step_definitions/declaration_submitted_steps.rb
  test/admin-hpa/features/step_definitions/generate_pupil_pins_steps.rb
  test/admin-hpa/features/step_definitions/pupil_audit_steps.rb
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
  test/admin-hpa/features/step_definitions/pupil_status_steps.rb
  test/admin-hpa/features/step_definitions/restarts_steps.rb
  test/admin-hpa/features/step_definitions/sta_admin_pupil_history_steps.rb
  test/admin-hpa/features/support/azure_blob_helper.rb
  test/admin-hpa/features/support/azure_queue_helper.rb
  test/admin-hpa/features/support/azure_table_helper.rb
  test/admin-hpa/features/support/env.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/received_check_decompressor.rb
  test/admin-hpa/features/support/site_prism_config.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  test/pupil-hpa/config/cucumber.yml
  test/pupil-hpa/features/step_definitions/access_arrangement_steps.rb
  test/pupil-hpa/features/step_definitions/check_steps.rb
  test/pupil-hpa/features/step_definitions/device_steps.rb
  test/pupil-hpa/features/step_definitions/event_auditing_steps.rb
  test/pupil-hpa/features/step_definitions/login_page_steps.rb
  test/pupil-hpa/features/step_definitions/pin_expiry_steps.rb
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/pupil-hpa/features/step_definitions/pupil_api.rb
  test/pupil-hpa/features/step_definitions/pupil_data_sync_steps.rb
  test/pupil-hpa/features/step_definitions/registered_inputs_steps.rb
  test/pupil-hpa/features/step_definitions/retro_input_steps.rb
  test/pupil-hpa/features/support/azure_blob_helper.rb
  test/pupil-hpa/features/support/azure_queue_helper.rb
  test/pupil-hpa/features/support/azure_table_helper.rb
  test/pupil-hpa/features/support/env.rb
  test/pupil-hpa/features/support/redis_helper.rb
  test/pupil-hpa/features/support/site_prism_config.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
  test/se_manager/.cache/selenium/se-config.toml
  test/se_manager/.cache/selenium/se-metadata.json
Labels: Tested, Signed Off, CI Enabled, ruby

#2696 Feature/63703 security rollup
  _util/chaos-proxy/yarn.lock
  admin/package.json
  admin/yarn.lock
  deploy/sql/yarn.lock
  design/spikes/spike-durable-functions/yarn.lock
  load-test/package.json
  load-test/yarn.lock
  pupil-spa/yarn.lock
Labels: Tested, CI Enabled, Requires Tech Sign Off

#2697 Feature/63510 pupil status page changes
  admin/helpers/pupil-status-presenter.js
  admin/services/pupil-status.service.js
  admin/spec/back-end/helpers/pupil-status-presenter.spec.js
  admin/spec/back-end/service/pupil-status.service.spec.js
  admin/views/pupil-status/view-pupil-status.ejs
  test/admin-hpa/features/pupil_status.feature
  test/admin-hpa/features/service_manager_pupil_search.feature
  test/admin-hpa/features/step_definitions/pupil_register_steps.rb
  test/admin-hpa/features/step_definitions/pupil_status_steps.rb
  test/admin-hpa/features/support/page_objects/pupil_status_page.rb
  test/se_manager/.cache/selenium/se-metadata.json
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2708 Update add_pupil_steps.rb
  test/admin-hpa/features/step_definitions/add_pupil_steps.rb
Labels: Tested, CI Enabled
