Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2024-05, with the labels that each got.

#2783 Feature/63516 add is edited to psreport
  admin/tests-integration/pupil-edit.service.spec.js
  db/migrations/schema-objects/20240419145419.do.update-is-edited-trigger.sql
  db/migrations/schema-objects/20240419145419.undo.update-is-edited-trigger.sql
  tslib/src/functions-ps-report/ps-report-2-pupil-data/models.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.data.service.spec.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.data.service.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.service.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/mocks/pupil-complete-and-restart-available-corrupt.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/mocks/pupil-not-attending-annulled.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/mocks/pupil-not-attending-corrupt.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/mocks/pupil-not-attending.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/mocks/pupil-who-completed-a-check.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/mocks/pupil-with-incomplete-check.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/models.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/report-line.class.ts
  tslib/src/functions-ps-report/ps-report-3b-stage-csv-file/csv-transform.spec.ts
  tslib/src/functions-ps-report/ps-report-3b-stage-csv-file/csv-transformer.ts
  tslib/src/functions-ps-report/ps-report-4-writer/ps-report-writer.service.ts
  tslib/src/tests-integration/mock-payload.class.ts
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled

#2785 feature/64193 Request PS Report for specific schools
  admin/controllers/tech-support.js
  admin/services/tech-support/ps-report-exec/ps-report-exec.data.service.ts
  admin/services/tech-support/ps-report-exec/ps-report-exec.service.spec.ts
  admin/services/tech-support/ps-report-exec/ps-report-exec.service.ts
  admin/spec/back-end/controllers/tech-support.spec.js
  admin/views/tech-support/ps-report-run.ejs
  example.env.txt
  test/admin-hpa/features/step_definitions/declaration_form_steps.rb
  test/pupil-hpa/features/a_ps_report.feature
  test/pupil-hpa/features/step_definitions/cookies_steps.rb
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/pupil-hpa/features/support/page_objects/run_ps_report_page.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
  test/se_manager/.cache/selenium/se-metadata.json
  tslib/src/functions-ps-report/common/ps-report-service-bus-messages.ts
  tslib/src/functions-ps-report/ps-report-1-list-schools/index.ts
  tslib/src/functions-ps-report/ps-report-1-list-schools/list-schools-service.spec.ts
  tslib/src/functions-ps-report/ps-report-1-list-schools/list-schools-service.ts
Labels: Tested, CI Enabled

#2787 [Snyk] Upgrade ioredis from 5.4.0 to 5.4.1
  load-test/package.json
Labels: CI Enabled

#2792 redis connection details
  test/admin-hpa/features/support/env.rb
  test/se_manager/.cache/selenium/se-metadata.json
Labels: CI NOT Required, expedited

#2788 feature/64388 sync function keys with key vault
  deploy/keys/express-session-secret-update-keyvault.sh
  deploy/keys/function-masterkey-update-keyvault.sh
  deploy/keys/functions.sh
  deploy/keys/keyvault-secret-refresh.yml
  deploy/keys/keyvault-update.sh
  deploy/keys/readme.md
Labels: CI Enabled, QA Not required

#2790 feature/pupil-spa-localstorage-error-page-not-shown
  pupil-spa/src/app/services/qr-code-usage/qr-code-usage.service.ts
  pupil-spa/yarn.lock
  test/admin-hpa/features/step_definitions/service_manager_pupil_search_steps.rb
  test/admin-hpa/features/support/page_objects/pupil_search_page.rb
  test/pupil-hpa/features/login_page.feature
  test/pupil-hpa/features/step_definitions/login_page_steps.rb
  test/pupil-hpa/features/support/env.rb
  test/pupil-hpa/features/support/hooks.rb
  test/pupil-hpa/features/support/page_objects/local_storage_error_page.rb
  test/se_manager/.cache/selenium/se-metadata.json
Labels: Tested, Signed Off, CI Enabled

#2789 Feature/61884 audit helpdesk impersonation
  admin/services/data-access/school-audit.data.service.js
  admin/services/school-impersonation.service.js
  admin/spec/back-end/service/school-impersonation.service.spec.js
  db/migrations/schema-objects/20240514111912.do.school-impersonation-audit-table.sql
  db/migrations/schema-objects/20240514111912.undo.school-impersonation-audit-table.sql
  db/migrations/schema-objects/20240514164016.do.school-impersonation-audit-trigger.sql
  db/migrations/schema-objects/20240514164016.undo.school-impersonation-audit-trigger.sql
  test/admin-hpa/features/helpdesk_pupil_history.feature
  test/admin-hpa/features/sta_admin_pupil_history.feature
  test/admin-hpa/features/step_definitions/helpdesk_pin_steps.rb
  test/admin-hpa/features/step_definitions/sta_admin_pupil_history_steps.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/se_manager/.cache/selenium/se-metadata.json
Labels: Tested, Signed Off, CI Enabled

#2791 Feature/64320 pin gen disable buttons after click
  admin/assets/javascripts/util-checkbox.js
  admin/package.json
  admin/views/access-arrangements/select-access-arrangements.ejs
  admin/views/pupil-pin/select-official-or-try-it-out-pins.ejs
  admin/yarn.lock
  func-consumption/yarn.lock
  func-ps-report/yarn.lock
  func-throttled/yarn.lock
  pupil-api/yarn.lock
  tslib/yarn.lock
Labels: Tested, CI Enabled

#2799 Add bash script to run local e2e tests in parallel
  .gitignore
  test/admin-hpa/run-local-tests.sh
  test/admin-hpa/tags-parallel.txt
  test/admin-hpa/tags-serial.txt
  test/pupil-hpa/run-local-tests.sh
  test/pupil-hpa/tags-parallel.txt
Labels: CI Enabled

#2800 Bug/64589 ps report failed on azure
  admin/yarn.lock
  setup.sh
  tslib/src/functions-ps-report/ps-report-4-writer/ps-report-writer.service.ts
Labels: Tested, Ready to merge, CI Enabled

#2801 bug/64757 mask newData field in pupilAudit table
  db/migrations/schema-objects/20240529151328.do.pupil-audit-new-data-mask.sql
  db/migrations/schema-objects/20240529151328.undo.pupil-audit-new-data-mask.sql
Labels: Tested, Signed Off, CI Enabled, expedited, QA Not required

#2796 Bug/64537 pupil restart delete date fix
  admin/services/data-access/pupil-attendance.data.service.js
Labels: Tested, Ready to merge, CI Enabled

#2798 spike/64121-enable-call-stack-capture-for-app-insights
  pupil-spa/angular.json
Labels: CI Enabled

#2803 Bug/64760 ps report run not populating the table
  deploy/service-bus/deploy.config.js
  tslib/src/functions-ps-report/ps-report-3b-stage-csv-file/index.ts
  tslib/src/functions-ps-report/ps-report-3b-stage-csv-file/ps-report-staging.data.service.ts
  tslib/src/functions-ps-report/ps-report-4-writer/index.ts
  tslib/src/functions-ps-report/ps-report-4-writer/ps-report-writer.service.ts
Labels: CI Enabled
