Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2024-11, with the labels that each got.

#2957 Feature/65809 restarts & check submission reference docs
  docs/architecture/check-submission/.$Check Submission-FlowChart.drawio.bkp
  docs/architecture/check-submission/check-submission-flowchart.drawio
  docs/architecture/check-submission/check-submission-flowchart.png
  docs/architecture/check-submission/readme.md
  docs/architecture/data/check-payload.json
  docs/architecture/messaging/message-schemas.md
  docs/architecture/messaging/messaging.md
  docs/architecture/messaging/readme.md
  docs/architecture/ps-report/readme.md
  docs/architecture/pupil-check/readme.md
  docs/architecture/readme.md
  docs/architecture/restarts/readme.md
  docs/architecture/restarts/restarts-flowchart.drawio
  docs/architecture/restarts/restarts-flowchart.png
  docs/readme.md
  docs/support-utils/readme.md
Labels: Signed Off, CI NOT Required, Requires Tech Sign Off

#2963 bug/65881 SPA crashes without app insights configured
  pupil-spa/src/app/error-handler.ts
  pupil-spa/src/app/services/app-insights/app-insights.service.ts
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/string-util.spec.ts
  pupil-spa/src/app/string-util.ts
Labels: Tested, CI Enabled, expedited, Requires Tech Sign Off

#2974 test fixes
  .gitignore
  test/admin-hpa/features/step_definitions/add_multiple_pupil_steps.rb
  test/admin-hpa/features/support/hooks.rb
  test/admin-hpa/features/support/request_helper.rb
  test/se_manager/.cache/selenium/se-config.toml
  test/se_manager/.cache/selenium/se-metadata.json
Labels: Tested, CI Enabled, ruby

#2978 test fix
  test/admin-hpa/features/step_definitions/add_multiple_pupil_steps.rb
  test/se_manager/.cache/selenium/se-metadata.json
Labels: Tested, CI Enabled, ruby

#2943 Feature/65499 spa asset optimisation
  admin/package.json
  admin/yarn.lock
  db/package.json
  db/yarn.lock
  deploy/service-bus/package.json
  deploy/service-bus/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  pupil-spa/angular.json
  pupil-spa/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2982 bug/66011 azure storage cannot send message using package v12.24.0
  admin/package.json
  admin/tests-integration/sas-token-expiry.spec.js
  admin/yarn.lock
  pupil-spa/Dockerfile
Labels: Tested, CI Enabled

#2941 feature/65545 node 20 upgrade
  .nvmrc
  admin/.nvmrc
  db/.nvmrc
  deploy/build-agent/Dockerfile
  deploy/build-agent/create-instance.sh
  deploy/build-agent/readme.md
  deploy/docker/circleci-node-multi/Dockerfile
  deploy/docker/circleci-node-multi/README.md
  deploy/service-bus/.nvmrc
  docs/node-runtime-upgrade.md
  func-consumption/.nvmrc
  func-consumption/package.json
  func-ps-report/.nvmrc
  func-ps-report/package.json
  func-throttled/.nvmrc
  func-throttled/package.json
  load-test/.nvmrc
  pupil-api/.nvmrc
  tslib/.nvmrc
Labels: Tested, CI Enabled
