Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2024-07, with the labels that each got.

#2833 Feature/64794 send check code with ajax
  example.env.txt
  pupil-spa/src/app/services/app-insights/app-insights.service.ts
  pupil-spa/yarn.lock
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2847 Feature/security 09 07 24
  design/spikes/home-page-notifications-59286/package.json
  design/spikes/home-page-notifications-59286/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  test/admin-hpa/features/step_definitions/sta_admin_pupil_history_steps.rb
  test/se_manager/.cache/selenium/se-metadata.json
  tslib/package.json
  tslib/yarn.lock
Labels: Tested, CI Enabled

#2844 Feature/64496 dfe sign in error
  admin/app.js
  admin/authentication/dfe-signin-strategy.js
  admin/error-types/dfe-signin-error.js
  admin/services/data-access/dfe-signin.data.service.js
  admin/services/dfe-signin.service.js
  admin/services/role.service.js
  admin/spec/back-end/error-types/dfe-sign-in-error.spec.js
  admin/views/dfe-sign-in-error-missing-org.ejs
  admin/views/dfe-sign-in-error.ejs
Labels: Tested, Signed Off, CI Enabled

#2846 feature/64752-delete-deploy-sql
  db/misc/anonymise-pupil-data/pupil-anon.sql
  db/misc/anonymise-pupil-data/school-anon.sql
  db/misc/anonymise-pupil-data/user-anon.sql
  deploy/build-defs/validate-pr-db-migrations.yml
  deploy/sql/.gitignore
  deploy/sql/.nvmrc
  deploy/sql/anonymise-sql-data/school-anon.sql
  deploy/sql/check-replay/readme.md
  deploy/sql/check-replay/reset-state-pupils-checks.sql
  deploy/sql/config.js
  deploy/sql/dummy-data/all.js
  deploy/sql/dummy-data/readme.md
  deploy/sql/dummy-data/upn.service.js
  deploy/sql/log.service.js
  deploy/sql/logger.js
  deploy/sql/package.json
  deploy/sql/readme.md
  deploy/sql/vso-validate-migrations/migrate-db.sh
  deploy/sql/vso-validate-migrations/seed-db.sh
  deploy/sql/vso-validate-migrations/vso-migrate-down.sh
  deploy/sql/vso-validate-migrations/vso-migrate-up.sh
  deploy/sql/yarn.lock
Labels: Tested, Reviewed & approved, CI Enabled
