Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2024-09, with the labels that each got.

#2864 Feature/64996 remove add pupil and pin once hdf signed
  admin/controllers/pupil-register.js
  admin/controllers/pupil.js
  admin/spec/back-end/controllers/pupil-register.spec.js
  admin/views/pupil-register/pupils-list.ejs
  admin/yarn.lock
  pupil-api/yarn.lock
  pupil-spa/src/app/services/timer/timer.service.spec.ts
  tslib/yarn.lock
Labels: Tested, Signed Off, CI Enabled

#2879 65031-allow-schools-to-view-register-post-check
  admin/config.js
  admin/helpers/app-insights.js
  admin/package.json
  admin/routes/pupil-register.js
  admin/yarn.lock
  docs/environment-variables.md
  example.env.txt
  load-test/check-submit-proxy/package.json
  load-test/check-submit-proxy/yarn.lock
  test/admin-hpa/features/step_definitions/post_check_window_steps.rb
  test/admin-hpa/features/step_definitions/sta_admin_add_pupils_steps.rb
  test/admin-hpa/features/support/page_objects/pupil_register_page.rb
  test/se_manager/.cache/selenium/se-metadata.json
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.service.spec.ts
Labels: Tested, Signed Off, CI Enabled

#2888 Feature/65094 SPA connectivity check removal
  pupil-spa/README.md
  pupil-spa/gen_config.sh
  pupil-spa/src/app/app.module.ts
  pupil-spa/src/app/connectivity-check.guard.spec.ts
  pupil-spa/src/app/connectivity-check.guard.ts
  pupil-spa/src/app/connectivity-check/connectivity-check.component.html
  pupil-spa/src/app/connectivity-check/connectivity-check.component.scss
  pupil-spa/src/app/connectivity-check/connectivity-check.component.spec.ts
  pupil-spa/src/app/connectivity-check/connectivity-check.component.ts
  pupil-spa/src/app/connectivity-error/connectivity-error.component.html
  pupil-spa/src/app/connectivity-error/connectivity-error.component.scss
  pupil-spa/src/app/connectivity-error/connectivity-error.component.spec.ts
  pupil-spa/src/app/connectivity-error/connectivity-error.component.ts
  pupil-spa/src/app/services/config/config.service.ts
  pupil-spa/src/app/services/connectivity-service/connectivity-error-messages.ts
  pupil-spa/src/app/services/connectivity-service/connectivity-service.spec.ts
  pupil-spa/src/app/services/connectivity-service/connectivity-service.ts
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled, Requires Tech Sign Off

#2878 bug/59556 preserve restart state when changing attendance state
  admin/package.json
  admin/services/data-access/pupil-attendance.data.service.js
  db/migrations/schema-objects/20240816100652.do.attendance-restart-deletion-ref-column.sql
  db/migrations/schema-objects/20240816100652.undo.attendance-restart-deletion-ref-column.sql
Labels: Tested, Testing, Signed Off, CI Enabled

#2910 Bug/65347 admin app unresponsive
  admin/config.js
  admin/helpers/app-insights.js
  admin/models/logger.js
  admin/package.json
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  tslib/package.json
  tslib/src/pupil-api/services/log.service.ts
  tslib/src/pupil-api/typings/index.d.ts
  tslib/yarn.lock
Labels: QA: regression only, Tested, Reviewed & approved, CI Enabled, expedited, Requires Tech Sign Off

#2903 Bug/65067 ps report utf8 chars
  admin/app.js
  admin/package.json
  admin/services/check-window-v2.service.js
  admin/services/csv-file.service.js
  admin/services/data-access/sql.service.js
  admin/services/type-of-establishment/type-of-establishment-service.ts
  admin/tests-integration/jest.integration.config.js
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  test/pupil-hpa/features/a_ps_report.feature
  test/pupil-hpa/features/step_definitions/login_page_steps.rb
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/se_manager/.cache/selenium/se-metadata.json
  tslib/package.json
  tslib/src/functions-ps-report/ps-report-3b-stage-csv-file/csv-transformer.ts
  tslib/src/functions-ps-report/ps-report-3b-stage-csv-file/index.ts
  tslib/src/functions-ps-report/ps-report-3b-stage-csv-file/ps-report-staging.data.service.ts
  tslib/src/functions-ps-report/ps-report-4-writer/index.ts
  tslib/src/functions-ps-report/ps-report-4-writer/ps-report-writer.service.ts
  tslib/src/functions-throttled/school-import/data-access/school.data.service.ts
  tslib/src/functions/check-marker/check-marker.v1.ts
  tslib/src/sql/sql.service.ts
  tslib/src/tests-integration/blob-service.spec.ts
  tslib/src/tests-integration/ps-report-.integration.spec.ts
  tslib/yarn.lock
Labels: Tested, Signed Off, CI Enabled

#2922 bug/65481 build agent image targets azure container registry
  deploy/build-agent/build-push-registry.sh
  deploy/build-agent/create-instance.sh
  deploy/build-agent/readme.md
Labels: Reviewed & approved, Signed Off, CI Enabled, Requires Tech Sign Off

#2924 65515-copy-change
  admin/views/availability/admin-window-unavailable.ejs
  test/admin-hpa/features/step_definitions/post_check_window_steps.rb
Labels: Tested, CI Enabled, expedited
