Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2024-12, with the labels that each got.

#2965 feature/65864 remove legacy check submission process
  admin/config.js
  admin/services/check-start/check-start.service.js
  admin/services/check-start/check-start.service.spec.js
  admin/services/sas-token.service.js
  admin/services/storage-queue-name-service.js
  admin/spec/back-end/service/sas-token.service.spec.js
  admin/tests-integration/sas-token-expiry.spec.js
  deploy/storage/tables-queues.json
  docs/architecture/data/check-payload.json
  docs/architecture/messaging/readme.md
  func-consumption/package.json
  func-ps-report/package.json
  func-throttled/package.json
  test/se_manager/.cache/selenium/se-metadata.json
  tslib/src/common/mocks/mock-prepared-check-2021.json
  tslib/src/common/mocks/mock-valid-submitted-check.2023.json
  tslib/src/functions-throttled/sync-results-to-sql/mocks/completed-check.message.ts
  tslib/src/functions-throttled/sync-results-to-sql/models.ts
  tslib/src/functions-util/create-school/index.ts
  tslib/src/functions-util/create-user/index.ts
  tslib/src/functions-util/util-submit-check/fake-completed-check-generator.service.spec.ts
  tslib/src/functions-util/util-submit-check/fake-submitted-check-generator.service.spec.ts
  tslib/src/functions-util/util-submit-check/index.ts
  tslib/src/functions/check-receiver/check-receiver.ts
  tslib/src/functions/check-receiver/index.ts
  tslib/src/functions/check-validator/check-validator.spec.ts
  tslib/src/schemas/check-schemas/mock-complete-check-2021.json
  tslib/src/schemas/check-schemas/prepared-check.ts
  tslib/src/schemas/check-schemas/validated-check.ts
  tslib/src/schemas/large-complete-check-V2.json
  tslib/src/schemas/submitted-check-message-template.json
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2990 Feature/64236 increase default pupil census import timeout
  admin/app.js
  admin/package.json
  admin/tests-integration/jest.integration.config.js
  admin/yarn.lock
  db/package.json
  db/yarn.lock
  docker-compose.yml
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/host.json
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/host.json
  func-throttled/package.json
  func-throttled/yarn.lock
  load-test/package.json
  pupil-api/package.json
  pupil-api/yarn.lock
  tslib/package.json
  tslib/yarn.lock
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled, Requires Tech Sign Off

#2984 Bug/65582 init app insights error logging asap
  admin-assets/Dockerfile
  admin/models/logger.js
  admin/package.json
  admin/services/data-access/redis-cache.service.js
  admin/yarn.lock
  load-test/package.json
  pupil-spa/package.json
  pupil-spa/yarn.lock
  test/admin-hpa/Gemfile.lock
  tslib/src/pupil-api/helpers/app-insights.ts
  tslib/src/pupil-api/services/log.service.ts
  tslib/src/pupil-api/services/redis.service.ts
  tslib/yarn.lock
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled, Requires Tech Sign Off

#2985 bug/66018-storage-queue-sas-perms-send-message-failure
  admin/package.json
  admin/tests-integration/sas-token-expiry.spec.js
  admin/yarn.lock
  z_spikes/66011-storage-queue-bug/index.js
  z_spikes/66011-storage-queue-bug/package.json
  z_spikes/66011-storage-queue-bug/yarn.lock
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2979 Feature/65231 disable gestures in pupil checks
  admin/tests-integration/jest.integration.config.js
  example.env.txt
  pupil-spa/src/styles.scss
Labels: Tested, Reviewed & approved, Signed Off, CI Enabled

#2996 Bug/65098 ps report fields populated when no attempt id present
  admin/package.json
  admin/tests-integration/pupil-edit.service.spec.js
  admin/yarn.lock
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  test/admin-hpa/features/support/env.rb
  test/pupil-hpa/features/a_ps_report.feature
  test/pupil-hpa/features/state.feature
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/pupil-hpa/features/step_definitions/state_steps.rb
  test/se_manager/.cache/selenium/se-metadata.json
  tslib/package.json
  tslib/src/common/csprng.d.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/check-incomplete.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/report-line.class.spec.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/report-line.class.ts
  tslib/src/functions-throttled/sync-results-init/index.ts
  tslib/src/functions-throttled/sync-results-to-sql/user-agent-parser.spec.ts
  tslib/src/tests-integration/mock-payload.class.ts
  tslib/yarn.lock
Labels: Tested, Signed Off, CI Enabled

#3004 bug/66196 build agent creation script failing due to os type
  deploy/build-agent/create-instance.sh
Labels: Reviewed & approved, Signed Off, CI Enabled, Requires Tech Sign Off

#3005 Check window error test fix
  test/admin-hpa/Rakefile
  test/admin-hpa/features/step_definitions/edit_check_window_steps.rb
  test/pupil-hpa/Rakefile
  test/pupil-hpa/tags-parallel.txt
Labels: Tested, CI Enabled, ruby
