Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2024-06, with the labels that each got.

#2804 feature/64782 HDF Text instruction update
  admin/views/hdf/declaration-form.ejs
Labels: Tested, Signed Off, CI Enabled, expedited

#2805 Bug/64781 delete ps report staging file
  func-ps-report/ps-report-2-pupil-data/function.json
  tslib/src/common/ContextLike.ts
  tslib/src/functions-ps-report/common/log-entry-formatter.spec.ts
  tslib/src/functions-ps-report/common/log-entry-formatter.ts
  tslib/src/functions-ps-report/common/ps-report-log-entry.ts
  tslib/src/functions-ps-report/common/ps-report-logger.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/index.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.service.spec.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.service.ts
  tslib/src/functions-ps-report/ps-report-3b-stage-csv-file/index.ts
  tslib/src/functions-ps-report/ps-report-4-writer/index.ts
  tslib/src/functions-ps-report/ps-report-4-writer/ps-report-writer.service.ts
Labels: Tested, Reviewed & approved, CI Enabled

#2802 Feature/64495 tech support service bus queue purge
  admin/bin/drain-sb-queue.js
  admin/bin/fill-sb-queue.js
  admin/controllers/tech-support.js
  admin/routes/tech-support.js
  admin/services/data-access/azure-queue.data.service.js
  admin/services/data-access/service-bus-queue-admin.data.service.js
  admin/services/queue-management.service.js
  admin/spec/back-end/controllers/tech-support.spec.js
  admin/spec/back-end/service/tech-support-queue-management.service.spec.js
  admin/views/tech-support/queue-overview.ejs
  admin/views/tech-support/queue-purge-confirm.ejs
Labels: Tested, Signed Off, CI Enabled, Requires Tech Sign Off

#2807 bug/64795 Tech support - send service bus messages
  admin/controllers/tech-support.js
  admin/package.json
  admin/routes/tech-support.js
  admin/services/data-access/service-bus-queue-admin.data.service.js
  admin/services/queue-management.service.js
  admin/spec/back-end/controllers/tech-support.spec.js
  admin/spec/back-end/service/queue-management.service.spec.js
  admin/views/tech-support/home.ejs
  admin/views/tech-support/ps-report-run.ejs
  admin/views/tech-support/queue-overview.ejs
  admin/views/tech-support/sb-queue-submit.ejs
Labels: Tested, CI Enabled

#2808 Hotfix/64795 ps report issue friday 7th june
  func-ps-report/ps-report-1-list-schools/function.json
  func-ps-report/ps-report-2-pupil-data/function.json
  func-ps-report/ps-report-3-transformer/function.json
  tslib/src/azure/service-bus-queue.names.ts
  tslib/src/azure/service-bus.queue.service.ts
  tslib/src/functions-ps-report/ps-report-1-list-schools/index.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/index.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/answers.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/check-config.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/check-form.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/check-incomplete.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/check.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/device.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/events.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/pupil-complete-and-restart-available-corrupt.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/pupil-not-attending-annulled.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/pupil-not-attending-corrupt.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/pupil-not-attending.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/pupil-who-completed-a-check.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/pupil-with-incomplete-check.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/mocks/school.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.data.service.spec.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.data.service.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.service.spec.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/ps-report.service.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/pupil-data.models.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/report-line-answer.class.spec.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/report-line-answer.class.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/report-line.class.spec.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/report-line.class.ts
  tslib/src/functions-ps-report/ps-report-2-pupil-data/transformer-models.ts
  tslib/src/functions-ps-report/ps-report-3-transformer/index.ts
  tslib/src/functions-ps-report/ps-report-3b-stage-csv-file/csv-transform.spec.ts
  tslib/src/functions-ps-report/ps-report-3b-stage-csv-file/csv-transformer.ts
  tslib/src/functions-ps-report/ps-report-3b-stage-csv-file/index.ts
  tslib/src/pupil-api/services/redis-pupil-auth.service.spec.ts
  tslib/src/services/check-submit.service.spec.ts
  tslib/src/tests-integration/mock-payload.class.ts
Labels: Signed Off, CI Enabled, expedited

#2809 Hotfix/64801 increase ps report lock durations
  admin/package.json
  func-ps-report/host.json
Labels: CI Enabled

#2810 Increase maxAutoRenewDuration to align with functionTimeout
  func-ps-report/host.json
Labels: CI Enabled, CI NOT Required

#2811 Increase ttl on ps-report-export queue
  deploy/service-bus/deploy.config.js
Labels: CI Enabled, CI NOT Required

#2813 Bug/52339 timestamp 1h behind
  admin/helpers/index.js
  admin/services/date.service.js
  admin/services/pupil-history/data-access/pupil-history.data.service.ts
  admin/services/pupil-history/pupil-history-service.ts
  admin/spec/back-end/service/date.service.spec.js
  admin/views/pupil-register/pupil-history.ejs
  test/admin-hpa/features/step_definitions/sta_admin_pupil_history_steps.rb
  test/se_manager/.cache/selenium/se-metadata.json
Labels: Tested, CI Enabled

#2819 Feature/test update
  test/admin-hpa/features/step_definitions/sta_admin_pupil_history_steps.rb
  test/se_manager/.cache/selenium/se-metadata.json
Labels: CI Enabled

#2820 Feature/build agent update
  deploy/build-agent/Dockerfile
Labels: CI NOT Required

#2821 device cookie fix
  test/admin-hpa/features/step_definitions/result_page_steps.rb
  test/pupil-hpa/features/step_definitions/pin_expiry_steps.rb
  test/pupil-hpa/features/step_definitions/ps_report_steps.rb
  test/pupil-hpa/features/step_definitions/pupil_data_sync_steps.rb
Labels: Tested, CI Enabled

#2834 Feature/security roll up 20 6 24
  admin-assets/Dockerfile
  admin/yarn.lock
  func-consumption/yarn.lock
  load-test/Dockerfile
  pupil-spa/package.json
  pupil-spa/yarn.lock
  test/admin-hpa/Gemfile
  test/admin-hpa/Gemfile.lock
  test/admin-hpa/features/step_definitions/edit_school_steps.rb
  test/admin-hpa/features/support/sql_db_helper.rb
  test/pupil-hpa/Gemfile
  test/pupil-hpa/Gemfile.lock
  test/pupil-hpa/features/support/env.rb
  test/se_manager/.cache/selenium/se-config.toml
  test/se_manager/.cache/selenium/se-metadata.json
  tslib/yarn.lock
Labels: Tested, CI Enabled, security-roll-up
