Repository DFEAGILEDEVOPS/MTC, pull requests merged in 2025-01, with the labels that each got.

#3008 Feature/60290 pupil feedback persistence move to sql from table storage
  admin/services/check-start/check-start.service.js
  admin/services/check-start/check-start.service.spec.js
  admin/services/sas-token.service.js
  admin/services/storage-queue-name-service.js
  admin/spec/back-end/service/sas-token.service.spec.js
  admin/tests-integration/sas-token-expiry.spec.js
  db/migrations/schema-objects/20250117111900.do.pupil-feedback-table.sql
  db/migrations/schema-objects/20250117111900.undo.pupil-feedback-table.sql
  deploy/service-bus/deploy.config.js
  deploy/storage/tables-queues.json
  func-consumption/package.json
  func-consumption/yarn.lock
  func-ps-report/package.json
  func-ps-report/yarn.lock
  func-throttled/package.json
  func-throttled/yarn.lock
  pupil-api/package.json
  pupil-api/yarn.lock
  pupil-spa/src/app/services/feedback/feedback.service.mock.ts
  pupil-spa/src/app/services/feedback/feedback.service.spec.ts
  pupil-spa/src/app/services/feedback/feedback.service.ts
  pupil-spa/src/app/services/submission/submission.service.spec.ts
  test/pupil-hpa/features/step_definitions/feedback_steps.rb
  test/pupil-hpa/features/support/azure_table_helper.rb
  test/pupil-hpa/features/support/sql_db_helper.rb
  test/se_manager/.cache/selenium/se-metadata.json
  tslib/package.json
  tslib/src/azure/service-bus-queue.names.ts
  tslib/src/azure/service-bus.queue.service.ts
  tslib/src/functions/pupil-feedback/feedback.service.spec.ts
  tslib/src/functions/pupil-feedback/feedback.service.ts
  tslib/src/functions/pupil-feedback/index.ts
  tslib/src/pupil-api/App.ts
  tslib/src/pupil-api/controllers/feedback.controller.spec.ts
  tslib/src/pupil-api/controllers/feedback.controller.ts
  tslib/src/pupil-api/controllers/submit.controller.spec.ts
  tslib/src/pupil-api/controllers/submit.controller.ts
  tslib/src/pupil-api/routes/feedback.ts
  tslib/src/pupil-api/services/feedback.service.spec.ts
  tslib/src/pupil-api/services/feedback.service.ts
  tslib/src/pupil-api/services/redis-pupil-auth.service.ts
  tslib/src/services/check-submit.service.spec.ts
  tslib/src/services/check-submit.service.ts
  tslib/yarn.lock
Labels: Tested, Ready to merge, Signed Off, CI Enabled, Requires Tech Sign Off

#3010 expected url change
  test/pupil-hpa/features/step_definitions/pupil_api.rb
  test/se_manager/.cache/selenium/se-metadata.json
Labels: Tested, Reviewed & approved, CI Enabled, Requires Tech Sign Off, ruby

#3011 Feature/65814 inputs outputs doc
  docs/architecture/data/inputs-outputs.md
Labels: CI Enabled

#3013 feature/65865 Queue reference doc
  docs/architecture/messaging/readme.md
Labels: CI Enabled, QA Not required

#3015 feature/66591 remove fast fail
  deploy/build-defs/pr-label-check.sh
  deploy/build-defs/should-it-build.js
  deploy/build-defs/validate-pr-db-migrations.yml
Labels: QA Not required
